'use strict';
const assert=require('assert'),fs=require('fs');const {chromium,webkit}=require('playwright');
const {serve}=require('./helpers/web-server'),{installMapFixture,expectedNetworkError}=require('./helpers/browser-network');
(async()=>{
 const server=await serve(),engine=process.env.GH_BROWSER==='webkit'?webkit:chromium,browser=await engine.launch({headless:true});
 const context=await browser.newContext({viewport:{width:844,height:390},locale:'ar-SA'});await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();await installMapFixture(page);await page.clock.install({time:new Date('2026-09-06T00:00:00Z')});await page.clock.pauseAt(new Date('2026-09-06T00:00:01Z'));
 // A deterministic 10 fps browser schedule exercises low-frame-rate operation.
 // The game clock, domain owners and every simulation slice remain production code.
 await page.addInitScript(()=>{window.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!expectedNetworkError(m))errors.push(m.text());});page.on('dialog',d=>d.accept());
 async function state(){return page.evaluate(()=>JSON.parse(JSON.stringify(window.__GH_STATE__)));}
 async function visible(selector){const choices=page.locator(selector);for(let i=0;i<await choices.count();i++)if(await choices.nth(i).isVisible())return choices.nth(i);throw new Error('No visible '+selector);}
 async function panel(name){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await (await visible('[data-panel="'+name+'"]')).click();}
 async function control(name){await panel('control');await page.click('[data-open="'+name+'"]');}
 async function speed(n){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await page.click('#speedToggle');await page.click('#speedMenu [data-speed="'+n+'"]');await page.click('#speedToggle');}
 const evidence={};const steps=[];function record(s){steps.push(s);console.log('E2E '+s);}
 try{
 await page.goto(server.baseURL,{waitUntil:'domcontentloaded'});
 await page.selectOption('#founderMode','sandbox');await page.click('#founderReview');await page.locator('#founderForm button[type="submit"]').click();await page.waitForFunction(()=>__GH_STATE__.onboardingComplete);
 let current=await state();assert(current.onboardingComplete);assert.strictEqual(current.cash,1000000000);assert.strictEqual(current.assets.length,0);assert(current.crew.every(c=>c.count===0));record('1–2 New Group and exact capital');
 await (await visible('[data-panel="companies"]')).click();await page.click('[data-companytab="subs"]');await page.locator('button.open-company[data-type="air"]').click();
 current=await state();assert(current.openedCompanies.includes('air'));record('3 Open company');
 const initialAir=current.companyFinance.air.accounts[0].balance;await panel('finance');await page.selectOption('#companyTransferFrom','group');await page.selectOption('#companyTransferTo','air');await page.fill('#companyTransferAmount','400000000');await page.click('.company-transfer-submit');current=await state();assert.strictEqual(current.companyFinance.air.accounts[0].balance,initialAir+400000000);record('4 Fund company through Finance UI');
 await page.click('#drawerClose');await page.click('#worldDirectoryBtn');await page.selectOption('#worldKind','air');await page.selectOption('#worldCountry','SA');await page.fill('#worldSearch','RUH');await page.clock.runFor(300);await page.locator('.world-result .open-directory-site[data-key="air:OERK"]').click();
 current=await state();assert.strictEqual(current.globalBases.length,1);const baseId=current.globalBases[0].id;assert.strictEqual(current.globalBases[0].company,'air');record('5 Create base through directory UI');
 await control('assetMarket');const beforeCompanyCash=(await state()).companyFinance.air.accounts[0].balance;
 const manual=await visible('.manual-buy-asset');await manual.locator('xpath=ancestor::article[contains(@class,"asset-market-card")]').locator('.manual-asset-qty').fill('2');await manual.click();await page.waitForTimeout(350);current=await state();
 assert(!Object.prototype.hasOwnProperty.call(current.advanced.procurement,'assetRequests'));assert(current.realism.procurement.deliveries.some(d=>String(d.requestRef||'').startsWith('MANUAL-')&&d.status==='delivered'));assert(current.companyFinance.air.accounts[0].balance<beforeCompanyCash);assert(!await page.locator('[data-gh-action="asset-portfolio-build"]').count());record('6–8 Manual market purchase is paid and delivered immediately');
 const airAssets=current.assets.filter(a=>a.type==='air');assert.strictEqual(airAssets.length,2,'manual purchase must create the requested quantity atomically');for(const asset of airAssets){assert(asset.baseFacility===baseId||asset.baseId===baseId);assert.strictEqual(asset.deliveryStatus,'delivered');assert.strictEqual(asset.staffing?.mode,'automatic-fixed');assert.strictEqual(asset.staffing?.ready,true);assert.strictEqual(asset.staffing?.total,12);assert(current.advanced.labor.hiringLog.some(row=>row.assetId===asset.id));}assert.strictEqual(current.crew.find(row=>row.id==='pilots')?.count,8);assert.strictEqual(current.crew.find(row=>row.id==='cabin')?.count,12);assert.strictEqual(current.crew.find(row=>row.id==='aeng')?.count,4);const asset=airAssets[0];record('9–12 Every purchased asset receives its exact fixed crew and payroll in the same transaction');
 await control('routes');await page.click('[data-routetype="air"]');const routesBefore=current.customRoutes.length;await page.click('.dispatch-international-network[data-type="air"]');await page.waitForTimeout(350);current=await state();const dispatched=current.assets.filter(a=>airAssets.some(original=>original.id===a.id));assert(current.customRoutes.length>=routesBefore+2);assert(dispatched.every(row=>row.routeId&&row.phase==='moving'),'bulk departure must assign and depart every eligible aircraft');assert.strictEqual(new Set(dispatched.map(row=>row.routeId)).size,dispatched.length,'every aircraft must own a different route');const routeSeparation=await page.evaluate(ids=>{const rows=ids.map(id=>__GH_STATE__.customRoutes.find(route=>route.id===id));return rows.every((first,index)=>rows.slice(index+1).every(second=>!GH_ROUTE_CORE.corridorMetrics(first,second).duplicate));},dispatched.map(row=>row.routeId));assert(routeSeparation,'bulk departure produced near-duplicate corridors');const retiredKey=String.fromCharCode(97,105);assert(!Object.prototype.hasOwnProperty.call(current.advanced,retiredKey));record('13–15 One-click bulk departure is atomic and gives every asset a distinct corridor');
 await page.click('#drawerClose');await speed(0);await page.clock.runFor(400);await speed(4);const motionPoints=[];for(let frame=0;frame<16;frame++){await page.clock.runFor(100);const point=await page.locator('.asset-marker.air.is-moving,.fleet-cluster-marker.air').first().evaluate(marker=>{const box=marker.getBoundingClientRect();return [box.left+box.width/2,box.top+box.height/2];});motionPoints.push(point);}await speed(0);
 const motion=(()=>{const deltas=motionPoints.slice(1).map((point,index)=>Math.hypot(point[0]-motionPoints[index][0],point[1]-motionPoints[index][1])),maxJump=Math.max(0,...deltas);return{samples:motionPoints.length,unique:new Set(motionPoints.map(point=>point.map(value=>value.toFixed(2)).join(','))).size,maxJump,maxJumpFrame:deltas.indexOf(maxJump)+1,distance:deltas.reduce((sum,value)=>sum+value,0),deltas:deltas.map(value=>Number(value.toFixed(2)))};})();assert(motion.samples>=5&&motion.unique>=4,`high-speed marker did not interpolate across frames: ${JSON.stringify(motion)}`);if(motion.distance>2){assert(motion.maxJump<Math.max(8,motion.distance*.55),`high-speed marker jumped: ${JSON.stringify(motion)}`);assert(motion.maxJump<=12,`600x visual motion exceeded the presentation speed cap at 10 fps: ${JSON.stringify(motion)}`);}evidence.motion=motion;record('15a High-speed marker interpolation is visually rate-limited and frame-based');
 current=await state();assert(current.tripRevenueAccrued.air>=0);assert(current.tripFuelAccrued.air>=0);assert(current.tripMaintenanceAccrued.air>=0);
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('[data-gh-action="save-slot"][data-slot="0"]');
 const health=await page.evaluate(()=>({integrity:GH_INTEGRITY_CORE.check(__GH_STATE__),critical:__GH_STATE__.controlPlane.incidents.filter(i=>i.severity==='critical'&&i.status!=='resolved')}));assert.strictEqual(health.integrity.counts.critical,0,JSON.stringify(health.integrity));assert.strictEqual(health.critical.length,0,JSON.stringify(health.critical));evidence.health=health;
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('global-holdings-world-v2.0.0')));assert(saved.assets.length===current.assets.length);evidence.cash=saved.cash;evidence.simSeconds=saved.simSeconds;evidence.assetCount=saved.assets.length;evidence.deliveryCount=saved.realism.procurement.deliveries.length;evidence.routeCount=saved.customRoutes.length;evidence.journalBalanced=saved.finance.journalEntries.every(j=>Math.abs(j.lines.reduce((n,l)=>n+l.debit-l.credit,0))<.02);assert(evidence.journalBalanced);record('16–17 Save and verified persisted business state');
 await page.reload({waitUntil:'domcontentloaded'});current=await state();
 for(const key of ['cash','debt','simSeconds','assets','crew','globalBases','companyFinance','tripRevenueAccrued','tripFuelAccrued'])assert.deepStrictEqual(current[key],saved[key],'Reload mismatch: '+key);
 assert(!Object.prototype.hasOwnProperty.call(current.advanced.procurement,'assetRequests'));record('18 Reload preserves funds, assets, deliveries and manual-only policy');
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('.new-game-direct');await page.locator('#founderForm').waitFor({state:'visible'});current=await state();
 assert.strictEqual(current.cash,0);assert.strictEqual(current.debt,0);assert.strictEqual(current.groupValue,0);for(const k of ['assets','globalBases','customRoutes','openedCompanies','ownedCompanies','hired'])assert.strictEqual(current[k].length,0,k);assert(current.crew.every(c=>c.count===0));assert.strictEqual(current.finance.journalEntries.length,0);assert(!Object.prototype.hasOwnProperty.call(current.advanced.procurement,'assetRequests'));assert.strictEqual(current.onboardingComplete,false);assert.strictEqual(current.saveVersion,'2.0.0');record('19 Reset returns to verified pristine state');
 assert.deepStrictEqual(errors,[]);record('No unexpected browser errors');
 }finally{fs.mkdirSync('tests/screenshots',{recursive:true});await page.screenshot({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-last.png'});await context.tracing.stop({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-trace.zip'});await browser.close();await server.close();}
 const report={suite:'browser-lifecycle',browser:process.env.GH_BROWSER||'chromium',browserVersion:browser.version(),steps,evidence};fs.mkdirSync('.ci-output/ci',{recursive:true});fs.writeFileSync('.ci-output/ci/browser-lifecycle-'+report.browser+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exitCode=1;});
