'use strict';
const assert=require('assert'),fs=require('fs');const {chromium,webkit}=require('playwright');
const {serve}=require('./helpers/web-server'),{installMapFixture,expectedNetworkError}=require('./helpers/browser-network');
(async()=>{
 const server=await serve(),engine=process.env.GH_BROWSER==='webkit'?webkit:chromium,browser=await engine.launch({headless:true});
 const context=await browser.newContext({viewport:{width:844,height:390},locale:'ar-SA'});await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();await installMapFixture(page);await page.clock.install({time:new Date('2026-09-06T00:00:00Z')});await page.clock.pauseAt(new Date('2026-09-06T00:00:01Z'));
 // A deterministic 10 fps browser schedule exercises low-frame-rate operation.
 // The game clock, domain owners and every simulation slice remain production code.
 await page.addInitScript(()=>{window.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!expectedNetworkError(m))errors.push(m.text());});page.on('dialog',d=>d.accept());
 async function state(){return page.evaluate(()=>JSON.parse(JSON.stringify(window.__GH_STATE__)));}
 async function visible(selector){const choices=page.locator(selector);for(let i=0;i<await choices.count();i++)if(await choices.nth(i).isVisible())return choices.nth(i);throw new Error('No visible '+selector);}
 async function panel(name){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await (await visible('[data-panel="'+name+'"]')).click();}
 async function control(name){await panel('control');await page.click('[data-open="'+name+'"]');}
 async function speed(n){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await page.click('#speedToggle');await page.click('#speedMenu [data-speed="'+n+'"]');await page.click('#speedToggle');}
 const evidence={};const steps=[];function record(s){steps.push(s);console.log('E2E '+s);}
 try{
 await page.goto(server.baseURL,{waitUntil:'domcontentloaded'});
 await page.selectOption('#founderMode','sandbox');await page.locator('#founderForm button[type="submit"]').click();
 let current=await state();assert(current.onboardingComplete);assert.strictEqual(current.cash,1000000000);assert.strictEqual(current.assets.length,0);assert(current.crew.every(c=>c.count===0));record('1–2 New Group and exact capital');
 await (await visible('[data-panel="companies"]')).click();await page.click('[data-companytab="subs"]');await page.locator('button.open-company[data-type="air"]').click();
 current=await state();assert(current.openedCompanies.includes('air'));record('3 Open company');
 const initialAir=current.companyFinance.air.accounts[0].balance;await panel('finance');await page.selectOption('#companyTransferFrom','group');await page.selectOption('#companyTransferTo','air');await page.fill('#companyTransferAmount','400000000');await page.click('.company-transfer-submit');current=await state();assert.strictEqual(current.companyFinance.air.accounts[0].balance,initialAir+400000000);record('4 Fund company through Finance UI');
 await page.click('#drawerClose');await page.click('#worldDirectoryBtn');await page.fill('#worldSearch','RUH');await page.clock.runFor(300);await page.locator('.open-global-base[data-key="air:OERK"]').click();
 current=await state();assert.strictEqual(current.globalBases.length,1);const baseId=current.globalBases[0].id;assert.strictEqual(current.globalBases[0].company,'air');record('5 Create base through directory UI');
 await control('procurement');
 await page.click('[data-gh-action="asset-request-ai-recommend"]');assert(await page.inputValue('#assetRequestCatalog'));record('6 AI recommends an asset');
 await page.fill('#assetRequestQty','3');const beforeOrder=(await state()).cash;
 await page.click('[data-gh-action="asset-request-create"]');current=await state();const request=current.advanced.procurement.assetRequests[0];assert(request.study.score>0);assert.strictEqual(request.status,'awaiting_authorization');assert.strictEqual(current.cash,beforeOrder);assert.strictEqual(request.qty,3);record('7 Request and AI study without debit');
 await page.click('[data-gh-action="asset-request-authorize"][data-request="'+request.id+'"]');current=await state();const order=current.advanced.procurement.assetRequests.find(r=>r.id===request.id),orders=current.realism.procurement.deliveries.filter(d=>d.requestRef===request.id);assert.strictEqual(order.status,'delivering');assert.strictEqual(orders.length,3);assert.strictEqual(new Set(orders.map(d=>d.asset.id)).size,3);assert(orders.every(d=>d.baseId===baseId&&d.payment.ref));assert(current.cash<beforeOrder);assert.strictEqual(current.assets.length,0);record('8–10 Authorization, verified payment and exactly three pending orders');
 await speed(4);await page.clock.runFor(26000);await speed(0);current=await state();assert.strictEqual(current.assets.length,3,JSON.stringify({time:current.simSeconds,incidents:current.controlPlane?.incidents,deliveries:current.realism.procurement.deliveries}));assert(current.assets.every(a=>a.baseFacility===baseId&&a.deliveryOrderId));record('11–12 Simulated delivery of exactly three assets to selected base');
 await panel('peopleHub');await page.click('[data-open="labor"]');await page.click('[data-gh-action="hr-request-all"]');current=await state();const hire=current.advanced.ai.requests.find(r=>r.kind==='workforce-all'&&r.status==='بانتظار التفويض');assert(hire);await page.click('[data-gh-action="ai-request-delegate"][data-request="'+hire.id+'"]');current=await state();assert(current.crew.some(c=>c.count>0));assert(current.advanced.ai.executionLog.some(e=>e.requestId===hire.id));record('13–14 HR need, authorization and verified hiring');
 await control('procurement');await page.click('[data-gh-action="asset-request-retry-all"]');current=await state();assert(current.advanced.procurement.assetRequestArchive.some(r=>r.id===request.id&&r.status==='completed'));record('15 Request closes with delivery and workforce evidence');
 await page.click('#drawerClose');await page.click('#worldDirectoryBtn');await page.fill('#worldSearch','DMM');await page.clock.runFor(300);await page.locator('.open-global-route[data-key="air:OEDF"]').click();await page.locator('.create-global-route').first().click();
 current=await state();const asset=current.assets.find(a=>a.routeId);assert(asset);assert.strictEqual(asset.phase,'turnaround');assert.strictEqual(asset.baseFacility,baseId);assert(current.customRoutes.some(r=>r.id===asset.routeId));record('16 Create route through directory UI');
 await page.click('.depart-now[data-id="'+asset.id+'"]');current=await state();assert.strictEqual(current.assets.find(a=>a.id===asset.id).phase,'moving');assert.strictEqual(current.assets.find(a=>a.id===asset.id).reverse,false);record('17 Depart from the actual origin with complete crew');
 const duration=current.assets.find(a=>a.id===asset.id).tripSeconds;assert(current.assets.find(a=>a.id===asset.id).distanceKm<550,'Expected the nearby DMM destination');console.log('TRIP_SECONDS',duration);await speed(4);
 // Advance the browser clock; every production simulation slice still executes.
 for(let remaining=Math.ceil(duration/4*1000)+2500;remaining>0;){const batch=Math.min(30000,remaining);await page.clock.runFor(batch);remaining-=batch;if(remaining>0&&Math.floor(remaining/30000)%10===0)console.log('E2E trip clock remaining '+Math.ceil(remaining/1000)+'s');}
 await speed(0);current=await state();assert(current.tripRevenueAccrued.air>0);assert(current.tripFuelAccrued.air>0);assert(current.tripMaintenanceAccrued.air>0);assert(current.assets.find(a=>a.id===asset.id).lastTrip.revenue>0);record('18 Actual simulated trip produces income and operating expenses');
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('[data-gh-action="save-slot"][data-slot="0"]');
 const health=await page.evaluate(()=>({integrity:GH_INTEGRITY_CORE.check(__GH_STATE__),critical:__GH_STATE__.controlPlane.incidents.filter(i=>i.severity==='critical'&&i.status!=='resolved')}));assert.strictEqual(health.integrity.counts.critical,0,JSON.stringify(health.integrity));assert.strictEqual(health.critical.length,0,JSON.stringify(health.critical));evidence.health=health;
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('global-holdings-world-v2.0.0')));assert(saved.assets.length===3);evidence.cash=saved.cash;evidence.simSeconds=saved.simSeconds;evidence.assetCount=saved.assets.length;evidence.deliveryCount=saved.realism.procurement.deliveries.length;evidence.routeCount=saved.customRoutes.length;evidence.journalBalanced=saved.finance.journalEntries.every(j=>Math.abs(j.lines.reduce((n,l)=>n+l.debit-l.credit,0))<.02);assert(evidence.journalBalanced);record('19 Save and verified persisted business state');
 await page.reload({waitUntil:'domcontentloaded'});current=await state();
 for(const key of ['cash','debt','simSeconds','assets','crew','globalBases','companyFinance','tripRevenueAccrued','tripFuelAccrued'])assert.deepStrictEqual(current[key],saved[key],'Reload mismatch: '+key);
 assert.strictEqual(current.advanced.procurement.assetRequestArchive.length,saved.advanced.procurement.assetRequestArchive.length);record('20 Reload preserves funds, assets, crew, requests and operating results');
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('.new-game-direct');await page.locator('#founderForm').waitFor({state:'visible'});current=await state();
 assert.strictEqual(current.cash,0);assert.strictEqual(current.debt,0);assert.strictEqual(current.groupValue,0);for(const k of ['assets','globalBases','customRoutes','openedCompanies','ownedCompanies','hired'])assert.strictEqual(current[k].length,0,k);assert(current.crew.every(c=>c.count===0));assert.strictEqual(current.finance.journalEntries.length,0);assert.strictEqual(current.advanced.procurement.assetRequests.length,0);assert.strictEqual(current.onboardingComplete,false);assert.strictEqual(current.saveVersion,'2.0.0');record('21 Reset returns to verified pristine state');
 assert.deepStrictEqual(errors,[]);record('No unexpected browser errors');
 }finally{fs.mkdirSync('tests/screenshots',{recursive:true});await page.screenshot({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-last.png'});await context.tracing.stop({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-trace.zip'});await browser.close();await server.close();}
 const report={suite:'browser-lifecycle',browser:process.env.GH_BROWSER||'chromium',browserVersion:browser.version(),steps,evidence};fs.mkdirSync('build/ci',{recursive:true});fs.writeFileSync('build/ci/browser-lifecycle-'+report.browser+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exitCode=1;});
