'use strict';
const assert=require('assert'),fs=require('fs');const {chromium,webkit}=require('playwright');
const {serve}=require('./helpers/web-server'),{installMapFixture,expectedNetworkError}=require('./helpers/browser-network');
(async()=>{
 const server=await serve(),engine=process.env.GH_BROWSER==='webkit'?webkit:chromium,browser=await engine.launch({headless:true});
 const context=await browser.newContext({viewport:{width:844,height:390},locale:'ar-SA'});await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();await installMapFixture(page);await page.clock.install({time:new Date('2026-09-06T00:00:00Z')});await page.clock.pauseAt(new Date('2026-09-06T00:00:01Z'));
 // A deterministic 10 fps browser schedule exercises low-frame-rate operation.
 // The game clock, domain owners and every simulation slice remain production code.
 await page.addInitScript(()=>{window.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!expectedNetworkError(m))errors.push(m.text());});page.on('dialog',d=>d.accept());
 async function state(){return page.evaluate(()=>JSON.parse(JSON.stringify(window.__GH_STATE__)));}
 async function visible(selector){const choices=page.locator(selector);for(let i=0;i<await choices.count();i++)if(await choices.nth(i).isVisible())return choices.nth(i);throw new Error('No visible '+selector);}
 async function panel(name){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await (await visible('[data-panel="'+name+'"]')).click();}
 async function control(name){await panel('control');await page.click('[data-open="'+name+'"]');}
 async function speed(n){if(await page.locator('#drawer').getAttribute('aria-hidden')==='false')await page.click('#drawerClose');await page.click('#speedToggle');await page.click('#speedMenu [data-speed="'+n+'"]');await page.click('#speedToggle');}
 const evidence={};const steps=[];function record(s){steps.push(s);console.log('E2E '+s);}
 try{
 await page.goto(server.baseURL,{waitUntil:'domcontentloaded'});
 await page.selectOption('#founderMode','sandbox');await page.locator('#founderForm button[type="submit"]').click();
 let current=await state();assert(current.onboardingComplete);assert.strictEqual(current.cash,1000000000);assert.strictEqual(current.assets.length,0);assert(current.crew.every(c=>c.count===0));record('1–2 New Group and exact capital');
 await (await visible('[data-panel="companies"]')).click();await page.click('[data-companytab="subs"]');await page.locator('button.open-company[data-type="air"]').click();
 current=await state();assert(current.openedCompanies.includes('air'));record('3 Open company');
 const initialAir=current.companyFinance.air.accounts[0].balance;await panel('finance');await page.selectOption('#companyTransferFrom','group');await page.selectOption('#companyTransferTo','air');await page.fill('#companyTransferAmount','400000000');await page.click('.company-transfer-submit');current=await state();assert.strictEqual(current.companyFinance.air.accounts[0].balance,initialAir+400000000);record('4 Fund company through Finance UI');
 await page.click('#drawerClose');await page.click('#worldDirectoryBtn');await page.fill('#worldSearch','RUH');await page.clock.runFor(300);await page.locator('.open-global-base[data-key="air:OERK"]').click();
 current=await state();assert.strictEqual(current.globalBases.length,1);const baseId=current.globalBases[0].id;assert.strictEqual(current.globalBases[0].company,'air');record('5 Create base through directory UI');
 await control('assets');const beforeCompanyCash=(await state()).companyFinance.air.accounts[0].balance;
 const manual=await visible('.manual-buy-asset');await manual.click();await page.waitForTimeout(350);current=await state();
 assert.strictEqual(current.advanced.procurement.assetRequests.length,0);assert(current.realism.procurement.deliveries.some(d=>String(d.requestRef||'').startsWith('MANUAL-')));assert(current.companyFinance.air.accounts[0].balance<beforeCompanyCash);assert(!await page.locator('[data-gh-action="asset-portfolio-build"]').count());record('6–8 Manual market purchase records delivery and debits the owning company');
 await page.click('#drawerClose');await speed(4);let deliverySteps=0;while(deliverySteps<180){current=await state();if(current.assets.some(a=>a.type==='air'))break;await page.clock.runFor(1000);deliverySteps++;}current=await state();const asset=current.assets.find(a=>a.type==='air');assert(asset,'manual delivery did not create an asset');assert(asset.baseFacility===baseId||asset.baseId===baseId);record('9–12 Delivery reaches the selected base before route assignment');
 await control('routes');const routesBefore=current.customRoutes.length;await page.click('.suggest-routes');await page.waitForTimeout(250);current=await state();assert(current.customRoutes.length===routesBefore);assert(Array.isArray(current.advanced.routeSuggestions));assert(!current.assets.some(a=>a.routeId&&a.phase==='moving'),'AI suggestion must not depart assets');record('13–15 AI route suggestions are advisory and do not mutate or depart assets');
 await page.click('#drawerClose');await speed(0);current=await state();assert(current.tripRevenueAccrued.air>=0);assert(current.tripFuelAccrued.air>=0);assert(current.tripMaintenanceAccrued.air>=0);
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('[data-gh-action="save-slot"][data-slot="0"]');
 const health=await page.evaluate(()=>({integrity:GH_INTEGRITY_CORE.check(__GH_STATE__),critical:__GH_STATE__.controlPlane.incidents.filter(i=>i.severity==='critical'&&i.status!=='resolved')}));assert.strictEqual(health.integrity.counts.critical,0,JSON.stringify(health.integrity));assert.strictEqual(health.critical.length,0,JSON.stringify(health.critical));evidence.health=health;
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('global-holdings-world-v2.0.0')));assert(saved.assets.length===current.assets.length);evidence.cash=saved.cash;evidence.simSeconds=saved.simSeconds;evidence.assetCount=saved.assets.length;evidence.deliveryCount=saved.realism.procurement.deliveries.length;evidence.routeCount=saved.customRoutes.length;evidence.journalBalanced=saved.finance.journalEntries.every(j=>Math.abs(j.lines.reduce((n,l)=>n+l.debit-l.credit,0))<.02);assert(evidence.journalBalanced);record('16–17 Save and verified persisted business state');
 await page.reload({waitUntil:'domcontentloaded'});current=await state();
 for(const key of ['cash','debt','simSeconds','assets','crew','globalBases','companyFinance','tripRevenueAccrued','tripFuelAccrued'])assert.deepStrictEqual(current[key],saved[key],'Reload mismatch: '+key);
 assert.strictEqual(current.advanced.procurement.assetRequests.length,0);record('18 Reload preserves funds, assets, deliveries and manual-only policy');
 await panel('systemHub');await page.locator('[data-open="settings"]').first().click();await page.click('.new-game-direct');await page.locator('#founderForm').waitFor({state:'visible'});current=await state();
 assert.strictEqual(current.cash,0);assert.strictEqual(current.debt,0);assert.strictEqual(current.groupValue,0);for(const k of ['assets','globalBases','customRoutes','openedCompanies','ownedCompanies','hired'])assert.strictEqual(current[k].length,0,k);assert(current.crew.every(c=>c.count===0));assert.strictEqual(current.finance.journalEntries.length,0);assert.strictEqual(current.advanced.procurement.assetRequests.length,0);assert.strictEqual(current.onboardingComplete,false);assert.strictEqual(current.saveVersion,'2.0.0');record('19 Reset returns to verified pristine state');
 assert.deepStrictEqual(errors,[]);record('No unexpected browser errors');
 }finally{fs.mkdirSync('tests/screenshots',{recursive:true});await page.screenshot({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-last.png'});await context.tracing.stop({path:'tests/screenshots/e2e-'+(process.env.GH_BROWSER||'chromium')+'-trace.zip'});await browser.close();await server.close();}
 const report={suite:'browser-lifecycle',browser:process.env.GH_BROWSER||'chromium',browserVersion:browser.version(),steps,evidence};fs.mkdirSync('.ci-output/ci',{recursive:true});fs.writeFileSync('.ci-output/ci/browser-lifecycle-'+report.browser+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exitCode=1;});
