const assert=require('assert');
global.GH_EVENT_LEDGER=require('../WebApp/event-ledger-core.js');
global.GH_DEPENDENCY_CORE=require('../WebApp/dependency-core.js');
global.GH_POLICY_CORE=require('../WebApp/policy-core.js');
global.GH_LIFECYCLE_CORE=require('../WebApp/lifecycle-core.js');
global.GH_DEMAND_CLOSURE=require('../WebApp/demand-closure-core.js');
global.GH_INTEGRITY_CORE=require('../WebApp/integrity-core.js');
const state={simSeconds:100,advanced:{procurement:{assetRequests:[],assetRequestArchive:[],assetClosureLog:[]},ai:{requests:[],requestArchive:[]}},realism:{procurement:{deliveries:[]}},assets:[]};
const r={id:'AR-1',status:'awaiting_review',linkedRequests:[],qty:2,company:'air',createdHour:0};
state.advanced.procurement.assetRequests.push(r);
GH_LIFECYCLE_CORE.transition(state,r,'assetRequest','awaiting_authorization',{event:'AI_STUDY_COMPLETED'});
GH_LIFECYCLE_CORE.transition(state,r,'assetRequest','authorized',{event:'AUTHORIZED'});
assert.throws(()=>GH_LIFECYCLE_CORE.transition(state,r,'assetRequest','completed',{}),/rejected/,'invalid lifecycle jump must fail');
const dep={id:'AI-FUND-1',status:'بانتظار التفويض',kind:'funding'};state.advanced.ai.requests.push(dep);r.linkedRequests.push(dep.id);GH_DEPENDENCY_CORE.link(state,r.id,dep.id,'funding');
let c=GH_DEMAND_CLOSURE.reconcile(state);assert.strictEqual(c.open,1);assert.strictEqual(GH_DEPENDENCY_CORE.unresolved(state,r.id).length,1);
assert.strictEqual(GH_DEMAND_CLOSURE.canClose(state,r,{staffingGap:0}).approved,false,'closure with open dependency must fail');
dep.status='منفذ';state.advanced.ai.requests=[];state.advanced.ai.requestArchive.push(dep);GH_DEMAND_CLOSURE.reconcile(state);assert.strictEqual(GH_DEPENDENCY_CORE.unresolved(state,r.id).length,0);
assert(GH_EVENT_LEDGER.summary(state).count>=2,'lifecycle transitions were not journaled');
assert.strictEqual(GH_INTEGRITY_CORE.check(state).counts.critical,0,'healthy lifecycle produced critical integrity issue');
console.log('Core Business Lifecycle 2.3.9: PASS');
