const assert=require('assert');
global.GH_TRANSACTION_CORE={VERSION:'2.9.0',execute(){}};
global.GH_SIMULATION_CORE={VERSION:'2.9.0',create(){}};
global.GH_SAVE_SCHEMA={VERSION:'2.9.0',normalize(){}};
global.GH_DETERMINISM={VERSION:'2.9.0'};
global.GH_REQUEST_CORE={VERSION:'2.9.0'};global.GH_LIFECYCLE_CORE={VERSION:'2.9.0',validate(){return true}};global.GH_POLICY_CORE={VERSION:'2.9.0'};global.GH_DEPENDENCY_CORE={VERSION:'2.9.0',detectCycles(){return []}};global.GH_EVENT_LEDGER={VERSION:'2.9.0',summary(){return {count:0}}};global.GH_DEMAND_CLOSURE={VERSION:'2.9.0',reconcile(){return {closureRate:100}}};global.GH_INTEGRITY_CORE={VERSION:'2.9.0',check(){return {issues:[],counts:{critical:0,warning:0,total:0},status:'healthy'}}};
const d=require('../WebApp/diagnostics-core.js');
const state={simSeconds:0,speed:1,saveVersion:'2.0.0',cash:1,debt:0,groupValue:1,assets:[],finance:{companyBooks:{},receivables:[],payables:[],invoices:[],cheques:[]},advanced:{ai:{}},simulationKernel:{},diagnostics:{}};
let r=d.runHealthCheck(state,{simulation:{}},{recordEvent:false,trackTransitions:true});
assert.equal(r.status,'healthy');
assert.equal(Object.keys(state.diagnostics.activeIssues).length,0);
state.assets=[{id:'A',condition:90},{id:'A',condition:90}];
r=d.runHealthCheck(state,{simulation:{}},{recordEvent:false,trackTransitions:true});
assert(r.issues.some(x=>x.id==='ASSET_DUPLICATE_IDS'));
assert(state.diagnostics.events.some(x=>x.type==='ISSUE_OPEN'&&x.detail.id==='ASSET_DUPLICATE_IDS'));
assert(state.diagnostics.activeIssues.ASSET_DUPLICATE_IDS);
state.assets=[{id:'A',condition:90}];
r=d.runHealthCheck(state,{simulation:{}},{recordEvent:false,trackTransitions:true});
assert(!r.issues.some(x=>x.id==='ASSET_DUPLICATE_IDS'));
assert(state.diagnostics.events.some(x=>x.type==='ISSUE_RESOLVED'&&x.detail.id==='ASSET_DUPLICATE_IDS'));
assert(!state.diagnostics.activeIssues.ASSET_DUPLICATE_IDS);
assert(state.diagnostics.resolvedIssues.some(x=>x.id==='ASSET_DUPLICATE_IDS'));
d.clear(state);
assert.equal(state.diagnostics.events.length,0);
assert.equal(state.diagnostics.resolvedIssues.length,0);
assert.equal(Object.keys(state.diagnostics.activeIssues).length,0);
assert.equal(state.diagnostics.lastHealth,null);
const fs=require('fs'); const app=fs.readFileSync('WebApp/app.js','utf8'); const adv=fs.readFileSync('WebApp/advanced-core.js','utf8');
assert(/if\(activeDrawerPanel==='diagnostics'\)openDrawer\('diagnostics'\)/.test(app),'Open diagnostics panel must live-refresh');
assert(/ctx\.clearDiagnostics\?\.\(\);ctx\.save\?\.\(\);/.test(adv),'Clear must persist immediately');
assert(!/RECENT_CRITICAL_EVENTS/.test(fs.readFileSync('WebApp/diagnostics-core.js','utf8')),'Historical critical events must not masquerade as current health issues');
console.log('Diagnostics lifecycle 2.3.9: PASS');
