const fs=require('fs');
const assert=(x,m)=>{if(!x)throw new Error(m);};
const project=fs.readFileSync('project.yml','utf8');
const storage=fs.readFileSync('iOS/GlobalHoldings/GlobalGameStorage.swift','utf8');
const app=fs.readFileSync('WebApp/app.js','utf8');
assert(project.includes('MARKETING_VERSION: "2.9.1"'),'MARKETING_VERSION must match current release');
assert(project.includes('CURRENT_PROJECT_VERSION: "'+fs.readFileSync('BUILD','utf8').trim()+'"'),'CURRENT_PROJECT_VERSION must match current release');
assert(project.includes('CFBundleShortVersionString: "2.9.1"'),'Info.plist marketing version mismatch');
assert(project.includes('CFBundleVersion: "'+fs.readFileSync('BUILD','utf8').trim()+'"'),'Info.plist build mismatch');
assert(storage.includes('?? "2.9.1"'),'Native bundled version fallback mismatch');
assert(app.includes("const APP_VERSION = '2.9.1'"),'WebApp version mismatch');
console.log('Native metadata current release guard: PASS');
