'use strict';
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');const {serve}=require('./helpers/web-server');
(async()=>{const server=await serve(path.resolve(__dirname,'../WebApp')),browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']}),page=await browser.newPage({viewport:{width:844,height:390},deviceScaleFactor:2}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(server.baseURL);
 await page.evaluate(()=>{
  const types=['air','sea','road','power','bank','mobility'],seed={simSeconds:365*86400,openedCompanies:types,profile:{name:'المجموعة العالمية القابضة',founder:'بدر العنزي',reputation:75},hired:[],assets:[],globalBases:[],customHubs:[],bank:{branches:32},energy:{solarMW:250},mobility:{vehicles:[]},companyRegistry:{}};const migrated=GH_COMPANY_PLATFORM.migrateState(seed);if(migrated.errors.length)throw new Error(`visual-company-fixture:${migrated.errors.join(',')}`);const s=migrated.state;GH_FINANCE_CORE.ensure(s);GH_HR_CORE.ensure(s);types.forEach(type=>{const c=GH_HR_CORE.OFFICIAL_MANAGER_CANDIDATES.find(c=>c.company===type);GH_HR_CORE.appointOfficialManager(s,{company:type,candidateId:c.id});});
  for(let day=0;day<365;day++)GH_FINANCE_CORE.execute({state:s},'record-daily-close',{day,net:270000,companies:Object.fromEntries(types.map((t,i)=>[t,{grossRevenue:100000+i*10000,expenses:80000,net:20000+i*10000}]))});
  window.qaSnapshot=GH_CONFERENCE.buildSnapshot(s,2026);window.qaConfig={snapshot:qaSnapshot,conferenceId:'QA-334-SYNTHETIC'};window.qaSession=GH_CONFERENCE_3D.launch(qaConfig,{mode:'manual'});
 });await page.waitForFunction(()=>GH_CONFERENCE_3D.diagnostics().assetsReady&&GH_CONFERENCE_3D.diagnostics().frames>0);
 const out=path.resolve(__dirname,'../verification');fs.mkdirSync(out,{recursive:true});const shot=async name=>{await page.waitForFunction(()=>!GH_CONFERENCE_3D.diagnostics().scheduledFrame);await page.screenshot({path:path.join(out,name+'.png')});};
 await shot('334-opening-iphone');await page.locator('[data-c3="next"]').click();await shot('334-results-iphone');
 const layout=await page.evaluate(()=>{const r=document.querySelector('.ghc3-viewport').getBoundingClientRect();return{width:innerWidth,height:innerHeight,contentHeight:r.height,contentShare:r.height/innerHeight,hasOverflow:document.querySelector('.ghc3').scrollWidth>innerWidth,font:GH_CONFERENCE_3D.diagnostics().fontReady,chart:[...document.querySelectorAll('.ghc3-bar')].map(x=>Number(x.dataset.value)),stats:document.querySelector('.ghc3-stats').textContent};});assert(layout.contentShare>.75);assert(!layout.hasOverflow);assert(layout.font);assert.deepEqual(layout.chart,[273750000,175200000,98550000]);
 for(const [view,name] of [['podium','334-stage-iphone'],['wide','334-hall-iphone'],['host','334-presenter-iphone']]){await page.locator(`[data-c3="camera-${view}"]`).click();await shot(name);}
 await page.setViewportSize({width:1440,height:810});await page.locator('[data-c3="camera-wide"]').click();await shot('334-hall-desktop');await page.locator('[data-c3="camera-podium"]').click();await shot('334-stage-desktop');await page.locator('[data-c3="camera-host"]').click();await shot('334-presenter-desktop');
 await page.setViewportSize({width:844,height:390});await page.locator('[data-c3="camera-screen"]').click();await page.locator('[data-c3="chapters"]').click();await page.locator('[data-c3="scene-25"]').click();await shot('334-closing-iphone');
	 const dense=await page.evaluate(()=>{const c=document.querySelector('.ghc3-chart').getBoundingClientRect(),stats=[...document.querySelectorAll('.ghc3-stats>div')].map(row=>({value:row.querySelector('b')?.textContent||'',label:row.querySelector('span')?.textContent||''}));return{stats,expectedAttendees:GH_CONF_MODEL.int(qaSnapshot.social?.attendees),rows:[...document.querySelectorAll('.ghc3-bar,.ghc3-chart>header')].map(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom};}),bounds:{top:c.top,bottom:c.bottom}};});assert.equal(dense.stats.find(row=>row.label==='الحضور')?.value,dense.expectedAttendees);assert(dense.rows.every(r=>r.top>=dense.bounds.top&&r.bottom<=dense.bounds.bottom));

 const before=await page.evaluate(()=>JSON.stringify(qaSnapshot));await page.evaluate(()=>{GH_CONFERENCE_3D.close();const s=structuredClone(qaSnapshot);s.group.reportedDays=35;s.group.prior={reportedDays:365};s.group.growth={revenue:800};s.group.net=-4200000;s.group.grossRevenue=1000000;s.group.expenses=5200000;s.group.complete=false;window.qaLoss=s;window.qaSession=GH_CONFERENCE_3D.launch({snapshot:s},{mode:'manual',startScene:1});});await page.waitForFunction(()=>GH_CONFERENCE_3D.diagnostics().frames>0);await shot('334-loss-iphone');assert.equal(await page.evaluate(()=>JSON.stringify(qaSnapshot)),before);
 const loss=await page.evaluate(()=>({values:[...document.querySelectorAll('.ghc3-bar')].map(x=>Number(x.dataset.value)),stats:document.querySelector('.ghc3-stats').textContent,negative:document.querySelectorAll('.ghc3-bar')[2].querySelector('.ghc3-fill').style.width}));assert.equal(loss.values[2],-4200000);assert.match(loss.stats,/غير متاح/);assert.notEqual(loss.negative,'0%');
 await page.evaluate(()=>{GH_CONFERENCE_3D.close();const s=structuredClone(qaSnapshot);s.group.reportedDays=0;s.group.dataQuality={status:'empty',reason:'لا توجد إقفالات مالية معتمدة.'};s.companies=[];window.qaSession=GH_CONFERENCE_3D.launch({snapshot:s},{mode:'manual',startScene:1});});await page.waitForFunction(()=>GH_CONFERENCE_3D.diagnostics().frames>0);await shot('334-empty-iphone');assert.equal(await page.locator('.ghc3-bar').count(),0);
 await page.setViewportSize({width:390,height:844});await shot('334-empty-portrait');await page.evaluate(()=>GH_CONFERENCE_3D.close());
 // Close during asynchronous model decode; no detached resources, callbacks, or stale overlays.
 await page.evaluate(async()=>{const s=GH_CONFERENCE_3D.launch(qaConfig,{mode:'manual'});s.close(false);await s.ready;window.disposedLate={active:GH_CONFERENCE_3D.isActive(),pool:s.world.pool.items.size,memory:{...s.renderer.info.memory}};});const late=await page.evaluate(()=>disposedLate);assert.equal(late.active,false);assert.equal(late.pool,0);assert.equal(late.memory.geometries,0);assert.equal(late.memory.textures,0);
 assert.deepEqual(errors,[]);const report={layout,dense,loss,late,errors,fixture:'Synthetic QA state, closed with production finance core. Not embedded in the app.'};fs.writeFileSync(path.join(out,'334-visual-validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await server.close();})().catch(e=>{console.error(e);process.exit(1)});
