const fs=require('fs'),vm=require('vm');
const assert=(x,m)=>{if(!x)throw new Error(m)};
const index=fs.readFileSync('WebApp/index.html','utf8');
const advanced=fs.readFileSync('WebApp/advanced-core.js','utf8');
const app=fs.readFileSync('WebApp/app.js','utf8');
assert(index.includes('ui-quality-core.js'),'ui-quality-core.js is not loaded');
assert(index.indexOf('ui-quality-core.js')<index.indexOf('advanced-core.js'),'UI quality core must load before advanced-core');
assert(advanced.includes("actionCenter:['القيادة التنفيذية','مركز المهام والقرارات']"),'Action Center meta is missing');
assert(advanced.includes('function renderActionCenter(ctx)'),'Action Center renderer is missing');
assert(advanced.includes("['actionCenter','NOW','مركز القرار اليومي'"),'Leadership hub does not expose Action Center');
assert(app.includes("'actionCenter'"),'app.js does not own Action Center as an advanced panel');
assert(advanced.includes('<h3>5 · المحلل التنفيذي</h3>'),'AI section numbering was not repaired');
assert(fs.readFileSync('WebApp/diagnostics-core.js','utf8').includes('actionCenter:{count:actionTasks.length'),'Diagnostics bundle does not include Action Center tasks');
const businessDateNow=advanced.split('\n').filter((line,i)=>line.includes('Date.now()') && i+1<730);
assert(businessDateNow.length===0,'Wall-clock Date.now() remains in business execution paths: '+businessDateNow.join('\n'));
const sandbox={globalThis:{},window:{},module:{exports:{}},console};sandbox.globalThis.window=sandbox.window;sandbox.window=sandbox.globalThis;
vm.runInNewContext(fs.readFileSync('WebApp/ui-quality-core.js','utf8'),sandbox);
const core=sandbox.module.exports;
const state={simSeconds:1000,advanced:{ai:{requests:[{id:'AI-1',title:'قرار تمويل',status:'بانتظار التفويض',priority:'critical'}]},procurement:{assetRequests:[{id:'AR-1',title:'طلب طائرة',status:'awaiting_authorization',blockers:[]}]},audit:{findings:2},legal:{openCases:1},safety:{incidents:0},cyber:{incidents:0}},realism:{procurement:{deliveries:[]}},diagnostics:{activeIssues:{}}};
const tasks=core.collectTasks(state);
assert(tasks.some(x=>x.id==='AI:AI-1'&&x.priority==='critical'),'AI pending task missing');
assert(tasks.some(x=>x.id==='AR:AR-1'&&x.panel==='procurement'),'Asset request task missing');
assert(tasks.some(x=>x.id==='AUDIT:OPEN'),'Audit exception task missing');
console.log('System Completion 2.3.9: PASS');
