(()=>{
  'use strict';
  const VERSION='1.0.0',SCHEMA='gh-authorization-v1',MAX_SIGNATURE_BYTES=32768,LIMITS=Object.freeze({people:64,visualSeals:256,visualSealsPerPerson:32,mandates:512,proofs:4000,archiveBytes:8*1024*1024});
  const clone=value=>value===undefined?undefined:(globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value)));
  const clean=(value,max=160)=>String(value??'').trim().slice(0,max);
  const now=state=>Math.max(0,Number(state?.simSeconds)||0);
  function stable(value){
    const stack=new WeakSet();
    const encode=current=>{
      if(current===undefined||typeof current==='function'||typeof current==='symbol'||typeof current==='bigint')throw new Error('authorization-unsupported-value');
      if(current===null)return'null';
      if(typeof current==='string'||typeof current==='boolean')return JSON.stringify(current);
      if(typeof current==='number'){if(!Number.isFinite(current))throw new Error('authorization-non-finite-value');return Object.is(current,-0)?'0':JSON.stringify(current);}
      if(typeof current!=='object')throw new Error('authorization-unsupported-value');
      if(stack.has(current))throw new Error('authorization-cyclic-value');stack.add(current);
      try{
        if(Array.isArray(current)){const values=[];for(let index=0;index<current.length;index++)values.push(encode(current[index]));return`[${values.join(',')}]`;}
        if(Object.prototype.toString.call(current)!=='[object Object]'||Object.getOwnPropertySymbols(current).length)throw new Error('authorization-non-json-object');
        return`{${Object.keys(current).sort().map(key=>`${JSON.stringify(key)}:${encode(current[key])}`).join(',')}}`;
      }finally{stack.delete(current);}
    };
    return encode(value);
  }
  function fallbackSha256(text){
    const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2],H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
    const bytes=[...new TextEncoder().encode(String(text))],bitLen=bytes.length*8;bytes.push(0x80);while(bytes.length%64!==56)bytes.push(0);const hi=Math.floor(bitLen/0x100000000),lo=bitLen>>>0;for(let i=3;i>=0;i--)bytes.push((hi>>>(i*8))&255);for(let i=3;i>=0;i--)bytes.push((lo>>>(i*8))&255);const rotr=(x,n)=>(x>>>n)|(x<<(32-n));
    for(let off=0;off<bytes.length;off+=64){const w=new Array(64);for(let i=0;i<16;i++)w[i]=((bytes[off+i*4]<<24)|(bytes[off+i*4+1]<<16)|(bytes[off+i*4+2]<<8)|bytes[off+i*4+3])>>>0;for(let i=16;i<64;i++){const s0=(rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3))>>>0,s1=(rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10))>>>0;w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}let [a,b,c,d,e,f,g,h]=H;for(let i=0;i<64;i++){const s1=(rotr(e,6)^rotr(e,11)^rotr(e,25))>>>0,ch=((e&f)^((~e)&g))>>>0,t1=(h+s1+ch+K[i]+w[i])>>>0,s0=(rotr(a,2)^rotr(a,13)^rotr(a,22))>>>0,maj=((a&b)^(a&c)^(b&c))>>>0,t2=(s0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}H[0]=(H[0]+a)>>>0;H[1]=(H[1]+b)>>>0;H[2]=(H[2]+c)>>>0;H[3]=(H[3]+d)>>>0;H[4]=(H[4]+e)>>>0;H[5]=(H[5]+f)>>>0;H[6]=(H[6]+g)>>>0;H[7]=(H[7]+h)>>>0;}
    return H.map(value=>value.toString(16).padStart(8,'0')).join('');
  }
  function digest(value){const text=typeof value==='string'?value:stable(value),owner=globalThis.GH_CONTROL_PLANE?.sha256;return owner?owner(text):fallbackSha256(text);}
  function ensure(state){
    if(!state||typeof state!=='object'||Array.isArray(state))throw new TypeError('authorization-state-required');
    state.authorization=state.authorization&&typeof state.authorization==='object'&&!Array.isArray(state.authorization)?state.authorization:{};
    const auth=state.authorization;auth.schema=SCHEMA;auth.version=1;auth.peopleById=auth.peopleById&&typeof auth.peopleById==='object'&&!Array.isArray(auth.peopleById)?auth.peopleById:{};auth.visualSealAssetsById=auth.visualSealAssetsById&&typeof auth.visualSealAssetsById==='object'&&!Array.isArray(auth.visualSealAssetsById)?auth.visualSealAssetsById:(auth.signatureAssetsById&&typeof auth.signatureAssetsById==='object'&&!Array.isArray(auth.signatureAssetsById)?auth.signatureAssetsById:{});auth.activeVisualSealByPerson=auth.activeVisualSealByPerson&&typeof auth.activeVisualSealByPerson==='object'&&!Array.isArray(auth.activeVisualSealByPerson)?auth.activeVisualSealByPerson:(auth.activeSignatureByPerson&&typeof auth.activeSignatureByPerson==='object'&&!Array.isArray(auth.activeSignatureByPerson)?auth.activeSignatureByPerson:{});auth.signatureAssetsById=auth.visualSealAssetsById;auth.activeSignatureByPerson=auth.activeVisualSealByPerson;auth.mandatesById=auth.mandatesById&&typeof auth.mandatesById==='object'&&!Array.isArray(auth.mandatesById)?auth.mandatesById:{};auth.proofsById=auth.proofsById&&typeof auth.proofsById==='object'&&!Array.isArray(auth.proofsById)?auth.proofsById:{};auth.proofSequence=Math.max(0,Math.floor(Number(auth.proofSequence)||0));return auth;
  }
  function proofRecord(state,id){const a=state?.authorization||{},hot=a.proofsById?.[id],cold=a.proofArchiveById?.[id];return hot&&cold?null:(hot||cold||null);}
  function proofRecords(state){const a=state?.authorization||{};return [...Object.values(a.proofsById||{}),...Object.values(a.proofArchiveById||{})];}
  function archiveProofsForAdmission(state){
    const auth=ensure(state);if(Object.keys(auth.proofsById).length<LIMITS.proofs)return;
    const next={...(auth.proofArchiveById||{})},moving=Object.values(auth.proofsById).sort((a,b)=>(Number(a.signedAtSim)||0)-(Number(b.signedAtSim)||0)||String(a.id).localeCompare(String(b.id))).slice(0,200);
    for(const row of moving){if(Object.prototype.hasOwnProperty.call(next,row.id))throw new Error('authorization-proof-residency-conflict');next[row.id]=row;}
    if(new TextEncoder().encode(JSON.stringify(next)).byteLength>LIMITS.archiveBytes)throw new Error('authorization-proof-archive-byte-limit');
    const nextHot={...auth.proofsById};for(const row of moving)delete nextHot[row.id];auth.proofArchiveById=next;auth.proofsById=nextHot;
  }
  function compact(state,targets={}){const auth=ensure(state),proofTarget=Math.max(0,Math.floor(Number.isFinite(Number(targets.proofs))?Number(targets.proofs):LIMITS.proofs-200)),sealTarget=Math.max(0,Math.floor(Number.isFinite(Number(targets.visualSeals))?Number(targets.visualSeals):LIMITS.visualSeals)),ownerSealTarget=Math.max(0,Math.floor(Number.isFinite(Number(targets.visualSealsPerPerson))?Number(targets.visualSealsPerPerson):LIMITS.visualSealsPerPerson)),mandateTarget=Math.max(0,Math.floor(Number.isFinite(Number(targets.mandates))?Number(targets.mandates):LIMITS.mandates)),referencedProofs=new Set();for(const row of (globalThis.GH_DOCUMENT_PROOF?.records?.(state)||Object.values(state.documentProofs?.recordsById||{})))if(row?.authorizationProofId)referencedProofs.add(row.authorizationProofId);for(const row of state.domainRuntime?.commands||[])if(row?.authorizationProofId)referencedProofs.add(row.authorizationProofId);for(const row of Object.values(state.domainRuntime?.idempotency||{}))if(row?.result?.authorizationProofId)referencedProofs.add(row.result.authorizationProofId);const proofRows=Object.values(auth.proofsById),removableProofs=proofRows.filter(row=>!referencedProofs.has(row.id)).sort((a,b)=>(Number(a.signedAtSim)||0)-(Number(b.signedAtSim)||0)||String(a.id).localeCompare(String(b.id))),proofRemove=Math.max(0,proofRows.length-proofTarget);for(const row of removableProofs.slice(0,proofRemove))delete auth.proofsById[row.id];for(const id of Object.keys(auth.proofArchiveById||{}))if(!referencedProofs.has(id))delete auth.proofArchiveById[id];const referencedSeals=new Set(proofRecords(state).map(row=>row.visualSealAssetId||row.signatureAssetId).filter(Boolean));for(const id of Object.values(auth.activeSignatureByPerson))referencedSeals.add(id);let sealRemoved=0;for(const row of Object.values(auth.signatureAssetsById).sort((a,b)=>(Number(a.createdAtSim)||0)-(Number(b.createdAtSim)||0))){const ownerCount=Object.values(auth.signatureAssetsById).filter(item=>item.ownerPersonId===row.ownerPersonId).length;if(ownerCount<=ownerSealTarget&&Object.keys(auth.signatureAssetsById).length<=sealTarget)continue;if(!referencedSeals.has(row.id)&&row.status!=='active'){delete auth.signatureAssetsById[row.id];sealRemoved++;}}const referencedMandates=new Set(proofRecords(state).map(row=>row.mandateId).filter(Boolean));let mandateRemoved=0;for(const row of Object.values(auth.mandatesById).sort((a,b)=>(Number(a.createdAtSim)||0)-(Number(b.createdAtSim)||0))){if(Object.keys(auth.mandatesById).length<=mandateTarget)break;if(row.status!=='active'&&!referencedMandates.has(row.id)){delete auth.mandatesById[row.id];mandateRemoved++;}}return {proofs:Object.keys(auth.proofsById).length,proofsRemoved:Math.min(proofRemove,removableProofs.length),visualSeals:Object.keys(auth.signatureAssetsById).length,visualSealsRemoved:sealRemoved,mandates:Object.keys(auth.mandatesById).length,mandatesRemoved:mandateRemoved};}
  function upsertPerson(state,input={}){const auth=ensure(state),id=clean(input.id||input.personId,80);if(!id)throw new Error('authorization-person-id-required');const prior=auth.peopleById[id]||{},row={id,legalName:clean(input.legalName??prior.legalName,180),displayName:clean(input.displayName??prior.displayName??input.legalName??prior.legalName,180),role:clean(input.role??prior.role??'signatory',80),status:clean(input.status??prior.status??'active',24)||'active'};if(!row.legalName)throw new Error('authorization-person-name-required');if(!prior.id&&Object.keys(auth.peopleById).length>=LIMITS.people)throw new Error('authorization-people-limit');auth.peopleById[id]=row;return clone(row);}
  function ensurePrincipal(state,input={}){const id=clean(input.id||input.personId||input.principalId||'founder',80),auth=ensure(state),existing=auth.peopleById[id];if(existing){if(input.legalName&&existing.legalName!==clean(input.legalName,180))return upsertPerson(state,{...existing,...input,id});return clone(existing);}return upsertPerson(state,{id,legalName:input.legalName||state.profile?.founder||'المؤسس',displayName:input.displayName||input.legalName||state.profile?.founder||'المؤسس',role:input.role||'founder'});}
  function normalizeStrokes(input){
    if(!Array.isArray(input)||!input.length||input.length>64)throw new Error('signature-strokes-invalid');let points=0;
    const strokes=input.map(stroke=>{if(!Array.isArray(stroke)||stroke.length<2||stroke.length>2048)throw new Error('signature-stroke-invalid');return stroke.map(point=>{const x=Number(Array.isArray(point)?point[0]:point?.x),y=Number(Array.isArray(point)?point[1]:point?.y),pressure=Number(Array.isArray(point)?point[2]:point?.pressure);if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>1||y<0||y>1)throw new Error('signature-point-out-of-range');points++;const row={x:Math.round(x*10000)/10000,y:Math.round(y*10000)/10000};if(Number.isFinite(pressure))row.pressure=Math.round(Math.max(0,Math.min(1,pressure))*1000)/1000;return row;});});
    if(points>8192||new TextEncoder().encode(stable(strokes)).byteLength>MAX_SIGNATURE_BYTES)throw new Error('signature-data-too-large');return strokes;
  }
  function createVisualSeal(state,input={}){
    const auth=ensure(state),ownerPersonId=clean(input.ownerPersonId||input.personId,80),person=auth.peopleById[ownerPersonId];if(!person||person.status!=='active')throw new Error('signature-owner-unavailable');compact(state,{visualSeals:LIMITS.visualSeals-1,visualSealsPerPerson:LIMITS.visualSealsPerPerson-1});const ownerRows=Object.values(auth.signatureAssetsById).filter(row=>row.ownerPersonId===ownerPersonId);if(ownerRows.length>=LIMITS.visualSealsPerPerson||Object.keys(auth.signatureAssetsById).length>=LIMITS.visualSeals)throw new Error('visual-seal-store-full');const strokes=normalizeStrokes(input.strokes),versions=ownerRows.map(row=>Number(row.version)||0),version=Math.max(0,...versions)+1,id=clean(input.id,100)||`SIG-${ownerPersonId.replace(/[^a-z0-9_-]/gi,'_')}-V${version}`,width=Math.max(1,Math.min(4096,Math.floor(Number(input.width)||640))),height=Math.max(1,Math.min(2048,Math.floor(Number(input.height)||220))),ink=/^#[0-9a-f]{6}$/i.test(String(input.ink||''))?String(input.ink).toLowerCase():'#123248',createdAtSim=now(state),signatureDigest=digest({format:'normalized-strokes-v1',ownerPersonId,version,strokes,width,height,ink});if(auth.signatureAssetsById[id])throw new Error('signature-id-conflict');const row={id,ownerPersonId,ownerNameSnapshot:person.legalName,version,kind:'visual-authorization-seal',format:'normalized-strokes-v1',strokes,width,height,ink,digest:signatureDigest,createdAtSim,status:'active'};auth.signatureAssetsById[id]=row;const previous=auth.activeSignatureByPerson[ownerPersonId];if(previous&&auth.signatureAssetsById[previous])auth.signatureAssetsById[previous].status='superseded';auth.activeSignatureByPerson[ownerPersonId]=id;return clone(row);
  }
  function validateVisualSeal(row){
    try{
      if(!row||typeof row!=='object'||Array.isArray(row)||!clean(row.id,100)||!clean(row.ownerPersonId,80))throw new Error('signature-shape-invalid');
      if(row.kind!=='visual-authorization-seal'||row.format!=='normalized-strokes-v1')throw new Error('signature-format-invalid');
      if(!Number.isSafeInteger(Number(row.version))||Number(row.version)<1)throw new Error('signature-version-invalid');
      if(!Number.isInteger(Number(row.width))||row.width<1||row.width>4096||!Number.isInteger(Number(row.height))||row.height<1||row.height>2048)throw new Error('signature-dimensions-invalid');
      if(!/^#[0-9a-f]{6}$/i.test(String(row.ink||'')))throw new Error('signature-ink-invalid');
      if(!['active','superseded','revoked'].includes(row.status))throw new Error('signature-status-invalid');
      const normalized=normalizeStrokes(row.strokes);if(stable(normalized)!==stable(row.strokes))throw new Error('signature-strokes-noncanonical');
      const expected=digest({format:row.format,ownerPersonId:row.ownerPersonId,version:row.version,strokes:normalized,width:row.width,height:row.height,ink:String(row.ink).toLowerCase()});if(expected!==row.digest)throw new Error('signature-digest-invalid');
      return {ok:true,digest:expected,points:normalized.reduce((sum,stroke)=>sum+stroke.length,0)};
    }catch(error){return {ok:false,reason:String(error?.message||error)};}
  }
  const createSignature=createVisualSeal;
  function revokeVisualSeal(state,id,reason='revoked'){const auth=ensure(state),row=auth.signatureAssetsById[clean(id,100)];if(!row)throw new Error('signature-not-found');row.status='revoked';row.revokedAtSim=now(state);row.revocationReason=clean(reason,240);if(auth.activeSignatureByPerson[row.ownerPersonId]===row.id)delete auth.activeSignatureByPerson[row.ownerPersonId];return clone(row);}
  const revokeSignature=revokeVisualSeal;
  function normalizeList(value,max=120){if(!Array.isArray(value)||!value.length||value.length>max)throw new Error('authorization-list-invalid');return [...new Set(value.map(item=>clean(item,120)).filter(Boolean))];}
  function createMandate(state,input={}){const auth=ensure(state),principalId=clean(input.principalId,80),person=auth.peopleById[principalId];if(!person||person.status!=='active')throw new Error('mandate-principal-unavailable');compact(state,{mandates:LIMITS.mandates-1});if(Object.keys(auth.mandatesById).length>=LIMITS.mandates)throw new Error('mandate-store-full');const priorVersions=Object.values(auth.mandatesById).filter(row=>row?.principalId===principalId).map(row=>Number(row.version)||0),version=input.version==null?Math.max(0,...priorVersions)+1:Math.max(1,Math.floor(Number(input.version)||1)),id=clean(input.id,120)||`MANDATE-${principalId.replace(/[^a-z0-9_-]/gi,'_')}-V${version}`;if(auth.mandatesById[id])throw new Error('mandate-id-conflict');const companyIds=normalizeList(input.companyIds),scopes=normalizeList(input.scopes),validFromSim=Math.max(0,Number(input.validFromSim)||now(state)),validToSim=input.validToSim==null?null:Math.max(validFromSim,Number(input.validToSim)||0),row={id,version,principalId,companyIds,scopes,validFromSim,validToSim,status:clean(input.status||'active',24),createdAtSim:now(state)};auth.mandatesById[id]=row;return clone(row);}
  function createDefaultMandate(state,input={}){const principal=ensurePrincipal(state,input),auth=ensure(state),companyIds=Array.isArray(input.companyIds)&&input.companyIds.length?input.companyIds:['*'],scopes=Array.isArray(input.scopes)&&input.scopes.length?input.scopes:['finance.*','contracts.*','company.*'],existing=Object.values(auth.mandatesById).find(row=>row.principalId===principal.id&&row.status==='active'&&stable(row.companyIds)===stable([...new Set(companyIds.map(String))])&&stable(row.scopes)===stable([...new Set(scopes.map(String))]));return existing?clone(existing):createMandate(state,{id:input.mandateId,principalId:principal.id,companyIds,scopes,validFromSim:input.validFromSim,validToSim:input.validToSim});}
  function scopeAllows(scopes,action){return scopes.includes('*')||scopes.includes(action)||scopes.some(scope=>scope.endsWith('.*')&&action.startsWith(scope.slice(0,-1)));}
  function commandIntent(command={}){if(command.payload!==undefined&&(!command.payload||typeof command.payload!=='object'||Array.isArray(command.payload)))throw new Error('approval-payload-object-required');const source=command.payload??{};stable(source);const domain=clean(command.domain,64),name=clean(command.name,96),payload=clone(source),idempotencyKey=clean(command.idempotencyKey||payload.idempotencyKey,160),expectedSaveRevision=Number(command.expectedSaveRevision);if(!domain||!name)throw new Error('approval-command-invalid');if(!Number.isSafeInteger(expectedSaveRevision)||expectedSaveRevision<0)throw new Error('approval-revision-required');return {domain,name,payload,idempotencyKey,expectedSaveRevision};}
  function intentDigest(command){return digest(commandIntent(command));}
  const commandTargetResolvers=new Map();let targetResolversSealed=false;
  function registerCommandTargetResolver(domain,resolver){domain=clean(domain,64);if(targetResolversSealed)throw new Error('authorization-target-resolvers-sealed');if(!domain||typeof resolver!=='function')throw new Error('authorization-target-resolver-invalid');if(commandTargetResolvers.has(domain)&&commandTargetResolvers.get(domain)!==resolver)throw new Error(`authorization-target-resolver-duplicate:${domain}`);commandTargetResolvers.set(domain,resolver);return resolver;}
  function sealTargetResolvers(){targetResolversSealed=true;return true;}
  function areTargetResolversSealed(){return targetResolversSealed;}
  function commandCompanyIds(state,command={}){
    const domain=clean(command.domain,64),name=clean(command.name,96),payload=command.payload&&typeof command.payload==='object'&&!Array.isArray(command.payload)?command.payload:{},ids=[],platform=globalThis.GH_COMPANY_PLATFORM;
    const add=value=>{if(Array.isArray(value)){for(const item of value)add(item);return;}const id=clean(value,100);if(id&&!ids.includes(id))ids.push(id);};
    const owner=value=>String(value?.ownerCompanyId||value?.companyId||value?.company||'').trim();
    const assetOwner=value=>owner(value)||String(platform?.ownerForLegacyAssetMode?.(value?.assetMode||value?.type)||'');
    const routeOwner=value=>owner(value)||String(platform?.ownerForLegacyRouteMode?.(value?.routeMode||value?.type)||'');
    const assetById=id=>(state?.assets||[]).find(row=>String(row?.id)===String(id));
    const routeById=id=>(state?.customRoutes||[]).find(row=>String(row?.id)===String(id));
    const facilityById=id=>[...(state?.globalBases||[]),...(state?.customHubs||[])].find(row=>String(row?.id)===String(id));
    const deliveryById=id=>(state?.realism?.procurement?.deliveries||[]).find(row=>String(row?.id)===String(id));
    const constructionById=id=>(state?.constructionContracts||[]).find(row=>String(row?.id)===String(id));
    const contractById=id=>state?.contractRegistry?.[String(id)]||null;
    const addAsset=id=>{const row=assetById(id);if(row)add(assetOwner(row));return row;};
    const addRoute=id=>{const row=routeById(id);if(row)add(routeOwner(row));return row;};
    const addFacility=id=>{const row=facilityById(id);if(row)add(owner(row));return row;};
    const addAllCompanies=()=>{add('group');add(Object.keys(state?.companyRegistry||{}));add(state?.openedCompanies||[]);add(Object.keys(state?.companyFinance||{}));};
    const unresolved=reference=>{throw new Error(`authorization-company-target-unresolved:${domain}.${name}:${clean(reference||'missing',100)}`);};
    const explicit=()=>{add(payload.ownerCompanyId);add(payload.companyId);add(payload.company);};
    const custom=commandTargetResolvers.get(domain);
    if(custom){const resolved=custom({state,domain,name,payload:clone(payload),helpers:Object.freeze({assetById,routeById,facilityById,deliveryById,constructionById,contractById,assetOwner,routeOwner,owner})});add(resolved);if(!ids.length)unresolved('custom-resolver');return ids;}
    explicit();
    if(domain==='finance'){
      for(const key of ['from','to','beneficiaryCompany'])add(payload[key]);if(['issue-intercompany-loan','repay-intercompany-loan','settle-intercompany-interest'].includes(name)){add(payload.lender);add(payload.borrower);}
      for(const row of [...(Array.isArray(payload.rows)?payload.rows:[]),...(Array.isArray(payload.report?.lines)?payload.report.lines:[])])for(const key of ['ownerCompanyId','companyId','company','from','to','lender','borrower'])add(row?.[key]);
      if(payload.companies&&typeof payload.companies==='object')add(Array.isArray(payload.companies)?payload.companies:Object.keys(payload.companies));
      const refs=[payload.id,payload.chequeId,payload.number,payload.invoiceNumber,payload.debtId,payload.loanId].filter(Boolean),buckets=['cheques','invoices','payables','receivables','debtRecords','debtSettlements','intercompanyLoans','intercompanyLoanSettlements','transfers'];
      for(const ref of refs)for(const bucket of buckets){const row=(state?.finance?.[bucket]||[]).find(item=>[item?.id,item?.number,item?.reference,item?.chequeNumber,item?.loanId,item?.debtId].some(value=>String(value||'')===String(ref)));if(row){add(row.company);add(row.ownerCompanyId);add(row.beneficiaryCompany);if(bucket==='intercompanyLoans'||bucket==='intercompanyLoanSettlements'){add(row.lender);add(row.borrower);}}}
      if(['bulk-transfer','cash-pool-sweep','set-central-treasury-policy','initialize-capital'].includes(name))add('group');
      if(['ensure','consume-trip-accruals','apply-simulation-journal','record-daily-close','close-vat-period'].includes(name))addAllCompanies();
    }else if(domain==='corporate'){
      const scoped=new Set(['decision','rename-company','set-logo','set-management-plan']);if(scoped.has(name)){add(payload.companyId||payload.type);if(!ids.length)unresolved(payload.id||payload.type);}else add('group');
    }else if(domain==='contracts'){
      const doc=contractById(payload.id);if(doc)add(doc.company||doc.companyId||doc.sector);if(!ids.length)add(payload.sector);if(name==='tick-day')addAllCompanies();
    }else if(domain==='fleet'){
      addAsset(payload.id||payload.assetId);for(const id of payload.ids||[])addAsset(id);for(const row of [...(payload.assignments||[]),...(payload.departures||[]),...(payload.deliveries||[])]){add(owner(row));add(owner(row?.asset));addAsset(row?.id||row?.assetId);}if(payload.asset)add(assetOwner(payload.asset));if(name==='reconcile-staffing')addAllCompanies();
    }else if(domain==='routes'){
      add(owner(payload.route));add(routeOwner(payload.route));addAsset(payload.assetId);addRoute(payload.id);addRoute(payload.replaceId);if(payload.routeId)addRoute(payload.routeId);
    }else if(domain==='procurement'){
      add(owner(payload.asset));add(owner(payload.base));const construction=constructionById(payload.id);if(construction)add(construction.company||construction.ownerCompanyId);const delivery=deliveryById(payload.id||payload.deliveryId);if(delivery)add(owner(delivery)||owner(delivery.asset));if(!ids.length)add(platform?.ownerForLegacyAssetMode?.(payload.assetMode||payload.type));
    }else if(domain==='facilities'){
      add(owner(payload.facility));const facility=addFacility(payload.id||payload.facilityId);if(name==='open-regional-hq'&&!facility)add('group');if(name==='tick-day')addAllCompanies();
    }else if(domain==='banking'){add('bank');add(payload.borrower);}
    else if(domain==='mobility')add(payload.ownerCompanyId||payload.companyId||payload.company||'mobility');
    else if(domain==='energy')add(payload.ownerCompanyId||payload.companyId||payload.company||'power');
    else if(domain==='hr'){
      if(payload.company==='all'||name==='tick-day')addAllCompanies();else add(payload.company);const candidateId=String(payload.candidateId||payload.id||''),candidate=(globalThis.GH_HR_CORE?.OFFICIAL_MANAGER_CANDIDATES||[]).find(row=>row.id===candidateId);if(candidate)add(candidate.company);if(!ids.length&&['appoint-official-manager','dismiss-official-manager','hire-executive','hire','requisition','apply-salary-raise'].includes(name))unresolved(candidateId);
    }else if(domain==='governance'){if(!ids.length)add(payload.sector);if(!ids.length)add('group');}
    else if(domain==='departments'){if(payload.company==='all')addAllCompanies();else add(payload.company);if(!ids.length)add('group');}
    else if(['conference','business-world','market','operations','strategy'].includes(domain))add('group');
    else unresolved('resolver-missing');
    if(!ids.length)unresolved(payload.id||payload.number||payload.type);return ids;
  }
  function mandateCovers(mandate,companyIds){return mandate.companyIds.includes('*')||companyIds.every(id=>mandate.companyIds.includes(id));}
  function buildEnvelope(state,{domain,name,payload={},idempotencyKey='',actor={},signatureAssetId='',mandateId='',mode='stored-signature'}={}){if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('approval-payload-object-required');stable(payload);const command={domain,name,payload:clone(payload),idempotencyKey:clean(idempotencyKey||payload.idempotencyKey,160),expectedSaveRevision:Math.max(0,Math.floor(Number(state?.saveRevision)||0))},normalizedActor={kind:clean(actor.kind||'player',32),principalId:clean(actor.principalId,80)};return {version:1,command,actor:normalizedActor,approval:{mode,signatureAssetId:clean(signatureAssetId,100),mandateId:clean(mandateId,120),intentDigest:intentDigest(command)}};}
  function buildActiveEnvelope(state,input={}){const auth=ensure(state),principal=ensurePrincipal(state,input.actor||input),principalId=clean(input.actor?.principalId||input.principalId||principal.id,80),signatureAssetId=clean(input.signatureAssetId||auth.activeSignatureByPerson[principalId],100),signature=auth.signatureAssetsById[signatureAssetId];if(!signatureAssetId||!signature||signature.status!=='active'||signature.ownerPersonId!==principalId||auth.activeSignatureByPerson[principalId]!==signatureAssetId)throw new Error('active-visual-seal-required');const action=`${clean(input.domain,64)}.${clean(input.name,96)}`,companyIds=commandCompanyIds(state,{domain:input.domain,name:input.name,payload:input.payload}),mandate=clean(input.mandateId,120)?auth.mandatesById[clean(input.mandateId,120)]:Object.values(auth.mandatesById).find(row=>row.principalId===principalId&&row.status==='active'&&mandateCovers(row,companyIds)&&scopeAllows(row.scopes,action));if(!mandate)throw new Error('active-mandate-required');return buildEnvelope(state,{...input,actor:{kind:input.actor?.kind||'player',principalId},signatureAssetId,mandateId:mandate.id,mode:input.mode||'stored-signature'});}
  function authorize(state,envelope={}){
    const auth=ensure(state),command=commandIntent(envelope.command),actor=envelope.actor&&typeof envelope.actor==='object'?envelope.actor:{},approval=envelope.approval&&typeof envelope.approval==='object'?envelope.approval:{},principalId=clean(actor.principalId,80),mode=clean(approval.mode,40);if(Number(state.saveRevision||0)!==command.expectedSaveRevision)throw new Error(`approval-revision-conflict:${command.expectedSaveRevision}:${Number(state.saveRevision)||0}`);if(!principalId||!auth.peopleById[principalId])throw new Error('approval-principal-unavailable');const expectedIntent=intentDigest(command);if(clean(approval.intentDigest,64)!==expectedIntent)throw new Error('approval-intent-digest-mismatch');const signatureId=clean(approval.signatureAssetId,100),signature=auth.signatureAssetsById[signatureId],mandate=auth.mandatesById[clean(approval.mandateId,120)],action=`${command.domain}.${command.name}`,companyIds=commandCompanyIds(state,command),companyId=companyIds[0],at=now(state),actorKind=clean(actor.kind||'player',32);if(!['stored-signature','delegated-system'].includes(mode)||mode==='delegated-system'&&actorKind!=='system')throw new Error('approval-mode-invalid');if(!signature||signature.ownerPersonId!==principalId||signature.status!=='active'||auth.activeSignatureByPerson[principalId]!==signatureId||!validateVisualSeal(signature).ok)throw new Error('approval-signature-invalid');if(!mandate||mandate.principalId!==principalId||mandate.status!=='active'||at<Number(mandate.validFromSim)||mandate.validToSim!=null&&at>Number(mandate.validToSim))throw new Error('approval-mandate-invalid');if(!mandateCovers(mandate,companyIds))throw new Error('approval-company-not-authorized');if(!scopeAllows(mandate.scopes,action))throw new Error('approval-scope-not-authorized');return {schema:'gh-approval-context-v1',command,actor:{kind:actorKind,principalId},mode,action,companyId,companyIds,intentDigest:expectedIntent,person:clone(auth.peopleById[principalId]),signature:clone(signature),mandate:clone(mandate),authorizedAtSim:at};
  }
  function findDelegatedAuthorization(state,input={}){
    const auth=ensure(state),domain=clean(input.domain||'system',64),name=clean(input.name||'execute',96),payload={...(input.payload||{})};if(input.companyId&&!payload.company&&!payload.companyId&&!payload.ownerCompanyId)payload.company=clean(input.companyId,100);const command={domain,name,payload,idempotencyKey:clean(input.idempotencyKey,160),expectedSaveRevision:Math.max(0,Math.floor(Number(state.saveRevision)||0))},companyIds=commandCompanyIds(state,command),companyId=companyIds[0],action=`${domain}.${name}`,at=now(state),requestedPrincipal=clean(input.principalId,80),requestedMandate=clean(input.mandateId,120);
    const mandates=Object.values(auth.mandatesById).filter(row=>(!requestedMandate||row.id===requestedMandate)&&(!requestedPrincipal||row.principalId===requestedPrincipal)&&row.status==='active'&&at>=Number(row.validFromSim)&&(row.validToSim==null||at<=Number(row.validToSim))&&mandateCovers(row,companyIds)&&scopeAllows(row.scopes,action)).sort((a,b)=>String(a.id).localeCompare(String(b.id)));
    for(const mandate of mandates){const person=auth.peopleById[mandate.principalId],signature=auth.signatureAssetsById[auth.activeSignatureByPerson[mandate.principalId]];if(!person||person.status!=='active'||!signature||signature.ownerPersonId!==person.id||signature.status!=='active'||!validateVisualSeal(signature).ok)continue;return {schema:'gh-approval-context-v1',command,actor:{kind:'system',principalId:person.id},mode:'delegated-system',action,companyId,companyIds,intentDigest:digest({schema:'gh-delegated-system-intent-v1',command}),person:clone(person),signature:clone(signature),mandate:clone(mandate),authorizedAtSim:at};}
    return null;
  }
  function mandateSnapshot(mandate){return {id:mandate.id,version:mandate.version,principalId:mandate.principalId,companyIds:clone(mandate.companyIds),scopes:clone(mandate.scopes),validFromSim:Number(mandate.validFromSim)||0,validToSim:mandate.validToSim==null?null:Number(mandate.validToSim)};}
  function sealDigest(signature){return digest({format:signature.format,ownerPersonId:signature.ownerPersonId,version:signature.version,strokes:signature.strokes,width:signature.width,height:signature.height,ink:signature.ink});}
  function issueProof(state,context,input={}){const auth=ensure(state);if(!context||context.schema!=='gh-approval-context-v1')throw new Error('approval-context-required');compact(state);archiveProofsForAdmission(state);if(Object.keys(auth.proofsById).length>=LIMITS.proofs)throw new Error('authorization-proof-store-full');const commandId=clean(input.commandId,100);if(!commandId)throw new Error('approval-command-id-required');const documentIds=Array.isArray(input.documentIds)?[...new Set(input.documentIds.map(value=>clean(value,160)).filter(Boolean))]:[],documentDigests=Array.isArray(input.documentDigests)?[...new Set(input.documentDigests.map(value=>clean(value,64)).filter(Boolean))]:[],companyIds=Array.isArray(context.companyIds)&&context.companyIds.length?[...new Set(context.companyIds.map(value=>clean(value,100)).filter(Boolean))]:[clean(context.companyId||'group',100)],id=`APR-${String(++auth.proofSequence).padStart(9,'0')}`,mandateCopy=mandateSnapshot(context.mandate),base={id,version:1,commandId,transactionId:clean(input.transactionId||commandId,100),signerPersonId:context.person.id,signerNameSnapshot:context.person.legalName,companyId:companyIds[0],companyIds,mandateId:context.mandate.id,mandateVersion:context.mandate.version,mandateSnapshot:mandateCopy,mandateDigest:digest(mandateCopy),visualSealAssetId:context.signature.id,visualSealVersion:context.signature.version,visualSealDigest:context.signature.digest,signatureAssetId:context.signature.id,signatureVersion:context.signature.version,signatureDigest:context.signature.digest,action:context.action,mode:context.mode,documentIds,documentDigests,signedAtSim:now(state),payloadDigest:context.intentDigest};base.proofDigest=digest(base);auth.proofsById[id]=base;return clone(base);}
  function verifyProof(state,id,cache=null){
    const auth=ensure(state),proofId=clean(id,100),proof=proofRecord(state,proofId);if(!proof)return {ok:false,reason:'proof-not-found'};
    const proofCache=cache?.proofs;if(proofCache?.has(proofId))return proofCache.get(proofId);
    const {proofDigest,...base}=proof,signature=auth.signatureAssetsById[proof.visualSealAssetId||proof.signatureAssetId],mandate=auth.mandatesById[proof.mandateId];let result;
    if(digest(base)!==proofDigest)result={ok:false,reason:'proof-digest-mismatch'};
    else{
      const sealId=signature?.id||proof.visualSealAssetId||proof.signatureAssetId,sealVersion=signature?.version??0,sealKey=`${sealId}:${sealVersion}:${signature?.digest||''}`,sealCache=cache?.sealDigests;let currentSealDigest=sealCache?.get(sealKey);
      if(signature&&currentSealDigest===undefined){currentSealDigest=sealDigest(signature);sealCache?.set(sealKey,currentSealDigest);}
      if(!signature||!validateVisualSeal(signature).ok||signature.version!==(proof.visualSealVersion??proof.signatureVersion)||signature.digest!==(proof.visualSealDigest||proof.signatureDigest)||currentSealDigest!==(proof.visualSealDigest||proof.signatureDigest))result={ok:false,reason:'proof-visual-seal-mismatch'};
      else if(!mandate||mandate.version!==proof.mandateVersion||mandate.principalId!==proof.signerPersonId)result={ok:false,reason:'proof-mandate-mismatch'};
      else{
        const mandateKey=`${mandate.id}:${mandate.version}`,mandateCache=cache?.mandateDigests;let currentMandateDigest=mandateCache?.get(mandateKey);if(currentMandateDigest===undefined){currentMandateDigest=digest(mandateSnapshot(mandate));mandateCache?.set(mandateKey,currentMandateDigest);}const proofMandateDigest=digest(proof.mandateSnapshot);result=proofMandateDigest!==proof.mandateDigest||currentMandateDigest!==proof.mandateDigest?{ok:false,reason:'proof-mandate-content-mismatch'}:{ok:true,proof:clone(proof)};
      }
    }
    proofCache?.set(proofId,result);return result;
  }
  const API=Object.freeze({VERSION,SCHEMA,LIMITS,MAX_SIGNATURE_BYTES,stable,digest,ensure,compact,upsertPerson,ensurePrincipal,normalizeStrokes,validateVisualSeal,createVisualSeal,createSignature,revokeVisualSeal,revokeSignature,createMandate,createDefaultMandate,registerCommandTargetResolver,sealTargetResolvers,areTargetResolversSealed,commandIntent,commandCompanyIds,intentDigest,buildEnvelope,buildActiveEnvelope,authorize,findDelegatedAuthorization,issueProof,proofRecord,proofRecords,verifyProof});globalThis.GH_AUTHORIZATION=API;if(globalThis.window&&globalThis.window!==globalThis)globalThis.window.GH_AUTHORIZATION=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
