(()=>{
  'use strict';
  const VERSION='3.0.0';
  const num=value=>Math.max(0,Number(value)||0),now=state=>Number(state.simSeconds)||0;
  const PRODUCTS=Object.freeze({
    consumer:{name:'قروض أفراد',rate:.082,termDays:1095,provision:.018,rsf:.85,minimum:1000000},
    mortgage:{name:'تمويل سكني',rate:.057,termDays:3650,provision:.009,rsf:.82,minimum:5000000},
    sme:{name:'تمويل منشآت صغيرة ومتوسطة',rate:.071,termDays:1825,provision:.016,rsf:.88,minimum:5000000},
    corporate:{name:'تمويل شركات',rate:.064,termDays:2555,provision:.012,rsf:.90,minimum:10000000},
    project:{name:'تمويل مشاريع وبنية تحتية',rate:.068,termDays:3650,provision:.014,rsf:.92,minimum:10000000},
    green:{name:'تمويل أخضر',rate:.052,termDays:2920,provision:.008,rsf:.86,minimum:5000000}
  });
  const HQLA_OF_FUNDING=.37,ASF_DEPOSITS=.90,ASF_WHOLESALE=.50;
  const clone=value=>globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value));
  function hash(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
  function deterministic(seed,min,max){return min+(hash(seed)/4294967295)*(max-min);}
  function ensure(state){
    const bank=state.bank=state.bank&&typeof state.bank==='object'?state.bank:{};
    bank.corporateClients=bank.corporateClients&&typeof bank.corporateClients==='object'?bank.corporateClients:{};
    for(const key of ['riskReviews','lettersOfCredit','guarantees','cashSweeps','branchNetwork','loanPortfolios','dailyHistory'])bank[key]=Array.isArray(bank[key])?bank[key].filter(Boolean):[];
    for(const type of ['group','air','sea','road','power','mobility'])if(!bank.corporateClients[type])bank.corporateClients[type]={company:type,creditLimit:5000000,drawn:0,depositBalance:0,lastReview:0,rating:'BBB'};
    for(const key of ['branches','deposits','loans','npl','capitalRatio','hqla','stableFunding','requiredStableFunding','wholesaleFunding','offBalance','feeIncomeYTD','provisions','retailCustomers','businessCustomers','dailyServiceFeeRevenue'])bank[key]=num(bank[key]);
    bank.sequence=Math.max(0,Math.floor(Number(bank.sequence)||0));
    const facilities=(state.customHubs||[]).filter(row=>row?.owned===true&&row.company==='bank'&&row.kind==='bank');
    for(const facility of facilities)if(!bank.branchNetwork.some(row=>row.facilityId===facility.id))bank.branchNetwork.push({id:`BR-${++bank.sequence}`,facilityId:facility.id,capitalId:facility.capitalId||null,city:facility.city||'غير محدد',country:facility.country||'غير محدد',openedAt:Number(facility.openedAt)||now(state),servicesActive:true,services:['حسابات وودائع','تحويلات ومدفوعات','بطاقات','تمويل أفراد','تمويل شركات','تجارة دولية'],retailCustomers:0,businessCustomers:0,deposits:0,loans:0,lastProcessedDay:Math.floor(now(state)/86400)});
    while(bank.branchNetwork.length<bank.branches)bank.branchNetwork.push({id:`BR-${++bank.sequence}`,facilityId:null,capitalId:null,city:'فرع محفوظ',country:'سجل قديم',openedAt:0,servicesActive:true,services:['حسابات وودائع','تحويلات ومدفوعات','تمويل'],retailCustomers:0,businessCustomers:0,deposits:0,loans:0,lastProcessedDay:Math.floor(now(state)/86400)});
    bank.branches=Math.max(bank.branches,bank.branchNetwork.length);
    return bank;
  }
  function dormant(bank){return num(bank.branches)===0&&num(bank.deposits)===0&&num(bank.loans)===0;}
  function reconcilePrudential(state){const bank=ensure(state),deposits=num(bank.deposits),wholesale=num(bank.wholesaleFunding);if(dormant(bank)){bank.hqla=0;bank.stableFunding=0;return bank;}bank.hqla=Math.round((deposits+wholesale)*HQLA_OF_FUNDING);bank.stableFunding=Math.round(deposits*ASF_DEPOSITS+wholesale*ASF_WHOLESALE);bank.requiredStableFunding=bank.loanPortfolios.reduce((sum,row)=>sum+num(row.outstanding)*num(row.rsfFactor||.85),0)+Object.values(bank.corporateClients).reduce((sum,row)=>sum+num(row.drawn)*.85,0);return bank;}
  function syncCorporateClients(state,p,F){const types=['group',...(state.openedCompanies||[]).filter(type=>['air','sea','road','power','mobility'].includes(type))];for(const type of types){const book=F.book(state,type),existing=state.bank.corporateClients[type]||{},baseValue=Math.max(5000000,num(state.groupValue)*(type==='group'?.04:.025));state.bank.corporateClients[type]={company:type,name:p.names?.[type]||state.companyRegistry?.[type]?.legalName||(type==='group'?state.profile?.name:type),accountId:book.accounts[0].id,depositBalance:num(existing.depositBalance),creditLimit:num(existing.creditLimit)||Math.round(baseValue),drawn:num(existing.drawn),rating:existing.rating||(type==='group'?state.profile?.creditRating:'BBB'),kyc:existing.kyc||'مكتمل',lastReview:num(existing.lastReview)};}return state.bank.corporateClients;}
  function openBranch(state,p={}){const bank=ensure(state),branch={id:String(p.branchId||`BR-${++bank.sequence}`),facilityId:p.facilityId||p.branchId||null,capitalId:p.capitalId||null,city:String(p.city||'غير محدد'),country:String(p.country||'غير محدد'),openedAt:now(state),servicesActive:p.servicesActive!==false,services:['حسابات وودائع','تحويلات ومدفوعات','بطاقات','تمويل أفراد','تمويل شركات','تمويل مشاريع','تجارة دولية'],retailCustomers:0,businessCustomers:0,deposits:0,loans:0,lastProcessedDay:Math.floor(now(state)/86400)};if(bank.branchNetwork.some(row=>row.id===branch.id||branch.facilityId&&row.facilityId===branch.facilityId))throw new Error('bank-branch-already-open');bank.branchNetwork.push(branch);bank.branches=bank.branchNetwork.length;state.unlockedSectors=Array.isArray(state.unlockedSectors)?state.unlockedSectors:[];if(!state.unlockedSectors.includes('bank'))state.unlockedSectors.push('bank');reconcilePrudential(state);return clone(branch);}
  function originateLoan(state,p,F){
    const bank=ensure(state),product=PRODUCTS[p.product]||PRODUCTS.corporate,branch=bank.branchNetwork.find(row=>row.id===p.branchId||row.facilityId===p.branchId)||bank.branchNetwork.find(row=>row.servicesActive);
    if(!branch?.servicesActive)throw new Error('bank-active-branch-required');
    const requested=num(p.amount);if(requested<=0)throw new Error('bank-loan-amount-invalid');const amount=Math.max(product.minimum,requested);
    const operating=F.operating(state,'bank'),minimumLiquidity=Math.max(5000000,num(bank.deposits)*.12);if(operating-amount<minimumLiquidity)throw new Error('bank-liquidity-buffer');
    const projectedLdr=(num(bank.loans)+amount)/Math.max(1,num(bank.deposits))*100;if(bank.deposits>0&&projectedLdr>95)throw new Error('bank-loan-deposit-limit');
    const fee=Math.max(25000,Math.round(amount*.006)),cashDisbursement=amount-fee,book=F.book(state,'bank'),id=`LOAN-${++bank.sequence}`;
    book.accounts[0].balance-=cashDisbursement;
    F.journal(state,'bank',`${id} · ${product.name}`,[{account:`محفظة قروض · ${product.name}`,debit:amount},{account:book.accounts[0].id,credit:cashDisbursement},{account:'إيراد رسوم ترتيب تمويل',credit:fee}],id);
    const portfolio={id,branchId:branch.id,product:String(p.product&&PRODUCTS[p.product]?p.product:'corporate'),name:product.name,region:`${branch.city} · ${branch.country}`,borrowers:Math.max(1,Math.floor(Number(p.borrowers)||Math.max(1,amount/product.minimum))),principal:amount,outstanding:amount,rate:Number(p.rate)||product.rate,termDays:Math.max(30,Math.floor(Number(p.termDays)||product.termDays)),remainingDays:Math.max(30,Math.floor(Number(p.termDays)||product.termDays)),provisionRate:num(p.provisionRate||product.provision),rsfFactor:num(p.rsfFactor||product.rsf),originationFee:fee,originatedAt:now(state),status:'نشطة'};
    bank.loanPortfolios.unshift(portfolio);bank.loans+=amount;bank.provisions+=amount*portfolio.provisionRate;bank.feeIncomeYTD+=fee;branch.loans+=amount;F.reconcile(state);reconcilePrudential(state);return clone(portfolio);
  }
  function tickDay(state,p,F){
    const bank=ensure(state),day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(state)/86400)));if(bank.lastProcessedDay===day)return bank.dailyHistory.find(row=>row.day===day)||{day,idempotent:true};
    let newDeposits=0,newRetail=0,newBusiness=0,serviceFees=0,principalRepaid=0,expired=0;
    for(const branch of bank.branchNetwork.filter(row=>row.servicesActive)){
      if(Number(branch.lastProcessedDay)>=day)continue;
      const retail=Math.max(1,Math.round(deterministic(`${branch.id}:${day}:retail`,18,65))),business=Math.max(0,Math.round(deterministic(`${branch.id}:${day}:business`,1,7))),deposits=Math.round(retail*deterministic(`${branch.id}:${day}:rdep`,9000,26000)+business*deterministic(`${branch.id}:${day}:bdep`,180000,720000));
      branch.retailCustomers+=retail;branch.businessCustomers+=business;branch.deposits+=deposits;branch.lastProcessedDay=day;newRetail+=retail;newBusiness+=business;newDeposits+=deposits;serviceFees+=Math.round(branch.retailCustomers*1.2+branch.businessCustomers*18);
    }
    if(newDeposits>0){const account=F.book(state,'bank').accounts[0];account.balance+=newDeposits;F.journal(state,'bank',`ودائع عملاء جديدة · يوم ${day}`,[{account:account.id,debit:newDeposits},{account:'ودائع العملاء',credit:newDeposits}],`DEP-${day}`);bank.deposits+=newDeposits;}
    for(const portfolio of bank.loanPortfolios.filter(row=>row.status==='نشطة')){const due=Math.min(num(portfolio.outstanding),num(portfolio.principal)/Math.max(1,Number(portfolio.termDays)||1));if(due>0){portfolio.outstanding=Math.max(0,num(portfolio.outstanding)-due);portfolio.remainingDays=Math.max(0,Number(portfolio.remainingDays)-1);principalRepaid+=due;const branch=bank.branchNetwork.find(row=>row.id===portfolio.branchId);if(branch)branch.loans=Math.max(0,num(branch.loans)-due);if(portfolio.outstanding<=.01)portfolio.status='مسددة';}}
    if(principalRepaid>0){const account=F.book(state,'bank').accounts[0];account.balance+=principalRepaid;F.journal(state,'bank',`تحصيل أصول قروض · يوم ${day}`,[{account:account.id,debit:principalRepaid},{account:'محفظة القروض',credit:principalRepaid}],`LOAN-PRINCIPAL-${day}`);bank.loans=Math.max(0,bank.loans-principalRepaid);}
    for(const instrument of [...bank.lettersOfCredit,...bank.guarantees])if(instrument.status==='ساري'&&Number(instrument.expiryDay||Infinity)<=day){instrument.status='منتهي';instrument.expiredDay=day;expired++;}
    bank.retailCustomers=bank.branchNetwork.reduce((sum,row)=>sum+num(row.retailCustomers),0);bank.businessCustomers=bank.branchNetwork.reduce((sum,row)=>sum+num(row.businessCustomers),0);bank.dailyServiceFeeRevenue=serviceFees;bank.lastProcessedDay=day;F.reconcile(state);reconcilePrudential(state);
    const report={day,newDeposits,newRetail,newBusiness,serviceFees,principalRepaid,expired,customers:bank.retailCustomers+bank.businessCustomers};bank.dailyHistory.unshift(report);bank.dailyHistory=bank.dailyHistory.slice(0,180);return clone(report);
  }
  function execute(ctx,cmd,p={}){
    const state=ctx.state||ctx,F=globalThis.GH_FINANCE_CORE,bank=ensure(state);if(!F)throw new Error('finance-core-missing');
    if(cmd==='sync-corporate-clients')return syncCorporateClients(state,p,F);
    if(cmd==='review-limits'){for(const client of Object.values(bank.corporateClients)){const type=client.company,assets=(state.assets||[]).filter(asset=>asset.type===type).reduce((sum,asset)=>sum+num(asset.purchasePrice)*.55,0),cash=F.total(state,type),debt=num(F.book(state,type).debt),base=Math.max(5000000,cash*.35+assets*.12-debt*.08);client.creditLimit=Math.max(5000000,Math.round(base/100000)*100000);client.lastReview=now(state);client.rating=debt>cash*2?'BB':cash>debt?'A-':'BBB';}bank.riskReviews.unshift({at:now(state),type:'corporate-limits',clients:Object.keys(bank.corporateClients).length});bank.riskReviews=bank.riskReviews.slice(0,40);return true;}
    if(cmd==='draw-facility'){const type=p.company;if(!['group','air','sea','road','power','mobility'].includes(type))throw new Error('invalid-company');if(type!=='group'&&!(state.openedCompanies||[]).includes(type))throw new Error('company-not-open');const client=bank.corporateClients[type],amount=Math.min(num(p.amount),Math.max(0,num(client.creditLimit)-num(client.drawn)));if(amount<=0||F.operating(state,'bank')<amount)throw new Error('facility-unavailable');const fee=Math.max(25000,amount*.0035);if(F.operating(state,type)+amount<fee)throw new Error('borrower-fee-unavailable');F.execute({state},'transfer',{from:'bank',to:type,amount,note:'سحب تسهيل ائتماني من بنك المجموعة'});F.execute({state},'spend',{company:type,amount:fee,note:'رسوم ترتيب تسهيل ائتماني مستحقة لبنك المجموعة',method:'قيد مصرفي',counterparty:'بنك المجموعة',line:'other'});F.execute({state},'credit',{company:'bank',amount:fee,note:`رسوم ترتيب تسهيل ائتماني · ${type}`,method:'قيد مصرفي',counterparty:type});client.drawn+=amount;bank.loans+=amount;bank.feeIncomeYTD+=fee;F.book(state,type).debt+=amount;reconcilePrudential(state);return amount;}
    if(cmd==='trade-instrument'){const type=p.company,kind=p.kind==='lc'?'lc':'guarantee',amount=Math.max(100000,num(p.amount)),client=bank.corporateClients[type];if(!client||amount>Math.max(0,num(client.creditLimit)-num(client.drawn)))throw new Error('credit-headroom');const fee=Math.max(15000,Math.round(amount*(kind==='lc'?.006:.004)));F.execute({state},'spend',{company:type,amount:fee,note:kind==='lc'?'رسوم اعتماد مستندي':'رسوم ضمان مصرفي',method:'قيد مصرفي',counterparty:'بنك المجموعة'});F.execute({state},'credit',{company:'bank',amount:fee,note:`رسوم ${kind==='lc'?'اعتماد مستندي':'ضمان'}`,method:'قيد مصرفي',counterparty:type});bank.feeIncomeYTD+=fee;bank.offBalance+=amount;const document={id:`${kind==='lc'?'LC':'GTEE'}-${Math.floor(now(state))}-${bank.lettersOfCredit.length+bank.guarantees.length+1}`,company:type,amount,fee,status:'ساري',issuedAt:now(state),expiryDay:Math.floor(now(state)/86400)+90,counterparty:p.counterparty||'طرف تجاري مسجل'};(kind==='lc'?bank.lettersOfCredit:bank.guarantees).unshift(document);return document;}
    if(cmd==='cash-sweep'){let total=0;for(const type of ['air','sea','road','power','mobility']){if(!(state.openedCompanies||[]).includes(type))continue;const balance=F.operating(state,type),floor=Math.max(5000000,balance*.65),amount=Math.max(0,Math.floor((balance-floor)/100000)*100000);if(amount<500000)continue;F.execute({state},'transfer',{from:type,to:'bank',amount,note:'Cash sweep يومي إلى بنك المجموعة'});bank.corporateClients[type].depositBalance+=amount;bank.deposits+=amount;total+=amount;}bank.cashSweeps.unshift({at:now(state),amount:total});bank.cashSweeps=bank.cashSweeps.slice(0,60);reconcilePrudential(state);return total;}
    if(cmd==='open-branch')return openBranch(state,p);
    if(cmd==='activate-market'){const branch=bank.branchNetwork.find(row=>row.id===p.branchId||row.facilityId===p.branchId);if(!branch)throw new Error('bank-branch-not-found');branch.servicesActive=true;branch.activatedAt=now(state);return clone(branch);}
    if(cmd==='originate-loan'||cmd==='issue-loans'||cmd==='fund-loan-portfolio')return originateLoan(state,{...p,product:p.product||'corporate'},F);
    if(cmd==='tick-day')return tickDay(state,p,F);
    if(cmd==='stress'){state.advanced=state.advanced||{};state.advanced.bankStress={at:now(state),npl:Math.min(100,num(bank.npl)+2.5),withdrawal:num(bank.deposits)*.12,depositsAfter:num(bank.deposits)*.88,capitalRatio:Math.max(0,num(bank.capitalRatio||16.4)-3.1),rateShock:.02};return state.advanced.bankStress;}
    throw new Error(`Unknown banking command: ${cmd}`);
  }
  const API={VERSION,PRODUCTS,ensure,execute,reconcilePrudential,dormant};globalThis.GH_BANKING_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('banking',API);if(globalThis.window&&window!==globalThis)window.GH_BANKING_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
