(()=>{'use strict';const VERSION='2.9.0',num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0;
function ensure(s){s.bank=s.bank||{};s.bank.corporateClients=s.bank.corporateClients&&typeof s.bank.corporateClients==='object'?s.bank.corporateClients:{};for(const k of ['riskReviews','lettersOfCredit','guarantees','cashSweeps'])s.bank[k]=Array.isArray(s.bank[k])?s.bank[k]:[];for(const t of ['group','air','sea','road','power'])if(!s.bank.corporateClients[t])s.bank.corporateClients[t]={company:t,creditLimit:5000000,drawn:0,depositBalance:0,lastReview:0,rating:'BBB'};return s.bank;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx,F=globalThis.GH_FINANCE_CORE;ensure(s);if(cmd==='sync-corporate-clients'){const types=['group',...(s.openedCompanies||[]).filter(x=>['air','sea','road','power'].includes(x))];for(const type of types){const book=F.book(s,type),existing=s.bank.corporateClients[type]||{},baseValue=Math.max(5000000,num(s.groupValue)*(type==='group'?.04:.025));s.bank.corporateClients[type]={company:type,name:p.names?.[type]||s.companyRegistry?.[type]?.legalName||(type==='group'?s.profile?.name:type),accountId:book.accounts[0].id,depositBalance:num(existing.depositBalance),creditLimit:num(existing.creditLimit)||Math.round(baseValue),drawn:num(existing.drawn),rating:existing.rating||(type==='group'?s.profile?.creditRating:'BBB'),kyc:existing.kyc||'مكتمل',lastReview:num(existing.lastReview)};}return s.bank.corporateClients;}if(cmd==='review-limits'){for(const c of Object.values(s.bank.corporateClients)){const t=c.company,assets=(s.assets||[]).filter(a=>a.type===t).reduce((n,a)=>n+num(a.purchasePrice)*.55,0),cash=F.total(s,t),debt=num(F.book(s,t).debt),base=Math.max(5e6,cash*.35+assets*.12-debt*.08);c.creditLimit=Math.max(5e6,Math.round(base/1e5)*1e5);c.lastReview=now(s);c.rating=debt>cash*2?'BB':cash>debt?'A-':'BBB';}s.bank.riskReviews.unshift({at:now(s),type:'corporate-limits',clients:Object.keys(s.bank.corporateClients).length});s.bank.riskReviews=s.bank.riskReviews.slice(0,40);return true;}
if(cmd==='draw-facility'){const t=p.company;if(!['group','air','sea','road','power'].includes(t))throw new Error('invalid-company');const c=s.bank.corporateClients[t],a=Math.min(num(p.amount),Math.max(0,num(c.creditLimit)-num(c.drawn)));if(a<=0||F.operating(s,'bank')<a)throw new Error('facility-unavailable');const arrangementFee=Math.max(25000,a*.0035);if(F.operating(s,t)+a<arrangementFee)throw new Error('borrower-fee-unavailable');F.execute({state:s},'transfer',{from:'bank',to:t,amount:a,note:`سحب تسهيل ائتماني من بنك المجموعة`});F.execute({state:s},'spend',{company:t,amount:arrangementFee,note:'رسوم ترتيب تسهيل ائتماني مستحقة لبنك المجموعة',method:'قيد مصرفي',counterparty:'بنك المجموعة',line:'other'});F.execute({state:s},'credit',{company:'bank',amount:arrangementFee,note:`رسوم ترتيب تسهيل ائتماني · ${t}`,method:'قيد مصرفي',counterparty:t});c.drawn+=a;s.bank.loans=num(s.bank.loans)+a;s.bank.feeIncomeYTD=num(s.bank.feeIncomeYTD)+arrangementFee;F.book(s,t).debt+=a;return a;}
if(cmd==='trade-instrument'){const t=p.company,kind=p.kind==='lc'?'lc':'guarantee',a=Math.max(1e5,num(p.amount)),c=s.bank.corporateClients[t];if(!c||a>Math.max(0,num(c.creditLimit)-num(c.drawn)))throw new Error('credit-headroom');const fee=Math.max(15000,Math.round(a*(kind==='lc'?.006:.004)));F.execute({state:s},'spend',{company:t,amount:fee,note:kind==='lc'?'رسوم اعتماد مستندي':'رسوم ضمان مصرفي',method:'قيد مصرفي',counterparty:'بنك المجموعة'});F.execute({state:s},'credit',{company:'bank',amount:fee,note:`رسوم ${kind==='lc'?'اعتماد مستندي':'ضمان'}`,method:'قيد مصرفي',counterparty:t});s.bank.feeIncomeYTD=num(s.bank.feeIncomeYTD)+fee;s.bank.offBalance=num(s.bank.offBalance)+a;const doc={id:`${kind==='lc'?'LC':'GTEE'}-${Math.floor(now(s))}-${s.bank.lettersOfCredit.length+s.bank.guarantees.length+1}`,company:t,amount:a,fee,status:'ساري',issuedAt:now(s),expiryDay:Math.floor(now(s)/86400)+90,counterparty:p.counterparty||'طرف تجاري مسجل'};(kind==='lc'?s.bank.lettersOfCredit:s.bank.guarantees).unshift(doc);return doc;}
if(cmd==='cash-sweep'){let total=0;for(const t of ['air','sea','road','power']){if(!(s.openedCompanies||[]).includes(t))continue;const bal=F.operating(s,t),floor=Math.max(5e6,bal*.65),a=Math.max(0,Math.floor((bal-floor)/1e5)*1e5);if(a<5e5)continue;F.execute({state:s},'transfer',{from:t,to:'bank',amount:a,note:'Cash sweep يومي إلى بنك المجموعة'});s.bank.corporateClients[t].depositBalance+=a;s.bank.deposits=num(s.bank.deposits)+a;total+=a;}s.bank.cashSweeps.unshift({at:now(s),amount:total});s.bank.cashSweeps=s.bank.cashSweeps.slice(0,60);return total;}
if(cmd==='open-branch'){s.bank.branches=num(s.bank.branches)+1;s.bank.deposits=num(s.bank.deposits)+num(p.depositSeed||70000000);if(!s.unlockedSectors.includes('bank'))s.unlockedSectors.push('bank');return s.bank.branches;}
if(cmd==='issue-loans'||cmd==='fund-loan-portfolio'){const amount=Math.min(num(p.amount||20000000),F.operating(s,'bank'));if(amount<=0)throw new Error('bank-liquidity');if(cmd==='fund-loan-portfolio')F.execute({state:s},'spend',{company:'bank',amount,note:p.note||'تمويل محفظة قروض',method:'تحويل بنكي',taxable:false,line:'capex'});s.bank.loans=num(s.bank.loans)+amount;s.bank.interestIncome=num(s.bank.interestIncome)+amount*(Number(p.rate)||.06);s.bank.provisions=num(s.bank.provisions)+amount*num(p.provisionRate||.012);s.bank.requiredStableFunding=num(s.bank.requiredStableFunding)+amount*num(p.rsfFactor||.85);return amount;}
if(cmd==='stress'){s.advanced=s.advanced||{};s.advanced.bankStress={at:now(s),npl:Math.min(100,num(s.bank.npl)+2.5),withdrawal:num(s.bank.deposits)*.12,depositsAfter:num(s.bank.deposits)*.88,capitalRatio:Math.max(0,num(s.bank.capitalRatio)-3.1),rateShock:.02};return s.advanced.bankStress;}
if(cmd==='tick-day'){const d=Math.floor(Number(p.day)||Math.floor(now(s)/86400));let expired=0;for(const x of [...s.bank.lettersOfCredit,...s.bank.guarantees]){if(x.status==='ساري'&&Number(x.expiryDay||Infinity)<=d){x.status='منتهي';x.expiredDay=d;expired++;}}return {day:d,expired};}
throw new Error(`Unknown banking command: ${cmd}`)}
const API={VERSION,ensure,execute};globalThis.GH_BANKING_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('banking',API);if(globalThis.window&&window!==globalThis)window.GH_BANKING_CORE=API;})();
