/* Build 334: immutable, capability-contributed conference story contract. */
(()=>{'use strict';
const VERSION='3.0.0',PLAN_SCHEMA='gh-conference-plan-v1';
const clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value));
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>Number.isFinite(Number(value))?Number(value):0;
const int=value=>number(value).toLocaleString('en-US',{maximumFractionDigits:0});
const money=value=>`${int(value)} USD`;
const growth=value=>value==null?'غير متاح':`${number(value)>0?'+':''}${number(value).toFixed(1)}%`;
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(freeze);}return value;};
const usable=row=>row?.reportedDays>0&&!['error','warning','empty'].includes(row?.dataQuality?.status);
const annualGrowth=(row,key,year)=>{const days=y=>(Date.UTC(y+1,0,1)-Date.UTC(y,0,1))/86400000;return row?.reportedDays===days(Number(year))&&row?.prior?.reportedDays===days(Number(year)-1)?row.growth?.[key]:null;};
const coverage=row=>`${int(row?.reportedDays)} يومًا مسجلًا${row?.complete?' · سنة مكتملة':' · فترة غير مكتملة؛ لا تعرض مقارنة نمو سنوية'}`;
const metric=(label,value,id='')=>({id:String(id||label),label:String(label),value:String(value)});
const cleanText=(value,max=420)=>String(value??'').trim().replace(/\s+/g,' ').slice(0,max);
const stable=value=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`;};
function hashOwner(){const owner=globalThis.GH_CONTROL_PLANE;if(!owner?.sha256)throw new Error('conference-plan-hash-owner-unavailable');return owner;}
function hash(value){const owner=hashOwner();return owner.sha256(typeof owner.stable==='function'?owner.stable(value):stable(value));}
function narration(lines){const rows=(Array.isArray(lines)?lines:[lines]).map(value=>cleanText(value)).filter(Boolean);const duration=globalThis.GH_ARABIC_COPY?.readingDuration?.(rows)||Math.max(3000,Math.min(18000,rows.join(' ').split(/\s+/u).length*480));return {lines:rows,durationMs:duration};}
function sceneDefaults(group,year,accent){return {kicker:'GLOBAL HOLDINGS / ANNUAL REVIEW',headline:'',subtitle:'',metrics:[],caption:'',presenter:group.founder||'رئيس المجموعة',role:'رئيس المجموعة',type:'group',accent,logo:group.brand?.logo||'',templateId:'statement',narration:narration([]),cues:{camera:'screen',presenter:'center',audience:'attentive'}};}
function contributionScene(company,contribution,group,year,accent){
 const id=cleanText(contribution.id||contribution.chapterId,80);if(!id)throw new Error(`conference-contribution-id-missing:${company.type}`);
 const title=cleanText(contribution.title||company.legalName,160),metrics=(contribution.metrics||[]).map((row,index)=>metric(row.label??row.title,row.value??row.text,row.id||index));
 const lines=contribution.narration?.lines||contribution.narration||[title,contribution.caption].filter(Boolean);
 return {...sceneDefaults(group,year,accent),id:`${company.type}-${id}`,title,kicker:cleanText(contribution.kicker||`${String(company.shortName||company.type).toUpperCase()} · ${year}`,100),headline:cleanText(contribution.headline||title,180),subtitle:cleanText(contribution.subtitle,180),metrics,caption:cleanText(contribution.caption,360),presenter:cleanText(contribution.presenter||company.manager?.name||group.founder||'رئيس المجموعة',100),role:cleanText(contribution.role||company.manager?.role||'رئيس المجموعة · المنصب التنفيذي شاغر',120),type:company.type,logo:company.brand?.logo||'',accent:company.brand?.accent||accent,kind:cleanText(contribution.kind||id,40),templateId:cleanText(contribution.templateId||contribution.template||'metrics',60),narration:narration(lines),cues:{camera:contribution.cues?.camera||'screen',presenter:contribution.cues?.presenter||'stage-right',audience:contribution.cues?.audience||'attentive'}};
}
function legacyContributions(company,snapshot){
 const quality=usable(company),ops=company.ops||{},copy=globalThis.GH_ARABIC_COPY;
 const leadership={id:'leadership',kind:'leadership',templateId:'leadership',title:company.legalName,headline:company.manager?.name||'القيادة التنفيذية',subtitle:company.manager?.role||'يقدم الفصل رئيس المجموعة',caption:company.manager?`${company.manager.experience||'—'} سنة خبرة · ${company.manager.specialty||''}`:'المنصب الرسمي شاغر؛ يُدار العرض من قيادة المجموعة.',metrics:[metric('الموظفون',copy?.count?.(company.headcount,'employee')||int(company.headcount)),metric('الأصول',copy?.count?.(company.assets,'asset')||int(company.assets)),metric('المنشآت',copy?.count?.(company.facilities,'facility')||int(company.facilities))]};
 const financial={id:'financial',kind:'finance',templateId:'financial-waterfall',title:`${company.legalName} · النتائج`,headline:quality?money(company.net):'مراجعة البيانات',subtitle:'صافي نتيجة الفترة',metrics:quality?[metric('الإيرادات',money(company.grossRevenue)),metric('المصروفات',money(company.expenses)),metric('نمو الإيرادات',growth(annualGrowth(company,'revenue',snapshot.year)))]:[],caption:quality?coverage(company):(company.dataQuality?.reason||'لا توجد إقفالات مالية معتمدة.')};
 let stats;if(company.type==='power')stats=[metric('قدرة التوليد',`${int(ops.generationMW)} MW`),metric('التخزين',`${int(ops.storageMWh)} MWh`),metric('المشاريع',copy?.count?.(ops.projects,'project')||int(ops.projects))];else if(company.type==='bank')stats=[metric('الفروع',copy?.count?.(ops.branches,'branch')||int(ops.branches)),metric('عملاء الشركات',int(ops.corporateClients)),metric('السيولة',money(ops.liquidity))];else if(company.type==='mobility')stats=[metric('المركبات',copy?.count?.(ops.vehicles,'vehicle')||int(ops.vehicles)),metric('السائقون',int(ops.drivers)),metric('المراكز',copy?.count?.(ops.centers,'facility')||int(ops.centers))];else stats=[metric('الأصول',copy?.count?.(ops.assetCount,'asset')||int(ops.assetCount)),metric('المسارات',copy?.count?.(ops.routeCount,'route')||int(ops.routeCount)),metric('الرحلات',copy?.count?.(ops.tripCount,'trip')||int(ops.tripCount))];
 const operations={id:'operations',kind:'operations',templateId:'operations-scorecard',title:`${company.legalName} · التشغيل`,headline:'التشغيل والقدرات',subtitle:company.priority||'الأداء التشغيلي',metrics:stats,caption:`أولوية العام المقبل: ${company.priority||'لم تعتمد بعد'}`};
 return [leadership,financial,operations];
}
function companyContributions(company,snapshot){const rows=Array.isArray(company.conferenceContributions)&&company.conferenceContributions.length?company.conferenceContributions:legacyContributions(company,snapshot);const seen=new Set();return rows.filter(row=>{const id=String(row?.id||row?.chapterId||'');if(!id||seen.has(id))return false;seen.add(id);return true;});}
function buildScenePlan(input,{mode='full'}={}){
 const snap=clone(input||{}),g=snap.group||{},companies=snap.companies||[],year=snap.year||'',accent='#245bdb',scenes=[];
 const add=(id,title,opts={})=>{const base={...sceneDefaults(g,year,accent),id,title,...opts};base.narration=base.narration?.lines?narration(base.narration.lines):narration(base.narration||[base.title,base.subtitle,base.caption]);scenes.push(base);};
 add('opening','المؤتمر التنفيذي السنوي',{headline:String(year),subtitle:g.name||'Global Holdings',caption:'أداء واضح. قرارات للمستقبل.',kind:'opening',templateId:'opening',narration:[`أهلًا بكم في المؤتمر التنفيذي السنوي لـ${g.name||'المجموعة'}.`,`نستعرض نتائج ${year} كما سُجلت في أنظمة المجموعة، ثم ننتقل إلى أولويات المرحلة المقبلة.`],cues:{camera:'wide',presenter:'entrance',audience:'welcome'}});
 add('group-results','النتائج المالية للمجموعة',{headline:usable(g)?money(g.net):'بيانات قيد المراجعة',subtitle:'صافي نتيجة الفترة',metrics:usable(g)?[metric('الإيرادات',money(g.grossRevenue)),metric('المصروفات',money(g.expenses)),metric('النمو السنوي',growth(annualGrowth(g,'revenue',year)))]:[],caption:usable(g)?coverage(g):(g.dataQuality?.reason||'لا توجد إقفالات مالية معتمدة.'),kind:'finance',templateId:'financial-waterfall'});
 add('portfolio','شركات المجموعة',{headline:`${companies.length} شركات`,subtitle:'محفظة الأعمال',metrics:companies.map(c=>metric(c.legalName||c.type,usable(c)?money(c.net):'بيانات غير مكتملة',c.type)),caption:'صافي نتيجة الفترة حسب الشركة · الأرقام من سجل المؤتمر.',kind:'portfolio',templateId:'portfolio'});
 if(mode!=='brief'){
  for(const company of companies)for(const contribution of companyContributions(company,snap))scenes.push(contributionScene(company,contribution,g,year,accent));
  add('people','القيادات والموظفون',{headline:'الناس يصنعون الأثر',subtitle:'رواتب وقيادة المجموعة',metrics:companies.slice(0,8).map(c=>metric(c.legalName,`${int(c.headcount)} موظف · ${money(c.monthlyPayroll)} / شهر`,c.type)),caption:'المسير الحالي يشمل الزيادات المعتمدة ولا يكرر منصب الرئيس التنفيذي.',kind:'people',templateId:'people'});
  if((snap.achievements||[]).length)add('achievements','إنجازات العام',{headline:'من الاستراتيجية إلى التنفيذ',metrics:snap.achievements.slice(0,6).map((a,index)=>metric(a.title,a.detail,a.id||index)),caption:'إنجازات مسجلة وقت إعداد المؤتمر.',kind:'achievements',templateId:'milestones'});
 }
 add('outlook','العام المقبل',{headline:String(Number(year)+1),subtitle:'أولويات المجموعة',metrics:[metric('هدف الإيرادات',g.targetRevenue?money(g.targetRevenue):'لم يعتمد'),metric('هامش الربح المستهدف',g.targetMargin?`${g.targetMargin}%`:'لم يعتمد'),metric('الأولوية',g.priority||'لم تعتمد')],caption:'الأهداف خطط مستقبلية وليست نتائج محققة.',kind:'outlook',templateId:'outlook'});
 if(mode!=='brief'){const comments=(snap.social?.comments||[]).slice(0,3).map((row,index)=>metric(`${row.handle||'تعليق'} · ${row.country||''}`,row.text||'',`comment-${index+1}`));add('audience','صدى المؤتمر',{headline:`${int(snap.social?.viewers)} مشاهدة`,subtitle:'تفاعل الجمهور داخل عالم اللعبة',metrics:[metric('الحضور',int(snap.social?.attendees)),metric('تفاعل إيجابي',`${int(snap.social?.positive)}%`),metric('المنشورات',int(snap.social?.posts)),...comments],caption:'مؤشرات وتعليقات محاكية مشتقة من لقطة المؤتمر المؤرشفة.',kind:'audience',templateId:'audience'});}
 add('closing','ختام المؤتمر',{headline:'نبدأ الفصل القادم',subtitle:g.name||'Global Holdings',caption:'من نتائج هذا العام إلى فرص العام المقبل.',kind:'closing',templateId:'closing',narration:['بهذا نختتم مراجعة العام.','تتحول الأولويات المعروضة الآن إلى قرارات وخطط قابلة للمتابعة داخل المجموعة.'],cues:{camera:'wide',presenter:'center',audience:'closing'}});
 return freeze(scenes);
}
function planBody(bundle){const body=clone(bundle);delete body.planHash;return body;}
function buildPlanBundle(snapshot,{conferenceId='',createdAt=0}={}){const frozenSnapshot=clone(snapshot||{}),bundle={schema:PLAN_SCHEMA,modelVersion:VERSION,conferenceId:cleanText(conferenceId,96),dataContractVersion:cleanText(frozenSnapshot.dataContractVersion,64),createdAt:Number(createdAt)||0,snapshotHash:hash(frozenSnapshot),modes:{full:clone(buildScenePlan(frozenSnapshot,{mode:'full'})),brief:clone(buildScenePlan(frozenSnapshot,{mode:'brief'})),manual:clone(buildScenePlan(frozenSnapshot,{mode:'manual'}))}};bundle.planHash=hash(planBody(bundle));return freeze(bundle);}
function validatePlanBundle(bundle,snapshot=null){if(!bundle||bundle.schema!==PLAN_SCHEMA||!bundle.modes?.full?.length||!bundle.modes?.brief?.length||!bundle.modes?.manual?.length)throw new Error('conference-plan-invalid');if(hash(planBody(bundle))!==bundle.planHash)throw new Error('conference-plan-hash-mismatch');if(snapshot&&hash(snapshot)!==bundle.snapshotHash)throw new Error('conference-plan-snapshot-mismatch');return true;}
function scenesForPlan(bundle,mode='full'){validatePlanBundle(bundle);const selected=['full','brief','manual'].includes(mode)?mode:'full';return freeze(clone(bundle.modes[selected]));}
globalThis.GH_CONF_MODEL=Object.freeze({VERSION,PLAN_SCHEMA,buildScenePlan,buildPlanBundle,validatePlanBundle,scenesForPlan,clone,freeze,esc,number,int,money,usable,annualGrowth,coverage,metric,stable,hash});
if(typeof module!=='undefined'&&module.exports)module.exports=globalThis.GH_CONF_MODEL;
})();
