/* Stable presentation API for the lightweight fixed-angle conference renderer. */
(()=>{'use strict';
const ENGINE_ID='GH-CONFERENCE-3D',VERSION='4.0.0',M=globalThis.GH_CONF_MODEL,{esc}=M;
let active=null,lastDiagnostics=null;
const ANGLES=Object.freeze(['front','wide','stage']);
function phoneProfile(){return /iPhone|iPod|Android.+Mobile/i.test(String(globalThis.navigator?.userAgent||''))||!!globalThis.matchMedia?.('(max-width: 900px) and (pointer: coarse)').matches;}
class ConferenceSession{
 constructor(config,options={}){
  this.config=config;this.snapshot=M.freeze(M.clone(config.snapshot));this.mode=['full','brief','manual'].includes(options.mode)?options.mode:'full';
  this.resumePhase=['preflight','opening','presenting'].includes(config.lifecycleState)?config.lifecycleState:'preflight';
  if(config.planBundle){M.validatePlanBundle(config.planBundle,this.snapshot);if(config.planHash&&config.planHash!==config.planBundle.planHash)throw new Error('conference-engine-plan-hash-mismatch');this.planBundle=M.freeze(M.clone(config.planBundle));this.scenes=M.scenesForPlan(this.planBundle,this.mode);}
  else if(config.live)throw new Error('conference-live-plan-required');else this.scenes=M.buildScenePlan(this.snapshot,{mode:this.mode});
  this.index=Math.max(0,Math.min(this.scenes.length-1,Math.floor(M.number(options.startScene))));this.disposed=false;this.failed=false;this.playing=false;this.frames=0;this.phase='created';this.timer=0;this.events=[];this.panelMode=null;this.angle='front';this.assetsReady=false;this.isPhone=phoneProfile();this.motionReduced=!!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 }
 setPhase(next,notify=true){const allowed={created:['preflight'],preflight:['opening'],opening:['presenting'],presenting:['closing'],closing:['closed'],closed:[]};if(this.phase===next)return;if(!allowed[this.phase]?.includes(next))throw new Error(`conference-engine-phase-invalid:${this.phase}->${next}`);this.phase=next;if(this.root)this.root.dataset.phase=next;if(notify&&['opening','presenting','closing'].includes(next))this.config.onPhaseChange?.({state:next,sceneId:this.scenes[this.index]?.id||''});}
 listen(target,event,fn,options){target.addEventListener(event,fn,options);this.events.push(()=>target.removeEventListener(event,fn,options));}
 mount(){
  this.setPhase('preflight',false);this.previousFocus=document.activeElement;this.previousOverflow=document.body.style.overflow;
  const root=this.root=document.createElement('section');root.className='ghc3';root.dir='rtl';root.dataset.angle=this.angle;root.dataset.phase=this.phase;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','المؤتمر التنفيذي السنوي');
  const shortName=this.snapshot.group.shortName||this.snapshot.group.brand?.shortName||'GH';
  root.innerHTML=`<header class="ghc3-header"><div class="ghc3-brand"><span class="ghc3-mark" dir="auto">${esc(shortName)}</span><b>${esc(this.snapshot.group.name||'Global Holdings')}</b><span class="ghc3-year">${esc(this.snapshot.year)}</span></div><nav class="ghc3-angle" aria-label="زوايا القاعة"><button data-c3="angle-front" aria-pressed="true">أمامية</button><button data-c3="angle-wide" aria-pressed="false">واسعة</button><button data-c3="angle-stage" aria-pressed="false">المسرح</button></nav><button class="ghc3-close" data-c3="close" aria-label="إغلاق المؤتمر">×</button></header><main class="ghc3-viewport"><div class="ghc3-screen-frame"><div class="ghc3-document"></div></div><div class="ghc3-speaker"><span></span><b></b><small></small></div><div class="ghc3-opening" role="status" aria-live="polite"><div class="ghc3-opening-copy"><span>GLOBAL HOLDINGS · EXECUTIVE CONFERENCE</span><b class="ghc3-opening-mark" dir="auto">${esc(shortName)}</b><h1>المؤتمر التنفيذي السنوي</h1><p>${esc(this.snapshot.group.name||'Global Holdings')} <bdi dir="ltr">${esc(this.snapshot.year)}</bdi></p><div class="ghc3-opening-route"><i></i><small>حصيلة العام</small><i></i><small>شركات المجموعة</small><i></i><small>المرحلة القادمة</small></div></div></div><div class="ghc3-loading" role="status"><span></span>تجهيز المؤتمر…</div><div class="ghc3-recovery" hidden><h2>تعذّر عرض المؤتمر</h2><p>أعد المحاولة من الفصل الحالي.</p><button data-c3="retry">إعادة المحاولة</button><button data-c3="close">إغلاق</button></div></main><footer class="ghc3-controls"><div class="ghc3-progress" role="progressbar" aria-label="تقدم فصول المؤتمر"><i></i></div><div class="ghc3-current"><button data-c3="chapters" aria-expanded="false" aria-label="فصول المؤتمر">☰</button><span class="ghc3-count" dir="ltr"></span><span class="ghc3-current-title"></span></div><div class="ghc3-transport"><button data-c3="prev" aria-label="الفصل السابق">→</button><button data-c3="play">تشغيل تلقائي</button><button data-c3="next" aria-label="الفصل التالي">←</button></div><div class="ghc3-detail-actions"><button data-c3="details">التفاصيل ↗</button><button data-c3="finish" hidden>اختتام المؤتمر</button></div></footer><aside class="ghc3-panel" hidden><header><h3></h3><button data-c3="panel-close" aria-label="إغلاق التفاصيل">×</button></header><div class="ghc3-panel-content"></div></aside>`;
  document.body.style.overflow='hidden';document.body.appendChild(root);this.siblings=[...document.body.children].filter(el=>el!==root&&el.tagName!=='SCRIPT').map(el=>[el,el.inert]);this.siblings.forEach(([el])=>{el.inert=true;});
  const viewport=root.querySelector('.ghc3-viewport');this.world=new globalThis.GH_CONF_WORLD.Auditorium(viewport);this.board=new globalThis.GH_CONF_BOARD.Board(root.querySelector('.ghc3-document'));this.updateChapter(false);
  this.listen(root,'click',e=>{const b=e.target.closest('[data-c3]');if(b&&root.contains(b))this.action(b.dataset.c3);});this.listen(root,'keydown',e=>this.keydown(e));
  this.listen(document,'visibilitychange',()=>{if(document.hidden){this.wasPlaying=this.playing;this.pause();}else if(this.wasPlaying){this.play();this.wasPlaying=false;}});this.listen(globalThis,'pagehide',()=>this.close(false));root.querySelector('[data-c3="close"]').focus();this.ready=this.initialize();return this;
 }
 async initialize(){try{
   this.setPhase('opening',this.config.live&&this.resumePhase==='preflight');
   await Promise.all([400,500,600].map(weight=>document.fonts?.load?.(`${weight} 20px "GH Plex Arabic"`,'المؤتمر')||Promise.resolve()));
   if(this.disposed)return;this.assetsReady=true;this.frames++;this.root.querySelector('.ghc3-loading')?.remove();this.setPhase('presenting',this.config.live&&this.resumePhase!=='presenting');this.root.querySelector('.ghc3-opening')?.classList.add('is-ready');this.persistProgress();if(this.mode!=='manual')this.play();
  }catch(error){if(!this.disposed)this.fail(error);}}
 updateChapter(persist=true){if(this.disposed)return;const row=this.scenes[this.index];this.board.update(this.snapshot,row);this.frames++;this.root.querySelector('.ghc3-current-title').textContent=row.title;this.root.querySelector('.ghc3-count').textContent=`${String(this.index+1).padStart(2,'0')} / ${String(this.scenes.length).padStart(2,'0')}`;
  const speaker=this.root.querySelector('.ghc3-speaker');speaker.querySelector('span').textContent=row.type==='group'?'قيادة المجموعة':row.title.split(' · ')[0];speaker.querySelector('b').textContent=row.presenter;speaker.querySelector('small').textContent=row.role;
  this.root.querySelector('[data-c3="prev"]').disabled=this.index===0;this.root.querySelector('[data-c3="next"]').disabled=this.index===this.scenes.length-1;this.root.querySelector('[data-c3="finish"]').hidden=!this.config.live||this.index!==this.scenes.length-1;
  const progress=this.root.querySelector('.ghc3-progress');progress.firstElementChild.style.width=`${(this.index+1)/this.scenes.length*100}%`;progress.setAttribute('aria-valuemin','1');progress.setAttribute('aria-valuemax',String(this.scenes.length));progress.setAttribute('aria-valuenow',String(this.index+1));if(this.panelMode==='details')this.openPanel('details');if(persist)this.persistProgress();}
 persistProgress(){try{this.config.onProgress?.({mode:this.mode,index:this.index,sceneId:this.scenes[this.index].id});}catch(error){this.pause();this.config.onError?.(error);}}
 go(index){if(this.disposed||this.failed)return;const next=Math.max(0,Math.min(this.scenes.length-1,index));if(next===this.index)return;this.index=next;this.updateChapter();if(this.playing)this.schedule();}
 setAngle(angle){if(this.disposed||!ANGLES.includes(angle))return;this.angle=this.world.setAngle(angle);for(const b of this.root.querySelectorAll('[data-c3^="angle-"]'))b.setAttribute('aria-pressed',String(b.dataset.c3===`angle-${angle}`));}
 schedule(){clearTimeout(this.timer);if(!this.playing||document.hidden)return;const narrated=Math.max(0,Number(this.scenes[this.index].narration?.durationMs)||0);this.timer=setTimeout(()=>{if(this.index===this.scenes.length-1)this.pause();else this.go(this.index+1);},this.mode==='brief'?Math.max(7000,narrated):Math.max(9000,narrated));}
 play(){if(this.disposed||this.failed||!this.assetsReady)return;this.playing=true;this.root.querySelector('[data-c3="play"]').textContent='إيقاف مؤقت';this.schedule();}
 pause(){this.playing=false;clearTimeout(this.timer);this.timer=0;this.root?.querySelector('[data-c3="play"]')?.replaceChildren(document.createTextNode('تشغيل تلقائي'));}
 openPanel(mode){this.pause();this.panelMode=mode;const panel=this.root.querySelector('.ghc3-panel');panel.hidden=false;panel.querySelector('h3').textContent=mode==='chapters'?'فصول المؤتمر':'تفاصيل الفصل';this.root.querySelector('[data-c3="chapters"]').setAttribute('aria-expanded',String(mode==='chapters'));const body=panel.querySelector('.ghc3-panel-content');
  if(mode==='chapters')body.innerHTML=this.scenes.map((s,i)=>`<button data-c3="scene-${i}" ${i===this.index?'aria-current="step"':''}><small>${String(i+1).padStart(2,'0')}</small><span>${esc(s.title)}</span></button>`).join('');
  else{const s=this.scenes[this.index];body.innerHTML=`<small>${esc(this.snapshot.year)} · سجل المؤتمر</small><h2>${esc(s.title)}</h2><p class="ghc3-detail-value" dir="auto">${esc(s.headline)}</p><p>${esc(s.subtitle)}</p><dl>${s.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd dir="auto">${esc(m.value)}</dd></div>`).join('')}</dl>${s.narration?.lines?.length?`<div class="ghc3-narration" aria-label="نص المتحدث">${s.narration.lines.map(line=>`<p>${esc(line)}</p>`).join('')}</div>`:''}<p>${esc(s.caption)}</p><p>${esc(s.presenter)} · ${esc(s.role)}</p>`;}panel.querySelector('[data-c3="panel-close"]').focus();}
 closePanel(){this.root.querySelector('.ghc3-panel').hidden=true;this.root.querySelector('[data-c3="chapters"]').setAttribute('aria-expanded','false');const mode=this.panelMode;this.panelMode=null;this.root.querySelector(`[data-c3="${mode==='chapters'?'chapters':'details'}"]`).focus();}
 keydown(e){if(e.key==='Escape'){e.preventDefault();if(this.panelMode)this.closePanel();else this.close();}else if(e.key==='ArrowLeft'){e.preventDefault();this.go(this.index+1);}else if(e.key==='ArrowRight'){e.preventDefault();this.go(this.index-1);}else if(e.key==='Tab'){const scope=this.panelMode?this.root.querySelector('.ghc3-panel'):this.root,items=[...scope.querySelectorAll('button:not([disabled])')].filter(el=>el.offsetParent!==null),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 action(action){if(action==='close')this.close();else if(action==='prev')this.go(this.index-1);else if(action==='next')this.go(this.index+1);else if(action==='play')this.playing?this.pause():this.play();else if(action==='chapters'||action==='details')this.openPanel(action);else if(action==='panel-close')this.closePanel();else if(action.startsWith('angle-'))this.setAngle(action.slice(6));else if(action.startsWith('scene-')){this.go(Number(action.slice(6)));this.closePanel();}else if(action==='retry'){const config=this.config,options={startScene:this.index,mode:this.mode};this.close(false);launch(config,options);}else if(action==='finish'&&!this.finishing){this.finishing=true;try{this.setPhase('closing');this.config.onFinish?.();this.close(false);}catch(error){this.finishing=false;this.config.onError?.(error);}}}
 fail(error){this.failed=true;this.pause();this.lastError=String(error.message||error);this.root.querySelector('.ghc3-loading')?.remove();this.root.querySelector('.ghc3-recovery').hidden=false;this.root.querySelector('[data-c3="retry"]').focus();}
 diagnostics(){return{engine:'GH-CONFERENCE-2D',engineId:ENGINE_ID,version:VERSION,active:!this.disposed,failed:this.failed,phase:this.phase,planHash:this.planBundle?.planHash||null,chapter:this.scenes[this.index].id,chapters:this.scenes.length,frames:this.frames,webglFrames:0,scheduledFrame:false,playing:this.playing,angle:this.angle,camera:this.angle,audience:0,pixelRatio:1,drawCalls:0,triangles:0,geometries:0,textures:0,assetsReady:!!this.assetsReady,staticPresenter:true,error:this.lastError||null};}
 close(persist=true){if(this.disposed)return;if(persist&&['opening','presenting'].includes(this.phase))this.persistProgress();lastDiagnostics=this.diagnostics();if(this.phase==='closing')this.setPhase('closed',false);this.disposed=true;this.pause();for(const remove of this.events)remove();this.events=[];this.board?.dispose();this.world?.dispose();this.root?.remove();document.body.style.overflow=this.previousOverflow;for(const [el,inert] of this.siblings||[])if(el.isConnected)el.inert=inert;if(this.previousFocus?.isConnected)this.previousFocus.focus();if(active===this)active=null;this.config.onClose?.();}
}
function launch(config,options={}){if(!config?.snapshot?.group)throw new Error('conference-snapshot-required');active?.close();const session=new ConferenceSession(config,options);active=session;return session.mount();}
globalThis.GH_CONFERENCE_3D=Object.freeze({ENGINE_ID,VERSION,buildScenePlan:M.buildScenePlan,launch,isActive:()=>!!active&&!active.disposed,close:()=>active?.close(),diagnostics:()=>active?.diagnostics()||{...lastDiagnostics,active:false}});
})();
