(()=>{'use strict';
const VERSION='3.1.0',DOCUMENT_MIGRATION_VERSION=1,num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0;
function ensure(s){s.contractRegistry=s.contractRegistry&&typeof s.contractRegistry==='object'&&!Array.isArray(s.contractRegistry)?s.contractRegistry:{};s.acceptedContracts=Array.isArray(s.acceptedContracts)?s.acceptedContracts:[];s.failedBids=Array.isArray(s.failedBids)?s.failedBids:[];s.contractStartDays=s.contractStartDays&&typeof s.contractStartDays==='object'&&!Array.isArray(s.contractStartDays)?s.contractStartDays:{};return s;}
function world(s,cmd,p){try{return globalThis.GH_BUSINESS_WORLD?.execute?.({state:s},cmd,p)||null;}catch(error){console.warn('business-world contract bridge rejected',cmd,error);return null;}}
function officialId(id,doc={}){return String(doc.financeDocumentId||`COMM-${doc.number||id}`);}
function finance(){const owner=globalThis.GH_FINANCE_CORE;if(!owner?.execute)throw new Error('contract-finance-owner-unavailable');return owner;}
function officialPayload(s,id,doc,p={}){const startDay=Number.isFinite(Number(p.startDay))?Number(p.startDay):Number(s.contractStartDays?.[id]??Math.floor(now(s)/86400)),termMonths=num(p.termMonths||doc.termMonths),endDay=Number.isFinite(Number(p.endDay))?Number(p.endDay):termMonths?startDay+Math.max(1,Math.round(termMonths*30)):null;return {id:officialId(id,doc),company:p.company||doc.company||doc.sector||'group',contractType:String(p.contractType||doc.category||'عقد عميل تجاري'),title:String(p.name||doc.title||id),counterparty:String(p.client||doc.counterparty||doc.client||'عميل تعاقدي'),amount:num(p.value||doc.amount||doc.value),currency:String(p.currency||doc.currency||'USD'),startDay,endDay,status:doc.status==='منتهي'?'منتهي':'موقع وساري',terms:{termMonths,sector:String(p.sector||doc.sector||''),region:String(p.region||doc.region||''),sla:String(p.sla||doc.sla||''),penalty:String(p.penalty||doc.penalty||''),capacity:String(p.capacity||doc.capacity||''),payment:String(p.payment||doc.payment||'')},sourceRefs:[id,doc.number].filter(Boolean),linkedDocumentNumbers:(p.linkedDocumentNumbers||[]).filter(Boolean),linkedTransferReferences:(p.linkedTransferReferences||[]).filter(Boolean)};}
function linkOfficialDocument(_s,_id,doc,official){if(doc.documentProofId)return doc;Object.assign(doc,{financeDocumentId:official.id,financeDocumentProofId:official.documentProofId,financeDocumentDigest:official.contentDigest});return doc;}
function migrateDocuments(s,meta={}){ensure(s);if(Number(s.contractDocumentMigrationVersion)>=DOCUMENT_MIGRATION_VERSION)return {migrated:0,skipped:0};const F=finance(),proofOwner=globalThis.GH_DOCUMENT_PROOF;let migrated=0,skipped=0;for(const [id,doc] of Object.entries(s.contractRegistry)){if(!doc||!['نشط','منتهي'].includes(doc.status))continue;const company=String(doc.company||doc.companyId||doc.ownerCompanyId||doc.sector||'');if(!company){skipped++;continue;}try{const official=F.execute({state:s},'register-commercial-contract',officialPayload(s,id,doc,{company}));if(doc.financeDocumentId!==official.id)linkOfficialDocument(s,id,doc,official,'legacy-name-only');if(!doc.documentProofId){if(!proofOwner?.sealDocument)throw new Error('contract-document-proof-owner-unavailable');proofOwner.sealDocument(s,doc,{type:'commercial-contract',companyId:company,authorizationKind:'legacy-name-only'});}migrated++;}catch(error){if(/company-(?:not-found|unknown)|commercial-contract-reference-conflict/.test(String(error?.message||error))){skipped++;continue;}throw error;}}if(!skipped)s.contractDocumentMigrationVersion=DOCUMENT_MIGRATION_VERSION;return {migrated,skipped};}
function execute(ctx,cmd,p={},meta={}){const s=ctx.state||ctx;ensure(s);
 if(cmd==='bid'){
  const id=String(p.id||'');if(!id)throw new Error('contract-id-required');if(s.acceptedContracts.includes(id))throw new Error('contract-already-signed');const won=!!p.won,partyId=globalThis.GH_BUSINESS_WORLD?.partyIdForName?.(s,p.client,'customer')||null;
  if(won){const row={status:'بانتظار التوقيع',number:p.number||`GH-CN-${Math.floor(now(s))}-${Object.keys(s.contractRegistry).length+1}`,wonAt:now(s),client:p.client||'',clientPartyId:partyId,sector:p.sector||'',category:p.category||'',title:p.title||id,value:num(p.value),termMonths:num(p.termMonths),region:p.region||'',sla:p.sla||'',penalty:p.penalty||'',capacity:p.capacity||'',payment:p.payment||''};s.contractRegistry[id]=row;world(s,'record-bid',{id,partyId,won:true,client:p.client,sector:p.sector,title:p.title,value:p.value});return {won:true,record:row};}
  if(!s.failedBids.includes(id))s.failedBids.push(id);world(s,'record-bid',{id,partyId,won:false,client:p.client,sector:p.sector,title:p.title,value:p.value,competitorId:p.competitorId,competitorName:p.competitorName});return {won:false,competitorId:p.competitorId||null};
 }
 if(cmd==='sign'){
  const id=String(p.id||''),doc=s.contractRegistry[id];if(!doc)throw new Error('contract-not-awarded');if(doc.status!=='بانتظار التوقيع')throw new Error('contract-not-signable');
  const company=String(p.company||p.companyId||p.sector||doc.sector||'group'),startDay=Math.floor(now(s)/86400);doc.status='نشط';doc.signedAt=now(s);doc.company=company;doc.counterparty=p.client||doc.client||'عميل تعاقدي';doc.counterpartyPartyId=doc.clientPartyId=doc.clientPartyId||globalThis.GH_BUSINESS_WORLD?.partyIdForName?.(s,doc.counterparty,'customer')||null;doc.amount=num(p.value||doc.value);doc.currency=String(p.currency||'USD');doc.note=String(p.note||`عقد تجاري · ${p.name||doc.title||id}`);for(const key of ['category','region','sla','penalty','capacity','payment'])if(p[key]!=null)doc[key]=String(p[key]);if(!s.acceptedContracts.includes(id))s.acceptedContracts.push(id);s.contractStartDays[id]=startDay;const F=finance(),linkedDocumentNumbers=[],linkedTransferReferences=[];if(num(p.deposit)>0){const deposit=F.execute({state:s},'credit',{company,amount:num(p.deposit),note:p.note||`دفعة مقدمة · ${p.name||id}`,method:'تحويل عميل',taxable:p.taxable!==false,counterparty:p.client||doc.client||'عميل تعاقدي',sourceRefs:[id,doc.number]});if(deposit?.number)linkedDocumentNumbers.push(deposit.number);if(deposit?.transferReference)linkedTransferReferences.push(deposit.transferReference);}const official=F.execute({state:s},'register-commercial-contract',officialPayload(s,id,doc,{...p,company,startDay,linkedDocumentNumbers,linkedTransferReferences}));Object.assign(doc,{financeDocumentId:official.id,financeDocumentProofId:official.documentProofId,financeDocumentDigest:official.contentDigest});const proofOwner=globalThis.GH_DOCUMENT_PROOF;if(!proofOwner?.sealDocument)throw new Error('contract-document-proof-owner-unavailable');const system=meta.systemAuthorized===true&&!globalThis.GH_DOMAIN_COMMANDS?.hasActivePlayerApproval?.();proofOwner.sealDocument(s,doc,{type:'commercial-contract',companyId:company,authorizationKind:system?'system-unsealed':'pending-approval'});
  world(s,'record-contract',{id,number:doc.number,partyId:doc.clientPartyId,client:p.client||doc.client,company:p.company||p.sector||doc.sector||'group',sector:p.sector||doc.sector,title:p.name||doc.title||id,value:num(p.value||doc.value),termMonths:num(p.termMonths||doc.termMonths),status:'نشط',signedAt:doc.signedAt});return doc;
 }
 if(cmd==='expire'){
  const id=String(p.id||''),doc=s.contractRegistry[id];if(!doc)return false;const proofOwner=globalThis.GH_DOCUMENT_PROOF;if(!proofOwner?.amendDocument)throw new Error('contract-document-proof-owner-unavailable');if(!doc.documentProofId)proofOwner.sealDocument(s,doc,{type:'commercial-contract',companyId:doc.company||doc.sector||'group',authorizationKind:'legacy-name-only'});const system=meta.systemAuthorized===true&&!globalThis.GH_DOMAIN_COMMANDS?.hasActivePlayerApproval?.(),authorizationKind=system?'system-unsealed':'pending-approval',endedAt=now(s),financeId=officialId(id,doc);if((s.finance?.commercialContracts||[]).some(row=>row.id===financeId))finance().execute({state:s},'update-commercial-contract-status',{id:financeId,status:'منتهي',endedAt,reason:'اكتمال مدة العقد'});proofOwner.amendDocument(s,doc,{transition:'contract-expired',authorizationKind,mutate:row=>{row.status='منتهي';row.endedAt=endedAt;}});s.acceptedContracts=s.acceptedContracts.filter(x=>x!==id);delete s.contractStartDays[id];
  world(s,'record-contract',{id,number:doc.number,partyId:doc.clientPartyId,client:doc.client,company:doc.company||doc.sector||'group',sector:doc.sector,title:doc.title||id,value:num(doc.value),termMonths:num(doc.termMonths),status:'منتهي'});return doc;
 }
 if(cmd==='tick-day'){const day=Math.max(0,Math.floor(Number(p.day)||0)),terms=p.terms&&typeof p.terms==='object'?p.terms:{},expired=[];for(const id of [...s.acceptedContracts]){const termDays=Math.max(1,Math.floor(Number(terms[id])||0));if(!termDays)continue;const start=Number(s.contractStartDays[id]??day);if(day-start>=termDays){execute({state:s},'expire',{id},meta);expired.push(id);}}return {day,expired};}
 if(cmd==='migrate-documents')return migrateDocuments(s,meta);
 throw new Error(`Unknown contracts command: ${cmd}`);
}
const API={VERSION,DOCUMENT_MIGRATION_VERSION,ensure,migrateDocuments,execute};globalThis.GH_CONTRACTS_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('contracts',API);if(globalThis.window&&window!==globalThis)window.GH_CONTRACTS_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
