(()=>{
'use strict';
const VERSION='2.9.0';
const DAY=86400;
const defs={
 air:{name:'إدارة عمليات الطيران',mission:'سلامة وجدولة واعتمادية الأسطول وربحية التشغيل.',cadence:1,report:'تقرير OCC اليومي',owner:'مدير مركز التحكم التشغيلي',tasks:['مراجعة Dispatch Reliability وAOG','موازنة الجداول والسعة والمسارات','مراجعة الصيانة والاحتياطي الفني','رفع الاستثناءات التشغيلية للإدارة']},
 sea:{name:'إدارة العمليات البحرية',mission:'إدارة الرحلات والموانئ والوقود والجاهزية البيئية.',cadence:1,report:'تقرير الأسطول والرحلات',owner:'مدير العمليات البحرية',tasks:['مراجعة CII/EEXI وSEEMP','مراجعة Dry Dock والصيانة','تحليل الانتظار وDemurrage والبنكر','رفع خطة تصحيح عند تدهور التصنيف']},
 road:{name:'إدارة اللوجستيات والشبكة',mission:'التسليم في الوقت والسعة والتتبع وكفاءة الشبكة.',cadence:1,report:'تقرير الشبكة اللوجستية',owner:'مدير الشبكة اللوجستية',tasks:['مراجعة OTIF والتوقيت','مراجعة Empty Miles واستغلال المستودعات','مراجعة التتبع والجمارك والبنية','رفع اختناقات الشبكة وخطة المعالجة']},
 power:{name:'إدارة تشغيل الطاقة',mission:'موثوقية الإمداد والتوليد والتخزين والصيانة.',cadence:1,report:'تقرير التشغيل والاعتمادية',owner:'مدير مركز التحكم بالطاقة',tasks:['مراجعة القدرة المتاحة وهامش الاحتياط','مراجعة Dispatch والصيانة','مراجعة SOC وصحة التخزين','رفع مخاطر الاعتمادية والتوسع المطلوب']},
 bank:{name:'إدارة البنك والمخاطر',mission:'رأس المال والسيولة والائتمان والتمويل المستقر.',cadence:1,report:'تقرير ALM والمخاطر البنكية',owner:'الرئيس التنفيذي للمخاطر',tasks:['مراجعة CET1/RWA','مراجعة LCR/NSFR','مراجعة NPL والمخصصات','رفع حدود المخاطر وخطة رأس المال/السيولة']},
 treasury:{name:'الخزينة والسيولة',mission:'السيولة اليومية والتمويل والتحويلات والتعرضات.',cadence:1,report:'تقرير الخزينة اليومي',owner:'أمين الخزينة',tasks:['تجميع مراكز النقد','مراجعة الدين والاستحقاقات','مراجعة التحويلات والتعرضات','رفع فجوات السيولة والتمويل']},
 audit:{name:'التدقيق الداخلي',mission:'اختبار الضوابط وتتبع الملاحظات وإغلاقها.',cadence:7,report:'تقرير لجنة التدقيق',owner:'رئيس التدقيق الداخلي',tasks:['اختبار القيود والمستندات','اختبار دورة الطلبات والموافقات','متابعة الملاحظات المفتوحة','رفع الملاحظات الحرجة للجنة التدقيق']},
 legal:{name:'الشؤون القانونية',mission:'العقود والقضايا والالتزامات والتجديدات.',cadence:7,report:'تقرير قانوني للإدارة',owner:'المستشار العام',tasks:['مراجعة العقود والتجديدات','مراجعة القضايا والمطالبات','فحص الالتزامات النظامية','رفع القضايا الجوهرية للإدارة']},
 insurance:{name:'التأمين والمخاطر القابلة للتحويل',mission:'التغطية والمطالبات والتجديد والتعرض.',cadence:7,report:'تقرير التأمين والتعرض',owner:'مدير التأمين المؤسسي',tasks:['مراجعة حدود التغطية','مراجعة المطالبات والاحتياطي','تحديث تعرض الأصول','رفع فجوات التغطية والتجديد']},
 cyber:{name:'الأمن السيبراني',mission:'المراقبة والحوادث والمرونة واستمرارية الأعمال.',cadence:1,report:'تقرير الأمن السيبراني',owner:'مسؤول أمن المعلومات',tasks:['مراجعة الحوادث والتنبيهات','فحص الضوابط الحرجة','مراجعة الاستمرارية والاستعادة','رفع الحوادث الجوهرية']},
 safety:{name:'السلامة وHSE',mission:'سلامة الأشخاص والأصول والتحقيقات والإجراءات التصحيحية.',cadence:1,report:'تقرير HSE',owner:'مدير السلامة',tasks:['مراجعة الحوادث وAOG/التعطل','فحص الصيانة والحالة','متابعة الإجراءات التصحيحية','رفع المخاطر الحرجة']},
 research:{name:'البحث والتطوير',mission:'تحويل البرامج من دراسة إلى أثر تشغيلي قابل للقياس.',cadence:7,report:'تقرير محفظة R&D',owner:'مدير البحث والتطوير',tasks:['مراجعة تقدم المراحل','مراجعة الإنفاق مقابل الأثر','اختبار الجاهزية التشغيلية','رفع قرار الاستمرار/الإيقاف']},
 esg:{name:'الاستدامة والتحول',mission:'تنفيذ برامج الاستدامة وقياس الأثر دون تضخيم تراكمي.',cadence:7,report:'تقرير الاستدامة',owner:'مدير الاستدامة',tasks:['مراجعة البرامج ونضجها','قياس أثر الانبعاثات والطاقة','مراجعة الالتزامات القطاعية','رفع البرامج المتعثرة والقرارات المطلوبة']},
 board:{name:'مجلس الإدارة والحوكمة',mission:'الرقابة الاستراتيجية والقرارات واللجان والمتابعة.',cadence:30,report:'حزمة مجلس الإدارة',owner:'أمين مجلس الإدارة',tasks:['مراجعة الأداء مقابل الخطة','مراجعة المخاطر ورأس المال','مراجعة القرارات الجوهرية','متابعة تنفيذ قرارات المجلس']}
};
const aiRoles={
 air:'يراقب الاعتمادية والـAOG والسعة والربحية، يفتح حالات استثناء، يقترح إعادة جدولة/صيانة/سعة، ويرفع CAPEX أو إيقاف توسع عند تجاوز الحدود.',
 sea:'يراقب CII/EEXI والوقود والانتظار والصيانة، يفتح خطة تصحيح ويتابعها ويصعد قرارات الوقود/السرعة/Dry Dock.',
 road:'يراقب OTIF والتتبع وEmpty Miles وتشبع المستودعات، يفتح اختناقات الشبكة ويقترح إعادة الموازنة ويرفع طلبات السعة عند ثبوت الفجوة.',
 power:'يراقب الاحتياط والتوافر والتخزين وCurtailment، يفتح حالات اعتمادية ويقترح Dispatch وصيانة ويصعد توسعة القدرة إذا بقي الهامش منخفضًا.',
 bank:'يراقب رأس المال والسيولة والائتمان، يفتح تجاوزات الحدود، يوقف اقتراح نمو الائتمان عند كسرها ويرفع خطة رأس مال/تمويل/مخصصات.',
 treasury:'يتنبأ فجوات النقد والاستحقاقات والتعرض، يفتح فجوات تمويل ويقترح Sweep/تحوط/تمويل ويرفع ما يتجاوز حدود التفويض.',
 audit:'يختار عينات عالية المخاطر من القيود والطلبات، يفتح ملاحظة موثقة ولا يغلقها إلا بعد تحقق مستقل، ويرفع الحرجة للجنة التدقيق.',
 legal:'يراقب العقود والقضايا والتجديدات والاختصاصات، ينشئ قائمة التزامات ويرفع المخاطر القانونية الجوهرية قبل التنفيذ.',
 insurance:'يعيد احتساب التعرض والحدود والاحتياط، يربط المطالبات بالأصول ويصعد فجوات التغطية والتجديد.',
 cyber:'يراقب الأخطاء والحوادث والتغطية والاستعادة، يفتح Incident ويحدد RTO/RPO التشغيلي ويصعد الحوادث الجوهرية وخطط الاستعادة.',
 safety:'يراقب الحالة والصيانة والحوادث، يفتح إجراءات تصحيحية ويصعد إيقاف الأصل/العملية عند تجاوز حدود السلامة.',
 research:'يقارن كل مرحلة بالميزانية والأثر المثبت، يفتح Gate review ويوصي استمرار/إيقاف/تجربة ويمنع احتساب أثر كامل قبل الجاهزية.',
 esg:'يراقب نضج البرامج والأثر القطاعي، يمنع تضخيم المؤشرات ويرفع البرامج المتعثرة أو الالتزامات البيئية الجوهرية.',
 board:'يجمع Board Pack من المال والمخاطر والتشغيل وAI، يرتب القرارات حسب الجوهرية، يسجل القرار والمالك والموعد ويتابع الإغلاق.'
};
const procedures={
 air:['OCC review','Exception triage','Maintenance/crew/capacity check','Network profitability review','Executive brief','Closure verification'],
 sea:['Voyage/port review','Fuel & carbon review','Dry-dock readiness','Corrective plan','Management escalation','Closure verification'],
 road:['Network & warehouse review','Shipment exception review','Tracking/customs review','Capacity rebalancing','Management escalation','Closure verification'],
 power:['Dispatch & load review','Reserve/contingency review','Maintenance coordination','Storage/curtailment review','Capacity decision','Closure verification'],
 bank:['Daily liquidity & ALM','Credit quality review','Capital/RWA review','Stress & limits','Management action','Closure verification'],
 treasury:['Cash positioning','Funding maturity review','FX/rate exposure review','Liquidity action','Escalation','Closure verification'],
 audit:['Risk-based plan','Evidence sampling','Finding & owner','Management response','Independent closure verification'],
 legal:['Contract/case intake','Obligation calendar','Legal review','Sign-off/escalation','Closure evidence'],
 insurance:['Exposure declaration','Coverage adequacy','Claim reserve','Renewal recommendation','Settlement/closure'],
 cyber:['Monitor & triage','Contain','Recover','Control test','Post-incident review','Closure'],
 safety:['Hazard review','Incident investigation','Corrective action','Verification','Closure'],
 research:['Business case','Prototype','Controlled trial','Readiness gate','Scale/stop decision'],
 esg:['Baseline','Program execution','Impact measurement','Independent verification','Disclosure/escalation'],
 board:['Agenda & board pack','Committee review','Resolution','Owner/deadline','Follow-up & closure']
};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,num(v)));
const dayOf=s=>Math.floor(num(s?.simSeconds)/DAY);
function ensure(state){state.advanced=state.advanced||{};const x=state.advanced.departmentLife=state.advanced.departmentLife||{version:VERSION,reviews:{},reports:[],escalations:[],workItems:[],managementSubmissions:[],sequence:0};x.version=VERSION;x.reviews=x.reviews||{};x.reports=Array.isArray(x.reports)?x.reports:[];x.escalations=Array.isArray(x.escalations)?x.escalations:[];x.workItems=Array.isArray(x.workItems)?x.workItems:[];x.managementSubmissions=Array.isArray(x.managementSubmissions)?x.managementSubmissions:[];x.sequence=num(x.sequence);if(!Number.isFinite(Number(x.activatedDay)))x.activatedDay=dayOf(state);return x;}
function signal(dept,state){const r=state.realism||{},fin=r.financial?.consolidated||{};switch(dept){
case'air':{const a=r.aviation||{};return {score:clamp((num(a.dispatchReliability,98)*.35)+(num(a.otp,92)*.25)+(num(a.healthMonitoringScore,80)*.2)+(Math.min(100,num(a.maintenanceReserveCoverage,100))*.2)),facts:[`Dispatch ${num(a.dispatchReliability).toFixed(1)}%`,`OTP ${num(a.otp).toFixed(1)}%`,`AOG ${num(a.aog)}`],critical:num(a.dispatchReliability,100)<94||num(a.maintenanceReserveCoverage,100)<60};}
case'sea':{const m=r.maritime||{};const cii=m.cii||m.ciiRating||'C';const cScore={A:100,B:90,C:75,D:55,E:30}[cii]||70;return {score:clamp(cScore*.45+num(m.eexiReadiness,100)*.25+Math.max(0,100-num(m.waitingHours)*.5)*.15+Math.max(0,100-num(m.dryDockDue)*8)*.15),facts:[`CII ${cii}`,`EEXI ${num(m.eexiReadiness).toFixed(0)}/100`,`Dry Dock ${num(m.dryDockDue)}`],critical:!!m.correctiveAction||['D','E'].includes(cii)};}
case'road':{const l=r.logistics||{};return {score:clamp(num(l.onTime,94)*.35+num(l.lpiProxy,4)/5*100*.35+Math.max(0,100-num(l.emptyMiles,18))*.2+Math.max(0,100-num(l.damageRate,.7)*10)*.1),facts:[`On-time ${num(l.onTime).toFixed(1)}%`,`LPI ${num(l.lpiProxy,4).toFixed(2)}/5`,`Empty ${num(l.emptyMiles).toFixed(0)}%`],critical:num(l.lpiProxy,4)<2.5||num(l.onTime,94)<80};}
case'power':{const e=r.energy||{};return {score:clamp(75+Math.min(15,num(e.reserveMargin,0))*.8+Math.max(-20,(num(e.storageHealth,100)-80))*.4-Math.max(0,num(e.curtailment,0)-5)),facts:[`Reserve ${num(e.reserveMargin).toFixed(1)}%`,`Storage ${num(e.storageHealth,100).toFixed(1)}%`,`Available ${num(e.availableMW).toFixed(0)}MW`],critical:num(e.reserveMargin,0)<0||num(e.storageHealth,100)<60};}
case'bank':{const b=r.banking||{};return {score:clamp(75+Math.min(15,num(b.cet1Headroom))*1.2+Math.min(10,num(b.lcrHeadroom))*0.35+Math.min(10,num(b.nsfrHeadroom))*0.35-Math.max(0,num(b.npl,2)-2)*5),facts:[`CET1 ${num(b.cet1).toFixed(1)}%`,`LCR ${num(b.lcr).toFixed(0)}%`,`NSFR ${num(b.nsfr).toFixed(0)}%`,`NPL ${num(b.npl).toFixed(1)}%`],critical:num(b.cet1,99)<7||num(b.lcr,120)<100||num(b.nsfr,112)<100};}
case'treasury':{const cash=num(state.cash),debt=num(state.debt),liq=Math.min(100,cash/Math.max(1,debt*.1+50000000)*100);return {score:clamp(liq),facts:[`سيولة ${Math.round(cash)}`,`دين ${Math.round(debt)}`,`صافي موحد ${Math.round(num(fin.net))}`],critical:cash<0};}
case'audit':{const issues=state.realism?.controls?.issues||[];return {score:clamp(100-issues.length*6),facts:[`ملاحظات ${issues.length}`,`قيود ${state.finance?.journal?.length||0}`,`فواتير ${state.finance?.invoices?.length||0}`],critical:issues.some(x=>x.severity==='critical')};}
case'legal':{const open=(state.advanced?.legal?.cases||[]).filter(x=>!['مغلق','مغلقة','closed'].includes(String(x.status))).length;return {score:clamp(100-open*8),facts:[`قضايا مفتوحة ${open}`,`عقود ${(state.acceptedContracts||[]).length}`],critical:open>5};}
case'insurance':{const covered=(state.insurancePolicies||[]).length,claims=(state.advanced?.insurance?.claims||[]).filter(x=>!['مغلقة','مدفوعة'].includes(x.status)).length;return {score:clamp(60+covered*8-claims*5),facts:[`تغطيات ${covered}`,`مطالبات مفتوحة ${claims}`],critical:covered<2};}
case'cyber':{const c=state.advanced?.cyber||{};return {score:clamp(num(c.score,85)-num(c.incidents,0)*2),facts:[`مؤشر ${num(c.score,85)}%`,`حوادث ${num(c.incidents)}`],critical:num(c.score,85)<60||num(c.incidents)>2};}
case'safety':{const h=state.advanced?.safety||{};const low=(state.assets||[]).filter(a=>num(a.condition,100)<70).length;return {score:clamp(num(h.score,90)-low*2-num(h.incidents,0)*3),facts:[`سلامة ${num(h.score,90)}%`,`حوادث ${num(h.incidents)}`,`أصول حرجة ${low}`],critical:num(h.score,90)<65||low>5};}
case'research':{const vals=Object.values(state.research||{}).map(num);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;return {score:clamp(50+avg*.5),facts:[`نضج ${avg.toFixed(0)}%`,`برامج ${vals.length}`],critical:false};}
case'esg':{const s=state.sustainability||state.advanced?.sustainability||{};const progs=Object.values(s.programs||{}),stalled=progs.filter(p=>num(p.maturity)<25&&num(p.cost)>0).length;return {score:clamp(75-stalled*10+Math.min(20,progs.reduce((n,p)=>n+num(p.maturity),0)/Math.max(1,progs.length)*.2)),facts:[`برامج ${progs.length}`,`متعثر ${stalled}`],critical:stalled>=3};}
case'board':{const b=r.board||{};const open=(b.resolutions||[]).filter(x=>!['مكتمل','closed'].includes(String(x.status))).length;return {score:clamp(90-open*4),facts:[`قرارات مفتوحة ${open}`,`اجتماعات ${(b.meetings||[]).length}`],critical:open>8};}
default:return {score:80,facts:[],critical:false};}}
function exceptionSpecs(dept,state){const r=state.realism||{},out=[];const add=(key,title,severity,evidence,requiresApproval=false,closureCheck=null)=>out.push({key,title,severity,evidence,requiresApproval,closureCheck});
 if(dept==='air'){const a=r.aviation||{};if(num(a.aog)>0)add('aog','معالجة أصول AOG','critical',`${num(a.aog)} أصل/أصول متوقفة`,false,s=>num(s.realism?.aviation?.aog)<=0);if(num(a.dispatchReliability,100)<96)add('dispatch','تحسين Dispatch Reliability','high',`${num(a.dispatchReliability).toFixed(1)}%`,false,s=>num(s.realism?.aviation?.dispatchReliability,100)>=96);if(num(a.maintenanceReserveCoverage,100)<80)add('mx-reserve','تغطية احتياطي الصيانة','high',`${num(a.maintenanceReserveCoverage).toFixed(0)}%`,true,s=>num(s.realism?.aviation?.maintenanceReserveCoverage,100)>=80);if(num(a.otp,100)<88)add('otp','خطة استعادة الالتزام بالمواعيد','medium',`${num(a.otp).toFixed(1)}%`,false,s=>num(s.realism?.aviation?.otp,100)>=88);}
 if(dept==='sea'){const m=r.maritime||{},cii=m.cii||m.ciiRating||'C';if(['D','E'].includes(cii)||m.correctiveAction)add('cii','خطة تصحيح CII/SEEMP','critical',`التصنيف ${cii}`,true,s=>!s.realism?.maritime?.correctiveAction&&!['D','E'].includes(s.realism?.maritime?.cii||s.realism?.maritime?.ciiRating));if(num(m.dryDockDue)>0)add('drydock','جدولة Dry Dock المستحق','high',`${num(m.dryDockDue)} سفينة`,true,s=>num(s.realism?.maritime?.dryDockDue)<=0);if(num(m.waitingHours)>24)add('port-wait','خفض انتظار الموانئ/Demurrage','medium',`${num(m.waitingHours).toFixed(0)} ساعة`,false,s=>num(s.realism?.maritime?.waitingHours)<=24);}
 if(dept==='road'){const l=r.logistics||{};if(num(l.onTime,100)<90)add('otif','استعادة OTIF/التوقيت','high',`${num(l.onTime).toFixed(1)}%`,false,s=>num(s.realism?.logistics?.onTime,100)>=90);if(num(l.emptyMiles)>22)add('empty','خفض الأميال الفارغة','medium',`${num(l.emptyMiles).toFixed(1)}%`,false,s=>num(s.realism?.logistics?.emptyMiles)<=22);if(num(l.lpiProxy,5)<3)add('lpi','خطة جودة الشبكة اللوجستية','high',`${num(l.lpiProxy).toFixed(2)}/5`,true,s=>num(s.realism?.logistics?.lpiProxy,5)>=3);if(num(l.warehouseUtilization)>92)add('warehouse','معالجة تشبع المستودعات','high',`${num(l.warehouseUtilization).toFixed(0)}%`,true,s=>num(s.realism?.logistics?.warehouseUtilization)<=92);}
 if(dept==='power'){const e=r.energy||{};if(num(e.reserveMargin)<10)add('reserve','خطة هامش احتياط القدرة','critical',`${num(e.reserveMargin).toFixed(1)}%`,true,s=>num(s.realism?.energy?.reserveMargin)>=10);if(num(e.storageHealth,100)<75)add('storage','معالجة صحة التخزين','high',`${num(e.storageHealth).toFixed(1)}%`,true,s=>num(s.realism?.energy?.storageHealth,100)>=75);if(num(e.curtailment)>10)add('curtail','خفض Curtailment','medium',`${num(e.curtailment).toFixed(1)}%`,false,s=>num(s.realism?.energy?.curtailment)<=10);}
 if(dept==='bank'){const b=r.banking||{};if(num(b.lcr,120)<110)add('lcr','تعزيز مخزون السيولة','critical',`LCR ${num(b.lcr).toFixed(0)}%`,true,s=>num(s.realism?.banking?.lcr)>=110);if(num(b.nsfr,115)<105)add('nsfr','تقوية التمويل المستقر','high',`NSFR ${num(b.nsfr).toFixed(0)}%`,true,s=>num(s.realism?.banking?.nsfr)>=105);if(num(b.cet1,15)<9)add('cet1','خطة رأس المال CET1','critical',`${num(b.cet1).toFixed(1)}%`,true,s=>num(s.realism?.banking?.cet1)>=9);if(num(b.npl,2)>5)add('npl','خطة جودة المحفظة والمخصصات','high',`NPL ${num(b.npl).toFixed(1)}%`,true,s=>num(s.realism?.banking?.npl)<=5);}
 if(dept==='treasury'){if(num(state.cash)<50000000)add('cash','رفع هامش السيولة التشغيلية','high',`${Math.round(num(state.cash))}`,true,s=>num(s.cash)>=50000000);if(num(state.advanced?.treasury?.fxExposure)>Math.max(10000000,num(state.cash)*.35))add('fx','معالجة تعرض العملات','high',`${Math.round(num(state.advanced?.treasury?.fxExposure))}`,true,s=>num(s.advanced?.treasury?.fxExposure)<=Math.max(10000000,num(s.cash)*.35));}
 if(dept==='audit'){const issues=r.controls?.issues||[];for(const i of issues.filter(x=>['critical','high'].includes(x.severity)).slice(0,3))add(`integrity-${i.id||i.title}`,`ملاحظة رقابية: ${i.title||i.id}`,i.severity||'high',String(i.value||'تحتاج معالجة'),false,s=>!(s.realism?.controls?.issues||[]).some(z=>(z.id||z.title)===(i.id||i.title)));}
 if(dept==='legal'){const open=(state.advanced?.legal?.cases||[]).filter(x=>!['مغلق','مغلقة','closed'].includes(String(x.status)));for(const c of open.slice(0,3))add(`case-${c.id||c.title}`,`متابعة قضية/ملف ${c.title||c.id||'قانوني'}`,'high',String(c.status||'مفتوح'),true,s=>!(s.advanced?.legal?.cases||[]).some(z=>(z.id||z.title)===(c.id||c.title)&&!['مغلق','مغلقة','closed'].includes(String(z.status))));}
 if(dept==='insurance'){const claims=(state.advanced?.insurance?.claims||[]).filter(x=>!['مغلقة','مدفوعة'].includes(String(x.status)));for(const c of claims.slice(0,3))add(`claim-${c.id||c.title}`,`متابعة مطالبة ${c.id||c.title||''}`,'medium',String(c.status||'مفتوحة'),false,s=>!(s.advanced?.insurance?.claims||[]).some(z=>(z.id||z.title)===(c.id||c.title)&&!['مغلقة','مدفوعة'].includes(String(z.status))));if((state.insurancePolicies||[]).length<2)add('coverage','مراجعة فجوة التغطية','high',`${(state.insurancePolicies||[]).length} وثيقة`,true,s=>(s.insurancePolicies||[]).length>=2);}
 if(dept==='cyber'){const c=state.advanced?.cyber||{};if(num(c.incidents)>0)add('incidents','معالجة الحوادث السيبرانية المفتوحة','critical',`${num(c.incidents)} حادث`,false,s=>num(s.advanced?.cyber?.incidents)<=0);if(num(c.coverage,100)<80)add('coverage','رفع تغطية الضوابط الحرجة','high',`${num(c.coverage).toFixed(0)}%`,true,s=>num(s.advanced?.cyber?.coverage,100)>=80);}
 if(dept==='safety'){const h=state.advanced?.safety||{},low=(state.assets||[]).filter(a=>num(a.condition,100)<70).length;if(num(h.incidents)>0)add('incident','تحقيق وإجراء تصحيحي للحوادث','critical',`${num(h.incidents)} حادث`,false,s=>num(s.advanced?.safety?.incidents)<=0);if(low>0)add('condition','معالجة الأصول منخفضة الحالة','high',`${low} أصل`,true,s=>(s.assets||[]).filter(a=>num(a.condition,100)<70).length===0);}
 if(dept==='research'){const vals=Object.entries(state.research||{}).filter(([,v])=>num(v)<25);for(const [k,v] of vals.slice(0,3))add(`rd-${k}`,`Gate review لبرنامج ${k}`,'medium',`نضج ${num(v).toFixed(0)}%`,true,s=>num(s.research?.[k])>=25);}
 if(dept==='esg'){const ps=Object.entries((state.sustainability||state.advanced?.sustainability||{}).programs||{}).filter(([,p])=>num(p.maturity)<25&&num(p.cost)>0);for(const [k,p] of ps.slice(0,3))add(`esg-${k}`,`مراجعة برنامج استدامة متعثر ${k}`,'medium',`نضج ${num(p.maturity).toFixed(0)}%`,true,s=>num((s.sustainability||s.advanced?.sustainability||{}).programs?.[k]?.maturity)>=25);}
 if(dept==='board'){const open=(r.board?.resolutions||[]).filter(x=>!['مكتمل','closed'].includes(String(x.status)));for(const q of open.slice(0,4))add(`resolution-${q.id||q.title}`,`متابعة قرار مجلس ${q.title||q.id||''}`,'high',String(q.status||'مفتوح'),false,s=>!(s.realism?.board?.resolutions||[]).some(z=>(z.id||z.title)===(q.id||q.title)&&!['مكتمل','closed'].includes(String(z.status))));}
 return out;}
function due(dept,state){const d=defs[dept];if(!d)return false;const x=ensure(state),day=dayOf(state),reviewDay=x.reviews[dept]?.day;if(Number.isFinite(Number(reviewDay)))return day-Number(reviewDay)>=d.cadence;const firstEligible=Number(x.activatedDay)+Math.max(1,num(d.cadence,1));return day>=firstEligible;}
function syncWork(dept,state){const x=ensure(state),today=dayOf(state),specs=exceptionSpecs(dept,state),activeKeys=new Set(specs.map(s=>`${dept}|${s.key}`));for(const spec of specs){const signature=`${dept}|${spec.key}`;let w=x.workItems.find(i=>i.signature===signature&&i.status!=='مغلق');if(!w){w={id:`DWI-${String(++x.sequence).padStart(6,'0')}`,signature,dept,title:spec.title,owner:defs[dept].owner,severity:spec.severity,evidence:spec.evidence,requiresApproval:!!spec.requiresApproval,status:'مفتوح',openedDay:today,dueDay:today+(spec.severity==='critical'?1:spec.severity==='high'?3:7),lastSeenDay:today,source:'department-scan'};x.workItems.unshift(w);}else{w.evidence=spec.evidence;w.severity=spec.severity;w.requiresApproval=!!spec.requiresApproval;w.lastSeenDay=today;}}
 for(const w of x.workItems.filter(i=>i.dept===dept&&i.status!=='مغلق')){if(!activeKeys.has(w.signature)){w.status='مغلق';w.closedDay=today;w.closure='زوال شرط الاستثناء والتحقق في دورة القسم.';}}
 x.workItems=x.workItems.slice(0,500);return x.workItems.filter(i=>i.dept===dept&&i.status!=='مغلق');}
function review(dept,state,actor='manual'){const d=defs[dept];if(!d)throw new Error('قسم غير معروف');const x=ensure(state),day=dayOf(state),s=signal(dept,state),open=syncWork(dept,state),grade=s.score>=90?'ممتاز':s.score>=75?'سليم':s.score>=60?'مراقبة':'تصعيد';const findings=s.facts.slice();if(open.length)findings.push(`مهام مفتوحة ${open.length}`);const recommendations=[];if(s.score<90)recommendations.push(`تنفيذ إجراءات تحسين ${d.name} ومراجعة المؤشرات في الدورة القادمة.`);if(s.critical)recommendations.push('رفع استثناء جوهري للإدارة وعدم إغلاقه حتى زوال السبب.');if(open.some(w=>w.requiresApproval))recommendations.push('توجد مهام تتطلب تفويضًا إداريًا قبل التنفيذ.');const id=`DREP-${String(++x.sequence).padStart(6,'0')}`;const report={id,dept,department:d.name,owner:d.owner,day,at:num(state.simSeconds),actor,grade,score:Math.round(s.score),critical:!!s.critical,findings,recommendations,reportType:d.report,status:s.critical||open.some(w=>w.requiresApproval)?'يحتاج متابعة':'مكتمل',openWorkItems:open.map(w=>w.id),nextReviewDay:day+d.cadence};x.reviews[dept]=report;x.reports.unshift(report);x.reports=x.reports.slice(0,250);return report;}
function escalate(dept,state,aiRequests,workItemId=null){const d=defs[dept];if(!d)return null;const x=ensure(state),r=x.reviews[dept]||review(dept,state,'manual'),day=dayOf(state),w=workItemId?x.workItems.find(i=>i.id===workItemId):null,signature=w?`department-work|${w.id}`:`department|${dept}|${day}|${r.grade}`;const existing=x.escalations.find(e=>e.signature===signature&&e.status!=='مغلق');if(existing)return existing;const e={id:`DESC-${String(++x.sequence).padStart(6,'0')}`,signature,dept,day,reportId:r.id,workItemId:w?.id||null,status:'بانتظار التفويض',title:w?`${d.name} · ${w.title}`:`${d.report} · ${r.grade}`,reason:w?`${w.evidence}. المالك: ${w.owner}. يتطلب قرارًا/تفويضًا قبل الإغلاق.`:`${d.name}: نتيجة ${r.score}/100. ${r.findings.join(' · ')} ${r.recommendations.join(' ')}`.trim(),company:['air','sea','road','power','bank'].includes(dept)?dept:'group',kind:'department-report',cost:0,score:w?.severity==='critical'||r.critical?95:Math.max(60,r.score),priority:w?.severity|| (r.critical?'critical':'high')};x.escalations.unshift(e);x.managementSubmissions.unshift({id:e.id,dept,title:e.title,day,status:e.status,workItemId:e.workItemId});x.managementSubmissions=x.managementSubmissions.slice(0,250);if(w){w.status='مرفوع للإدارة';w.escalationId=e.id;}if(Array.isArray(aiRequests)&&!aiRequests.some(q=>q.signature===signature||q.departmentEscalationId===e.id))aiRequests.unshift({...e,departmentEscalationId:e.id});return e;}
function actOnWorkItem(id,state,aiRequests,actor='manual'){const x=ensure(state),w=x.workItems.find(i=>i.id===id);if(!w)throw new Error('مهمة القسم غير موجودة');if(w.status==='مغلق')return {status:'closed',workItem:w};const spec=exceptionSpecs(w.dept,state).find(s=>`${w.dept}|${s.key}`===w.signature);if(!spec){w.status='مغلق';w.closedDay=dayOf(state);w.closure='تم التحقق من زوال سبب المهمة.';return {status:'closed',workItem:w};}if(w.requiresApproval){const e=escalate(w.dept,state,aiRequests,w.id);return {status:'escalated',workItem:w,escalation:e};}w.status='قيد المعالجة';w.lastActionDay=dayOf(state);w.lastActor=actor;w.actionNote='تمت مراجعة الإجراء؛ يبقى مفتوحًا حتى يزول المؤشر المسبب ثم تغلقه دورة القسم تلقائيًا.';return {status:'in-progress',workItem:w};}
function aiScan(state,aiRequests){const out=[];for(const dept of Object.keys(defs)){syncWork(dept,state);if(!due(dept,state))continue;const r=review(dept,state,'ai');const x=ensure(state),criticalWork=x.workItems.filter(w=>w.dept===dept&&w.status!=='مغلق'&&(w.severity==='critical'||(w.requiresApproval&&dayOf(state)>=w.dueDay)));for(const w of criticalWork)out.push(escalate(dept,state,aiRequests,w.id));if((r.critical||r.score<70)&&!criticalWork.length)out.push(escalate(dept,state,aiRequests));}return out.filter(Boolean);}
function snapshot(dept,state){const d=defs[dept];if(!d)return null;const x=ensure(state),open=syncWork(dept,state),today=dayOf(state),r=x.reviews[dept]||null;return {definition:d,aiRole:aiRoles[dept]||'',procedures:procedures[dept]||[],last:r,due:due(dept,state),signal:signal(dept,state),openWorkItems:open.slice(0,8),overdue:open.filter(w=>today>w.dueDay).length,managementSubmissions:x.managementSubmissions.filter(z=>z.dept===dept).slice(0,5),reports:x.reports.filter(z=>z.dept===dept).slice(0,5)};}
const api={VERSION,definitions:defs,aiRoles,procedures,ensure,signal,exceptionSpecs,syncWork,due,review,escalate,actOnWorkItem,aiScan,snapshot};
if(typeof module!=='undefined'&&module.exports)module.exports=api;globalThis.GH_DEPARTMENT_CORE=api;if(typeof window!=='undefined')window.GH_DEPARTMENT_CORE=api;
})();
