(()=>{
  'use strict';
  const VERSION='3.0.0';
  const num=value=>Math.max(0,Number(value)||0),now=state=>Number(state.simSeconds)||0;
  const clone=value=>globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value));
  const KIND={gas:{name:'توليد غازي',factor:.56,variableCost:39},solar:{name:'طاقة شمسية',factor:.25,variableCost:7},wind:{name:'طاقة رياح',factor:.39,variableCost:12},storage:{name:'تخزين شبكي',factor:0,variableCost:3}};
  function inferFacility(facility){const text=String(facility.capacity||''),amount=num(facility.capacityAmount||text.match(/[\d,.]+/)?.[0]?.replace(/,/g,'')),kind=facility.energyKind||(/شمس/.test(`${facility.name} ${text}`)?'solar':/رياح/.test(`${facility.name} ${text}`)?'wind':/تخزين|MWh/.test(`${facility.name} ${text}`)?'storage':/غاز/.test(`${facility.name} ${text}`)?'gas':'solar');return {kind,amount};}
  function syncSites(state,energy){for(const facility of (state.customHubs||[]).filter(row=>row?.owned===true&&row.company==='power'&&row.kind==='power')){const inferred=inferFacility(facility),existing=energy.sites.find(row=>row.facilityId===facility.id);if(existing){Object.assign(existing,{name:facility.name,city:facility.city,country:facility.country,kind:inferred.kind,capacity:inferred.amount,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء'});continue;}energy.sites.push({id:`SITE-${facility.id}`,facilityId:facility.id,constructionContractId:facility.constructionContractId||null,name:facility.name,city:facility.city||'غير محدد',country:facility.country||'غير محدد',kind:inferred.kind,capacity:inferred.amount,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء',openedAt:Number(facility.openedAt)||now(state)});}return energy.sites;}
  function ensure(state){const energy=state.energy=state.energy&&typeof state.energy==='object'?state.energy:{};for(const key of ['gasMW','solarMW','windMW','storageMWh','availability'])energy[key]=num(energy[key]);if(!energy.availability&&(energy.gasMW+energy.solarMW+energy.windMW)>0)energy.availability=90;for(const key of ['sites','ppaOffers','ppaContracts','dailyHistory'])energy[key]=Array.isArray(energy[key])?energy[key].filter(Boolean):[];energy.sequence=Math.max(0,Math.floor(Number(energy.sequence)||0));syncSites(state,energy);for(const site of energy.sites.filter(row=>row.commissioned&&row.kind!=='storage')){const hasOpen=energy.ppaOffers.some(row=>row.siteId===site.id&&row.status==='متاح'),hasActive=energy.ppaContracts.some(row=>row.siteId===site.id&&row.status==='ساري');if(!hasOpen&&!hasActive){const spot=num(state.advanced?.economy?.electricityPriceMWh||90),capacity=Math.max(1,site.capacity);[['مرافق المدينة',.32,.94,1825],['مجمع صناعي دولي',.24,1.02,2555],['مركز بيانات عالمي',.18,1.09,3650]].forEach(([buyer,share,multiplier,termDays],index)=>energy.ppaOffers.push({id:`PPA-OFFER-${++energy.sequence}`,siteId:site.id,buyer:`${buyer} · ${site.city}`,capacityMW:Math.max(1,Math.round(capacity*share)),tariff:Number((spot*multiplier).toFixed(2)),termDays,startDay:Math.floor(now(state)/86400),status:'متاح',rank:index+1}));}}energy.ppaOffers=energy.ppaOffers.slice(-240);return energy;}
  function acceptedCapacity(energy,siteId){return energy.ppaContracts.filter(row=>row.siteId===siteId&&row.status==='ساري').reduce((sum,row)=>sum+num(row.capacityMW),0);}
  function acceptPpa(state,p){const energy=ensure(state),offer=energy.ppaOffers.find(row=>row.id===p.id&&row.status==='متاح');if(!offer)throw new Error('energy-ppa-offer-unavailable');const site=energy.sites.find(row=>row.id===offer.siteId&&row.commissioned);if(!site)throw new Error('energy-site-not-commissioned');const capacity=Math.min(num(offer.capacityMW),Math.max(0,num(site.capacity)-acceptedCapacity(energy,site.id)));if(capacity<=0)throw new Error('energy-capacity-fully-contracted');offer.status='مقبول';offer.acceptedAt=now(state);const contract={id:`PPA-${++energy.sequence}`,offerId:offer.id,siteId:site.id,siteName:site.name,buyer:offer.buyer,kind:site.kind,capacityMW:capacity,tariff:num(offer.tariff),termDays:Number(offer.termDays)||1825,startDay:Math.floor(now(state)/86400),endDay:Math.floor(now(state)/86400)+(Number(offer.termDays)||1825),status:'ساري'};energy.ppaContracts.unshift(contract);return clone(contract);}
  function economics(state,market=state.advanced?.economy||{}){const energy=ensure(state),availability=Math.max(0,Math.min(1,num(energy.availability||100)/100)),spot=num(market.electricityPriceMWh||90),gasMWh=num(energy.gasMW)*24*KIND.gas.factor*availability,solarMWh=num(energy.solarMW)*24*KIND.solar.factor*availability,windMWh=num(energy.windMW)*24*KIND.wind.factor*availability,generationByKind={gas:gasMWh,solar:solarMWh,wind:windMWh},capacityByKind={gas:num(energy.gasMW),solar:num(energy.solarMW),wind:num(energy.windMW)};let ppaRevenue=0,ppaMWh=0;for(const contract of energy.ppaContracts.filter(row=>row.status==='ساري')){const kind=contract.kind||'solar',capacity=Math.min(num(contract.capacityMW),capacityByKind[kind]||0),mwh=capacity*24*(KIND[kind]?.factor||0)*availability;ppaMWh+=mwh;ppaRevenue+=mwh*num(contract.tariff);}const generation=gasMWh+solarMWh+windMWh,spotMWh=Math.max(0,generation-ppaMWh),spotRevenue=spotMWh*spot,storageRevenue=num(energy.storageMWh)*.16*Math.max(8,spot-num(market.gasCostMWh||39))*.22,powerRevenue=ppaRevenue+spotRevenue+storageRevenue,gasFuel=gasMWh*num(market.gasCostMWh||39),carbon=gasMWh*.36*num(market.carbonPriceTon||0),operations=(num(energy.gasMW)*18+num(energy.solarMW)*7+num(energy.windMW)*12)*availability,gridFees=generation*1.7,storageCost=num(energy.storageMWh)*.35,powerExpense=gasFuel+carbon+operations+gridFees+storageCost;return {generation,generationByKind,ppaMWh,spotMWh,ppaRevenue,spotRevenue,storageRevenue,powerRevenue,powerExpense,gasFuel,carbon,operations,gridFees,net:powerRevenue-powerExpense};}
  function tickDay(state,p){const energy=ensure(state),day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(state)/86400)));if(energy.lastProcessedDay===day)return energy.dailyHistory.find(row=>row.day===day)||{day,idempotent:true};for(const contract of energy.ppaContracts)if(contract.status==='ساري'&&day>=Number(contract.endDay)){contract.status='منتهي';contract.endedDay=day;}const report={day,...economics(state)};energy.dailyHistory.unshift(report);energy.dailyHistory=energy.dailyHistory.slice(0,400);energy.lastProcessedDay=day;return clone(report);}
  function siteEconomics(state){
    const energy=ensure(state),market=state.advanced?.economy||{},availability=Math.max(0,Math.min(1,num(energy.availability||100)/100)),spot=num(market.electricityPriceMWh||90),storageTotal=Math.max(1,energy.sites.filter(row=>row.commissioned&&row.kind==='storage').reduce((sum,row)=>sum+num(row.capacity),0)),storageTotals=economics(state,market);
    return energy.sites.map(site=>{
      const contractedMW=acceptedCapacity(energy,site.id);if(!site.commissioned)return {...clone(site),contractedMW,generationMWh:0,ppaRevenue:0,spotRevenue:0,dailyRevenue:0,dailyExpense:0,dailyNet:0};
      if(site.kind==='storage'){const share=num(site.capacity)/storageTotal,dailyRevenue=storageTotals.storageRevenue*share,dailyExpense=num(energy.storageMWh)*.35*share;return {...clone(site),contractedMW:0,generationMWh:0,ppaRevenue:0,spotRevenue:0,dailyRevenue,dailyExpense,dailyNet:dailyRevenue-dailyExpense};}
      const profile=KIND[site.kind]||KIND.solar,generationMWh=num(site.capacity)*24*profile.factor*availability,contracts=energy.ppaContracts.filter(row=>row.siteId===site.id&&row.status==='ساري');let ppaMWh=0,ppaRevenue=0;
      for(const contract of contracts){const mwh=Math.min(num(contract.capacityMW),num(site.capacity))*24*profile.factor*availability;ppaMWh+=mwh;ppaRevenue+=mwh*num(contract.tariff);}
      const spotMWh=Math.max(0,generationMWh-ppaMWh),spotRevenue=spotMWh*spot,gasFuel=site.kind==='gas'?generationMWh*num(market.gasCostMWh||39):0,carbon=site.kind==='gas'?generationMWh*.36*num(market.carbonPriceTon||0):0,operations=num(site.capacity)*(site.kind==='gas'?18:profile.variableCost)*availability,gridFees=generationMWh*1.7,dailyRevenue=ppaRevenue+spotRevenue,dailyExpense=gasFuel+carbon+operations+gridFees;
      return {...clone(site),contractedMW,generationMWh,ppaMWh,spotMWh,ppaRevenue,spotRevenue,dailyRevenue,dailyExpense,dailyNet:dailyRevenue-dailyExpense};
    });
  }
  function execute(ctx,cmd,p={}){const state=ctx.state||ctx;if(cmd==='ensure')return ensure(state);if(cmd==='accept-ppa')return acceptPpa(state,p);if(cmd==='tick-day')return tickDay(state,p);throw new Error(`Unknown energy command: ${cmd}`);}
  const API={VERSION,KIND,ensure,economics,siteEconomics,acceptPpa,tickDay,execute};globalThis.GH_ENERGY_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('energy',API);if(globalThis.window&&window!==globalThis)window.GH_ENERGY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
