(()=>{
  'use strict';
  const VERSION='3.0.0';
  const num=value=>Math.max(0,Number(value)||0),now=state=>Number(state.simSeconds)||0;
  const clone=value=>globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value));
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const KIND=Object.freeze({
    gas:{name:'توليد غازي',factor:.56,variableCost:18,forcedOutage:.04,degradation:.004,lifeYears:30,financeYears:10,maintenance:{days:12,costPerMW:15000,availabilityDuring:0,recovery:.7,contractor:'مقاول صيانة التوربينات الغازية'}},
    solar:{name:'طاقة شمسية',factor:.25,variableCost:7,forcedOutage:.012,degradation:.006,lifeYears:28,financeYears:15,maintenance:{days:2,costPerMW:3000,availabilityDuring:.5,recovery:.5,contractor:'مقاول تشغيل وصيانة الألواح الشمسية'}},
    wind:{name:'طاقة رياح',factor:.39,variableCost:12,forcedOutage:.022,degradation:.005,lifeYears:25,financeYears:15,maintenance:{days:5,costPerMW:9000,availabilityDuring:.6,recovery:.6,contractor:'مقاول صيانة توربينات الرياح'}},
    storage:{name:'تخزين شبكي',factor:0,variableCost:3,forcedOutage:.018,degradation:.018,lifeYears:18,financeYears:8,maintenance:{days:3,costPerMW:4000,availabilityDuring:.5,recovery:.5,contractor:'مقاول صيانة أنظمة التخزين'}}
  });
  // Contracts are priced from the market (GH_REALISM forwards, GH_FINANCE_CORE debt rates), never typed in.
  const FUEL_TERMS=Object.freeze([365,730,1095]),FUEL_MARGIN=.02,TAKE_OR_PAY=.75,PROJECT_PREMIUM=.015,PROJECT_LEVERAGE=.75;
  function hash(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
  function deterministic(seed,min,max){return min+(hash(seed)/4294967295)*(max-min);}
  function inferFacility(facility){const text=String(facility.capacity||''),amount=num(facility.capacityAmount||text.match(/[\d,.]+/)?.[0]?.replace(/,/g,'')),kind=facility.energyKind||(/شمس/.test(`${facility.name} ${text}`)?'solar':/رياح/.test(`${facility.name} ${text}`)?'wind':/تخزين|MWh/.test(`${facility.name} ${text}`)?'storage':/غاز/.test(`${facility.name} ${text}`)?'gas':'solar');return {kind,amount};}
  function siteDefaults(state,facility,inferred){
    const profile=KIND[inferred.kind]||KIND.solar,capacity=num(inferred.amount);return {id:`SITE-${facility.id}`,facilityId:facility.id,constructionContractId:facility.constructionContractId||null,name:facility.name,city:facility.city||'غير محدد',country:facility.country||'غير محدد',kind:inferred.kind,capacity,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء',openedAt:Number(facility.openedAt)||now(state),commissionedDay:facility.commissioned===true?Math.floor(now(state)/86400):null,availability:100,forcedOutageRate:profile.forcedOutage,degradationRate:profile.degradation,gridExportLimitMW:capacity,gridLossRate:.02,gridOperator:'مشغل الشبكة المحلي',dispatchMode:inferred.kind==='gas'?'follow-market':inferred.kind==='storage'?'arbitrage':'must-run',reserveMargin:inferred.kind==='gas'?10:0,maintenanceReservePerMW:inferred.kind==='gas'?18:profile.variableCost,capex:num(facility.cost),debtOutstanding:0,debtRate:0,debtTermDays:0,debtStartDay:null};
  }
  function syncSites(state,energy){
    for(const facility of (state.customHubs||[]).filter(row=>row?.owned===true&&String(row.ownerCompanyId||row.companyId||row.company||'')==='power'&&row.kind==='power')){
      const inferred=inferFacility(facility),existing=energy.sites.find(row=>row.facilityId===facility.id);
      if(existing){const wasCommissioned=existing.commissioned===true;Object.assign(existing,{name:facility.name,city:facility.city||existing.city,country:facility.country||existing.country,kind:inferred.kind,capacity:inferred.amount,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء'});if(!wasCommissioned&&existing.commissioned)existing.commissionedDay=Math.floor(now(state)/86400);const defaults=siteDefaults(state,facility,inferred);for(const [key,value] of Object.entries(defaults))if(existing[key]===undefined||existing[key]===null)existing[key]=value;continue;}
      energy.sites.push(siteDefaults(state,facility,inferred));
    }
    return energy.sites;
  }
  function ensure(state){
    const energy=state.energy=state.energy&&typeof state.energy==='object'?state.energy:{};
    for(const key of ['gasMW','solarMW','windMW','storageMWh','availability'])energy[key]=num(energy[key]);if(!energy.availability&&(energy.gasMW+energy.solarMW+energy.windMW)>0)energy.availability=90;
    for(const key of ['sites','ppaOffers','ppaContracts','dailyHistory','outages','maintenancePlans','fuelContracts','gridAgreements','projectFinance','dispatchInstructions','renewableCertificates'])energy[key]=Array.isArray(energy[key])?energy[key].filter(Boolean):[];delete energy.regionalOffices;delete energy.gridAgreements;
    energy.sequence=Math.max(0,Math.floor(Number(energy.sequence)||0));syncSites(state,energy);for(const site of energy.sites){site.gridExportLimitMW=num(site.capacity);site.gridLossRate=.02;}
    for(const facility of energy.projectFinance){
      const site=energy.sites.find(row=>row.id===facility.siteId),startDay=Math.max(0,Math.floor(Number(facility.startDay)||0)),termDays=Math.max(365,Math.floor(Number(facility.termDays)||3650));
      facility.amount=num(facility.amount);facility.originalAmount=num(facility.originalAmount||facility.amount);facility.outstanding=num(facility.outstanding);facility.principalArrears=num(facility.principalArrears);facility.capitalizedInterest=num(facility.capitalizedInterest);facility.startDay=startDay;facility.termDays=termDays;facility.lastInterestDay=Math.max(startDay,Math.floor(Number(facility.lastInterestDay)||startDay));
      if(facility.repaymentStartDay===undefined){facility.repaymentStartDay=site?.commissioned?Math.max(startDay,Math.floor(Number(site.commissionedDay)||startDay)):null;}
      if(facility.repaymentStartDay!==null&&Number.isFinite(Number(facility.repaymentStartDay))){facility.repaymentStartDay=Math.max(startDay,Math.floor(Number(facility.repaymentStartDay)));facility.amortizationAmount=num(facility.amortizationAmount)||facility.originalAmount/termDays;facility.maturityDay=facility.repaymentStartDay+termDays;}else{facility.repaymentStartDay=null;facility.amortizationAmount=num(facility.amortizationAmount);}
    }
    // Build 360: migrate old saves from mutable financing documents to Finance Core's operational balance register.
    // Project Finance is authoritative per facility; Finance preserves the company's unchanged total debt while it
    // realigns any historical oldest-debt allocations made before Energy supplied the exact debt id.
    if(Number(energy.debtBalanceMigrationVersion)<1){const F=globalThis.GH_FINANCE_CORE;if(!energy.projectFinance.length)energy.debtBalanceMigrationVersion=1;else if(F?.reconcileDebtBalances){F.reconcileDebtBalances(state,{company:'power',balancesById:Object.fromEntries(energy.projectFinance.map(row=>[row.id,num(row.outstanding)]))});energy.debtBalanceMigrationVersion=1;}}
    // Build 358: buyers no longer leave three standing offers per plant; they open tenders the player bids on (below).
    // Offers already in a save stay acceptable.
    for(const key of ['tenders','tenderHistory'])energy[key]=Array.isArray(energy[key])?energy[key].filter(Boolean):[];
    energy.ppaOffers=energy.ppaOffers.slice(-240);return energy;
  }
  // Tenders (owner review, Build 358: the energy company ran itself). A buyer asks for capacity from one of the
  // player's operating plants for a term at its reference price; the player bids low, at the reference or high. A lower
  // price wins more often and earns less per MWh; a win signs a PPA at the bid price for the plant's uncontracted
  // capacity. Load: at most 3 open tenders, at most one new a day, 10 days to bid, 40 results kept.
  const MAX_OPEN_TENDERS=3,TENDER_DAYS=10,TENDER_HISTORY=40;
  const TENDER_BUYERS=Object.freeze([['مرافق المدينة',.30,.95,1825],['مجمع صناعي',.25,1.00,2555],['مركز بيانات',.18,1.08,3650],['محطة تحلية مياه',.22,.98,2920],['مشغل الشبكة الوطنية',.35,.93,1095]]);
  const BID_LEVELS=Object.freeze({low:{price:.92,chance:.85,label:'سعر منافس'},market:{price:1,chance:.55,label:'سعر المرجع'},high:{price:1.08,chance:.25,label:'سعر مرتفع'}});
  function openCapacity(energy,site){return Math.max(0,num(site.capacity)-acceptedCapacity(energy,site.id)-energy.tenders.filter(row=>row.siteId===site.id).reduce((sum,row)=>sum+num(row.capacityMW),0));}
  function generateTender(state,energy,day){
    if(energy.tenders.length>=MAX_OPEN_TENDERS||deterministic(`${day}:tender`,0,1)>=.35)return null;
    const sites=energy.sites.filter(row=>row.commissioned&&row.kind!=='storage'&&openCapacity(energy,row)>=10);if(!sites.length)return null;
    const site=sites[Math.floor(deterministic(`${day}:tender:site`,0,sites.length))%sites.length],[buyer,share,multiplier,termDays]=TENDER_BUYERS[Math.floor(deterministic(`${day}:tender:buyer`,0,TENDER_BUYERS.length))%TENDER_BUYERS.length],spot=num(state.advanced?.economy?.electricityPriceMWh||90);
    const tender={id:`TENDER-${++energy.sequence}`,siteId:site.id,siteName:site.name,buyer:`${buyer} · ${site.city}`,capacityMW:Math.max(10,Math.min(openCapacity(energy,site),Math.round(num(site.capacity)*share))),referencePrice:Math.round(spot*multiplier*100)/100,termDays,competitors:2+Math.floor(deterministic(`${day}:tender:rivals`,0,3)),day,expiresDay:day+TENDER_DAYS,status:'مفتوحة'};
    energy.tenders.push(tender);return tender;
  }
  function tenderQuote(state,tender){
    const site=(ensure(state).sites||[]).find(row=>row.id===tender.siteId),factor=(KIND[site?.kind]||KIND.solar).factor,annualMWh=num(tender.capacityMW)*24*365*factor,rivals=Math.max(0,Number(tender.competitors||2)-2);
    return Object.fromEntries(Object.entries(BID_LEVELS).map(([level,row])=>{const price=Math.round(num(tender.referencePrice)*row.price*100)/100;return [level,{level,label:row.label,price,chance:Math.max(.05,row.chance-.06*rivals),annualRevenue:annualMWh*price}];}));
  }
  function closeTender(energy,tender,status,extra={}){energy.tenders=energy.tenders.filter(row=>row.id!==tender.id);energy.tenderHistory.unshift({...tender,...extra,status});energy.tenderHistory=energy.tenderHistory.slice(0,TENDER_HISTORY);}
  function registerEnergyContract(state,contract,contractType,counterparty,terms={}){const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');const document=F.execute({state},'register-commercial-contract',{id:`LEGAL-${contract.id}`,company:'power',contractType,counterparty,title:`${contractType} · ${contract.siteName||contract.siteId}`,startDay:contract.startDay,endDay:contract.endDay,amount:num(contract.amount||contract.capacityMW*contract.tariff||contract.volumeMWh*contract.priceMWh),terms,sourceRefs:[contract.id,contract.offerId,contract.siteId].filter(Boolean)});contract.legalDocumentId=document.id;contract.documentProofId=document.documentProofId;contract.contentDigest=document.contentDigest;return contract;}
  function bidTender(state,p){
    const energy=ensure(state),tender=energy.tenders.find(row=>row.id===String(p.id||''));if(!tender)throw new Error('energy-tender-not-found');
    const day=Math.floor(now(state)/86400);if(day>=Number(tender.expiresDay)){closeTender(energy,tender,'منتهية',{closedDay:day});throw new Error('energy-tender-expired');}
    const level=BID_LEVELS[p.level]?p.level:null;if(!level)throw new Error('energy-tender-bid-invalid');
    const quote=tenderQuote(state,tender)[level],won=deterministic(`${tender.id}:award`,0,1)<quote.chance;
    if(!won){const winner=Math.round(num(tender.referencePrice)*deterministic(`${tender.id}:winner`,.86,quote.price/num(tender.referencePrice))*100)/100;closeTender(energy,tender,'خسرناها',{closedDay:day,bidPrice:quote.price,winningPrice:winner});return {id:tender.id,won:false,bidPrice:quote.price,winningPrice:winner};}
    const site=energy.sites.find(row=>row.id===tender.siteId&&row.commissioned);if(!site)throw new Error('energy-site-not-commissioned');
    const capacity=Math.min(num(tender.capacityMW),Math.max(0,num(site.capacity)-acceptedCapacity(energy,site.id)));if(capacity<=0)throw new Error('energy-capacity-fully-contracted');
    const startDay=day,contract={id:`PPA-${++energy.sequence}`,offerId:tender.id,siteId:site.id,siteName:site.name,buyer:tender.buyer,kind:site.kind,capacityMW:capacity,tariff:quote.price,termDays:tender.termDays,startDay,endDay:startDay+tender.termDays,status:'ساري',source:'مناقصة'};registerEnergyContract(state,contract,'اتفاقية شراء طاقة',contract.buyer,{siteId:site.id,capacityMW:capacity,tariff:quote.price,termDays:tender.termDays,awardSource:'مناقصة'});
    energy.ppaContracts.unshift(contract);closeTender(energy,tender,'فزنا بها',{closedDay:day,bidPrice:quote.price,contractId:contract.id});return {id:tender.id,won:true,bidPrice:quote.price,contract:clone(contract)};
  }
  function acceptedCapacity(energy,siteId){return energy.ppaContracts.filter(row=>row.siteId===siteId&&row.status==='ساري').reduce((sum,row)=>sum+num(row.capacityMW),0);}
  function acceptPpa(state,p){
    const energy=ensure(state),offer=energy.ppaOffers.find(row=>row.id===p.id&&row.status==='متاح');if(!offer)throw new Error('energy-ppa-offer-unavailable');const site=energy.sites.find(row=>row.id===offer.siteId&&row.commissioned);if(!site)throw new Error('energy-site-not-commissioned');
    const capacity=Math.min(num(offer.capacityMW),Math.max(0,num(site.capacity)-acceptedCapacity(energy,site.id)));if(capacity<=0)throw new Error('energy-capacity-fully-contracted');offer.status='مقبول';offer.acceptedAt=now(state);const startDay=Math.floor(now(state)/86400),contract={id:`PPA-${++energy.sequence}`,offerId:offer.id,siteId:site.id,siteName:site.name,buyer:offer.buyer,kind:site.kind,capacityMW:capacity,tariff:num(offer.tariff),termDays:Number(offer.termDays)||1825,startDay,endDay:startDay+(Number(offer.termDays)||1825),status:'ساري'};registerEnergyContract(state,contract,'اتفاقية شراء طاقة',contract.buyer,{siteId:site.id,capacityMW:capacity,tariff:contract.tariff,termDays:contract.termDays,awardSource:'عرض مباشر'});energy.ppaContracts.unshift(contract);return clone(contract);
  }
  function siteById(state,id){return ensure(state).sites.find(row=>row.id===id||row.facilityId===id);}
  function setDispatchPolicy(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const allowed=site.kind==='storage'?['arbitrage','reserve','idle']:['must-run','follow-market','reserve'];if(!allowed.includes(p.mode))throw new Error('energy-dispatch-mode-invalid');site.dispatchMode=p.mode;site.reserveMargin=clamp(p.reserveMargin??site.reserveMargin,0,45);const instruction={id:`DSP-${++energy.sequence}`,siteId:site.id,mode:site.dispatchMode,reserveMargin:site.reserveMargin,at:now(state)};energy.dispatchInstructions.unshift(instruction);energy.dispatchInstructions=energy.dispatchInstructions.slice(0,300);return clone(site);}
  // A fixed-price gas contract for a term: the expected average gas price over it plus the supplier's margin, for the
  // fuel the plant burns at its capacity factor, 75% take-or-pay.
  function fuelOffer(state,site,termDays){if(!FUEL_TERMS.includes(termDays))throw new Error('energy-fuel-term-invalid');const forward=globalThis.GH_REALISM.gasForward(state,termDays),priceMWh=Math.round(forward*(1+FUEL_MARGIN+.005*termDays/365)*100)/100,volumeMWh=Math.max(1000,Math.round(num(site.capacity)*24*termDays*KIND.gas.factor/1000)*1000);return {siteId:site.id,termDays,priceMWh,volumeMWh,takeOrPay:TAKE_OR_PAY,supplier:`مورد الغاز الإقليمي · ${site.country}`};}
  function signFuelContract(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site||site.kind!=='gas')throw new Error('energy-gas-site-required');const offer=fuelOffer(state,site,Math.floor(Number(p.termDays)||0));for(const row of energy.fuelContracts.filter(row=>row.siteId===site.id&&row.status==='ساري'))row.status='مستبدل';const startDay=Math.floor(now(state)/86400),contract={id:`FUEL-${++energy.sequence}`,siteId:site.id,siteName:site.name,supplier:offer.supplier,priceMWh:offer.priceMWh,volumeMWh:offer.volumeMWh,remainingMWh:offer.volumeMWh,usedMWh:0,termDays:offer.termDays,startDay,endDay:startDay+offer.termDays,takeOrPay:offer.takeOrPay,status:'ساري'};registerEnergyContract(state,contract,'عقد توريد وقود',contract.supplier,{siteId:site.id,priceMWh:contract.priceMWh,volumeMWh:contract.volumeMWh,takeOrPay:contract.takeOrPay,termDays:contract.termDays});energy.fuelContracts.unshift(contract);site.fuelContractId=contract.id;return clone(contract);}
  // A plant type's overhaul: its length, cost per MW and how much of the wear since the last one it recovers.
  function maintenanceQuote(site){const m=(KIND[site.kind]||KIND.solar).maintenance;return {...m,cost:Math.round(num(site.capacity)*m.costPerMW)};}
  function scheduleMaintenance(state,p){
    const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const plan0=maintenanceQuote(site),startDay=Math.max(Math.floor(now(state)/86400),Math.floor(Number(p.startDay)||0)),durationDays=plan0.days,cost=plan0.cost,supplier=plan0.contractor;if(energy.maintenancePlans.some(row=>row.siteId===site.id&&row.status==='مجدولة'&&startDay<row.endDay&&startDay+durationDays>row.startDay))throw new Error('energy-maintenance-overlap');
    let chequeId=null,invoiceNumber=null;if(cost>0){const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');const payment=F.execute({state},'pay-by-cheque',{company:'power',amount:cost,note:`صيانة مجدولة · ${site.name}`,beneficiary:supplier,line:'maintenance',requestRef:`ENERGY-MAINT-${site.id}-${startDay}`});if(!payment?.cheque?.id||payment.cheque.status!=='مصروف')throw new Error('energy-maintenance-cheque-not-cleared');chequeId=payment.cheque.id;invoiceNumber=payment.invoice.number;}
    const plan={id:`MAINT-${++energy.sequence}`,siteId:site.id,siteName:site.name,startDay,endDay:startDay+durationDays,durationDays,cost,supplier,availabilityDuring:plan0.availabilityDuring,recovery:plan0.recovery,status:'مجدولة',chequeId,invoiceNumber};energy.maintenancePlans.unshift(plan);return clone(plan);
  }
  function projectFinanceRate(state){const F=globalThis.GH_FINANCE_CORE;if(!F?.floatingDebtRate)throw new Error('finance-core-missing');return Math.round((F.floatingDebtRate(state)+PROJECT_PREMIUM)*1e5)/1e5;}
  function projectFinanceRoom(energy,site){return Math.max(0,num(site.capex)*PROJECT_LEVERAGE-energy.projectFinance.filter(row=>row.siteId===site.id&&row.status!=='مسدد').reduce((sum,row)=>sum+num(row.outstanding),0));}
  function financeProject(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const amount=num(p.amount),rate=projectFinanceRate(state),termDays=(KIND[site.kind]||KIND.solar).financeYears*365;if(amount<=0)throw new Error('energy-project-finance-invalid');if(amount>projectFinanceRoom(energy,site)+.01)throw new Error('energy-project-finance-above-leverage');const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');const startDay=Math.floor(now(state)/86400),financing=F.execute({state},'raise-debt',{company:'power',amount,liabilityAccount:'تمويل مشاريع طاقة',lender:'اتحاد بنوك تمويل المشاريع',note:`تمويل مشروع · ${site.name}`,ref:`PF-${site.id}-${++energy.sequence}`});site.debtOutstanding+=amount;site.debtRate=rate;site.debtTermDays=termDays;site.debtStartDay=startDay;const repaymentStartDay=site.commissioned?Math.max(startDay,Math.floor(Number(site.commissionedDay)||startDay)):null,row={id:financing.ref,siteId:site.id,lender:'اتحاد بنوك تمويل المشاريع',amount,originalAmount:amount,outstanding:amount,principalArrears:0,capitalizedInterest:0,rate,termDays,startDay,lastInterestDay:startDay,repaymentStartDay,amortizationAmount:repaymentStartDay===null?0:amount/termDays,maturityDay:repaymentStartDay===null?null:repaymentStartDay+termDays,status:'ساري'};energy.projectFinance.unshift(row);return clone(row);}
  function operatingRows(state,energy){
    const commissioned=energy.sites.filter(row=>row.commissioned);if(commissioned.length)return commissioned;
    const legacy=[];for(const [kind,key] of [['gas','gasMW'],['solar','solarMW'],['wind','windMW'],['storage','storageMWh']])if(num(energy[key])>0)legacy.push({id:`LEGACY-${kind}`,facilityId:null,name:`قدرة محفوظة · ${KIND[kind].name}`,city:'سجل قديم',country:'سجل قديم',kind,capacity:num(energy[key]),commissioned:true,status:'تشغيل تجاري',commissionedDay:0,availability:100,forcedOutageRate:KIND[kind].forcedOutage,degradationRate:KIND[kind].degradation,gridExportLimitMW:num(energy[key]),gridLossRate:.02,dispatchMode:kind==='gas'?'follow-market':kind==='storage'?'arbitrage':'must-run',reserveMargin:kind==='gas'?10:0,maintenanceReservePerMW:KIND[kind].variableCost,capex:0,debtOutstanding:0,debtRate:0,debtTermDays:0});return legacy;
  }
  // The forced outage rate is the share of time a plant is down (EFOR); outages last 1-4 days (2.5 on average), and the
  // rate grows with the time since the last overhaul (or commissioning), up to three times the base.
  const OUTAGE_MEAN_DAYS=2.5;
  function outageAging(site,day){const since=Math.max(0,day-Number(site.lastMaintenanceDay??site.commissionedDay??day));return Math.min(3,1+since/365);}
  function availabilityFor(state,energy,site,day){
    const fleetAvailability=clamp(energy.availability||100,0,100)/100,siteAvailability=clamp(site.availability??100,0,100)/100,ageDays=Math.max(0,day-Number(site.commissionedDay??day)-num(site.recoveredWearDays)),degradation=Math.max(.65,1-num(site.degradationRate)*(ageDays/365)),maintenance=energy.maintenancePlans.find(row=>row.siteId===site.id&&['مجدولة','قيد التنفيذ'].includes(row.status)&&day>=row.startDay&&day<row.endDay),outage=energy.outages.find(row=>row.siteId===site.id&&row.status==='نشط'&&day>=row.startDay&&day<row.endDay),realismHealth=clamp(state.realism?.energy?.storageHealth||100,0,100)/100;let availability=fleetAvailability*siteAvailability*degradation;if(maintenance)availability*=clamp(maintenance.availabilityDuring,0,1);if(outage)availability*=clamp(outage.availabilityDuring??0,0,1);if(site.kind==='storage')availability*=realismHealth;return {availability:clamp(availability,0,1),maintenance,outage,degradation};
  }
  function debtSchedule(energy,site,day=0){
    const rows=energy.projectFinance.filter(row=>row.siteId===site.id&&['ساري','متأخر'].includes(row.status)&&num(row.outstanding)>0);let principal=0,interest=0,outstanding=0;
    for(const row of rows){const balance=num(row.outstanding);outstanding+=balance;const repaymentStart=Number(row.repaymentStartDay);if(!site.commissioned||!Number.isFinite(repaymentStart)||day<=repaymentStart)continue;const regular=num(row.amortizationAmount)||num(row.originalAmount||row.amount)/Math.max(1,Number(row.termDays)||1);principal+=Math.min(balance,regular+num(row.principalArrears));interest+=balance*num(row.rate)/365;}
    return {rows,principal,interest,outstanding,service:principal+interest};
  }
  function facilityCostSnapshot(state){
    const core=globalThis.GH_FACILITY_CORE;
    if(core?.dailyOperatingCosts)return core.dailyOperatingCosts(state);
    if([...(state.globalBases||[]),...(state.customHubs||[])].some(row=>row?.owned===true&&String(row.ownerCompanyId||row.companyId||row.company||'')==='power'))throw new Error('facility-daily-cost-owner-missing');
    return {total:0,byCompany:Object.create(null),byFacility:Object.create(null)};
  }
  function siteEconomics(state){
    const energy=ensure(state),costSnapshot=facilityCostSnapshot(state),market=state.advanced?.economy||{},spot=num(market.electricityPriceMWh||90),day=Math.floor(now(state)/86400),curtailment=clamp(state.realism?.energy?.curtailment||0,0,100)/100,storageSites=operatingRows(state,energy).filter(row=>row.kind==='storage'),storageTotal=Math.max(1,storageSites.reduce((sum,row)=>sum+num(row.capacity),0));
    return energy.sites.map(site=>{
      const contractedMW=acceptedCapacity(energy,site.id),debt=debtSchedule(energy,site,day),cost=costSnapshot.byFacility[site.facilityId],facilityOpex=cost?.ownerCompanyId==='power'?num(cost.amount):0;if(!site.commissioned)return {...clone(site),debtOutstanding:debt.outstanding,constructionInterestCapitalized:debt.rows.reduce((sum,row)=>sum+num(row.capitalizedInterest),0),contractedMW,generationMWh:0,gridExportMWh:0,ppaRevenue:0,spotRevenue:0,dailyRevenue:0,dailyExpense:facilityOpex,variableOpex:0,facilityOpex,ebitda:-facilityOpex,debtPrincipal:0,debtInterest:0,debtService:0,freeCashFlow:-facilityOpex,lcoe:0,npv:0,irr:0,dailyNet:-facilityOpex};
      const availability=availabilityFor(state,energy,site,day).availability,profile=KIND[site.kind]||KIND.solar,debtPrincipal=debt.principal,debtInterest=debt.interest,debtService=debt.service;
      if(site.kind==='storage'){const share=num(site.capacity)/storageTotal,spread=Math.max(8,spot-num(market.gasCostMWh||39)),cycles=.16*availability,storageRevenue=num(energy.storageMWh||site.capacity)*cycles*spread*.22*share,capacityRevenue=site.dispatchMode==='reserve'?num(site.capacity)*num(market.capacityPriceMWDay||65)*availability:0,balancingRevenue=site.dispatchMode==='reserve'?num(site.capacity)*num(market.balancingPriceMWDay||18)*availability:0,ancillaryRevenue=capacityRevenue+balancingRevenue,dailyRevenue=storageRevenue+ancillaryRevenue,variableOpex=num(site.capacity)*profile.variableCost*.35*availability,dailyExpense=variableOpex+facilityOpex,ebitda=dailyRevenue-dailyExpense,freeCashFlow=ebitda-debtService;return {...clone(site),debtOutstanding:debt.outstanding,contractedMW:0,availability,generationMWh:0,gridExportMWh:0,ppaMWh:0,spotMWh:0,ppaRevenue:0,spotRevenue:0,storageRevenue,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue:0,dailyRevenue,dailyExpense,variableOpex,facilityOpex,ebitda,debtPrincipal,debtInterest,debtService,freeCashFlow,lcoe:0,npv:freeCashFlow*365*8-num(site.capex),irr:num(site.capex)?freeCashFlow*365/num(site.capex)*100:0,dailyNet:freeCashFlow};}
      const margin=spot-profile.variableCost,dispatchFactor=site.dispatchMode==='reserve'?Math.max(.25,1-clamp(site.reserveMargin,0,45)/100):site.dispatchMode==='follow-market'?clamp(.65+margin/180,.45,1):1,grossGeneration=num(site.capacity)*24*profile.factor*availability*dispatchFactor*(1-curtailment),gridCap=num(site.gridExportLimitMW||site.capacity)*24,gridExportMWh=Math.min(grossGeneration,gridCap)*(1-clamp(site.gridLossRate,0,.20)),contracts=energy.ppaContracts.filter(row=>row.siteId===site.id&&row.status==='ساري');let ppaMWh=0,ppaRevenue=0;
      for(const contract of contracts){const share=Math.min(1,num(contract.capacityMW)/Math.max(1,num(site.capacity))),mwh=Math.min(gridExportMWh-ppaMWh,gridExportMWh*share);if(mwh<=0)continue;ppaMWh+=mwh;ppaRevenue+=mwh*num(contract.tariff);}
      const spotMWh=Math.max(0,gridExportMWh-ppaMWh),spotRevenue=spotMWh*spot,reserveMWh=Math.max(0,grossGeneration-gridExportMWh),balancingRevenue=site.dispatchMode==='reserve'?reserveMWh*Math.max(6,spot*.12):0,capacityRevenue=['gas'].includes(site.kind)&&site.dispatchMode==='reserve'?num(site.capacity)*Math.max(0,num(site.reserveMargin))/100*num(market.capacityPriceMWDay||65)*availability:0,ancillaryRevenue=balancingRevenue+capacityRevenue,recRevenue=['solar','wind'].includes(site.kind)?gridExportMWh*num(market.recPriceMWh||2.5):0;
      const fuelContract=energy.fuelContracts.find(row=>row.id===site.fuelContractId&&row.status==='ساري'),fuelNeedMWh=site.kind==='gas'?grossGeneration:0,fuelContractMWh=Math.min(fuelNeedMWh,num(fuelContract?.remainingMWh)),spotFuelMWh=Math.max(0,fuelNeedMWh-fuelContractMWh),spotFuelPrice=num(market.gasCostMWh||39),gasFuel=fuelContractMWh*num(fuelContract?.priceMWh)+spotFuelMWh*spotFuelPrice,carbon=site.kind==='gas'?grossGeneration*.36*num(market.carbonPriceTon||0):0,operations=num(site.capacity)*num(site.maintenanceReservePerMW||profile.variableCost)*availability,gridFees=gridExportMWh*1.7,dailyRevenue=ppaRevenue+spotRevenue+ancillaryRevenue+recRevenue,variableOpex=gasFuel+carbon+operations+gridFees,dailyExpense=variableOpex+facilityOpex,ebitda=dailyRevenue-dailyExpense,freeCashFlow=ebitda-debtService,lcoe=gridExportMWh?dailyExpense/gridExportMWh:0,annualCash=freeCashFlow*365,npv=annualCash*8-num(site.capex),irr=num(site.capex)?annualCash/num(site.capex)*100:0;
      return {...clone(site),debtOutstanding:debt.outstanding,contractedMW,availability,generationMWh:gridExportMWh,grossGenerationMWh:grossGeneration,gridExportMWh,ppaMWh,spotMWh,ppaRevenue,spotRevenue,storageRevenue:0,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue,fuelContractMWh,spotFuelMWh,gasFuel,carbon,operations,gridFees,dailyRevenue,dailyExpense,variableOpex,facilityOpex,ebitda,debtPrincipal,debtInterest,debtService,freeCashFlow,lcoe,npv,irr,dailyNet:freeCashFlow};
    });
  }
  function economics(state){
    const energy=ensure(state),sites=siteEconomics(state),operating=sites.filter(row=>row.commissioned),legacy=operating.length?[]:operatingRows(state,energy);if(!operating.length&&legacy.length){const shadow=clone(state);shadow.customHubs=[];shadow.energy={...clone(energy),sites:legacy.map(row=>({...row,facilityId:row.id}))};return economics(shadow);}
    const sum=key=>operating.reduce((total,row)=>total+(Number(row[key])||0),0),generation=sum('generationMWh'),ppaMWh=sum('ppaMWh'),spotMWh=sum('spotMWh'),ppaRevenue=sum('ppaRevenue'),spotRevenue=sum('spotRevenue'),storageRevenue=sum('storageRevenue'),capacityRevenue=sum('capacityRevenue'),balancingRevenue=sum('balancingRevenue'),ancillaryRevenue=sum('ancillaryRevenue'),recRevenue=sum('recRevenue'),powerRevenue=sum('dailyRevenue'),gasFuel=sum('gasFuel'),carbon=sum('carbon'),operations=sum('operations'),gridFees=sum('gridFees'),debtPrincipal=sum('debtPrincipal'),debtInterest=sum('debtInterest'),debtService=debtPrincipal+debtInterest,facilityOpex=num(facilityCostSnapshot(state).byCompany.power),variableOpex=sum('variableOpex'),powerExpense=variableOpex+facilityOpex;return {generation,generationByKind:{gas:operating.filter(row=>row.kind==='gas').reduce((n,row)=>n+num(row.generationMWh),0),solar:operating.filter(row=>row.kind==='solar').reduce((n,row)=>n+num(row.generationMWh),0),wind:operating.filter(row=>row.kind==='wind').reduce((n,row)=>n+num(row.generationMWh),0)},ppaMWh,spotMWh,ppaRevenue,spotRevenue,storageRevenue,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue,powerRevenue,powerExpense,variableOpex,facilityOpex,gasFuel,carbon,operations,gridFees,debtPrincipal,debtInterest,debtService,ebitda:powerRevenue-powerExpense,net:powerRevenue-powerExpense-debtService};
  }
  function tickDay(state,p){
    const energy=ensure(state),day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(state)/86400)));if(energy.lastProcessedDay===day)return energy.dailyHistory.find(row=>row.day===day)||{day,idempotent:true};let takeOrPayAccrued=0;
    for(const contract of energy.ppaContracts)if(contract.status==='ساري'&&day>=Number(contract.endDay)){contract.status='منتهي';contract.endedDay=day;}
    for(const contract of energy.fuelContracts)if(contract.status==='ساري'&&day>=Number(contract.endDay)){
      contract.status='منتهي';contract.endedDay=day;contract.takeOrPayExposure=Math.max(0,num(contract.volumeMWh)*num(contract.takeOrPay)-num(contract.usedMWh))*num(contract.priceMWh);
      if(contract.takeOrPayExposure>0){
        const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');
        const number=`TOP-${contract.id}`,existing=(state.finance?.invoices||[]).find(row=>row.number===number);
        if(existing){
          if(existing.company!=='power'||existing.kind!=='مصروف'||Math.abs(num(existing.total??existing.amount)-contract.takeOrPayExposure)>.01)throw new Error('energy-take-or-pay-liability-conflict');
          contract.takeOrPayPayableNumber=number;
        }else{
          const payable=F.execute({state},'issue-invoice',{kind:'مصروف',company:'power',amount:contract.takeOrPayExposure,status:'مستحقة',taxable:false,method:'التزام عقد وقود',counterparty:contract.supplier,note:`حد أدنى ملزم لعقد الوقود · ${contract.id}`,number,dueDay:day,sourceRef:`TAKE-OR-PAY-${contract.id}`});
          contract.takeOrPayPayableNumber=payable.number;
        }
        takeOrPayAccrued+=contract.takeOrPayExposure;
      }
    }
    for(const plan of energy.maintenancePlans){if(plan.status==='مجدولة'&&day>=plan.startDay&&day<plan.endDay)plan.status='قيد التنفيذ';if(plan.status==='قيد التنفيذ'&&day>=plan.endDay){plan.status='مكتملة';plan.completedDay=day;const site=energy.sites.find(row=>row.id===plan.siteId);if(site){const age=Math.max(0,day-Number(site.commissionedDay??day)),worn=Math.max(0,age-num(site.recoveredWearDays));site.recoveredWearDays=num(site.recoveredWearDays)+worn*clamp(plan.recovery??.5,0,1);site.lastMaintenanceDay=day;}}}
    for(const site of energy.sites.filter(row=>row.commissioned)){const active=energy.outages.some(row=>row.siteId===site.id&&row.status==='نشط'&&day<row.endDay);if(!active&&deterministic(`${site.id}:${day}:outage`,0,1)<num(site.forcedOutageRate)*outageAging(site,day)/OUTAGE_MEAN_DAYS){const duration=Math.max(1,Math.round(deterministic(`${site.id}:${day}:duration`,1,4)));energy.outages.unshift({id:`OUT-${++energy.sequence}`,siteId:site.id,startDay:day,endDay:day+duration,durationDays:duration,availabilityDuring:0,status:'نشط',cause:'توقف قسري تشغيلي'});}}
    for(const outage of energy.outages)if(outage.status==='نشط'&&day>=outage.endDay){outage.status='مغلق';outage.closedDay=day;}
    const siteRows=siteEconomics(state),dailySummary=economics(state);for(const row of siteRows.filter(item=>item.kind==='gas'&&num(item.fuelContractMWh)>0)){const contract=energy.fuelContracts.find(item=>item.id===row.fuelContractId&&item.status==='ساري');if(!contract)continue;const used=Math.min(num(contract.remainingMWh),num(row.fuelContractMWh));contract.remainingMWh=Math.max(0,num(contract.remainingMWh)-used);contract.usedMWh=num(contract.usedMWh)+used;if(contract.remainingMWh<=.01){contract.status='مستنفد';contract.exhaustedDay=day;}}
    for(const row of siteRows.filter(item=>['solar','wind'].includes(item.kind)&&num(item.gridExportMWh)>0)){const id=`REC-${row.id}-${day}`;if(!energy.renewableCertificates.some(item=>item.id===id))energy.renewableCertificates.unshift({id,siteId:row.id,day,mwh:num(row.gridExportMWh),status:'صادرة'});}energy.renewableCertificates=energy.renewableCertificates.slice(0,1200);
    const F=globalThis.GH_FINANCE_CORE;let debtPrincipalPaid=0,debtPrincipalDeferred=0,constructionInterestCapitalized=0;if(F?.execute){for(const facility of energy.projectFinance.filter(row=>['ساري','متأخر'].includes(row.status)&&num(row.outstanding)>0)){const site=energy.sites.find(row=>row.id===facility.siteId);if(!site)continue;if(!site.commissioned){const last=Math.max(Number(facility.startDay)||0,Number(facility.lastInterestDay)||0),days=Math.max(0,day-last);if(days>0){const opening=num(facility.outstanding),interest=opening*(Math.pow(1+num(facility.rate)/365,days)-1);if(interest>0){F.journal(state,'power',`فوائد مرسملة أثناء إنشاء ${site.name} · يوم ${day}`,[{account:'مشروعات طاقة تحت التنفيذ · فوائد مرسملة',debit:interest},{account:'تمويل مشاريع طاقة',credit:interest}],`PF-CAPINT-${facility.id}-${day}`);F.book(state,'power').debt+=interest;F.adjustDebtOutstanding(state,facility.id,interest,{at:now(state)});facility.outstanding+=interest;facility.capitalizedInterest=num(facility.capitalizedInterest)+interest;constructionInterestCapitalized+=interest;}facility.lastInterestDay=day;}facility.status='ساري';facility.principalArrears=0;continue;}if(facility.repaymentStartDay===null||!Number.isFinite(Number(facility.repaymentStartDay))){facility.repaymentStartDay=Math.max(day,Math.floor(Number(site.commissionedDay)||day));facility.amortizationAmount=num(facility.outstanding)/Math.max(1,Number(facility.termDays)||1);facility.maturityDay=facility.repaymentStartDay+Math.max(1,Number(facility.termDays)||1);}if(day<=Number(facility.repaymentStartDay))continue;const regular=Math.min(num(facility.outstanding),num(facility.amortizationAmount)||num(facility.outstanding)/Math.max(1,Number(facility.termDays)||1)),due=Math.min(num(facility.outstanding),regular+num(facility.principalArrears));if(due<=0)continue;if(F.operating(state,'power')+1e-8>=due){const paid=F.execute({state},'repay-debt',{company:'power',debtId:facility.id,amount:due,liabilityAccount:'تمويل مشاريع طاقة',lender:facility.lender,note:`سداد أصل تمويل مشروع · ${facility.id}`,ref:`PF-PAY-${facility.id}-${day}`}),amount=num(paid.amount);facility.outstanding=Math.max(0,num(facility.outstanding)-amount);facility.principalArrears=Math.max(0,due-amount);debtPrincipalPaid+=amount;if(facility.outstanding<=.01){facility.outstanding=0;facility.status='مسدد';facility.repaidDay=day;}else facility.status=facility.principalArrears>0?'متأخر':'ساري';}else{facility.principalArrears=due;facility.status='متأخر';facility.overdueSinceDay=Number(facility.overdueSinceDay)||day;facility.daysPastDue=Math.max(1,day-facility.overdueSinceDay+1);debtPrincipalDeferred+=due;}}F.reconcile(state);}
    for(const site of energy.sites){site.debtOutstanding=energy.projectFinance.filter(row=>row.siteId===site.id&&row.status!=='مسدد').reduce((sum,row)=>sum+num(row.outstanding),0);}
    for(const tender of [...energy.tenders])if(day>=Number(tender.expiresDay))closeTender(energy,tender,'منتهية',{closedDay:day});
    const newTender=generateTender(state,energy,day);
    const supply=internalSupply(state,energy,dailySummary,day,String(p.ownerCompanyId||'power'));
    // The day's report keeps the supply compact (rounded, no empty lists): 400 days of history are kept.
    const r2=value=>Math.round(num(value)*100)/100,compactSupply=supply.rows.length||supply.settlements.length?{mwh:r2(supply.mwh),revenue:r2(supply.revenue),displacedSpotRevenue:r2(supply.displacedSpotRevenue),cashPostedRevenue:r2(supply.cashPostedRevenue),tariff:supply.tariff,rows:supply.rows.map(row=>({buyer:row.buyer,mwh:r2(row.mwh),amount:r2(row.amount),avoidedExternalCost:r2(row.avoidedExternalCost)})),...(supply.settlements.length?{settlements:supply.settlements.map(row=>({buyer:row.buyer,amount:r2(row.amount),mwh:r2(row.mwh),days:row.days,reference:row.reference}))}:{})}:null;
    const report={day,...(newTender?{newTender:newTender.id}:{}),...dailySummary,powerRevenue:num(dailySummary.powerRevenue)-supply.displacedSpotRevenue+supply.revenue,spotRevenue:num(dailySummary.spotRevenue)-supply.displacedSpotRevenue,spotMWh:Math.max(0,num(dailySummary.spotMWh)-supply.mwh),...(compactSupply?{internalSupply:compactSupply}:{}),powerExpense:num(dailySummary.powerExpense)+takeOrPayAccrued,takeOrPayAccrued,debtPrincipalPaid,debtPrincipalDeferred,constructionInterestCapitalized,sites:siteRows.map(row=>({siteId:row.id,revenue:row.dailyRevenue,ppaRevenue:row.ppaRevenue,spotRevenue:row.spotRevenue,storageRevenue:row.storageRevenue,capacityRevenue:row.capacityRevenue,balancingRevenue:row.balancingRevenue,recRevenue:row.recRevenue,expense:row.dailyExpense,variableOpex:row.variableOpex,facilityOpex:row.facilityOpex,debtInterest:row.debtInterest,debtPrincipal:row.debtPrincipal,net:row.dailyNet,availability:row.availability,generationMWh:row.generationMWh,fuelContractMWh:row.fuelContractMWh,spotFuelMWh:row.spotFuelMWh}))};energy.dailyHistory.unshift(report);energy.dailyHistory=energy.dailyHistory.slice(0,400);energy.lastProcessedDay=day;return clone(report);
  }
  // Build 358 (owner review): the group buys its electricity from its own power company. About 30% of a facility's
  // daily running cost is its electricity bill, paid at the retail price (35% over the wholesale spot price). The power
  // company sells the uncontracted part of today's export to the operating subsidiaries at 10% over spot, so a buyer pays
  // about 19% less for what it takes and the power company earns more than the market would pay.
  // Load: a day only adds numbers to each buyer's running account (energy.internalSupplyAccounts); the documents are
  // written once a month per buyer (SETTLE_EVERY_DAYS): one Finance Core settlement with the buyer's expense document,
  // the power company's income document and the cash transfer. A buyer short of cash on its settlement day carries the
  // balance to the next one. The daily close books the day's internal price in both companies' results and leaves the
  // cash to the settlement, so nothing is posted twice.
  const ELECTRICITY_SHARE=.3,RETAIL_MARKUP=1.35,INTERNAL_MARKUP=1.10,SETTLE_EVERY_DAYS=30;
  function supplyAccounts(energy){energy.internalSupplyAccounts=energy.internalSupplyAccounts&&typeof energy.internalSupplyAccounts==='object'&&!Array.isArray(energy.internalSupplyAccounts)?energy.internalSupplyAccounts:{};return energy.internalSupplyAccounts;}
  function internalSupply(state,energy,summary,day,seller){
    const F=globalThis.GH_FINANCE_CORE,market=state.advanced?.economy||{},spot=num(market.electricityPriceMWh||90),out={rows:[],mwh:0,revenue:0,displacedSpotRevenue:0,cashPostedRevenue:0,settlements:[],spot,tariff:Math.round(spot*INTERNAL_MARKUP*100)/100},accounts=supplyAccounts(energy);
    let available=num(summary.spotMWh);
    // Buyers are the operating subsidiaries whose facility costs the daily close posts (the holding's own premises are
    // not part of it, so the group never buys here).
    const byCompany=facilityCostSnapshot(state).byCompany||{},operating=new Set((globalThis.GH_COMPANY_PLATFORM?.listInstances?.(state,{includeGroup:false,openedOnly:true})||[]).filter(row=>row?.operational).map(row=>String(row.id)));
    if(spot>0&&available>0)for(const buyer of Object.keys(byCompany).filter(id=>operating.has(id)&&id!==seller).sort()){
      if(available<=0)break;const bill=num(byCompany[buyer])*ELECTRICITY_SHARE;if(bill<=0)continue;
      const demand=bill/(spot*RETAIL_MARKUP),mwh=Math.min(demand,available),amount=Math.round(mwh*out.tariff*100)/100,avoided=Math.round(bill*(mwh/demand)*100)/100;if(amount<=0)continue;
      available-=mwh;out.mwh+=mwh;out.revenue+=amount;out.displacedSpotRevenue+=mwh*spot;out.rows.push({buyer,mwh,amount,avoidedExternalCost:avoided});
      const account=accounts[buyer]=accounts[buyer]||{buyer,openedDay:day,mwh:0,amount:0,avoided:0,days:0};account.mwh+=mwh;account.amount=Math.round((num(account.amount)+amount)*100)/100;account.avoided=Math.round((num(account.avoided)+avoided)*100)/100;account.days++;
    }
    // The day's internal revenue is booked in the results, its cash arrives with the monthly settlement.
    out.cashPostedRevenue=out.revenue;
    if(F?.execute)for(const buyer of Object.keys(accounts).sort()){
      const account=accounts[buyer];if(!account||num(account.amount)<=0){delete accounts[buyer];continue;}if(day-Math.floor(Number(account.openedDay)||day)<SETTLE_EVERY_DAYS)continue;
      let cash=0;try{cash=num(F.operating(state,buyer));}catch{continue;}if(cash+1e-8<num(account.amount)){account.carriedOver=(Number(account.carriedOver)||0)+1;continue;}
      const result=F.execute({state},'settle-intercompany-supply',{from:buyer,to:seller,amount:account.amount,mwh:account.mwh,note:`توريد كهرباء داخلي · ${Math.round(account.mwh)} ميغاواط ساعة · ${account.days} يوم حتى يوم ${day}`,ref:`ENERGY-SUPPLY-${buyer}-${day}`});
      out.settlements.push({buyer,amount:account.amount,mwh:account.mwh,days:account.days,reference:result?.reference||`ENERGY-SUPPLY-${buyer}-${day}`});delete accounts[buyer];
    }
    return out;
  }
  // Called only through the existing company operations provider. Keep the
  // domain command inside the caller's atomic time/day boundary transaction.
  function onFinancialDay(ctx,p={}){
    const platform=globalThis.GH_COMPANY_PLATFORM,commands=globalThis.GH_DOMAIN_COMMANDS;
    if(!platform?.requireCompany||!commands?.dispatchSystem)throw new Error('company-daily-owner-unavailable');
    const company=platform.requireCompany(ctx.state,ctx.companyId,{registered:true,operational:true,capability:'operations.energy'});
    return commands.dispatchSystem({state:ctx.state},'energy','tick-day',{...p,ownerCompanyId:company.id},{actor:'simulation-scheduler'}).result;
  }
  function execute(ctx,cmd,p={}){const state=ctx.state||ctx;if(cmd==='ensure')return ensure(state);if(cmd==='accept-ppa')return acceptPpa(state,p);if(cmd==='set-dispatch-policy')return setDispatchPolicy(state,p);if(cmd==='sign-fuel-contract')return signFuelContract(state,p);if(cmd==='schedule-maintenance')return scheduleMaintenance(state,p);if(cmd==='finance-project')return financeProject(state,p);if(cmd==='bid-tender')return bidTender(state,p);if(cmd==='tick-day')return tickDay(state,p);throw new Error(`Unknown energy command: ${cmd}`);}
  const API={tenderQuote,MAX_OPEN_TENDERS,VERSION,DAILY_FINANCIAL_ORDER:200,onFinancialDay,KIND,FUEL_TERMS,fuelOffer,maintenanceQuote,outageAging,projectFinanceRate,projectFinanceRoom,ensure,economics,siteEconomics,acceptPpa,tickDay,execute};globalThis.GH_ENERGY_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('energy',API);if(globalThis.window&&window!==globalThis)window.GH_ENERGY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
