(()=>{
  'use strict';
  const VERSION='3.0.0';
  const num=value=>Math.max(0,Number(value)||0),now=state=>Number(state.simSeconds)||0;
  const clone=value=>globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value));
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const KIND=Object.freeze({
    gas:{name:'توليد غازي',factor:.56,variableCost:18,forcedOutage:.04,degradation:.004,lifeYears:30},
    solar:{name:'طاقة شمسية',factor:.25,variableCost:7,forcedOutage:.012,degradation:.006,lifeYears:28},
    wind:{name:'طاقة رياح',factor:.39,variableCost:12,forcedOutage:.022,degradation:.005,lifeYears:25},
    storage:{name:'تخزين شبكي',factor:0,variableCost:3,forcedOutage:.018,degradation:.018,lifeYears:18}
  });
  function hash(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
  function deterministic(seed,min,max){return min+(hash(seed)/4294967295)*(max-min);}
  function inferFacility(facility){const text=String(facility.capacity||''),amount=num(facility.capacityAmount||text.match(/[\d,.]+/)?.[0]?.replace(/,/g,'')),kind=facility.energyKind||(/شمس/.test(`${facility.name} ${text}`)?'solar':/رياح/.test(`${facility.name} ${text}`)?'wind':/تخزين|MWh/.test(`${facility.name} ${text}`)?'storage':/غاز/.test(`${facility.name} ${text}`)?'gas':'solar');return {kind,amount};}
  function siteDefaults(state,facility,inferred){
    const profile=KIND[inferred.kind]||KIND.solar,capacity=num(inferred.amount);return {id:`SITE-${facility.id}`,facilityId:facility.id,constructionContractId:facility.constructionContractId||null,name:facility.name,city:facility.city||'غير محدد',country:facility.country||'غير محدد',kind:inferred.kind,capacity,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء',openedAt:Number(facility.openedAt)||now(state),commissionedDay:facility.commissioned===true?Math.floor(now(state)/86400):null,availability:100,forcedOutageRate:profile.forcedOutage,degradationRate:profile.degradation,gridExportLimitMW:capacity,gridLossRate:.02,gridOperator:'مشغل الشبكة المحلي',dispatchMode:inferred.kind==='gas'?'follow-market':inferred.kind==='storage'?'arbitrage':'must-run',reserveMargin:inferred.kind==='gas'?10:0,maintenanceReservePerMW:inferred.kind==='gas'?18:profile.variableCost,capex:num(facility.cost),debtOutstanding:0,debtRate:0,debtTermDays:0,debtStartDay:null};
  }
  function syncSites(state,energy){
    for(const facility of (state.customHubs||[]).filter(row=>row?.owned===true&&String(row.ownerCompanyId||row.companyId||row.company||'')==='power'&&row.kind==='power')){
      const inferred=inferFacility(facility),existing=energy.sites.find(row=>row.facilityId===facility.id);
      if(existing){const wasCommissioned=existing.commissioned===true;Object.assign(existing,{name:facility.name,city:facility.city||existing.city,country:facility.country||existing.country,kind:inferred.kind,capacity:inferred.amount,commissioned:facility.commissioned===true,status:facility.commissioned===true?'تشغيل تجاري':'قيد الإنشاء'});if(!wasCommissioned&&existing.commissioned)existing.commissionedDay=Math.floor(now(state)/86400);const defaults=siteDefaults(state,facility,inferred);for(const [key,value] of Object.entries(defaults))if(existing[key]===undefined||existing[key]===null)existing[key]=value;continue;}
      energy.sites.push(siteDefaults(state,facility,inferred));
    }
    return energy.sites;
  }
  function ensure(state){
    const energy=state.energy=state.energy&&typeof state.energy==='object'?state.energy:{};
    for(const key of ['gasMW','solarMW','windMW','storageMWh','availability'])energy[key]=num(energy[key]);if(!energy.availability&&(energy.gasMW+energy.solarMW+energy.windMW)>0)energy.availability=90;
    for(const key of ['sites','ppaOffers','ppaContracts','dailyHistory','outages','maintenancePlans','fuelContracts','gridAgreements','projectFinance','dispatchInstructions','renewableCertificates','regionalOffices'])energy[key]=Array.isArray(energy[key])?energy[key].filter(Boolean):[];
    energy.sequence=Math.max(0,Math.floor(Number(energy.sequence)||0));syncSites(state,energy);
    for(const facility of energy.projectFinance){
      const site=energy.sites.find(row=>row.id===facility.siteId),startDay=Math.max(0,Math.floor(Number(facility.startDay)||0)),termDays=Math.max(365,Math.floor(Number(facility.termDays)||3650));
      facility.amount=num(facility.amount);facility.originalAmount=num(facility.originalAmount||facility.amount);facility.outstanding=num(facility.outstanding);facility.principalArrears=num(facility.principalArrears);facility.capitalizedInterest=num(facility.capitalizedInterest);facility.startDay=startDay;facility.termDays=termDays;facility.lastInterestDay=Math.max(startDay,Math.floor(Number(facility.lastInterestDay)||startDay));
      if(facility.repaymentStartDay===undefined){facility.repaymentStartDay=site?.commissioned?Math.max(startDay,Math.floor(Number(site.commissionedDay)||startDay)):null;}
      if(facility.repaymentStartDay!==null&&Number.isFinite(Number(facility.repaymentStartDay))){facility.repaymentStartDay=Math.max(startDay,Math.floor(Number(facility.repaymentStartDay)));facility.amortizationAmount=num(facility.amortizationAmount)||facility.originalAmount/termDays;facility.maturityDay=facility.repaymentStartDay+termDays;}else{facility.repaymentStartDay=null;facility.amortizationAmount=num(facility.amortizationAmount);}
    }
    for(const site of energy.sites.filter(row=>row.commissioned&&row.kind!=='storage')){
      const hasOpen=energy.ppaOffers.some(row=>row.siteId===site.id&&row.status==='متاح'),hasActive=energy.ppaContracts.some(row=>row.siteId===site.id&&row.status==='ساري');if(hasOpen||hasActive)continue;
      const spot=num(state.advanced?.economy?.electricityPriceMWh||90),capacity=Math.max(1,site.capacity);[['مرافق المدينة',.32,.94,1825],['مجمع صناعي دولي',.24,1.02,2555],['مركز بيانات عالمي',.18,1.09,3650]].forEach(([buyer,share,multiplier,termDays],index)=>energy.ppaOffers.push({id:`PPA-OFFER-${++energy.sequence}`,siteId:site.id,buyer:`${buyer} · ${site.city}`,capacityMW:Math.max(1,Math.round(capacity*share)),tariff:Number((spot*multiplier).toFixed(2)),termDays,startDay:Math.floor(now(state)/86400),status:'متاح',rank:index+1}));
    }
    energy.ppaOffers=energy.ppaOffers.slice(-240);return energy;
  }
  function acceptedCapacity(energy,siteId){return energy.ppaContracts.filter(row=>row.siteId===siteId&&row.status==='ساري').reduce((sum,row)=>sum+num(row.capacityMW),0);}
  function acceptPpa(state,p){
    const energy=ensure(state),offer=energy.ppaOffers.find(row=>row.id===p.id&&row.status==='متاح');if(!offer)throw new Error('energy-ppa-offer-unavailable');const site=energy.sites.find(row=>row.id===offer.siteId&&row.commissioned);if(!site)throw new Error('energy-site-not-commissioned');
    const capacity=Math.min(num(offer.capacityMW),Math.max(0,num(site.capacity)-acceptedCapacity(energy,site.id)));if(capacity<=0)throw new Error('energy-capacity-fully-contracted');offer.status='مقبول';offer.acceptedAt=now(state);const startDay=Math.floor(now(state)/86400),contract={id:`PPA-${++energy.sequence}`,offerId:offer.id,siteId:site.id,siteName:site.name,buyer:offer.buyer,kind:site.kind,capacityMW:capacity,tariff:num(offer.tariff),termDays:Number(offer.termDays)||1825,startDay,endDay:startDay+(Number(offer.termDays)||1825),status:'ساري'};energy.ppaContracts.unshift(contract);return clone(contract);
  }
  function siteById(state,id){return ensure(state).sites.find(row=>row.id===id||row.facilityId===id);}
  function setDispatchPolicy(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const allowed=site.kind==='storage'?['arbitrage','reserve','idle']:['must-run','follow-market','reserve'];if(!allowed.includes(p.mode))throw new Error('energy-dispatch-mode-invalid');site.dispatchMode=p.mode;site.reserveMargin=clamp(p.reserveMargin??site.reserveMargin,0,45);const instruction={id:`DSP-${++energy.sequence}`,siteId:site.id,mode:site.dispatchMode,reserveMargin:site.reserveMargin,at:now(state)};energy.dispatchInstructions.unshift(instruction);energy.dispatchInstructions=energy.dispatchInstructions.slice(0,300);return clone(site);}
  function setGridConnection(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const limit=num(p.exportLimitMW);if(limit<=0)throw new Error('energy-grid-limit-invalid');site.gridExportLimitMW=limit;site.gridLossRate=clamp(p.lossRate??site.gridLossRate,0,.20);site.gridOperator=String(p.gridOperator||site.gridOperator||'مشغل الشبكة المحلي');let agreement=energy.gridAgreements.find(row=>row.siteId===site.id&&row.status==='ساري');if(!agreement){agreement={id:`GRID-${++energy.sequence}`,siteId:site.id,status:'ساري',signedAt:now(state)};energy.gridAgreements.unshift(agreement);}Object.assign(agreement,{exportLimitMW:limit,lossRate:site.gridLossRate,gridOperator:site.gridOperator});return clone(site);}
  function signFuelContract(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site||site.kind!=='gas')throw new Error('energy-gas-site-required');const priceMWh=num(p.priceMWh),volumeMWh=num(p.volumeMWh),termDays=Math.max(30,Math.floor(Number(p.termDays)||365));if(priceMWh<=0||volumeMWh<=0)throw new Error('energy-fuel-contract-invalid');for(const row of energy.fuelContracts.filter(row=>row.siteId===site.id&&row.status==='ساري'))row.status='مستبدل';const startDay=Math.floor(now(state)/86400),contract={id:`FUEL-${++energy.sequence}`,siteId:site.id,supplier:String(p.supplier||'مورد وقود معتمد'),priceMWh,volumeMWh,remainingMWh:volumeMWh,usedMWh:0,termDays,startDay,endDay:startDay+termDays,takeOrPay:clamp(p.takeOrPay??.75,0,1),status:'ساري'};energy.fuelContracts.unshift(contract);site.fuelContractId=contract.id;return clone(contract);}
  function scheduleMaintenance(state,p){
    const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const startDay=Math.max(Math.floor(now(state)/86400),Math.floor(Number(p.startDay)||0)),durationDays=Math.max(1,Math.floor(Number(p.durationDays)||1)),cost=num(p.cost),supplier=String(p.supplier||'مقاول صيانة طاقة معتمد');if(energy.maintenancePlans.some(row=>row.siteId===site.id&&row.status==='مجدولة'&&startDay<row.endDay&&startDay+durationDays>row.startDay))throw new Error('energy-maintenance-overlap');
    let chequeId=null,invoiceNumber=null;if(cost>0){const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');const payment=F.execute({state},'pay-by-cheque',{company:'power',amount:cost,note:`صيانة مجدولة · ${site.name}`,beneficiary:supplier,line:'maintenance',requestRef:`ENERGY-MAINT-${site.id}-${startDay}`});if(!payment?.cheque?.id||payment.cheque.status!=='مصروف')throw new Error('energy-maintenance-cheque-not-cleared');chequeId=payment.cheque.id;invoiceNumber=payment.invoice.number;}
    const plan={id:`MAINT-${++energy.sequence}`,siteId:site.id,siteName:site.name,startDay,endDay:startDay+durationDays,durationDays,cost,supplier,availabilityDuring:clamp(p.availabilityDuring??0,0,1),status:'مجدولة',chequeId,invoiceNumber};energy.maintenancePlans.unshift(plan);return clone(plan);
  }
  function financeProject(state,p){const energy=ensure(state),site=siteById(state,p.siteId);if(!site)throw new Error('energy-site-not-found');const amount=num(p.amount),rate=clamp(p.rate||.065,0,.30),termDays=Math.max(365,Math.floor(Number(p.termDays)||3650));if(amount<=0)throw new Error('energy-project-finance-invalid');const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');const startDay=Math.floor(now(state)/86400),financing=F.execute({state},'raise-debt',{company:'power',amount,liabilityAccount:'تمويل مشاريع طاقة',lender:p.lender||'اتحاد بنوك المشاريع',note:`تمويل مشروع · ${site.name}`,ref:`PF-${site.id}-${++energy.sequence}`});site.debtOutstanding+=amount;site.debtRate=rate;site.debtTermDays=termDays;site.debtStartDay=startDay;const repaymentStartDay=site.commissioned?Math.max(startDay,Math.floor(Number(site.commissionedDay)||startDay)):null,row={id:financing.ref,siteId:site.id,lender:String(p.lender||'اتحاد بنوك المشاريع'),amount,originalAmount:amount,outstanding:amount,principalArrears:0,capitalizedInterest:0,rate,termDays,startDay,lastInterestDay:startDay,repaymentStartDay,amortizationAmount:repaymentStartDay===null?0:amount/termDays,maturityDay:repaymentStartDay===null?null:repaymentStartDay+termDays,status:'ساري'};energy.projectFinance.unshift(row);return clone(row);}
  function operatingRows(state,energy){
    const commissioned=energy.sites.filter(row=>row.commissioned);if(commissioned.length)return commissioned;
    const legacy=[];for(const [kind,key] of [['gas','gasMW'],['solar','solarMW'],['wind','windMW'],['storage','storageMWh']])if(num(energy[key])>0)legacy.push({id:`LEGACY-${kind}`,facilityId:null,name:`قدرة محفوظة · ${KIND[kind].name}`,city:'سجل قديم',country:'سجل قديم',kind,capacity:num(energy[key]),commissioned:true,status:'تشغيل تجاري',commissionedDay:0,availability:100,forcedOutageRate:KIND[kind].forcedOutage,degradationRate:KIND[kind].degradation,gridExportLimitMW:num(energy[key]),gridLossRate:.02,dispatchMode:kind==='gas'?'follow-market':kind==='storage'?'arbitrage':'must-run',reserveMargin:kind==='gas'?10:0,maintenanceReservePerMW:KIND[kind].variableCost,capex:0,debtOutstanding:0,debtRate:0,debtTermDays:0});return legacy;
  }
  function availabilityFor(state,energy,site,day){
    const fleetAvailability=clamp(energy.availability||100,0,100)/100,siteAvailability=clamp(site.availability??100,0,100)/100,ageDays=Math.max(0,day-Number(site.commissionedDay||day)),degradation=Math.max(.65,1-num(site.degradationRate)*(ageDays/365)),maintenance=energy.maintenancePlans.find(row=>row.siteId===site.id&&['مجدولة','قيد التنفيذ'].includes(row.status)&&day>=row.startDay&&day<row.endDay),outage=energy.outages.find(row=>row.siteId===site.id&&row.status==='نشط'&&day>=row.startDay&&day<row.endDay),realismHealth=clamp(state.realism?.energy?.storageHealth||100,0,100)/100;let availability=fleetAvailability*siteAvailability*degradation;if(maintenance)availability*=clamp(maintenance.availabilityDuring,0,1);if(outage)availability*=clamp(outage.availabilityDuring??0,0,1);if(site.kind==='storage')availability*=realismHealth;return {availability:clamp(availability,0,1),maintenance,outage,degradation};
  }
  function debtSchedule(energy,site,day=0){
    const rows=energy.projectFinance.filter(row=>row.siteId===site.id&&['ساري','متأخر'].includes(row.status)&&num(row.outstanding)>0);let principal=0,interest=0,outstanding=0;
    for(const row of rows){const balance=num(row.outstanding);outstanding+=balance;const repaymentStart=Number(row.repaymentStartDay);if(!site.commissioned||!Number.isFinite(repaymentStart)||day<=repaymentStart)continue;const regular=num(row.amortizationAmount)||num(row.originalAmount||row.amount)/Math.max(1,Number(row.termDays)||1);principal+=Math.min(balance,regular+num(row.principalArrears));interest+=balance*num(row.rate)/365;}
    return {rows,principal,interest,outstanding,service:principal+interest};
  }
  function openRegionalOffice(state,p={}){
    const energy=ensure(state),F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');
    const region=String(p.region||'').trim(),city=String(p.city||'').trim(),country=String(p.country||'').trim();if(!region||!city||!country)throw new Error('energy-office-location-required');
    if(energy.regionalOffices.some(row=>row.status==='نشط'&&row.city===city&&row.country===country))throw new Error('energy-office-already-open');
    const setupCost=Math.max(1000000,num(p.setupCost||3500000)),dailyOpex=Math.max(2500,num(p.dailyOpex||12000));
    F.execute({state},'spend',{company:'power',amount:setupCost,note:`تأسيس مكتب إقليمي للطاقة · ${city} · ${region}`,method:'تحويل بنكي',taxable:false,counterparty:`مزود تجهيزات المكاتب · ${city}`,line:'other'});
    const row={id:`ENERGY-OFFICE-${++energy.sequence}`,region,city,country,status:'نشط',openedAt:now(state),setupCost,dailyOpex,headcount:Math.max(4,Math.floor(Number(p.headcount)||12)),mandate:String(p.mandate||'تطوير المشاريع والعقود وعلاقات الشبكة')};energy.regionalOffices.unshift(row);return clone(row);
  }
  function facilityCostSnapshot(state){
    const core=globalThis.GH_FACILITY_CORE;
    if(core?.dailyOperatingCosts)return core.dailyOperatingCosts(state);
    if([...(state.globalBases||[]),...(state.customHubs||[])].some(row=>row?.owned===true&&String(row.ownerCompanyId||row.companyId||row.company||'')==='power'))throw new Error('facility-daily-cost-owner-missing');
    return {total:0,byCompany:Object.create(null),byFacility:Object.create(null)};
  }
  function siteEconomics(state){
    const energy=ensure(state),costSnapshot=facilityCostSnapshot(state),market=state.advanced?.economy||{},spot=num(market.electricityPriceMWh||90),day=Math.floor(now(state)/86400),curtailment=clamp(state.realism?.energy?.curtailment||0,0,100)/100,storageSites=operatingRows(state,energy).filter(row=>row.kind==='storage'),storageTotal=Math.max(1,storageSites.reduce((sum,row)=>sum+num(row.capacity),0));
    return energy.sites.map(site=>{
      const contractedMW=acceptedCapacity(energy,site.id),debt=debtSchedule(energy,site,day),cost=costSnapshot.byFacility[site.facilityId],facilityOpex=cost?.ownerCompanyId==='power'?num(cost.amount):0;if(!site.commissioned)return {...clone(site),debtOutstanding:debt.outstanding,constructionInterestCapitalized:debt.rows.reduce((sum,row)=>sum+num(row.capitalizedInterest),0),contractedMW,generationMWh:0,gridExportMWh:0,ppaRevenue:0,spotRevenue:0,dailyRevenue:0,dailyExpense:facilityOpex,variableOpex:0,facilityOpex,ebitda:-facilityOpex,debtPrincipal:0,debtInterest:0,debtService:0,freeCashFlow:-facilityOpex,lcoe:0,npv:0,irr:0,dailyNet:-facilityOpex};
      const availability=availabilityFor(state,energy,site,day).availability,profile=KIND[site.kind]||KIND.solar,debtPrincipal=debt.principal,debtInterest=debt.interest,debtService=debt.service;
      if(site.kind==='storage'){const share=num(site.capacity)/storageTotal,spread=Math.max(8,spot-num(market.gasCostMWh||39)),cycles=.16*availability,storageRevenue=num(energy.storageMWh||site.capacity)*cycles*spread*.22*share,capacityRevenue=site.dispatchMode==='reserve'?num(site.capacity)*num(market.capacityPriceMWDay||65)*availability:0,balancingRevenue=site.dispatchMode==='reserve'?num(site.capacity)*num(market.balancingPriceMWDay||18)*availability:0,ancillaryRevenue=capacityRevenue+balancingRevenue,dailyRevenue=storageRevenue+ancillaryRevenue,variableOpex=num(site.capacity)*profile.variableCost*.35*availability,dailyExpense=variableOpex+facilityOpex,ebitda=dailyRevenue-dailyExpense,freeCashFlow=ebitda-debtService;return {...clone(site),debtOutstanding:debt.outstanding,contractedMW:0,availability,generationMWh:0,gridExportMWh:0,ppaMWh:0,spotMWh:0,ppaRevenue:0,spotRevenue:0,storageRevenue,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue:0,dailyRevenue,dailyExpense,variableOpex,facilityOpex,ebitda,debtPrincipal,debtInterest,debtService,freeCashFlow,lcoe:0,npv:freeCashFlow*365*8-num(site.capex),irr:num(site.capex)?freeCashFlow*365/num(site.capex)*100:0,dailyNet:freeCashFlow};}
      const margin=spot-profile.variableCost,dispatchFactor=site.dispatchMode==='reserve'?Math.max(.25,1-clamp(site.reserveMargin,0,45)/100):site.dispatchMode==='follow-market'?clamp(.65+margin/180,.45,1):1,grossGeneration=num(site.capacity)*24*profile.factor*availability*dispatchFactor*(1-curtailment),gridCap=num(site.gridExportLimitMW||site.capacity)*24,gridExportMWh=Math.min(grossGeneration,gridCap)*(1-clamp(site.gridLossRate,0,.20)),contracts=energy.ppaContracts.filter(row=>row.siteId===site.id&&row.status==='ساري');let ppaMWh=0,ppaRevenue=0;
      for(const contract of contracts){const share=Math.min(1,num(contract.capacityMW)/Math.max(1,num(site.capacity))),mwh=Math.min(gridExportMWh-ppaMWh,gridExportMWh*share);if(mwh<=0)continue;ppaMWh+=mwh;ppaRevenue+=mwh*num(contract.tariff);}
      const spotMWh=Math.max(0,gridExportMWh-ppaMWh),spotRevenue=spotMWh*spot,reserveMWh=Math.max(0,grossGeneration-gridExportMWh),balancingRevenue=site.dispatchMode==='reserve'?reserveMWh*Math.max(6,spot*.12):0,capacityRevenue=['gas'].includes(site.kind)&&site.dispatchMode==='reserve'?num(site.capacity)*Math.max(0,num(site.reserveMargin))/100*num(market.capacityPriceMWDay||65)*availability:0,ancillaryRevenue=balancingRevenue+capacityRevenue,recRevenue=['solar','wind'].includes(site.kind)?gridExportMWh*num(market.recPriceMWh||2.5):0;
      const fuelContract=energy.fuelContracts.find(row=>row.id===site.fuelContractId&&row.status==='ساري'),fuelNeedMWh=site.kind==='gas'?grossGeneration:0,fuelContractMWh=Math.min(fuelNeedMWh,num(fuelContract?.remainingMWh)),spotFuelMWh=Math.max(0,fuelNeedMWh-fuelContractMWh),spotFuelPrice=num(market.gasCostMWh||39),gasFuel=fuelContractMWh*num(fuelContract?.priceMWh)+spotFuelMWh*spotFuelPrice,carbon=site.kind==='gas'?grossGeneration*.36*num(market.carbonPriceTon||0):0,operations=num(site.capacity)*num(site.maintenanceReservePerMW||profile.variableCost)*availability,gridFees=gridExportMWh*1.7,dailyRevenue=ppaRevenue+spotRevenue+ancillaryRevenue+recRevenue,variableOpex=gasFuel+carbon+operations+gridFees,dailyExpense=variableOpex+facilityOpex,ebitda=dailyRevenue-dailyExpense,freeCashFlow=ebitda-debtService,lcoe=gridExportMWh?dailyExpense/gridExportMWh:0,annualCash=freeCashFlow*365,npv=annualCash*8-num(site.capex),irr=num(site.capex)?annualCash/num(site.capex)*100:0;
      return {...clone(site),debtOutstanding:debt.outstanding,contractedMW,availability,generationMWh:gridExportMWh,grossGenerationMWh:grossGeneration,gridExportMWh,ppaMWh,spotMWh,ppaRevenue,spotRevenue,storageRevenue:0,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue,fuelContractMWh,spotFuelMWh,gasFuel,carbon,operations,gridFees,dailyRevenue,dailyExpense,variableOpex,facilityOpex,ebitda,debtPrincipal,debtInterest,debtService,freeCashFlow,lcoe,npv,irr,dailyNet:freeCashFlow};
    });
  }
  function economics(state){
    const energy=ensure(state),sites=siteEconomics(state),operating=sites.filter(row=>row.commissioned),legacy=operating.length?[]:operatingRows(state,energy);if(!operating.length&&legacy.length){const shadow=clone(state);shadow.customHubs=[];shadow.energy={...clone(energy),sites:legacy.map(row=>({...row,facilityId:row.id}))};return economics(shadow);}
    const sum=key=>operating.reduce((total,row)=>total+(Number(row[key])||0),0),generation=sum('generationMWh'),ppaMWh=sum('ppaMWh'),spotMWh=sum('spotMWh'),ppaRevenue=sum('ppaRevenue'),spotRevenue=sum('spotRevenue'),storageRevenue=sum('storageRevenue'),capacityRevenue=sum('capacityRevenue'),balancingRevenue=sum('balancingRevenue'),ancillaryRevenue=sum('ancillaryRevenue'),recRevenue=sum('recRevenue'),powerRevenue=sum('dailyRevenue'),gasFuel=sum('gasFuel'),carbon=sum('carbon'),operations=sum('operations'),gridFees=sum('gridFees'),regionalOfficeOpex=energy.regionalOffices.filter(row=>row.status==='نشط').reduce((t,row)=>t+num(row.dailyOpex),0),debtPrincipal=sum('debtPrincipal'),debtInterest=sum('debtInterest'),debtService=debtPrincipal+debtInterest,facilityOpex=num(facilityCostSnapshot(state).byCompany.power),variableOpex=sum('variableOpex')+regionalOfficeOpex,powerExpense=variableOpex+facilityOpex;return {generation,generationByKind:{gas:operating.filter(row=>row.kind==='gas').reduce((n,row)=>n+num(row.generationMWh),0),solar:operating.filter(row=>row.kind==='solar').reduce((n,row)=>n+num(row.generationMWh),0),wind:operating.filter(row=>row.kind==='wind').reduce((n,row)=>n+num(row.generationMWh),0)},ppaMWh,spotMWh,ppaRevenue,spotRevenue,storageRevenue,capacityRevenue,balancingRevenue,ancillaryRevenue,recRevenue,powerRevenue,powerExpense,variableOpex,facilityOpex,gasFuel,carbon,operations,gridFees,regionalOfficeOpex,debtPrincipal,debtInterest,debtService,ebitda:powerRevenue-powerExpense,net:powerRevenue-powerExpense-debtService};
  }
  function tickDay(state,p){
    const energy=ensure(state),day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(state)/86400)));if(energy.lastProcessedDay===day)return energy.dailyHistory.find(row=>row.day===day)||{day,idempotent:true};let takeOrPayAccrued=0;
    for(const contract of energy.ppaContracts)if(contract.status==='ساري'&&day>=Number(contract.endDay)){contract.status='منتهي';contract.endedDay=day;}
    for(const contract of energy.fuelContracts)if(contract.status==='ساري'&&day>=Number(contract.endDay)){
      contract.status='منتهي';contract.endedDay=day;contract.takeOrPayExposure=Math.max(0,num(contract.volumeMWh)*num(contract.takeOrPay)-num(contract.usedMWh))*num(contract.priceMWh);
      if(contract.takeOrPayExposure>0){
        const F=globalThis.GH_FINANCE_CORE;if(!F?.execute)throw new Error('finance-core-missing');
        const number=`TOP-${contract.id}`,existing=(state.finance?.invoices||[]).find(row=>row.number===number);
        if(existing){
          if(existing.company!=='power'||existing.kind!=='مصروف'||Math.abs(num(existing.total??existing.amount)-contract.takeOrPayExposure)>.01)throw new Error('energy-take-or-pay-liability-conflict');
          contract.takeOrPayPayableNumber=number;
        }else{
          const payable=F.execute({state},'issue-invoice',{kind:'مصروف',company:'power',amount:contract.takeOrPayExposure,status:'مستحقة',taxable:false,method:'التزام عقد وقود',counterparty:contract.supplier,note:`حد أدنى ملزم لعقد الوقود · ${contract.id}`,number,dueDay:day,sourceRef:`TAKE-OR-PAY-${contract.id}`});
          contract.takeOrPayPayableNumber=payable.number;
        }
        takeOrPayAccrued+=contract.takeOrPayExposure;
      }
    }
    for(const plan of energy.maintenancePlans){if(plan.status==='مجدولة'&&day>=plan.startDay&&day<plan.endDay)plan.status='قيد التنفيذ';if(plan.status==='قيد التنفيذ'&&day>=plan.endDay){plan.status='مكتملة';plan.completedDay=day;}}
    for(const site of energy.sites.filter(row=>row.commissioned)){const active=energy.outages.some(row=>row.siteId===site.id&&row.status==='نشط'&&day<row.endDay);if(!active&&deterministic(`${site.id}:${day}:outage`,0,1)<num(site.forcedOutageRate)/365){const duration=Math.max(1,Math.round(deterministic(`${site.id}:${day}:duration`,1,4)));energy.outages.unshift({id:`OUT-${++energy.sequence}`,siteId:site.id,startDay:day,endDay:day+duration,durationDays:duration,availabilityDuring:0,status:'نشط',cause:'توقف قسري تشغيلي'});}}
    for(const outage of energy.outages)if(outage.status==='نشط'&&day>=outage.endDay){outage.status='مغلق';outage.closedDay=day;}
    const siteRows=siteEconomics(state),dailySummary=economics(state);for(const row of siteRows.filter(item=>item.kind==='gas'&&num(item.fuelContractMWh)>0)){const contract=energy.fuelContracts.find(item=>item.id===row.fuelContractId&&item.status==='ساري');if(!contract)continue;const used=Math.min(num(contract.remainingMWh),num(row.fuelContractMWh));contract.remainingMWh=Math.max(0,num(contract.remainingMWh)-used);contract.usedMWh=num(contract.usedMWh)+used;if(contract.remainingMWh<=.01){contract.status='مستنفد';contract.exhaustedDay=day;}}
    for(const row of siteRows.filter(item=>['solar','wind'].includes(item.kind)&&num(item.gridExportMWh)>0)){const id=`REC-${row.id}-${day}`;if(!energy.renewableCertificates.some(item=>item.id===id))energy.renewableCertificates.unshift({id,siteId:row.id,day,mwh:num(row.gridExportMWh),status:'صادرة'});}energy.renewableCertificates=energy.renewableCertificates.slice(0,1200);
    const F=globalThis.GH_FINANCE_CORE;let debtPrincipalPaid=0,debtPrincipalDeferred=0,constructionInterestCapitalized=0;if(F?.execute){for(const facility of energy.projectFinance.filter(row=>['ساري','متأخر'].includes(row.status)&&num(row.outstanding)>0)){const site=energy.sites.find(row=>row.id===facility.siteId);if(!site)continue;if(!site.commissioned){const last=Math.max(Number(facility.startDay)||0,Number(facility.lastInterestDay)||0),days=Math.max(0,day-last);if(days>0){const opening=num(facility.outstanding),interest=opening*(Math.pow(1+num(facility.rate)/365,days)-1);if(interest>0){F.journal(state,'power',`فوائد مرسملة أثناء إنشاء ${site.name} · يوم ${day}`,[{account:'مشروعات طاقة تحت التنفيذ · فوائد مرسملة',debit:interest},{account:'تمويل مشاريع طاقة',credit:interest}],`PF-CAPINT-${facility.id}-${day}`);F.book(state,'power').debt+=interest;facility.outstanding+=interest;facility.capitalizedInterest=num(facility.capitalizedInterest)+interest;constructionInterestCapitalized+=interest;}facility.lastInterestDay=day;}facility.status='ساري';facility.principalArrears=0;continue;}if(facility.repaymentStartDay===null||!Number.isFinite(Number(facility.repaymentStartDay))){facility.repaymentStartDay=Math.max(day,Math.floor(Number(site.commissionedDay)||day));facility.amortizationAmount=num(facility.outstanding)/Math.max(1,Number(facility.termDays)||1);facility.maturityDay=facility.repaymentStartDay+Math.max(1,Number(facility.termDays)||1);}if(day<=Number(facility.repaymentStartDay))continue;const regular=Math.min(num(facility.outstanding),num(facility.amortizationAmount)||num(facility.outstanding)/Math.max(1,Number(facility.termDays)||1)),due=Math.min(num(facility.outstanding),regular+num(facility.principalArrears));if(due<=0)continue;if(F.operating(state,'power')+1e-8>=due){const paid=F.execute({state},'repay-debt',{company:'power',amount:due,liabilityAccount:'تمويل مشاريع طاقة',lender:facility.lender,note:`سداد أصل تمويل مشروع · ${facility.id}`,ref:`PF-PAY-${facility.id}-${day}`}),amount=num(paid.amount);facility.outstanding=Math.max(0,num(facility.outstanding)-amount);facility.principalArrears=Math.max(0,due-amount);debtPrincipalPaid+=amount;if(facility.outstanding<=.01){facility.outstanding=0;facility.status='مسدد';facility.repaidDay=day;}else facility.status=facility.principalArrears>0?'متأخر':'ساري';}else{facility.principalArrears=due;facility.status='متأخر';facility.overdueSinceDay=Number(facility.overdueSinceDay)||day;facility.daysPastDue=Math.max(1,day-facility.overdueSinceDay+1);debtPrincipalDeferred+=due;}}F.reconcile(state);}
    for(const site of energy.sites){site.debtOutstanding=energy.projectFinance.filter(row=>row.siteId===site.id&&row.status!=='مسدد').reduce((sum,row)=>sum+num(row.outstanding),0);}
    const report={day,...dailySummary,powerExpense:num(dailySummary.powerExpense)+takeOrPayAccrued,takeOrPayAccrued,debtPrincipalPaid,debtPrincipalDeferred,constructionInterestCapitalized,sites:siteRows.map(row=>({siteId:row.id,revenue:row.dailyRevenue,ppaRevenue:row.ppaRevenue,spotRevenue:row.spotRevenue,storageRevenue:row.storageRevenue,capacityRevenue:row.capacityRevenue,balancingRevenue:row.balancingRevenue,recRevenue:row.recRevenue,expense:row.dailyExpense,variableOpex:row.variableOpex,facilityOpex:row.facilityOpex,debtInterest:row.debtInterest,debtPrincipal:row.debtPrincipal,net:row.dailyNet,availability:row.availability,generationMWh:row.generationMWh,fuelContractMWh:row.fuelContractMWh,spotFuelMWh:row.spotFuelMWh}))};energy.dailyHistory.unshift(report);energy.dailyHistory=energy.dailyHistory.slice(0,400);energy.lastProcessedDay=day;return clone(report);
  }
  // Called only through the existing company operations provider. Keep the
  // domain command inside the caller's atomic time/day boundary transaction.
  function onFinancialDay(ctx,p={}){
    const platform=globalThis.GH_COMPANY_PLATFORM,commands=globalThis.GH_DOMAIN_COMMANDS;
    if(!platform?.requireCompany||!commands?.dispatchSystem)throw new Error('company-daily-owner-unavailable');
    const company=platform.requireCompany(ctx.state,ctx.companyId,{registered:true,operational:true,capability:'operations.energy'});
    return commands.dispatchSystem({state:ctx.state},'energy','tick-day',{...p,ownerCompanyId:company.id},{actor:'simulation-scheduler'}).result;
  }
  function execute(ctx,cmd,p={}){const state=ctx.state||ctx;if(cmd==='ensure')return ensure(state);if(cmd==='accept-ppa')return acceptPpa(state,p);if(cmd==='open-regional-office')return openRegionalOffice(state,p);if(cmd==='set-dispatch-policy')return setDispatchPolicy(state,p);if(cmd==='set-grid-connection')return setGridConnection(state,p);if(cmd==='sign-fuel-contract')return signFuelContract(state,p);if(cmd==='schedule-maintenance')return scheduleMaintenance(state,p);if(cmd==='finance-project')return financeProject(state,p);if(cmd==='tick-day')return tickDay(state,p);throw new Error(`Unknown energy command: ${cmd}`);}
  const API={VERSION,DAILY_FINANCIAL_ORDER:200,onFinancialDay,KIND,ensure,economics,siteEconomics,acceptPpa,openRegionalOffice,tickDay,execute};globalThis.GH_ENERGY_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('energy',API);if(globalThis.window&&window!==globalThis)window.GH_ENERGY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
