(()=>{
'use strict';
const VERSION='2.9.1',TYPES=['group','air','sea','road','power','bank','mobility'];
const clone=v=>globalThis.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v));
const num=v=>Math.max(0,Number(v)||0), now=s=>Number(s.simSeconds)||0;
function companyName(s,t){return t==='group'?(s.profile?.name||'المجموعة'):(s.companyRegistry?.[t]?.legalName||({air:'الطيران',sea:'الشحن البحري',road:'النقل البري',power:'الطاقة',bank:'البنك',mobility:'التنقل الذكي'}[t]||t));}
function makeBook(s,t,balance=0){const c=t==='group'?'GH':String(t).toUpperCase();return {type:t,accounts:[{id:`${c}-OPER-001`,name:'الحساب الجاري',currency:'USD',balance:num(balance)},{id:`${c}-RES-002`,name:'حساب الاحتياطي',currency:'USD',balance:0}],ledger:[],taxPayable:0,taxPaid:0,vat:{output:0,input:0,creditCarry:0,periodOutputStart:0,periodInputStart:0},debt:0,lastReconciledAt:now(s)};}
function ensure(s){
 s.finance=s.finance&&typeof s.finance==='object'?s.finance:{};for(const k of ['invoices','payables','receivables','cheques','periods','journalEntries','transfers'])s.finance[k]=Array.isArray(s.finance[k])?s.finance[k]:[];
 s.finance.paymentSequence=Math.max(1,Math.floor(Number(s.finance.paymentSequence)||1));s.finance.invoiceSequence=Math.max(1,Math.floor(Number(s.finance.invoiceSequence)||1));
 s.treasury=s.treasury&&typeof s.treasury==='object'?s.treasury:{accounts:[],ledger:[],paymentQueue:[]};s.treasury.accounts=Array.isArray(s.treasury.accounts)?s.treasury.accounts:[];s.treasury.ledger=Array.isArray(s.treasury.ledger)?s.treasury.ledger:[];
 while(s.treasury.accounts.length<3){const i=s.treasury.accounts.length;s.treasury.accounts.push({id:['GH-OPER-001','GH-RES-002','GH-INV-003'][i],name:['الحساب الجاري','حساب الاحتياطي','الاستثمارات'][i],currency:'USD',balance:0});}
 const had=s.companyFinance&&typeof s.companyFinance==='object'&&!Array.isArray(s.companyFinance)&&Object.keys(s.companyFinance).length>0;s.companyFinance=had?s.companyFinance:{};
 s.companyFinance.group=s.companyFinance.group||makeBook(s,'group');s.companyFinance.group.accounts=s.treasury.accounts;
 for(const t of TYPES){if(!s.companyFinance[t])s.companyFinance[t]=makeBook(s,t);const b=s.companyFinance[t];b.accounts=Array.isArray(b.accounts)&&b.accounts.length?b.accounts:makeBook(s,t).accounts;b.ledger=Array.isArray(b.ledger)?b.ledger:[];for(const a of b.accounts)a.balance=num(a.balance);b.taxPayable=num(b.taxPayable);b.taxPaid=num(b.taxPaid);b.debt=num(b.debt);b.vat=b.vat&&typeof b.vat==='object'?b.vat:{};for(const k of ['output','input','creditCarry','periodOutputStart','periodInputStart'])b.vat[k]=num(b.vat[k]);}
 s.companyFinance.group.accounts=s.treasury.accounts;
 if(!had&&(s.openedCompanies||[]).length){const opened=s.openedCompanies.filter(t=>TYPES.includes(t)&&t!=='group'),src=s.treasury.accounts[0],pool=num(src.balance)*.55,weights=opened.map(t=>[t,Math.max(1,(s.assets||[]).filter(a=>a.type===t).length*2+1)]),sw=weights.reduce((n,x)=>n+x[1],0)||1;let alloc=0;weights.forEach(([t,x],i)=>{const a=i===weights.length-1?Math.max(0,pool-alloc):Math.floor(pool*x/sw);s.companyFinance[t].accounts[0].balance=a;alloc+=a;});src.balance=Math.max(0,num(src.balance)-alloc);}
 s.companyBudgets=s.companyBudgets&&typeof s.companyBudgets==='object'&&!Array.isArray(s.companyBudgets)?s.companyBudgets:{};reconcile(s);return s.companyFinance;
}
function book(s,t='group'){ensure(s);return s.companyFinance[TYPES.includes(t)?t:'group'];}
function operating(s,t='group'){return num(book(s,t).accounts?.[0]?.balance)} function total(s,t='group'){return (book(s,t).accounts||[]).reduce((n,a)=>n+num(a.balance),0)}
function budget(s,t='group'){ensure(s);t=TYPES.includes(t)?t:'group';const period=Math.floor(Math.floor(now(s)/86400)/30);let b=s.companyBudgets[t];if(!b||typeof b!=='object')b=s.companyBudgets[t]={limit:0,spent:0,reserved:0,period,enabled:false,lines:{},spentByLine:{},reservedByLine:{}};for(const k of ['limit','spent','reserved'])b[k]=num(b[k]);b.enabled=!!b.enabled;b.lines=b.lines&&typeof b.lines==='object'?b.lines:{};b.spentByLine=b.spentByLine&&typeof b.spentByLine==='object'?b.spentByLine:{};b.reservedByLine=b.reservedByLine&&typeof b.reservedByLine==='object'?b.reservedByLine:{};for(const k of ['payroll','fuel','maintenance','marketing','insurance','technology','capex','other'])b.lines[k]=num(b.lines[k]);if(Number(b.period)!==period){b.period=period;b.spent=0;b.reserved=0;b.spentByLine={};b.reservedByLine={};}return b;}
function lineFor(note='',method=''){const t=`${note} ${method}`.toLowerCase();if(/راتب|رواتب|payroll/.test(t))return'payroll';if(/وقود|fuel/.test(t))return'fuel';if(/صيان|maintenance|mro/.test(t))return'maintenance';if(/تسويق|marketing/.test(t))return'marketing';if(/تأمين|insurance/.test(t))return'insurance';if(/تقنية|technology|software|نظام/.test(t))return'technology';if(/شراء|إنشاء|بناء|أصل|طائرة|سفينة|شاحن|capex/.test(t))return'capex';return'other';}
function remaining(s,t){const b=budget(s,t);return !b.enabled||b.limit<=0?Infinity:Math.max(0,b.limit-b.spent-b.reserved)} function lineRemaining(s,t,l){const b=budget(s,t),lim=num(b.lines[l]);return !b.enabled||lim<=0?Infinity:Math.max(0,lim-num(b.spentByLine[l])-num(b.reservedByLine[l]));}
function canSpend(s,t,a,l=null){a=Number(a);if(!Number.isFinite(a)||a<0)return false;if(s.godMoney&&s.infiniteMoney)return true;return operating(s,t)>=a&&remaining(s,t)>=a&&(!l||lineRemaining(s,t,l)>=a);}
function consumeBudget(s,t,a,l){const b=budget(s,t);a=num(a);if(b.enabled&&b.limit>0)b.spent+=a;if(l)b.spentByLine[l]=num(b.spentByLine[l])+a;} function reserveBudget(s,t,a,l='other'){a=num(a);if(!canSpend(s,t,a,l))return false;const b=budget(s,t);if(b.enabled&&b.limit>0)b.reserved+=a;b.reservedByLine[l]=num(b.reservedByLine[l])+a;return true;} function consumeReserved(s,t,a,l='other'){const b=budget(s,t),held=Math.min(num(a),num(b.reservedByLine[l]));b.reserved=Math.max(0,b.reserved-held);b.reservedByLine[l]=Math.max(0,num(b.reservedByLine[l])-held);consumeBudget(s,t,a,l);} function releaseReserved(s,t,a,l='other'){const b=budget(s,t),held=Math.min(num(a),num(b.reservedByLine[l]));b.reserved=Math.max(0,b.reserved-held);b.reservedByLine[l]=Math.max(0,num(b.reservedByLine[l])-held);return held;}
function reconcile(s){if(!s.companyFinance)return Number(s.cash)||0;s.cash=Math.max(0,TYPES.reduce((n,t)=>n+((s.companyFinance[t]?.accounts||[]).reduce((x,a)=>x+num(a.balance),0)),0));s.debt=TYPES.reduce((n,t)=>n+num(s.companyFinance[t]?.debt),0);if(s.finance){s.finance.taxPayable=TYPES.reduce((n,t)=>n+num(s.companyFinance[t]?.taxPayable),0);s.finance.taxPaid=TYPES.reduce((n,t)=>n+num(s.companyFinance[t]?.taxPaid),0);}return s.cash;}
function ledger(s,t,e){book(s,t).ledger.unshift(e);s.treasury.ledger.unshift(e);s.treasury.ledger=s.treasury.ledger.slice(0,1200);}
function journal(s,t,desc,lines,ref=''){ensure(s);const rows=(lines||[]).map(x=>({account:String(x.account||''),debit:num(x.debit),credit:num(x.credit)})).filter(x=>x.account&&(x.debit>0||x.credit>0)),dr=rows.reduce((n,x)=>n+x.debit,0),cr=rows.reduce((n,x)=>n+x.credit,0);if(!rows.length||Math.abs(dr-cr)>.02)throw new Error(`قيد غير متوازن: ${desc}`);const row={id:`JE-${String(s.finance.journalEntries.length+1).padStart(8,'0')}`,company:t,description:desc,lines:rows,sourceRef:ref,at:now(s)};s.finance.journalEntries.unshift(row);return row;}
function invoice(s,{kind,amount,note,method='تحويل بنكي',taxable=true,status='مدفوعة',company='group',counterparty='',number=null,dueDay=null}={}){ensure(s);company=TYPES.includes(company)?company:'group';amount=num(amount);const tax=taxable?Math.round(amount*(.15/1.15)):0,subtotal=Math.max(0,amount-tax),doc=number||`${company==='group'?'GH':company.toUpperCase()}-${String(s.finance.invoiceSequence).padStart(6,'0')}`;if(!number)s.finance.invoiceSequence++;const row={number:doc,company,companyName:companyName(s,company),accountId:book(s,company).accounts[0].id,kind,amount,subtotal,tax,total:amount,note:String(note||''),method,status,counterparty:String(counterparty||(kind==='دخل'?'عميل تعاقدي مسجل':'طرف تعاقدي مسجل')),at:now(s)};if(dueDay!=null)row.dueDay=dueDay;s.finance.invoices.unshift(row);const settled=['مدفوعة','مسددة','محصلة'].includes(status);if(!settled)(kind==='دخل'?s.finance.receivables:s.finance.payables).unshift({...row,dueDay:row.dueDay??Math.floor(now(s)/86400)+30});const vat=book(s,company).vat;if(taxable){if(kind==='دخل')vat.output+=tax;else vat.input+=tax;}book(s,company).taxPayable=Math.max(0,vat.output-vat.input-vat.creditCarry);const cash=book(s,company).accounts[0].id,counter=kind==='دخل'?'ذمم مدينة':'ذمم دائنة';journal(s,company,`${doc} · ${note}`,kind==='دخل'?[{account:settled?cash:counter,debit:amount},{account:'إيرادات تشغيلية',credit:subtotal},{account:'ضريبة مخرجات VAT',credit:tax}]:[{account:'مصروف تشغيلي',debit:subtotal},{account:'ضريبة مدخلات VAT',debit:tax},{account:settled?cash:counter,credit:amount}],doc);return row;}
function transfer(s,p){ensure(s);const a=num(p.amount),from=String(p.from),to=String(p.to);if(from===to||!TYPES.includes(from)||!TYPES.includes(to)||a<=0)throw new Error('invalid-transfer');if(operating(s,from)<a)throw new Error('insufficient-cash');const fa=book(s,from).accounts[0],ta=book(s,to).accounts[0];fa.balance-=a;ta.balance+=a;const e={at:now(s),from:fa.id,to:ta.id,amount:a,note:p.note||'تحويل داخلي',kind:'intercompany',company:from,beneficiaryCompany:to};ledger(s,from,e);book(s,to).ledger.unshift(e);journal(s,from,e.note,[{account:'استثمار/ذمم بين شركات المجموعة',debit:a},{account:fa.id,credit:a}],p.ref||'');journal(s,to,e.note,[{account:ta.id,debit:a},{account:'رأس مال/ذمم بين شركات المجموعة',credit:a}],p.ref||'');reconcile(s);return {transferred:true,status:'transferred',from,to,amount:a};}
function bulkTransfer(s,p){const rows=Array.isArray(p.rows)?p.rows:[],seen=new Set(),clean=[];for(const x of rows){const t=String(x.company||''),a=num(x.amount);if(!TYPES.includes(t)||t==='group'||a<=0)continue;if(seen.has(t))throw new Error('duplicate-beneficiary');seen.add(t);clean.push({company:t,amount:a});}if(!clean.length)throw new Error('empty-bulk-transfer');const total=clean.reduce((n,x)=>n+x.amount,0);if(operating(s,'group')<total)throw new Error('insufficient-cash');const batch=p.batchId||`BULK-${Math.floor(now(s))}-${s.finance.transfers.length+1}`;for(const x of clean)transfer(s,{from:'group',to:x.company,amount:x.amount,note:`${p.note||'توزيع رأسمالي'} · ${batch}`,ref:batch});return {total,count:clean.length,batchId:batch};}
function transferReserve(s,p){const toReserve=p.toReserve!==undefined?!!p.toReserve:String(p.direction||'')!=='to-operating',b=book(s,p.company),src=toReserve?b.accounts[0]:b.accounts[1],dst=toReserve?b.accounts[1]:b.accounts[0],a=num(p.amount);if(a<=0)throw new Error('invalid-amount');if(num(src.balance)<a)throw new Error('insufficient-cash');src.balance-=a;dst.balance+=a;const e={at:now(s),from:src.id,to:dst.id,amount:a,note:toReserve?'تحويل إلى الاحتياطي':'إعادة من الاحتياطي',company:p.company};ledger(s,p.company,e);journal(s,p.company,e.note,[{account:dst.id,debit:a},{account:src.id,credit:a}],p.ref||'');reconcile(s);return {amount:a,toReserve,from:src.id,to:dst.id};}
function spend(s,p){const t=p.company||'group',a=num(p.amount),line=p.line||lineFor(p.note,p.method);if(!canSpend(s,t,a,line))throw new Error('insufficient-funds-or-budget');const b=book(s,t);if(!(s.godMoney&&s.infiniteMoney))b.accounts[0].balance-=a;consumeBudget(s,t,a,line);const doc=invoice(s,{kind:'مصروف',amount:a,note:p.note,method:p.method||'تحويل بنكي',taxable:p.taxable!==false,status:p.status||'مدفوعة',company:t,counterparty:p.counterparty||''});if((p.status||'مدفوعة')==='مدفوعة'){const e={at:now(s),from:b.accounts[0].id,to:doc.counterparty,amount:a,note:p.note,company:t,kind:'cash-document',documentNumber:doc.number};ledger(s,t,e);}reconcile(s);return doc;}
function accrue(s,p){const t=p.company||'group',a=num(p.amount),line=p.line||lineFor(p.note,p.method||'قيد مستحق');if(!reserveBudget(s,t,a,line))throw new Error('insufficient-budget');const doc=invoice(s,{kind:'مصروف',amount:a,note:p.note,method:p.method||'قيد مستحق',taxable:p.taxable!==false,status:'مستحقة',company:t,counterparty:p.counterparty||'',dueDay:p.dueDay,number:p.number});doc.budgetLine=line;doc.budgetReserved=a;ledger(s,t,{at:now(s),from:'ذمم دائنة',to:doc.counterparty,amount:a,note:p.note,company:t,kind:'accrual-document',documentNumber:doc.number});return doc;}
function credit(s,p){const t=p.company||'group',a=num(p.amount);book(s,t).accounts[0].balance+=a;const doc=invoice(s,{kind:'دخل',amount:a,note:p.note||'إيراد تشغيلي',method:p.method||'تحويل عميل',taxable:p.taxable!==false,status:'محصلة',company:t,counterparty:p.counterparty||''});const e={at:now(s),from:doc.counterparty,to:book(s,t).accounts[0].id,amount:a,note:p.note||'إيراد',company:t};ledger(s,t,e);reconcile(s);return doc;}
function collectReceivable(s,p){const n=String(p.number||''),item=s.finance.receivables.find(x=>x.number===n);if(!item)throw new Error('receivable-not-found');const t=item.company||'group',a=num(item.total??item.amount),b=book(s,t);b.accounts[0].balance+=a;const inv=s.finance.invoices.find(x=>x.number===n);if(inv){inv.status='محصلة';inv.settledAt=now(s);}s.finance.receivables=s.finance.receivables.filter(x=>x.number!==n);journal(s,t,`تحصيل ${n} · تحويل عميل`,[{account:b.accounts[0].id,debit:a},{account:'ذمم مدينة',credit:a}],n);ledger(s,t,{at:now(s),from:'عميل',to:b.accounts[0].id,amount:a,note:`تحصيل ${n} · تحويل عميل`,company:t});reconcile(s);return {company:t,amount:a};}
function settlePayable(s,p){const n=String(p.number||''),item=s.finance.payables.find(x=>x.number===n);if(!item)throw new Error('payable-not-found');const t=item.company||'group',a=num(item.total??item.amount),inv=s.finance.invoices.find(x=>x.number===n),line=inv?.budgetLine||lineFor(inv?.note||item.note||'',inv?.method||item.method||''),reserved=num(inv?.budgetReserved),b=book(s,t);if(operating(s,t)<a)throw new Error('insufficient-cash');if(!reserved&&!canSpend(s,t,a,line))throw new Error('insufficient-budget');b.accounts[0].balance-=a;if(reserved)consumeReserved(s,t,a,line);else consumeBudget(s,t,a,line);if(inv){inv.status='مسددة';inv.settledAt=now(s);inv.budgetReserved=0;}s.finance.payables=s.finance.payables.filter(x=>x.number!==n);journal(s,t,`سداد ${n} · تحويل بنكي`,[{account:'ذمم دائنة',debit:a},{account:b.accounts[0].id,credit:a}],n);ledger(s,t,{at:now(s),from:b.accounts[0].id,to:inv?.counterparty||item.counterparty||'طرف تعاقدي مسجل',amount:a,note:`سداد ${n} · تحويل بنكي`,company:t});reconcile(s);return {company:t,amount:a};}
function payTaxes(s,p){const t=TYPES.includes(p.company)?p.company:'group',periods=s.finance.periods.filter(x=>(x.company||'group')===t&&x.status==='مستحق'),a=periods.reduce((n,x)=>n+num(x.amount),0),b=book(s,t);if(a<=0)return {company:t,amount:0,count:0};if(operating(s,t)<a)throw new Error('insufficient-cash');b.accounts[0].balance-=a;journal(s,t,'سداد فترات VAT مستحقة',[{account:'ضريبة VAT مستحقة',debit:a},{account:b.accounts[0].id,credit:a}],`VAT-PAY-${Math.floor(now(s)/86400)}-${t}`);ledger(s,t,{at:now(s),from:b.accounts[0].id,to:'هيئة الزكاة والضريبة والجمارك',amount:a,note:'سداد فترات VAT مستحقة · تحويل حكومي',kind:'tax-settlement',company:t});b.taxPaid+=a;periods.forEach(x=>{x.status='مسدد';x.paidAt=now(s)});b.taxPayable=0;reconcile(s);return {company:t,amount:a,count:periods.length};}
function issueCheque(s,p){const t=p.company||'group',a=num(p.amount);if(!canSpend(s,t,a,p.line||'other'))throw new Error('insufficient-funds-or-budget');const id=`${t==='group'?'GH':t.toUpperCase()}-CHQ-${String(s.finance.paymentSequence++).padStart(6,'0')}`,r={id,company:t,companyName:companyName(s,t),accountId:book(s,t).accounts[0].id,amount:a,note:p.note||'',beneficiary:p.beneficiary||'طرف تعاقدي مسجل',dueDay:p.dueDay??Math.floor(now(s)/86400),status:'صادر',issuedAt:now(s),invoiceNumber:p.invoiceNumber||'',requestRef:p.requestRef||null,type:p.type||'شيك مصدق'};s.finance.cheques.unshift(r);return r;}
function chequeResult(c,settled,reason){return {id:c.id,settled,status:settled?'settled':'bounced',reason,company:c.company,amount:c.amount,invoiceNumber:c.invoiceNumber||null,requestRef:c.requestRef||null};}
function settleCheque(s,p){const c=s.finance.cheques.find(x=>x.id===p.id);if(!c)throw new Error('cheque-not-found');if(c.status==='مصروف')return chequeResult(c,true,'already-settled');const t=c.company||'group',a=num(c.amount),inv=c.invoiceNumber?s.finance.invoices.find(x=>x.number===c.invoiceNumber):null,payable=c.invoiceNumber?s.finance.payables.find(x=>x.number===c.invoiceNumber):null,line=p.line||inv?.budgetLine||lineFor(c.note,'شيك'),reserved=num(inv?.budgetReserved),b=book(s,t);if(operating(s,t)<a||(!reserved&&!canSpend(s,t,a,line))){c.status='مرتجع';c.returnedAt=now(s);if(inv)inv.status='شيك مرتجع';return chequeResult(c,false,'insufficient-funds-or-budget');}b.accounts[0].balance-=a;if(reserved)consumeReserved(s,t,a,line);else consumeBudget(s,t,a,line);c.status='مصروف';c.clearedAt=now(s);if(payable){s.finance.payables=s.finance.payables.filter(x=>x.number!==c.invoiceNumber);if(inv){inv.status='مسددة';inv.settledAt=now(s);inv.budgetReserved=0;}journal(s,t,`صرف ${c.id} · تسوية ${c.invoiceNumber}`,[{account:'ذمم دائنة',debit:a},{account:b.accounts[0].id,credit:a}],c.id);}else journal(s,t,`صرف ${c.id} · ${c.note}`,[{account:'مصروف تشغيلي',debit:a},{account:b.accounts[0].id,credit:a}],c.id);ledger(s,t,{at:now(s),from:b.accounts[0].id,to:c.beneficiary,amount:a,note:`صرف ${c.id}`,company:t});reconcile(s);return chequeResult(c,true,'settled');}
function founderInvestment(s,p){const t=TYPES.includes(p.company)?p.company:'group',a=num(p.amount);if(a<=0)throw new Error('invalid-amount');const b=book(s,t),founder=s.profile?.founder||'المؤسس',id=p.ref||`FND-${Math.floor(now(s))}-${s.finance.transfers.length+1}`;if(s.finance.transfers.some(x=>x.id===id)||s.treasury.ledger.some(x=>x.reference===id))return {ref:id,amount:0,company:t,idempotent:true};b.accounts[0].balance+=a;const transfer={id,reference:id,at:now(s),kind:'founder-investment',label:'حوالة استثمار واردة',from:`المستثمر · ${founder}`,to:b.accounts[0].id,toAccount:b.accounts[0].id,amount:a,company:t,beneficiaryCompany:t,status:'منفذة',note:p.note||'استثمار المؤسس'};s.finance.transfers.unshift({...transfer,to:companyName(s,t)});ledger(s,t,transfer);journal(s,t,`${id} · استثمار المؤسس`,[{account:b.accounts[0].id,debit:a},{account:'حقوق ملكية المؤسس',credit:a}],id);reconcile(s);return {ref:id,amount:a,company:t};}
function founderWithdrawal(s,p){const t=TYPES.includes(p.company)?p.company:'group',requested=num(p.amount),b=book(s,t),a=Math.min(requested,operating(s,t));if(a<=0)throw new Error('insufficient-cash');const founder=s.profile?.founder||'المؤسس',id=p.ref||`FND-WD-${Math.floor(now(s))}-${s.finance.transfers.length+1}`;if(s.finance.transfers.some(x=>x.id===id)||s.treasury.ledger.some(x=>x.reference===id))return {ref:id,amount:0,company:t,idempotent:true};b.accounts[0].balance-=a;const transfer={id,reference:id,at:now(s),kind:'founder-withdrawal',label:'سحب رأس مال للمؤسس',from:b.accounts[0].id,to:`المستثمر · ${founder}`,amount:a,company:t,status:'منفذة',note:p.note||'تسوية رأسمالية'};s.finance.transfers.unshift({...transfer,from:companyName(s,t),to:founder});ledger(s,t,transfer);journal(s,t,`${id} · سحب رأسمالي للمؤسس`,[{account:'حقوق ملكية المؤسس',debit:a},{account:b.accounts[0].id,credit:a}],id);reconcile(s);return {ref:id,amount:a,company:t};}

function refreshIdentity(s,p){const t=TYPES.includes(p.company)?p.company:'group',name=companyName(s,t);for(const bucket of [s.finance?.invoices,s.finance?.cheques,s.finance?.payables,s.finance?.receivables,s.finance?.periods])for(const doc of (bucket||[])){if((doc.company||'group')===t){doc.company=t;doc.companyName=name;delete doc.logo;delete doc.companyLogo;delete doc.issuerLogo;}}for(const entry of (s.treasury?.ledger||[])){if(entry.company===t)entry.companyName=name;if(entry.beneficiaryCompany===t)entry.beneficiaryName=name;}return name;}
function raiseDebt(s,p){const t=TYPES.includes(p.company)?p.company:'group',a=num(p.amount);if(a<=0)throw new Error('invalid-amount');const b=book(s,t),id=p.ref||`DEBT-${Math.floor(now(s))}-${b.ledger.length+1}`;b.accounts[0].balance+=a;b.debt=num(b.debt)+a;journal(s,t,p.note||'تمويل دين',[{account:b.accounts[0].id,debit:a},{account:p.liabilityAccount||'تسهيلات ائتمانية مستحقة',credit:a}],id);ledger(s,t,{at:now(s),from:p.lender||'جهة تمويل',to:b.accounts[0].id,amount:a,note:p.note||'تمويل دين',company:t,kind:'debt-financing',reference:id});reconcile(s);return {ref:id,amount:a,debt:b.debt};}
function repayDebt(s,p){const t=TYPES.includes(p.company)?p.company:'group',b=book(s,t),a=Math.min(num(p.amount),num(b.debt));if(a<=0)return {amount:0,debt:num(b.debt)};if(operating(s,t)<a)throw new Error('insufficient-cash');b.accounts[0].balance-=a;b.debt=Math.max(0,num(b.debt)-a);journal(s,t,p.note||'سداد أصل دين',[{account:p.liabilityAccount||'تسهيلات ائتمانية مستحقة',debit:a},{account:b.accounts[0].id,credit:a}],p.ref||`DEBT-PAY-${Math.floor(now(s))}`);ledger(s,t,{at:now(s),from:b.accounts[0].id,to:p.lender||'جهة تمويل',amount:a,note:p.note||'سداد أصل دين',company:t,kind:'debt-repayment'});reconcile(s);return {amount:a,debt:b.debt};}
function raiseEquity(s,p){const t=TYPES.includes(p.company)?p.company:'group',a=num(p.amount);if(a<=0)throw new Error('invalid-amount');const b=book(s,t),id=p.ref||`EQUITY-${Math.floor(now(s))}-${s.finance.transfers.length+1}`;b.accounts[0].balance+=a;journal(s,t,p.note||'زيادة رأس مال',[{account:b.accounts[0].id,debit:a},{account:p.equityAccount||'رأس مال وعلاوة إصدار',credit:a}],id);ledger(s,t,{at:now(s),from:p.source||'مستثمرون',to:b.accounts[0].id,amount:a,note:p.note||'زيادة رأس مال',company:t,kind:'equity-financing',reference:id});reconcile(s);return {ref:id,amount:a};}

function zeroSectorMap(){return {air:0,sea:0,road:0,power:0,bank:0,mobility:0};}
function consumeTripAccruals(s){
  ensure(s);
  const result={
    profit:{...zeroSectorMap(),...(s.tripProfitAccrued||{})},
    revenue:{...zeroSectorMap(),...(s.tripRevenueAccrued||{})},
    fuel:{...zeroSectorMap(),...(s.tripFuelAccrued||{})},
    maintenance:{...zeroSectorMap(),...(s.tripMaintenanceAccrued||{})},
    count:{...zeroSectorMap(),...(s.tripCountAccrued||{})}
  };
  s.tripProfitAccrued=zeroSectorMap();s.tripRevenueAccrued=zeroSectorMap();s.tripFuelAccrued=zeroSectorMap();s.tripMaintenanceAccrued=zeroSectorMap();s.tripCountAccrued=zeroSectorMap();
  return result;
}
function recordDailyClose(s,p){
  const sectors={...zeroSectorMap(),...(p.sectors||{})},net=Number(p.net)||0;
  s.lastClosedSectorProfit=sectors;s.lastClosedProfit=net;s.sectorProfitToday=zeroSectorMap();s.todayProfit=0;
  return {sectors:{...sectors},net};
}

function applySimulationJournal(s,p={}){
  ensure(s);const j=p.journal&&typeof p.journal==='object'?p.journal:{},types=['air','sea','road','power','bank','mobility'];
  s.todayProfit=(Number(s.todayProfit)||0)+(Number(j.todayProfit)||0);
  s.sectorProfitToday=s.sectorProfitToday&&typeof s.sectorProfitToday==='object'?s.sectorProfitToday:zeroSectorMap();
  for(const k of ['tripProfitAccrued','tripRevenueAccrued','tripFuelAccrued','tripMaintenanceAccrued','tripCountAccrued'])s[k]=s[k]&&typeof s[k]==='object'?s[k]:zeroSectorMap();
  for(const type of types){
    s.sectorProfitToday[type]=(Number(s.sectorProfitToday[type])||0)+(Number(j.sectorProfit?.[type])||0);
    s.tripProfitAccrued[type]=(Number(s.tripProfitAccrued[type])||0)+(Number(j.tripProfit?.[type])||0);
    s.tripRevenueAccrued[type]=(Number(s.tripRevenueAccrued[type])||0)+(Number(j.tripRevenue?.[type])||0);
    s.tripFuelAccrued[type]=(Number(s.tripFuelAccrued[type])||0)+(Number(j.tripFuel?.[type])||0);
    s.tripMaintenanceAccrued[type]=(Number(s.tripMaintenanceAccrued[type])||0)+(Number(j.tripMaintenance?.[type])||0);
    s.tripCountAccrued[type]=(Number(s.tripCountAccrued[type])||0)+(Number(j.tripCount?.[type])||0);
    const cash=Number(j.cash?.[type])||0;if(cash)book(s,type).accounts[0].balance+=cash;
  }
  reconcile(s);return {todayProfit:Number(s.todayProfit)||0,cash:Number(s.cash)||0};
}
function initializeCapital(s,p){
 const capital=Number(p.capital);if(!Number.isFinite(capital)||capital<=0)throw new Error('invalid-initial-capital');
 if(s.finance?.foundingCapital)throw new Error('capital-already-initialized');
 const ref=String(p.ref||'');if(!ref)throw new Error('founding-capital-reference-required');
 s.companyFinance={};s.companyBudgets={};s.treasury={accounts:[],ledger:[],paymentQueue:[]};
 s.finance={invoices:[],cheques:[],payables:[],receivables:[],periods:[],journalEntries:[],transfers:[],paymentSequence:1,invoiceSequence:1,taxPayable:0,taxPaid:0};
 ensure(s);s.advanced=s.advanced||{};if(s.advanced.treasury)s.advanced.treasury.liquidityBuffer=0;
 const result=founderInvestment(s,{company:'group',amount:capital,ref,note:'رأس المال عند تأسيس المجموعة'});
 s.finance.foundingCapital={ref,amount:capital};return result;
}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);switch(cmd){case'initialize-capital':return initializeCapital(s,p);case'ensure':return ensure(s);case'spend':return spend(s,p);case'accrue-expense':return accrue(s,p);case'credit':return credit(s,p);case'transfer':return transfer(s,p);case'bulk-transfer':return bulkTransfer(s,p);case'transfer-reserve':return transferReserve(s,p);case'collect-receivable':return collectReceivable(s,p);case'settle-payable':return settlePayable(s,p);case'pay-taxes':return payTaxes(s,p);case'issue-cheque':return issueCheque(s,p);case'settle-cheque':return settleCheque(s,p);case'founder-investment':return founderInvestment(s,p);case'founder-withdrawal':return founderWithdrawal(s,p);case'set-budget':{const b=budget(s,p.company);b.limit=num(p.limit);b.enabled=b.limit>0;if(p.lines)b.lines={...b.lines,...p.lines};if(p.resetSpent){b.spent=0;b.reserved=0;b.spentByLine={};b.reservedByLine={};}return clone(b);}case'reset-budget':{const b=budget(s,p.company);b.limit=0;b.spent=0;b.reserved=0;b.enabled=false;b.lines={};b.spentByLine={};b.reservedByLine={};return clone(b);}case'refresh-identity':return refreshIdentity(s,p);case'raise-debt':return raiseDebt(s,p);case'raise-equity':return raiseEquity(s,p);case'repay-debt':return repayDebt(s,p);case'set-debt':book(s,p.company).debt=num(p.amount);reconcile(s);return true;case'consume-trip-accruals':return consumeTripAccruals(s);case'apply-simulation-journal':return applySimulationJournal(s,p);case'record-daily-close':return recordDailyClose(s,p);case'close-vat-period':{const day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(s)/86400))),month=Math.max(1,Math.ceil(day/30)),rows=[];for(const t of TYPES){const b=book(s,t),vat=b.vat||(b.vat={output:0,input:0,creditCarry:0,periodOutputStart:0,periodInputStart:0}),deltaOutput=Math.max(0,num(vat.output)-num(vat.periodOutputStart)),deltaInput=Math.max(0,num(vat.input)-num(vat.periodInputStart)),openingCredit=num(vat.creditCarry),net=deltaOutput-deltaInput-openingCredit,periodTax=Math.max(0,net),closingCredit=Math.max(0,-net);vat.creditCarry=closingCredit;vat.periodOutputStart=num(vat.output);vat.periodInputStart=num(vat.input);const row={id:`TAX-${t}-${day}`,company:t,companyName:companyName(s,t),period:`شهر المحاكاة ${month}`,outputVAT:deltaOutput,inputVAT:deltaInput,openingCredit,closingCredit,amount:periodTax,dueDay:day+15,status:periodTax>0?'مستحق':'صفر'};s.finance.periods.unshift(row);b.taxPayable=periodTax;rows.push(row);}s.finance.taxPayable=TYPES.reduce((n,t)=>n+num(book(s,t).taxPayable),0);s.finance.taxPaid=TYPES.reduce((n,t)=>n+num(book(s,t).taxPaid),0);reconcile(s);return rows;}default:throw new Error(`Unknown finance command: ${cmd}`)}}
const API={VERSION,TYPES,ensure,makeBook,book,operating,total,budget,remaining,lineRemaining,lineFor,canSpend,consumeBudget,reserveBudget,consumeReserved,releaseReserved,reconcile,journal,invoice,execute};globalThis.GH_FINANCE_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('finance',API);if(globalThis.window&&window!==globalThis)window.GH_FINANCE_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
