(()=>{'use strict';
const VERSION='2.9.1',num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function ensure(s){s.advanced=s.advanced||{};s.advanced.board=s.advanced.board||{meetings:[],committees:{audit:70,risk:70,remuneration:70,investment:70}};s.advanced.board.meetings=Array.isArray(s.advanced.board.meetings)?s.advanced.board.meetings:[];s.advanced.insurance=s.advanced.insurance||{policies:{},claims:[],annualPremium:0};s.advanced.insurance.claims=Array.isArray(s.advanced.insurance.claims)?s.advanced.insurance.claims:[];s.advanced.audit=s.advanced.audit||{findings:[],lastRun:0,score:80};s.advanced.legal=s.advanced.legal||{};s.advanced.cyber=s.advanced.cyber||{};s.advanced.safety=s.advanced.safety||{};s.advanced.researchPrograms=s.advanced.researchPrograms||{};s.esg=s.esg||{environment:50,social:50,governance:50};s.sustainability=s.sustainability||{targetYear:2035,renewableShare:12,safShare:0,shorePower:0,electricRoadShare:0,circularity:42,waterScore:55,supplyChainScore:60,disclosure:68,carbonIntensity:100,programs:{}};s.sustainability.programs=s.sustainability.programs||{};s.research=s.research&&typeof s.research==='object'?s.research:{};return s;}
function spend(s,amount,note,company='group'){if(num(amount)<=0)return true;globalThis.GH_FINANCE_CORE?.execute?.({state:s},'spend',{company,amount,note,method:'تحويل بنكي',line:'other'});return true;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);
 if(cmd==='board-meeting'){spend(s,p.cost||120000,'اجتماع مجلس الإدارة');const risks=(s.realism?.risk?.register||[]),pending=(s.advanced.ai?.requests||[]).filter(r=>r.status==='بانتظار التفويض'),agenda=['الأداء المالي','السيولة'];if(risks.length)agenda.push(`المخاطر (${risks.length})`);if(pending.length)agenda.push(`طلبات التفويض (${pending.length})`);if((s.realism?.banking?.cet1Headroom||0)<2)agenda.push('رأس مال البنك');if((s.realism?.aviation?.maintenanceDue||0)>0)agenda.push('جاهزية الأسطول');const meeting={id:p.id||`BRD-${Math.floor(now(s))}-${s.advanced.board.meetings.length+1}`,at:now(s),result:'اكتمل النصاب وسجل المحضر.',agenda,riskSnapshot:risks.slice(0,5).map(x=>({id:x.id,severity:x.severity,title:x.title})),pendingApprovals:pending.length};s.advanced.board.meetings.unshift(meeting);return meeting;}
 if(cmd==='board-decision'){s.governance=s.governance||{};s.governance.boardDecision=p.status;s.realism=s.realism||{};s.realism.board=s.realism.board||{meetings:[],resolutions:[]};s.realism.board.resolutions=Array.isArray(s.realism.board.resolutions)?s.realism.board.resolutions:[];const risks=s.realism?.risk?.register||[],high=risks.filter(x=>['high','critical'].includes(x.severity)).length,pending=(s.advanced?.ai?.requests||[]).filter(r=>r.status==='بانتظار التفويض').length,row={id:p.id||`BRD-RES-${Math.floor(now(s))}-${s.realism.board.resolutions.length+1}`,at:now(s),status:p.status,highRisks:high,pendingApprovals:pending,conditions:[]};if(p.status==='approved'){if(high)row.conditions.push(`إغلاق/تخفيف ${high} مخاطر مرتفعة قبل سحب رأسمالي جديد`);if(pending>5)row.conditions.push('تخفيض تراكم طلبات الاعتماد');if(s.profile)s.profile.reputation=clamp(num(s.profile.reputation)+(high?0:2),0,100);}else row.conditions.push(...risks.slice(0,3).map(x=>x.title));s.realism.board.resolutions.unshift(row);s.realism.board.resolutions=s.realism.board.resolutions.slice(0,50);return row;}
 if(cmd==='insurance-policy'){const sector=String(p.sector||'');if(!sector)throw new Error('sector-required');s.insurancePolicies=Array.isArray(s.insurancePolicies)?s.insurancePolicies:[];if(s.insurancePolicies.includes(sector))throw new Error('policy-exists');const premium=num(p.premium);spend(s,premium,`وثيقة تأمين ${sector}`,sector);s.insurancePolicies.push(sector);s.advanced.insurance.annualPremium=num(s.advanced.insurance.annualPremium)+premium;s.advanced.insurance.policies=s.advanced.insurance.policies||{};s.advanced.insurance.policies[sector]={premium,inceptionAt:now(s),renewalIndex:num(p.renewalIndex||100),deductiblePct:Number(p.deductiblePct??.02),coveragePct:Number(p.coveragePct??.92)};return s.advanced.insurance.policies[sector];}
 if(cmd==='insurance-claim'){const sector=p.sector,policy=s.advanced.insurance.policies?.[sector]||{},assets=(s.assets||[]).filter(a=>a.type===sector),subject=assets.slice().sort((a,b)=>(Number(a.condition)||100)-(Number(b.condition)||100))[0],exposure=Math.max(250000,Number(subject?.purchasePrice)||assets.reduce((n,a)=>n+num(a.purchasePrice),0)*.1),condition=Number(subject?.condition)||85,grossLoss=Math.round(exposure*Math.min(.35,Math.max(.04,(100-condition)/100+.05))),deductible=Math.round(grossLoss*(Number(policy.deductiblePct)||.02)),covered=Math.max(0,Math.round((grossLoss-deductible)*(Number(policy.coveragePct)||.92))),reserve=Math.round(covered*.85),claim={id:p.id||`CLM-${Math.floor(now(s))}-${s.advanced.insurance.claims.length+1}`,sector,assetId:subject?.id||null,assetName:subject?.name||null,status:'قيد الفحص',grossLoss,deductible,covered,reserve,openedAt:now(s)};s.advanced.insurance.claims.unshift(claim);return claim;}
 if(cmd==='research-fund'){const id=p.project;if(!Object.prototype.hasOwnProperty.call(s.research,id))throw new Error('unknown-research');spend(s,p.cost||0,`تمويل بحث ${id}`);const meta=s.advanced.researchPrograms[id]||(s.advanced.researchPrograms[id]={spent:0,rounds:0,history:[],status:'بحث'});meta.spent+=num(p.cost);meta.rounds++;const before=Number(s.research[id])||0;s.research[id]=Math.min(100,before+Math.max(1,Number(p.progress)||25));meta.history.unshift({at:now(s),cost:num(p.cost),from:before,to:s.research[id]});meta.status=s.research[id]>=100?'تشغيلي':'بحث';return {project:id,progress:s.research[id]};}
 if(cmd==='tick-sustainability'){
   const day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(s)/86400))),su=s.sustainability,programs=su.programs||{};
   for(const [id,program] of Object.entries(programs)){
     if(!program||program.status==='مكتمل')continue;const started=Math.max(0,Number(program.at)||0),elapsedDays=Math.max(0,Math.floor((now(s)-started)/86400)),maturity=clamp((Number(program.maturity)||0)+Math.max(0,elapsedDays-(Number(program.lastMaturityDay)||0))*4,0,100);program.maturity=maturity;program.lastMaturityDay=elapsedDays;const factor=maturity/100;
     if(id==='fleet')su.electricRoadShare=Math.max(num(su.electricRoadShare),12*factor);if(id==='saf')su.safShare=Math.max(num(su.safShare),15*factor);if(id==='shore')su.shorePower=Math.max(num(su.shorePower),25*factor);if(id==='renewable')su.renewableShare=Math.max(num(su.renewableShare),18*factor);if(id==='circular')su.circularity=Math.max(num(su.circularity),14*factor);if(id==='supply')su.supplyChainScore=Math.max(num(su.supplyChainScore),15*factor);if(id==='water')su.waterScore=Math.max(num(su.waterScore),18*factor);if(id==='disclosure')su.disclosure=Math.max(num(su.disclosure),18*factor);program.status=maturity>=100?'مكتمل':'قيد التنفيذ';
   }
   const envBase=46,socialBase=58,govBase=62;s.esg.environment=clamp(envBase+num(su.electricRoadShare)*.05+num(su.safShare)*.08+num(su.shorePower)*.04+num(su.renewableShare)*.08+num(su.circularity)*.04+num(su.waterScore)*.03,0,100);s.esg.social=clamp(socialBase+num(su.supplyChainScore)*.04,0,100);s.esg.governance=clamp(govBase+num(su.disclosure)*.08+num(su.supplyChainScore)*.03,0,100);su.lastTickDay=day;return {esg:{...s.esg},sustainability:{...su}};
 }
 if(cmd==='esg-review'){const su=s.sustainability,priorities=[],road=(s.assets||[]).filter(x=>x.type==='road'),dirtyRoad=road.filter(x=>!x.specs?.electric&&!x.specs?.hydrogen).length;if(dirtyRoad>road.length*.55)priorities.push('تحديث الأسطول البري منخفض الانبعاثات');if((su.safShare||0)<15&&(s.assets||[]).some(x=>x.type==='air'))priorities.push('رفع استخدام SAF للطيران');if((su.shorePower||0)<30&&(s.assets||[]).some(x=>x.type==='sea'))priorities.push('كهرباء الموانئ');if((su.renewableShare||0)<35)priorities.push('طاقة متجددة للمرافق');if((su.supplyChainScore||0)<75)priorities.push('تقييم الموردين وسلسلة التوريد');su.lastReviewDay=Math.floor(now(s)/86400);return priorities;}
 if(cmd==='esg-program'){const id=p.id;if(s.sustainability.programs[id])throw new Error('program-exists');spend(s,p.cost||0,`برنامج استدامة ${id}`,p.company||'group');s.sustainability.programs[id]={id,at:now(s),cost:num(p.cost),company:p.company||'group',status:'قيد التنفيذ',maturity:0,lastMaturityDay:0,title:p.title||id};return s.sustainability.programs[id];}
 if(cmd==='esg-invest'){s.esg.environment=clamp(num(s.esg.environment)+num(p.environment||4),0,100);s.esg.social=clamp(num(s.esg.social)+num(p.social||2),0,100);s.esg.governance=clamp(num(s.esg.governance)+num(p.governance||1),0,100);if(s.profile)s.profile.reputation=clamp(num(s.profile.reputation)+1,0,100);return {...s.esg};}
 if(cmd==='audit-run'){spend(s,p.cost||350000,'تدقيق داخلي');const report=globalThis.GH_INTEGRITY_CORE?.check?.(s)||{counts:{critical:0,warning:0,total:0},issues:[]};s.advanced.audit.lastRun=now(s);s.advanced.audit.findings=report.counts?.total||0;s.advanced.audit.score=Math.max(45,Math.min(99,100-(report.counts?.critical||0)*12-(report.counts?.warning||0)*3));s.advanced.audit.lastReport={at:now(s),counts:report.counts,top:(report.issues||[]).slice(0,8).map(x=>({id:x.id,severity:x.severity,title:x.title,domain:x.domain}))};return s.advanced.audit;}
 if(cmd==='legal-review'){spend(s,p.cost||420000,'مراجعة قانونية');const bases=[...(s.globalBases||[]),...(s.customHubs||[])],missing=bases.filter(f=>!f.country&&!f.countryCode).length,contracts=(s.acceptedContracts||[]).length,openCases=num(s.advanced.legal.openCases);s.advanced.legal.lastReview=now(s);s.advanced.legal.licenses=Math.max(num(s.advanced.legal.licenses),bases.length);s.advanced.legal.compliance=Math.max(40,Math.min(99,96-missing*5-openCases*3+(contracts?1:0)));s.advanced.legal.lastReviewDetail={facilities:bases.length,missingJurisdiction:missing,contracts,openCases};return s.advanced.legal;}
 if(cmd==='cyber-drill'){spend(s,p.cost||650000,'تمرين استجابة سيبرانية');const runtime=(s.diagnostics?.events||[]).filter(e=>['ERROR','UNHANDLED_REJECTION','CONSOLE_ERROR'].includes(e.type)).slice(0,50).length,coverage=Math.min(100,num(s.advanced.cyber.coverage)),rto=Math.max(8,90-coverage*.65+runtime*2);s.advanced.cyber.lastDrill=now(s);s.advanced.cyber.rtoMinutes=Math.round(rto);s.advanced.cyber.recoveryScore=clamp(100-rto*.55,0,100);s.advanced.cyber.score=clamp(78+coverage*.18-runtime*.8,45,99);s.advanced.cyber.coverage=Math.min(100,coverage+Math.max(1,Math.round((100-coverage)*.08)));return s.advanced.cyber;}
 if(cmd==='safety-audit'){spend(s,p.cost||500000,'تدقيق السلامة HSE');const assets=s.assets||[],weak=assets.filter(a=>Number(a.condition)<70).length,aog=assets.filter(a=>Number(a.condition)<60).length,maint=num(s.realism?.aviation?.maintenanceDue);s.advanced.safety.lastAudit=now(s);s.advanced.safety.openFindings=weak+maint;s.advanced.safety.score=clamp(98-weak*1.8-aog*3-maint*.8-num(s.advanced.safety.incidents)*2,45,99);return {weak,aog,maintenanceDue:maint,...s.advanced.safety};}
 if(cmd==='treasury-hedge'){spend(s,p.cost||600000,'برنامج تحوط الخزينة');s.advanced.treasury=s.advanced.treasury||{};s.advanced.treasury.hedgeRatio=Math.min(90,num(s.advanced.treasury.hedgeRatio)+10);return s.advanced.treasury.hedgeRatio;}
 if(cmd==='treasury-stress'){s.advanced.treasury=s.advanced.treasury||{};const loss=num(s.advanced.treasury.fxExposure)*.08+num(s.debt)*.02;s.advanced.treasury.lastStress=`خسارة ضغط ${loss}؛ نسبة التغطية ${Math.round(num(s.cash)/Math.max(1,loss)*100)}%.`;return {loss,coverage:Math.round(num(s.cash)/Math.max(1,loss)*100)};}
 throw new Error(`Unknown governance command: ${cmd}`);
}
const API={VERSION,ensure,execute};globalThis.GH_GOVERNANCE_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('governance',API);if(globalThis.window&&window!==globalThis)window.GH_GOVERNANCE_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
