(()=>{'use strict';
const VERSION='3.0.0',num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const fleetData=()=>{const api=globalThis.GH_FLEET_DATA||(typeof require==='function'?require('./fleet-access-core.js'):null);if(!api)throw new Error('fleet-data-access-unavailable');return api;};
function assetOwner(a){return String(a?.ownerCompanyId||a?.companyId||a?.company||globalThis.GH_COMPANY_PLATFORM?.ownerForLegacyAssetMode?.(a?.assetMode||a?.type)||'').trim();}
function companyFor(s,p={}){const requested=String(p.ownerCompanyId||p.companyId||p.company||p.sector||'').trim();if(!requested)throw new Error('company-id-required');const platform=globalThis.GH_COMPANY_PLATFORM;if(platform?.requireCompany){platform.requireCompany(s,requested,{registered:true});return requested;}return requested;}
function ensure(s){s.advanced=s.advanced||{};s.advanced.insurance=s.advanced.insurance||{policies:{},claims:[],annualPremium:0};s.advanced.insurance.claims=Array.isArray(s.advanced.insurance.claims)?s.advanced.insurance.claims:[];s.advanced.cyber=s.advanced.cyber||{};s.advanced.safety=s.advanced.safety||{};s.advanced.researchPrograms=s.advanced.researchPrograms||{};s.esg=s.esg||{environment:50,social:50,governance:50};s.sustainability=s.sustainability||{targetYear:2035,renewableShare:12,safShare:0,shorePower:0,electricRoadShare:0,circularity:42,waterScore:55,supplyChainScore:60,disclosure:68,carbonIntensity:100,programs:{}};s.sustainability.programs=s.sustainability.programs||{};s.research=s.research&&typeof s.research==='object'?s.research:{};return s;}
function spend(s,amount,note,company='group'){if(num(amount)<=0)return true;globalThis.GH_FINANCE_CORE?.execute?.({state:s},'spend',{company,amount,note,method:'تحويل بنكي',line:'other'});return true;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);
 if(cmd==='research-fund'){const id=p.project;if(!Object.prototype.hasOwnProperty.call(s.research,id))throw new Error('unknown-research');spend(s,p.cost||0,`تمويل بحث ${id}`);const meta=s.advanced.researchPrograms[id]||(s.advanced.researchPrograms[id]={spent:0,rounds:0,history:[],status:'بحث'});meta.spent+=num(p.cost);meta.rounds++;const before=Number(s.research[id])||0;s.research[id]=Math.min(100,before+Math.max(1,Number(p.progress)||25));meta.history.unshift({at:now(s),cost:num(p.cost),from:before,to:s.research[id]});meta.status=s.research[id]>=100?'تشغيلي':'بحث';return {project:id,progress:s.research[id]};}
 if(cmd==='tick-sustainability'){
   const day=Math.max(0,Math.floor(Number(p.day)||Math.floor(now(s)/86400))),su=s.sustainability,programs=su.programs||{};
   for(const [id,program] of Object.entries(programs)){
     if(!program||program.status==='مكتمل')continue;const started=Math.max(0,Number(program.at)||0),elapsedDays=Math.max(0,Math.floor((now(s)-started)/86400)),maturity=clamp((Number(program.maturity)||0)+Math.max(0,elapsedDays-(Number(program.lastMaturityDay)||0))*4,0,100);program.maturity=maturity;program.lastMaturityDay=elapsedDays;const factor=maturity/100;
     if(id==='fleet')su.electricRoadShare=Math.max(num(su.electricRoadShare),12*factor);if(id==='saf')su.safShare=Math.max(num(su.safShare),15*factor);if(id==='shore')su.shorePower=Math.max(num(su.shorePower),25*factor);if(id==='renewable')su.renewableShare=Math.max(num(su.renewableShare),18*factor);if(id==='circular')su.circularity=Math.max(num(su.circularity),14*factor);if(id==='supply')su.supplyChainScore=Math.max(num(su.supplyChainScore),15*factor);if(id==='water')su.waterScore=Math.max(num(su.waterScore),18*factor);if(id==='disclosure')su.disclosure=Math.max(num(su.disclosure),18*factor);program.status=maturity>=100?'مكتمل':'قيد التنفيذ';
   }
   const envBase=46,socialBase=58,govBase=62;s.esg.environment=clamp(envBase+num(su.electricRoadShare)*.05+num(su.safShare)*.08+num(su.shorePower)*.04+num(su.renewableShare)*.08+num(su.circularity)*.04+num(su.waterScore)*.03,0,100);s.esg.social=clamp(socialBase+num(su.supplyChainScore)*.04,0,100);s.esg.governance=clamp(govBase+num(su.disclosure)*.08+num(su.supplyChainScore)*.03,0,100);su.lastTickDay=day;return {esg:{...s.esg},sustainability:{...su}};
 }
 if(cmd==='esg-program'){const id=p.id;if(s.sustainability.programs[id])throw new Error('program-exists');spend(s,p.cost||0,`برنامج استدامة ${id}`,p.company||'group');s.sustainability.programs[id]={id,at:now(s),cost:num(p.cost),company:p.company||'group',status:'قيد التنفيذ',maturity:0,lastMaturityDay:0,title:p.title||id};return s.sustainability.programs[id];}
 if(cmd==='cyber-drill'){spend(s,p.cost||650000,'تمرين استجابة سيبرانية');const runtime=(s.diagnostics?.events||[]).filter(e=>['ERROR','UNHANDLED_REJECTION','CONSOLE_ERROR'].includes(e.type)).slice(0,50).length,coverage=Math.min(100,num(s.advanced.cyber.coverage)),rto=Math.max(8,90-coverage*.65+runtime*2);s.advanced.cyber.lastDrill=now(s);s.advanced.cyber.rtoMinutes=Math.round(rto);s.advanced.cyber.recoveryScore=clamp(100-rto*.55,0,100);s.advanced.cyber.score=clamp(78+coverage*.18-runtime*.8,45,99);s.advanced.cyber.coverage=Math.min(100,coverage+Math.max(1,Math.round((100-coverage)*.08)));return s.advanced.cyber;}
 if(cmd==='safety-audit'){spend(s,p.cost||500000,'تدقيق السلامة HSE');const weak=fleetData().count(s,a=>Number(a.condition)<70),aog=fleetData().count(s,a=>Number(a.condition)<60),maint=num(s.realism?.aviation?.maintenanceDue);s.advanced.safety.lastAudit=now(s);s.advanced.safety.openFindings=weak+maint;s.advanced.safety.score=clamp(98-weak*1.8-aog*3-maint*.8-num(s.advanced.safety.incidents)*2,45,99);return {weak,aog,maintenanceDue:maint,...s.advanced.safety};}
 throw new Error(`Unknown governance command: ${cmd}`);
}
const API={VERSION,ensure,execute};globalThis.GH_GOVERNANCE_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('governance',API);if(globalThis.window&&window!==globalThis)window.GH_GOVERNANCE_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
