/* Build 333 Atlas Executive presentation. Business commands retain their atomic owners. */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const history=[];let returning=false,pending=null;
function historyButton(){const b=document.getElementById('workspaceBack');if(b)b.hidden=history.length<2;}
function navigate(panel,arg){const key=JSON.stringify([panel,arg??null]);if(returning)returning=false;else if(history.at(-1)?.key!==key){history.push({key,panel,arg});if(history.length>30)history.shift();}historyButton();}
function back(open){if(history.length<2)return;history.pop();const row=history.at(-1);returning=true;open(row.panel,row.arg);historyButton();}
function resetHistory(){history.length=0;historyButton();}
const card=(panel,title,copy,icon='i-company',arg)=>`<button class="command-btn" data-open="${esc(panel)}"${arg===undefined?'':` data-arg="${esc(arg)}"`}><span><svg aria-hidden="true"><use href="#${icon}"></use></svg></span><div><b>${esc(title)}</b><small>${esc(copy)}</small></div><em aria-hidden="true">←</em></button>`;
const HEROES=Object.freeze({
 companies:['assets/images/company-system-v2.webp','محفظة الشركات','الشركات التابعة','هوية موحدة، وقرارات مستقلة لكل شركة.'],
 companyManage:['assets/images/company-system-v2.webp','إدارة الشركة','غرفة قيادة الشركة','الأداء والتشغيل والهوية في مساحة واحدة.'],
 control:['assets/images/facility-logistics-v2.webp','العمليات العالمية','مركز التشغيل','الأصول والمسارات والمنشآت من الحالة المباشرة.'],
 assets:['assets/images/air-widebody.webp','الأصول','الأسطول المملوك','حالة كل أصل ومهمته وتكلفته الفعلية.'],
 assetMarket:['assets/images/air-regional.webp','التوسع','سوق الأصول','اختيار ممول يرتبط بالتشغيل والميزانية.'],
 routes:['assets/images/facility-airport-v2.webp','الشبكة','مركز المسارات','خطوط فعلية مرتبطة بالأصول والمنشآت.'],
 globalRoute:['assets/images/facility-port-v2.webp','الشبكة','مسار عالمي','تخطيط وتشغيل من خريطة المجموعة.'],
 finance:['assets/images/company-bank-v2.webp','الخزينة','المركز المالي','السيولة والديون والمستندات من دفاتر اللعبة.'],
 monthlyFinance:['assets/images/company-bank-v2.webp','المالية','نتائج الفترة','دخل ومصروف وفائض كل كيان.'],
 invoices:['assets/images/company-bank-v2.webp','المستندات','السجل المالي','شيكات وفواتير وحوالات بصيغها الرسمية.'],
 treasury:['assets/images/company-bank-v2.webp','السيولة','الخزينة المركزية','تمويل واحتياطي وتسويات موثقة.'],
 labor:['assets/images/company-hq-v2.webp','الموارد البشرية','القيادات والموظفون','عقود ورواتب وتعيينات محفوظة.'],
 conference:['assets/images/company-hq-v2.webp','علاقات المستثمرين','المؤتمر السنوي','نتائج المجموعة وصوت السوق من البيانات الحالية.'],
 energy:['assets/images/company-energy-v2.webp','GH ENERGY','قيادة الطاقة','المشاريع والإنتاج والعقود في مشهد واحد.'],
 bank:['assets/images/company-bank-v2.webp','GH BANK','قيادة البنك','السيولة والائتمان والفروع تحت رقابة واحدة.']
});
function companyKey(panel,arg,state){if(panel==='energy')return typeof arg==='object'?String(arg.companyId||arg.ownerCompanyId||'power'):'power';if(panel==='bank')return typeof arg==='object'?String(arg.companyId||arg.ownerCompanyId||'bank'):'bank';if(panel==='mobilityAsset')return typeof arg==='object'?String(arg.companyId||arg.ownerCompanyId||'mobility'):'mobility';if(panel==='companyManage'||panel==='companyFacilities'){const raw=typeof arg==='object'?String(arg?.companyId||arg?.ownerCompanyId||arg?.type||''):String(arg||'').split(':')[0],company=globalThis.GH_COMPANY_PLATFORM?.resolveCompany?.(state,raw);return company?.known?raw:'';}return'';}
function injectHero(root,panel,arg,ctx){const company=companyKey(panel,arg,ctx.state);if(company)root.dataset.company=company;if(root.querySelector('.ui-section-hero,.visual-hero'))return;const spec=HEROES[panel];if(!spec)return;const [photo,kicker,title,copy]=spec,node=document.createElement('div');node.className='ui-section-hero';node.innerHTML=`<img src="${photo}" alt=""><div><span>${esc(kicker)}</span><h3>${esc(title)}</h3><p>${esc(copy)}</p></div>`;root.prepend(node);}
function hub(panel,ctx){const s=ctx.state;
if(panel==='leadershipHub')return `<div class="ui-section-hero"><img src="assets/images/company-hq-v2.webp" alt="مقر المجموعة"><div><span>إدارة المجموعة</span><h3>${esc(s.profile?.name||'المجموعة القابضة')}</h3><p>الشركات والقرارات والخطط في مكان واحد.</p></div></div><div class="command-grid">${card('groupManagement','أداء المجموعة','الأداء والخطط وملكية الشركات')}${card('conference','المؤتمر السنوي','الافتتاحية والنتائج والقيادات','i-world')}${card('actionCenter','المهام الحالية','ما يحتاج تدخلك الآن','i-bell')}${card('businessWorld','العلاقات التجارية','العملاء والموردون والرعايات','i-market')}</div><details class="ui-more"><summary>الاستراتيجية والسجل</summary>${card('executionLog','سجل التنفيذ','نتائج القرارات والإجراءات','i-target')}${card('news','أخبار المجموعة','أحداث المال والتشغيل','i-bell')}${card('realism','السوق والاقتصاد','الوقود والطلب والأسعار','i-market')}${card('ma','الاستحواذات','فرص الاستثمار والملكية')}${card('research','البحث والتطوير','مشروعات التطوير','i-ops')}${card('esg','الاستدامة','مؤشرات البيئة والمسؤولية','i-world')}${card('career','تقدم المجموعة','مراحل نمو أعمالك','i-ops')}</details>`;
if(panel==='labor'&&String(ctx.currentArg||'').startsWith('managers'))return managerView(ctx);
if(panel==='peopleHub'){const company=globalThis.GH_COMPANY_PLATFORM?.listInstances?.(s,{includeGroup:false,openedOnly:true,capability:'hr.management'}).find(row=>row.operational)?.id||(s.openedCompanies||[]).find(id=>globalThis.GH_HR_CORE?.MANAGER_COMPANIES?.includes(id));return `<div class="ui-section-hero"><img src="assets/images/company-hq-v2.webp" alt="الموارد البشرية"><div><span>الموارد البشرية</span><h3>القيادة والموظفون</h3><p>تعيين واضح، وعقود ورواتب تخص كل شركة.</p></div></div><div class="command-grid">${card('labor','المديرون التنفيذيون','المرشحون والتعيين الرسمي','i-company',company?'managers:'+company:'managers')}${card('labor','تغطية الوظائف','احتياجات المراكز والمنشآت','i-ops','dashboard')}${card('labor','العقود','عقود العمل السارية','i-company','contracts')}${card('labor','الرواتب','المسير والتكاليف','i-market','payroll')}</div>`;}
if(panel==='workspaceHub')return `<div class="command-grid">${card('governanceHub','الحوكمة والمخاطر','المجلس والتدقيق والامتثال')}${card('systemHub','سلامة اللعبة','التشخيص والصيانة','i-target')}${card('settings','الإعدادات والحفظ','التفضيلات والنسخ والتحديثات','i-settings')}${card('executionLog','سجل التنفيذ','مراجعة النتائج والإجراءات','i-ops')}</div>`;
return null;}
function managerView(ctx){
 const s=ctx.state,H=globalThis.GH_HR_CORE,opened=globalThis.GH_COMPANY_PLATFORM?.listInstances?.(s,{includeGroup:false,openedOnly:true,capability:'hr.management'}).filter(c=>c.operational).map(c=>c.id)||(s.openedCompanies||[]).filter(c=>H.MANAGER_COMPANIES.includes(c)),requested=String(ctx.currentArg||'').split(':')[1],company=opened.includes(requested)?requested:opened[0],current=company?H.officialManager(s,company):null;
 const actionAttr=id=>{try{return globalThis.GH_ADVANCED?.actionAttributes?.(id)||'disabled';}catch(_error){return 'disabled';}};
 const nav=`<div class="tabs">${[['dashboard','الوظائف'],['managers','المديرون'],['contracts','العقود'],['payroll','الرواتب']].map(([key,title])=>`<button class="tab-btn ${key==='managers'?'active':''}" data-labortab="${key}">${title}</button>`).join('')}</div>`;
 if(!company)return nav+'<div class="empty">افتح شركة تابعة أولًا لتعيين مديرها التنفيذي.</div>';
 return nav+`<label class="ui-owner-label">الشركة<select id="uiManagerCompany">${opened.map(c=>`<option value="${esc(c)}" ${c===company?'selected':''}>${esc(globalThis.GH_IDENTITY?.legalName?.(s,c)||s.companyRegistry?.[c]?.legalName||ctx.typeName(c))}</option>`).join('')}</select></label><article class="ui-card ui-manager-current"><div class="list-item-head"><div><small>المدير الحالي</small><h3>${esc(current?.name||'المنصب شاغر')}</h3></div><span class="tag ${current?'positive':''}">${current?'معيّن':'بانتظار التعيين'}</span></div>${current?`<small>عقد ${esc(current.contractId)}</small><button class="secondary-btn" ${actionAttr('hr-dismiss-manager')} data-company="${esc(company)}">إنهاء التكليف</button>`:''}</article><div class="official-manager-candidate-grid">${H.officialManagerCandidates(s,company).map(c=>`<article class="ui-card manager-candidate" data-company="${esc(company)}"><div class="list-item-head"><div><h3>${esc(c.name)}</h3><small>${esc(c.city)} · ${esc(c.role)}</small></div><span class="tag">${c.skill}/100</span></div><div class="metric-row"><div><span>الراتب السنوي</span><b>${esc(ctx.fmtMoney(c.salary))}</b></div><div><span>الخبرة</span><b>${c.experience} سنة</b></div></div><p>${esc(c.specialty)} · ${esc(c.style)}</p><button class="primary-btn" ${actionAttr('hr-appoint-manager')} data-company="${esc(company)}" data-candidate="${esc(c.id)}" ${c.appointed?'disabled title="المدير الحالي للشركة"':''}>${c.appointed?'معيّن رسميًا':current?'مراجعة الاستبدال':'مراجعة عقد التعيين'}</button></article>`).join('')}</div>`;
}
function prepare(root,panel,arg,ctx){root.dataset.panel=panel;delete root.dataset.company;const title={leadershipHub:'المجموعة',peopleHub:'الموارد البشرية',workspaceHub:'المزيد',companies:'شركات المجموعة',control:'التشغيل',finance:'المالية',systemHub:'سلامة اللعبة',labor:String(arg||'').startsWith('managers')?'المديرون التنفيذيون':'الموارد البشرية'}[panel];if(title)document.getElementById('drawerTitle').textContent=title;
const replacement=hub(panel,ctx);if(replacement!==null)root.innerHTML=replacement;injectHero(root,panel,arg,ctx);const companySelect=root.querySelector('#uiManagerCompany');if(companySelect)companySelect.onchange=()=>ctx.openDrawer('labor','managers:'+companySelect.value);
root.querySelectorAll('.visual-hero').forEach(el=>{el.className='ui-section-hero';el.querySelector('.visual-hero-shade')?.remove();const intro=el.querySelector('p');if(intro){const detail=document.createElement('details');detail.className='ui-hero-note';const summary=document.createElement('summary');summary.textContent='نبذة';intro.before(detail);detail.append(summary,intro);}});
const sectionHero=root.querySelector('.ui-section-hero'),sectionCompany=root.dataset.company;if(sectionHero&&sectionCompany&&globalThis.GH_IDENTITY?.logoMarkup&&!sectionHero.querySelector('.company-logo-badge'))sectionHero.insertAdjacentHTML('beforeend',globalThis.GH_IDENTITY.logoMarkup(ctx.state,sectionCompany,'small'));
root.querySelectorAll('[style]').forEach(el=>{if(el.namespaceURI!=='http://www.w3.org/1999/xhtml'||el.closest('.financial-paper,.invoice-paper,.authority-paper,.authorization-paper,.approval-log-paper'))return;for(const key of ['background','background-color','background-image','color','box-shadow','text-shadow','border-color'])el.style.removeProperty(key);});
if(panel==='finance'){const overview=root.querySelector('.finance-overview-v202');if(overview){const d=document.createElement('details');d.className='ui-more';d.innerHTML='<summary>نطاق الحسابات والديون</summary>';overview.before(d);d.append(overview);}root.querySelector('.finance-domain-nav')?.classList.add('ui-finance-tools');}
root.querySelectorAll('.command-grid,.finance-domain-nav').forEach(grid=>{const rows=[...grid.children];if(rows.length<=4||grid.closest('.ui-more'))return;const more=document.createElement('details');more.className='ui-more';const summary=document.createElement('summary');summary.textContent=`كل أدوات القسم (${rows.length})`;more.append(summary);for(const row of rows.slice(4))more.append(row);grid.after(more);});
root.querySelectorAll('.company-identity-editor').forEach(editor=>{const tools=editor.nextElementSibling,details=document.createElement('details');details.className='ui-more';const summary=document.createElement('summary');summary.textContent='تعديل الاسم والشعار';details.append(summary);editor.before(details);details.append(editor);if(tools?.classList.contains('company-logo-actions'))details.append(tools);});
root.querySelectorAll('.company-visual-card').forEach(el=>{const photo=el.querySelector(':scope>img'),body=el.querySelector('.company-visual-body'),heading=body?.querySelector('h3');if(!photo||!body||!heading)return;const identity=document.createElement('header');identity.className='ui-company-row';const copy=document.createElement('div'),company=el.dataset.company;if(company&&globalThis.GH_IDENTITY?.logoMarkup)identity.insertAdjacentHTML('beforeend',globalThis.GH_IDENTITY.logoMarkup(ctx.state,company,'small'));copy.append(heading);const p=body.querySelector('p');if(p)copy.append(p);identity.append(photo,copy);el.prepend(identity);el.classList.add('ui-card');const detail=document.createElement('details');detail.className='ui-more';const summary=document.createElement('summary');summary.textContent='الأداء والإجراءات';detail.append(summary);el.append(detail);detail.append(body);});
root.querySelectorAll('.eyebrow,.ui-section-hero span').forEach(e=>{if(/BUILD|DOMAIN|CORE|CENTER|WORKSPACE|V\d|\d+\.\d+\.\d+/i.test(e.textContent))e.textContent='المجموعة العالمية';});root.querySelectorAll('img').forEach(img=>{img.decoding='async';if(!img.alt)img.alt='';});
globalThis.GH_FINANCE_PRESENTATION?.prepare(root);
const selected=root.querySelector('.tabs .active,.hr-manager-company-tabs .active');if(selected)requestAnimationFrame(()=>{const parent=selected.parentElement;if(parent)parent.scrollLeft=selected.offsetLeft-parent.offsetLeft;});}
function confirm(message,{title='مراجعة القرار',accept='تأكيد',state,action='hr-official-manager',risk='personnel'}={}){if(pending)return Promise.resolve(false);return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='ui-confirm';dialog.dir='rtl';dialog.setAttribute('aria-labelledby','uiConfirmTitle');dialog.innerHTML=`<h2 id="uiConfirmTitle">${esc(title)}</h2><p>${esc(message)}</p><footer><button type="button" class="secondary-btn" data-confirm="cancel">إلغاء</button><button type="button" class="primary-btn" data-confirm="accept">${esc(accept)}</button></footer>`;const prior=document.activeElement;let done=false;const finish=accepted=>{if(done)return;done=true;pending=null;globalThis.GH_WORKFLOW?.record?.(state,accepted?'WORKFLOW_CONFIRM_ACCEPTED':'WORKFLOW_CONFIRM_CANCELLED',{action,risk});dialog.close();dialog.remove();if(prior?.isConnected)prior.focus();resolve(accepted);};pending=finish;document.body.append(dialog);globalThis.GH_WORKFLOW?.record?.(state,'WORKFLOW_CONFIRM_SHOWN',{action,risk});dialog.querySelector('[data-confirm=cancel]').onclick=()=>finish(false);dialog.querySelector('[data-confirm=accept]').onclick=()=>finish(true);dialog.addEventListener('cancel',e=>{e.preventDefault();finish(false);});dialog.addEventListener('close',()=>finish(false));dialog.showModal();dialog.querySelector('[data-confirm=cancel]').focus();});}
function mapViewport(){
 const map=document.querySelector('.map-stage'),rect=map.getBoundingClientRect(),style=getComputedStyle(document.documentElement),num=k=>parseFloat(style.getPropertyValue(k))||0,header=document.querySelector('.topbar').getBoundingClientRect(),rail=document.querySelector('.side-nav').getBoundingClientRect();
 let left=rect.left+num('--safe-left')+8,right=rect.right-num('--safe-right')-8,top=header.bottom+6,bottom=rect.bottom-num('--safe-bottom')-8;
 const portrait=matchMedia('(orientation:portrait)').matches;if(portrait)top=rail.bottom+6;else right=Math.min(right,rail.left-6);
 const panel=document.querySelector('.drawer.open,.god-panel.open');if(panel){const p=panel.getBoundingClientRect();if(portrait)bottom=Math.min(bottom,p.top-6);else right=Math.min(right,p.left-6);}
 return {left,top,right,bottom,width:Math.max(0,right-left),height:Math.max(0,bottom-top)};
}
globalThis.GH_INTERFACE=Object.freeze({VERSION:'2.0.0',prepare,navigate,back,resetHistory,confirm,mapViewport});
})();
