(()=>{
  'use strict';
  const VERSION='2.9.1';
  const COMPANY_TYPES=['group','air','sea','road','power','bank','mobility'];
  const issue=(id,severity,title,detail,domain='business',evidence={})=>({id,severity,title,detail,domain,evidence});
  const finite=v=>Number.isFinite(Number(v));
  function duplicates(rows,key){const seen=new Set(),dups=[];for(const row of rows||[]){const v=String(row?.[key]??'').trim();if(!v)continue;if(seen.has(v))dups.push(v);else seen.add(v);}return [...new Set(dups)];}
  function financeChecks(state,issues){
    const books=state.companyFinance&&typeof state.companyFinance==='object'?state.companyFinance:{},accountIds=new Set(),balances=[];
    for(const type of COMPANY_TYPES){const book=books[type];if(!book)continue;
      if(!Array.isArray(book.accounts)||!book.accounts.length){issues.push(issue(`FINANCE_ACCOUNTS_MISSING_${type}`,'critical','دفتر شركة بلا حسابات',`دفتر ${type} لا يحتوي حسابًا ماليًا صالحًا.`,'finance',{company:type}));continue;}
      for(const a of book.accounts){const id=String(a?.id||'').trim();if(!id)issues.push(issue(`FINANCE_ACCOUNT_ID_MISSING_${type}`,'critical','حساب بلا معرف',`يوجد حساب في ${type} بدون id.`,'finance',{company:type}));else if(accountIds.has(id))issues.push(issue(`FINANCE_ACCOUNT_ID_DUP_${id}`,'critical','معرف حساب مكرر',`المعرف ${id} مستخدم في أكثر من حساب.`,'finance',{accountId:id}));else accountIds.add(id);
        if(!finite(a?.balance))issues.push(issue(`FINANCE_BALANCE_INVALID_${id||type}`,'critical','رصيد حساب غير رقمي',`رصيد ${id||type} ليس رقمًا صالحًا.`,'finance',{company:type,accountId:id,balance:a?.balance}));else{const n=Number(a.balance);balances.push(n);if(n<0&&!(state.godMoney&&state.infiniteMoney))issues.push(issue(`FINANCE_BALANCE_NEGATIVE_${id}`,'critical','رصيد حساب سالب',`الحساب ${id} أصبح سالبًا ${n}.`,'finance',{company:type,accountId:id,balance:n}));}
      }
      for(const field of ['debt','taxPayable','taxPaid'])if(book[field]!=null&&!finite(book[field]))issues.push(issue(`FINANCE_${field.toUpperCase()}_INVALID_${type}`,'critical','قيمة مالية غير صالحة',`${field} في ${type} ليست رقمًا صالحًا.`,'finance',{company:type,field,value:book[field]}));
    }
    if(balances.length&&finite(state.cash)){const expected=balances.reduce((n,v)=>n+v,0),actual=Number(state.cash);if(Math.abs(expected-actual)>.01&&!state.infiniteMoney)issues.push(issue('FINANCE_CONSOLIDATED_CASH_MISMATCH','critical','السيولة الموحدة لا تطابق دفاتر الشركات',`السيولة ${actual} بينما مجموع الحسابات ${expected}.`,'finance',{actual,expected,difference:actual-expected}));}
    const f=state.finance||{},invoices=Array.isArray(f.invoices)?f.invoices:[],cheques=Array.isArray(f.cheques)?f.cheques:[],payables=Array.isArray(f.payables)?f.payables:[],receivables=Array.isArray(f.receivables)?f.receivables:[];
    for(const n of duplicates(invoices,'number'))issues.push(issue(`FINANCE_INVOICE_DUP_${n}`,'critical','رقم فاتورة مكرر',`الفاتورة ${n} مكررة.`,'finance',{number:n}));
    for(const n of duplicates(cheques,'id'))issues.push(issue(`FINANCE_CHEQUE_DUP_${n}`,'critical','رقم شيك مكرر',`الشيك ${n} مكرر.`,'finance',{id:n}));
    for(const c of cheques){if(!c?.beneficiary)issues.push(issue(`FINANCE_CHEQUE_BENEFICIARY_${c?.id||'UNKNOWN'}`,'warning','شيك بلا مستفيد واضح',`الشيك ${c?.id||'غير معروف'} لا يملك مستفيدًا.`,'finance',{id:c?.id}));if(!c?.accountId)issues.push(issue(`FINANCE_CHEQUE_ACCOUNT_${c?.id||'UNKNOWN'}`,'critical','شيك بلا حساب مصدر',`الشيك ${c?.id||'غير معروف'} غير مربوط بحساب.`,'finance',{id:c?.id}));if(!finite(c?.amount)||Number(c.amount)<0)issues.push(issue(`FINANCE_CHEQUE_AMOUNT_${c?.id||'UNKNOWN'}`,'critical','قيمة شيك غير صالحة',`الشيك ${c?.id||'غير معروف'} يحمل قيمة غير صالحة.`,'finance',{id:c?.id,amount:c?.amount}));}
    const paidStatuses=new Set(['مدفوعة','مسددة','مصروف','مغلق','مقفلة']);
    for(const p of payables)if(paidStatuses.has(String(p?.status||'')))issues.push(issue(`FINANCE_PAYABLE_PAID_OPEN_${p?.number||p?.id||'UNKNOWN'}`,'warning','ذمة دائنة مسددة ما زالت مفتوحة',`السجل ${p?.number||p?.id||'غير معروف'} موجود في payables رغم حالته ${p?.status}.`,'finance',{record:p?.number||p?.id,status:p?.status}));
    for(const r of receivables)if(paidStatuses.has(String(r?.status||'')))issues.push(issue(`FINANCE_RECEIVABLE_PAID_OPEN_${r?.number||r?.id||'UNKNOWN'}`,'warning','ذمة مدينة محصلة ما زالت مفتوحة',`السجل ${r?.number||r?.id||'غير معروف'} موجود في receivables رغم حالته ${r?.status}.`,'finance',{record:r?.number||r?.id,status:r?.status}));
    const ledger=Array.isArray(state.treasury?.ledger)?state.treasury.ledger:[];for(const e of ledger.slice(0,300)){if(!finite(e?.amount)||Number(e.amount)<0)issues.push(issue(`FINANCE_LEDGER_AMOUNT_${e?.id||e?.at||'UNKNOWN'}`,'critical','قيد مالي بقيمة غير صالحة','يوجد قيد خزينة بقيمة سالبة أو غير رقمية.','finance',{entry:e}));if(!e?.from||!e?.to)issues.push(issue(`FINANCE_LEDGER_PARTY_${e?.id||e?.at||'UNKNOWN'}`,'warning','قيد مالي بلا طرفين','يوجد قيد خزينة لا يحدد المصدر والمستفيد بوضوح.','finance',{entry:e}));}

    const journals=Array.isArray(f.journalEntries)?f.journalEntries:[];
    for(const j of journals.slice(0,1200)){const lines=Array.isArray(j?.lines)?j.lines:[],dr=lines.reduce((n,x)=>n+(Number(x?.debit)||0),0),cr=lines.reduce((n,x)=>n+(Number(x?.credit)||0),0);if(!lines.length||Math.abs(dr-cr)>.02)issues.push(issue(`FINANCE_JOURNAL_UNBALANCED_${j?.id||'UNKNOWN'}`,'critical','قيد مزدوج غير متوازن',`القيد ${j?.id||'غير معروف'} مدين ${dr} ودائن ${cr}.`,'finance',{entryId:j?.id,debit:dr,credit:cr}));}
    const archive=f.auditArchive;if(archive!=null){if(!archive||typeof archive!=='object'||Array.isArray(archive)||!archive.records||typeof archive.records!=='object'||Array.isArray(archive.records)||!Array.isArray(archive.digests))issues.push(issue('FINANCE_AUDIT_ARCHIVE_INVALID','critical','أرشيف التدقيق المالي غير صالح','بنية أرشيف السجلات المالية تالفة أو غير مكتملة.','finance',{archive}));else{for(const [kind,rows] of Object.entries(archive.records))if(!Array.isArray(rows))issues.push(issue(`FINANCE_AUDIT_ARCHIVE_BUCKET_${kind}`,'critical','حاوية أرشيف مالي غير صالحة',`الحاوية ${kind} ليست قائمة سجلات.`,'finance',{kind}));for(const d of archive.digests){if(!d||!String(d.kind||'')||!Number.isInteger(Number(d.count))||Number(d.count)<=0||!finite(d.total)||Number(d.total)<0||!String(d.checksum||''))issues.push(issue(`FINANCE_AUDIT_DIGEST_INVALID_${String(d?.kind||'UNKNOWN')}`,'critical','ملخص أرشيف مالي غير صالح','يوجد digest أرشيفي لا يطابق عقد التدقيق.','finance',{digest:d}));}}}
    const periods=Array.isArray(f.periods)?f.periods:[];for(const p of periods){if(!finite(p?.amount)||Number(p.amount)<0)issues.push(issue(`FINANCE_TAX_PERIOD_INVALID_${p?.id||'UNKNOWN'}`,'critical','فترة ضريبية بقيمة غير صالحة',`الفترة ${p?.id||'غير معروفة'} تحمل مبلغًا غير صالح.`,'finance',{period:p}));if(finite(p?.outputVAT)&&finite(p?.inputVAT)){const opening=Math.max(0,Number(p?.openingCredit)||0),expected=Math.max(0,Number(p.outputVAT)-Number(p.inputVAT)-opening),closing=Math.max(0,Number(p.inputVAT)+opening-Number(p.outputVAT));if(Math.abs((Number(p.amount)||0)-expected)>.02||Math.abs((Number(p?.closingCredit)||0)-closing)>.02)issues.push(issue(`FINANCE_TAX_PERIOD_MATH_${p?.id||'UNKNOWN'}`,'critical','حساب فترة VAT غير متطابق',`الفترة ${p?.id||'غير معروفة'} لا تطابق معادلة Output/Input/Credit.`, 'finance',{period:p,expected,closing}));}}
    for(const type of COMPANY_TYPES){const book=books[type];if(!book)continue;const vat=book.vat;if(vat){for(const k of ['output','input','creditCarry','periodOutputStart','periodInputStart'])if(!finite(vat[k])||Number(vat[k])<0)issues.push(issue(`FINANCE_VAT_INVALID_${type}_${k}`,'critical','حساب VAT غير صالح',`${k} في ${type} غير صالح.`,'finance',{company:type,field:k,value:vat[k]}));}const expectedTax=periods.filter(p=>(p.company||'group')===type&&p.status==='مستحق').reduce((n,p)=>n+Math.max(0,Number(p.amount)||0),0);if(Math.abs(expectedTax-(Number(book.taxPayable)||0))>.02)issues.push(issue(`FINANCE_TAX_PAYABLE_MISMATCH_${type}`,'critical','الضريبة المستحقة لا تطابق الفترات المفتوحة',`دفتر ${type}=${book.taxPayable||0} بينما الفترات المفتوحة=${expectedTax}.`,'finance',{company:type,bookTax:book.taxPayable,expectedTax}));}
    const budgets=state.companyBudgets&&typeof state.companyBudgets==='object'?state.companyBudgets:{};for(const [type,b] of Object.entries(budgets)){const spent=Number(b?.spent)||0,reserved=Number(b?.reserved)||0;if(b?.enabled&&Number(b.limit)>0&&spent+reserved>Number(b.limit)+.01)issues.push(issue(`FINANCE_BUDGET_EXCEEDED_${type}`,'critical','تجاوز ميزانية الشركة',`${type} ملتزم/منفق ${spent+reserved} فوق حد ${b.limit}.`,'finance',{company:type,spent,reserved,limit:b.limit}));for(const line of new Set([...Object.keys(b?.spentByLine||{}),...Object.keys(b?.reservedByLine||{})])){const lineSpent=Number(b?.spentByLine?.[line])||0,lineReserved=Number(b?.reservedByLine?.[line])||0,limit=Number(b?.lines?.[line])||0;if(b?.enabled&&limit>0&&lineSpent+lineReserved>limit+.01)issues.push(issue(`FINANCE_BUDGET_LINE_EXCEEDED_${type}_${line}`,'critical','تجاوز بند ميزانية',`${type}/${line} ملتزم/منفق ${lineSpent+lineReserved} فوق حد ${limit}.`,'finance',{company:type,line,spent:lineSpent,reserved:lineReserved,limit}));}}
  }

  function domainDepthChecks(state,issues){
    const r=state.realism||{},ops=r.operations||{},bank=r.banking||{},energy=r.energy||{};
    const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
    if(num(bank.cet1,99)<4.5)issues.push(issue('BANK_CET1_REGULATORY_MIN','critical','CET1 دون الحد الأساسي','CET1 الداخلي أقل من 4.5% من RWA.','bank',{cet1:bank.cet1,minimum:4.5}));
    if(num(bank.lcr,999)<100)issues.push(issue('BANK_LCR_BELOW_100','critical','LCR دون 100%','السيولة عالية الجودة لا تغطي صافي التدفقات المضغوطة وفق المؤشر الداخلي.','bank',{lcr:bank.lcr}));
    if(num(bank.nsfr,999)<100)issues.push(issue('BANK_NSFR_BELOW_100','critical','NSFR دون 100%','التمويل المستقر المتاح أقل من التمويل المستقر المطلوب وفق المؤشر الداخلي.','bank',{nsfr:bank.nsfr}));
    if(num(bank.provisionCoverage,100)<60&&num(bank.npl,0)>3)issues.push(issue('BANK_PROVISION_COVERAGE_LOW','warning','تغطية المخصصات ضعيفة','ارتفاع NPL مع تغطية مخصصات منخفضة يحتاج مراجعة ائتمانية.','bank',{npl:bank.npl,coverage:bank.provisionCoverage}));
    const av=r.aviation||ops.aviation||{};if(num(av.dispatchReliability,100)<94)issues.push(issue('AIR_DISPATCH_RELIABILITY_LOW','warning','اعتمادية التشغيل الجوي منخفضة',`Dispatch Reliability ${num(av.dispatchReliability).toFixed(1)}%.`,'aviation',{dispatchReliability:av.dispatchReliability}));
    if(num(av.maintenanceReserveCoverage,100)<70)issues.push(issue('AIR_MRO_RESERVE_LOW','warning','احتياطي صيانة الطيران منخفض',`التغطية ${num(av.maintenanceReserveCoverage).toFixed(0)}%.`,'aviation',{coverage:av.maintenanceReserveCoverage}));
    const mar=r.maritime||ops.maritime||{};if(mar.correctiveAction)issues.push(issue('SEA_CII_CORRECTIVE_ACTION','warning','الأسطول البحري يحتاج خطة تصحيح','مؤشر CII التشغيلي الداخلي دخل نطاقًا يحتاج تحسين تشغيل/وقود.','maritime',{rating:mar.ciiRating,ratio:mar.ciiRatio}));
    if(num(mar.eexiReadiness,100)<80)issues.push(issue('SEA_EEXI_READINESS_LOW','warning','جاهزية كفاءة السفن الفنية منخفضة',`EEXI readiness proxy ${num(mar.eexiReadiness).toFixed(0)}%.`,'maritime',{readiness:mar.eexiReadiness}));
    const log=r.logistics||ops.logistics||{};if(num(log.lpiProxy,5)<3)issues.push(issue('ROAD_LPI_PROXY_LOW','warning','جودة الشبكة اللوجستية منخفضة',`LPI proxy ${num(log.lpiProxy).toFixed(2)}/5.`,'logistics',{lpiProxy:log.lpiProxy}));
    if(num(log.emptyMiles,0)>30)issues.push(issue('ROAD_EMPTY_MILES_HIGH','warning','الأميال الفارغة مرتفعة',`${num(log.emptyMiles).toFixed(1)}% من الحركة دون حمولة.`,'logistics',{emptyMiles:log.emptyMiles}));
    const powerActive=(state.openedCompanies||[]).includes('power')||['gasMW','solarMW','windMW'].some(k=>Number(state.energy?.[k])>0);
    if(powerActive){
    if(num(energy.reserveMargin,99)<0)issues.push(issue('POWER_RESERVE_MARGIN_NEGATIVE','critical','هامش احتياطي القدرة سالب','القدرة المتاحة لا تغطي الطلب التشغيلي المقدر.','energy',{reserveMargin:energy.reserveMargin}));
    else if(num(energy.reserveMargin,99)<8)issues.push(issue('POWER_RESERVE_MARGIN_LOW','warning','هامش احتياطي القدرة منخفض',`${num(energy.reserveMargin).toFixed(1)}%.`,'energy',{reserveMargin:energy.reserveMargin}));
    if(num(energy.storageHealth,100)<70)issues.push(issue('POWER_STORAGE_HEALTH_LOW','warning','صحة التخزين منخفضة',`${num(energy.storageHealth).toFixed(1)}%.`,'energy',{storageHealth:energy.storageHealth}));
    }
    const adv=state.advanced||{},rp=adv.researchPrograms||{};for(const [id,p] of Object.entries(rp)){const pct=num(state.research?.[id],0);if(![0,25,50,75,100].includes(pct))issues.push(issue(`RND_STAGE_INVALID_${id}`,'warning','مرحلة بحث غير منضبطة',`المشروع ${id} عند ${pct}% وليس على حد مرحلة معتمد.`,'research',{id,pct}));if(num(p.spent,0)<0)issues.push(issue(`RND_SPEND_INVALID_${id}`,'critical','إنفاق بحث غير صالح',`المشروع ${id} يحمل إنفاقًا سالبًا.`,'research',{id,spent:p.spent}));}
    const programs=state.sustainability?.programs||{};for(const [id,p] of Object.entries(programs)){const m=num(p.maturity,0);if(m<0||m>100)issues.push(issue(`ESG_MATURITY_INVALID_${id}`,'critical','نضج برنامج استدامة غير صالح',`البرنامج ${id} عند ${m}%.`,'esg',{id,maturity:m}));}
  }
  function check(state){const issues=[],assets=Array.isArray(state.assets)?state.assets:[],assetIds=new Set(assets.map(a=>String(a?.id||'')).filter(Boolean)),reqs=state.advanced?.procurement?.assetRequests||[],archive=state.advanced?.procurement?.assetRequestArchive||[],deliveries=state.realism?.procurement?.deliveries||[],ai=state.advanced?.ai?.requests||[],aiArchive=state.advanced?.ai?.requestArchive||[];
    for(const r of reqs){if(!globalThis.GH_LIFECYCLE_CORE?.validate?.('assetRequest',r.status))issues.push(issue(`LIFECYCLE_ASSET_REQUEST_${r.id}`,'critical','حالة طلب أصل غير معتمدة',`الطلب ${r.id} في حالة غير معرفة: ${r.status}`,'lifecycle',{id:r.id,status:r.status}));if(r.status==='delivering'&&!deliveries.some(d=>d.requestRef===r.id))issues.push(issue(`DELIVERY_ORPHAN_${r.id}`,'critical','طلب في التسليم بلا أمر تسليم',`الطلب ${r.id} لا يملك Delivery مرتبطًا.`,'operations',{id:r.id}));for(const depId of r.linkedRequests||[])if(!ai.some(x=>x.id===depId)&&!aiArchive.some(x=>x.id===depId)&&!deliveries.some(x=>x.id===depId))issues.push(issue(`DEPENDENCY_ORPHAN_${r.id}_${depId}`,'warning','تبعية طلب مفقودة',`الطلب ${r.id} يشير إلى تبعية غير موجودة ${depId}.`,'dependencies',{requestId:r.id,dependencyId:depId}));}
    for(const r of archive.filter(x=>x.status==='completed')){const unresolved=globalThis.GH_DEPENDENCY_CORE?.unresolved?.(state,r.id)||[];if(unresolved.length)issues.push(issue(`CLOSED_WITH_OPEN_DEPS_${r.id}`,'critical','طلب مغلق وتبعياته مفتوحة',`الطلب ${r.id} مغلق لكن لديه ${unresolved.length} تبعية مفتوحة.`,'dependencies',{edges:unresolved.slice(0,10)}));}
    for(const d of deliveries){if(d.status==='delivered'&&d.assetId&&!assetIds.has(String(d.assetId)))issues.push(issue(`DELIVERED_ASSET_MISSING_${d.id}`,'critical','تسليم مكتمل بلا أصل',`التسليم ${d.id} يشير إلى أصل غير موجود ${d.assetId}.`,'operations',{deliveryId:d.id,assetId:d.assetId}));if(d.status==='pending'&&!d.baseId)issues.push(issue(`DELIVERY_DESTINATION_MISSING_${d.id}`,'critical','تسليم بلا وجهة',`التسليم ${d.id} لا يملك baseId.`,'operations',{deliveryId:d.id}));}
    for(const id of duplicates(deliveries,'id'))issues.push(issue(`DELIVERY_ID_DUP_${id}`,'critical','معرف تسليم مكرر',`أمر التسليم ${id} مكرر.`,'operations',{id}));
    for(const id of duplicates(ai,'id'))issues.push(issue(`AI_REQUEST_ID_DUP_${id}`,'critical','معرف طلب AI مكرر',`طلب AI ${id} مكرر.`,'ai',{id}));
    for(const id of duplicates(state.customRoutes||[],'id'))issues.push(issue(`ROUTE_ID_DUP_${id}`,'critical','معرف مسار مكرر',`المسار ${id} مكرر.`,'operations',{id}));
    const cycles=globalThis.GH_DEPENDENCY_CORE?.detectCycles?.(state)||[];if(cycles.length)issues.push(issue('DEPENDENCY_GRAPH_CYCLE','critical','دورة مغلقة في شبكة التبعيات','توجد تبعيات تعتمد على بعضها بشكل دائري وتمنع الإغلاق.','dependencies',{cycles:cycles.slice(0,8)}));
    const ledger=state.businessLedger?.events;if(ledger!=null&&!Array.isArray(ledger))issues.push(issue('EVENT_LEDGER_INVALID','critical','دفتر الأحداث غير صالح','businessLedger.events يجب أن يكون مصفوفة.','integrity'));
    financeChecks(state,issues);
    domainDepthChecks(state,issues);
    const dl=state.advanced?.departmentLife,day=Math.floor((Number(state.simSeconds)||0)/86400);
    if(dl){
      const work=Array.isArray(dl.workItems)?dl.workItems:[];
      for(const item of work.filter(x=>x&&x.status!=='مغلق')){
        if(Number.isFinite(Number(item.dueDay))&&day>Number(item.dueDay))issues.push(issue(`DEPARTMENT_TASK_OVERDUE_${item.id}`,(item.severity==='critical'?'critical':'warning'),'مهمة إدارة متأخرة',`${item.title||item.id} متأخرة عن يوم ${item.dueDay}.`,'department',{id:item.id,dept:item.dept,dueDay:item.dueDay,status:item.status}));
        if(!item.owner)issues.push(issue(`DEPARTMENT_TASK_OWNER_MISSING_${item.id}`,'warning','مهمة إدارة بلا مالك',`${item.title||item.id} لا تملك مسؤولًا محددًا.`,'department',{id:item.id,dept:item.dept}));
      }
      const defs=globalThis.GH_DEPARTMENT_CORE?.definitions||{};
      for(const [dept,d] of Object.entries(defs)){const last=dl.reviews?.[dept];if(last&&day-Number(last.day||0)>Math.max(1,Number(d.cadence)||1)*2)issues.push(issue(`DEPARTMENT_REVIEW_STALE_${dept}`,'warning','دورة إدارة متأخرة',`${d.name||dept} لم تُراجع ضمن دوريتها.`,'department',{dept,lastDay:last.day,cadence:d.cadence}));}
    }
    const w=state.workflowControl;if(w&&(!Array.isArray(w.history)||!finite(w.sequence)))issues.push(issue('WORKFLOW_CONTROL_INVALID','warning','حالة Workflow Control غير صالحة','workflowControl يحتاج sequence رقمي وhistory مصفوفة.','workflow'));
    return {version:VERSION,status:issues.some(x=>x.severity==='critical')?'critical':issues.length?'warning':'healthy',counts:{critical:issues.filter(x=>x.severity==='critical').length,warning:issues.filter(x=>x.severity==='warning').length,total:issues.length},byDomain:issues.reduce((o,x)=>(o[x.domain]=(o[x.domain]||0)+1,o),{}),issues};
  }
  const API=Object.freeze({VERSION,check});globalThis.GH_INTEGRITY_CORE=API;if(globalThis.window&&globalThis.window!==globalThis)globalThis.window.GH_INTEGRITY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
