(()=>{
  'use strict';
  const VERSION='2.9.1',FLEET_BASELINE=480;
  const ZONES=Object.freeze([
    {id:'KAFD',name:'مركز الملك عبدالله المالي',coords:[24.767,46.643],weight:1.25},{id:'OLAYA',name:'العليا',coords:[24.711,46.674],weight:1.18},
    {id:'AIRPORT',name:'مطار الملك خالد',coords:[24.958,46.702],weight:1.12},{id:'DIRIYAH',name:'الدرعية',coords:[24.735,46.575],weight:.92},
    {id:'MALQA',name:'الملقا',coords:[24.798,46.608],weight:1.02},{id:'RIMAL',name:'الرمال',coords:[24.846,46.813],weight:.84},
    {id:'INDUSTRIAL',name:'المدينة الصناعية',coords:[24.529,46.789],weight:.78},{id:'STATION',name:'محطة قطار الرياض',coords:[24.648,46.716],weight:.98},
    {id:'QURTUBAH',name:'قرطبة',coords:[24.808,46.747],weight:1.04},{id:'NAKHEEL',name:'النخيل',coords:[24.738,46.618],weight:1.08},
    {id:'SULAIMANIYAH',name:'السليمانية',coords:[24.703,46.706],weight:1.1},{id:'SHIFA',name:'الشفا',coords:[24.565,46.668],weight:.82}
  ]);
  // Real models keep the asset ledger useful while the simulation still
  // aggregates by class (so the map stays light even with a large fleet).
  const CLASSES=Object.freeze([
    {id:'eco-ev',name:'GH Go Electric',manufacturer:'Tesla · BYD · Hyundai',models:['Tesla Model 3','BYD Seal','Hyundai Ioniq 6'],count:260,cost:42000,capacity:4,rate:1.05,base:2.8,icon:'🚙'},
    {id:'comfort',name:'GH Comfort',manufacturer:'Toyota · Hyundai · Kia',models:['Toyota Camry Hybrid','Hyundai Sonata Hybrid','Kia K8'],count:120,cost:61000,capacity:4,rate:1.42,base:4.5,icon:'🚘'},
    {id:'premium',name:'GH Black',manufacturer:'Mercedes-Benz · BMW · Genesis',models:['Mercedes-Benz E-Class','BMW i5','Genesis G80'],count:60,cost:108000,capacity:4,rate:2.35,base:9,icon:'🚖'},
    {id:'accessible-van',name:'GH Access',manufacturer:'Toyota · Mercedes-Benz · Ford',models:['Toyota Sienna','Mercedes-Benz V-Class','Ford E-Transit'],count:40,cost:79000,capacity:6,rate:1.72,base:5.5,icon:'🚐'}
  ]);
  // Mobility centres are capital-only. The compact registry covers the main
  // countries served by the network and never accepts arbitrary map points.
  const CAPITALS=Object.freeze([
    {id:'RUH',country:'السعودية',city:'الرياض',coords:[24.7136,46.6753]},
    {id:'AUH',country:'الإمارات',city:'أبوظبي',coords:[24.4539,54.3773]},
    {id:'DOH',country:'قطر',city:'الدوحة',coords:[25.2854,51.5310]},
    {id:'KWI',country:'الكويت',city:'مدينة الكويت',coords:[29.3759,47.9774]},
    {id:'CAI',country:'مصر',city:'القاهرة',coords:[30.0444,31.2357]},
    {id:'ANK',country:'تركيا',city:'أنقرة',coords:[39.9334,32.8597]},
    {id:'BER',country:'ألمانيا',city:'برلين',coords:[52.5200,13.4050]},
    {id:'LON',country:'المملكة المتحدة',city:'لندن',coords:[51.5074,-0.1278]},
    {id:'PAR',country:'فرنسا',city:'باريس',coords:[48.8566,2.3522]},
    {id:'MAD',country:'إسبانيا',city:'مدريد',coords:[40.4168,-3.7038]},
    {id:'ROM',country:'إيطاليا',city:'روما',coords:[41.9028,12.4964]},
    {id:'WAS',country:'الولايات المتحدة',city:'واشنطن العاصمة',coords:[38.9072,-77.0369]},
    {id:'OTT',country:'كندا',city:'أوتاوا',coords:[45.4215,-75.6972]},
    {id:'MEX',country:'المكسيك',city:'مكسيكو سيتي',coords:[19.4326,-99.1332]},
    {id:'BSB',country:'البرازيل',city:'برازيليا',coords:[-15.7939,-47.8828]},
    {id:'NBO',country:'كينيا',city:'نيروبي',coords:[-1.2921,36.8219]},
    {id:'DEL',country:'الهند',city:'نيودلهي',coords:[28.6139,77.2090]},
    {id:'SIN',country:'سنغافورة',city:'سنغافورة',coords:[1.3521,103.8198]},
    {id:'TYO',country:'اليابان',city:'طوكيو',coords:[35.6762,139.6503]},
    {id:'CAN',country:'أستراليا',city:'كانبرا',coords:[-35.2809,149.1300]}
  ]);
  const clone=v=>globalThis.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v));
  const now=s=>Math.max(0,Number(s.simSeconds)||0);
  const hash=text=>{let h=2166136261>>>0;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;};
  const random=(seed,min=0,max=1)=>min+(hash(seed)/4294967295)*(max-min);
  const distance=(a,b)=>{const r=Math.PI/180,dLat=(b[0]-a[0])*r,dLon=(b[1]-a[1])*r,x=Math.sin(dLat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};

  function ensure(state){
    const m=state.mobility=state.mobility&&typeof state.mobility==='object'?state.mobility:{};
    m.schema='gh-mobility-v2';m.version=VERSION;m.status=m.status||'not-launched';
    for(const key of ['vehicles','drivers','rideRequests','activeTrips','tripArchive','events','capitalCenters'])m[key]=Array.isArray(m[key])?m[key].filter(Boolean):[];
    m.zones=clone(ZONES);m.sequence=Math.max(0,Number(m.sequence)||0);m.lastDemandAt=Math.max(0,Number(m.lastDemandAt)||0);
    for(const vehicle of m.vehicles){const spec=CLASSES.find(x=>x.id===vehicle.assetClass);if(!spec)continue;const serial=Math.max(1,Number(String(vehicle.id||'').split('-').pop())||m.vehicles.indexOf(vehicle)+1);vehicle.manufacturer=vehicle.manufacturer||spec.manufacturer;vehicle.model=vehicle.model||spec.models[(serial-1)%spec.models.length];vehicle.realModel=vehicle.realModel||vehicle.model;vehicle.routeLocked=vehicle.routeLocked!==false;vehicle.baseLocation=vehicle.baseLocation||'الرياض';}
    m.kpis={requests:0,completed:0,cancelled:0,grossBookings:0,driverPayouts:0,platformRevenue:0,avgRating:4.91,acceptanceRate:100,completionRate:100,...(m.kpis||{})};
    return m;
  }
  function id(m,prefix){m.sequence++;return `${prefix}-${String(m.sequence).padStart(7,'0')}`;}
  function classCounts(total){const rows=CLASSES.map(spec=>({spec,count:Math.floor(total*spec.count/FLEET_BASELINE)}));let left=total-rows.reduce((n,x)=>n+x.count,0);for(let i=0;left>0;i++,left--)rows[i%rows.length].count++;return rows;}
  function vehicleBatch(m,total){let serial=m.vehicles.length;for(const {spec,count} of classCounts(total))for(let i=0;i<count;i++){const model=spec.models[serial%spec.models.length];serial++;m.vehicles.push({id:id(m,'MOB-V'),assetClass:spec.id,name:`${spec.name} · ${model} ${String(serial).padStart(4,'0')}`,manufacturer:spec.manufacturer,model,realModel:model,icon:spec.icon,capacity:spec.capacity,purchasePrice:spec.cost,ownership:'owned',condition:100,battery:100,status:'available',zoneId:ZONES[(serial-1)%ZONES.length].id,baseLocation:'الرياض',tripId:null,totalTrips:0,totalKm:0,routeLocked:true,routeSource:'GH Mobility · مسار حضري ثابت',commissionedAt:0});}}
  function driverBatch(state,m,count,source='شراء يدوي'){const first=m.drivers.length;for(let i=0;i<count;i++)m.drivers.push({id:id(m,'DRV'),name:`شريك قيادة ${String(first+i+1).padStart(4,'0')}`,status:'online',rating:Number(random(`driver:${first+i}`,4.72,4.99).toFixed(2)),zoneId:ZONES[(first+i)%ZONES.length].id,tripId:null,totalTrips:0,earnings:0});const hr=globalThis.GH_HR_CORE?.ensure?.(state);if(hr&&count)hr.employmentContracts.unshift({id:id(m,'EMP-MOB'),company:'mobility',name:`${count} × شريك قيادة وتشغيل`,role:'شريك قيادة',count,center:'شبكة الرياض الحضرية',salary:0,startDay:Math.floor(now(state)/86400),termMonths:24,status:'ساري',source});}
  const acquisitionCost=total=>classCounts(total).reduce((n,x)=>n+x.spec.cost*x.count,0);
  function recordFleetPurchase(state,m,total,note){const capex=acquisitionCost(total);globalThis.GH_FINANCE_CORE?.execute?.({state},'spend',{company:'mobility',amount:capex,note,method:'تحويل شراء أصول يدوي',taxable:false,line:'capex',counterparty:'مورّدو أسطول GH Mobility'});vehicleBatch(m,total);driverBatch(state,m,Math.ceil(total*1.35),'تجهيز تشغيلي مرتبط بشراء يدوي');m.events.unshift({id:id(m,'MOB-EV'),at:now(state),type:'MANUAL_FLEET_PURCHASE',vehiclesAdded:total,driversAdded:Math.ceil(total*1.35),capex});return capex;}
  // A fixed corridor is used for every pair of city zones. There is no
  // per-frame or per-trip random offset, so vehicles cannot drift away from
  // their registered path and repeat runs produce the same geometry.
  function urbanPath(from,to){const a=from.coords,b=to.coords,latDelta=b[0]-a[0],lonDelta=b[1]-a[1];return [[...a],[a[0],a[1]+lonDelta*.22],[a[0]+latDelta*.42,a[1]+lonDelta*.22],[a[0]+latDelta*.68,b[1]-lonDelta*.22],[b[0],b[1]-lonDelta*.08],[...b]];}
  function routePosition(route,progress){if(!Array.isArray(route)||route.length<2)return route?.[0]||[0,0];let total=0;const lengths=route.slice(0,-1).map((point,i)=>{const d=distance(point,route[i+1]);total+=d;return d;});let target=Math.max(0,Math.min(1,Number(progress)||0))*total;for(let i=0;i<lengths.length;i++){const d=lengths[i];if(target<=d){const t=d?target/d:0;return [route[i][0]+(route[i+1][0]-route[i][0])*t,route[i][1]+(route[i+1][1]-route[i][1])*t];}target-=d;}return [...route[route.length-1]];}
  function zone(m,index){return m.zones[((index%m.zones.length)+m.zones.length)%m.zones.length];}
  function generate(m,at){const seq=m.sequence+1,from=zone(m,hash(`from:${seq}:${Math.floor(at/45)}`)),to=zone(m,m.zones.indexOf(from)+1+Math.floor(random(`to:${seq}`,0,m.zones.length-1))),km=Math.max(2.2,distance(from.coords,to.coords)*1.22),pick=random(`class:${seq}`),service=pick>.94?CLASSES[2]:pick>.82?CLASSES[3]:pick>.56?CLASSES[1]:CLASSES[0],surge=Number((1+Math.max(0,random(`surge:${Math.floor(at/900)}`,-.08,.55))).toFixed(2)),fare=Number((service.base+km*service.rate*surge).toFixed(2));m.rideRequests.push({id:id(m,'RIDE'),requestedAt:at,status:'queued',fromZone:from.id,toZone:to.id,distanceKm:Number(km.toFixed(2)),service:service.id,surge,fare});m.kpis.requests++;}
  function dispatch(m,at){let assigned=0;for(const request of m.rideRequests){if(request.status!=='queued')continue;const vehicle=m.vehicles.find(v=>v.status==='available'&&v.assetClass===request.service)||m.vehicles.find(v=>v.status==='available'),driver=m.drivers.find(d=>d.status==='online');if(!vehicle||!driver)break;const from=m.zones.find(z=>z.id===request.fromZone)||m.zones[0],to=m.zones.find(z=>z.id===request.toZone)||from,pickup=45+Math.round(random(`pickup:${request.id}`,25,150)),duration=pickup+Math.max(180,Math.round(request.distanceKm/30*3600));request.status='active';request.acceptedAt=at;request.vehicleId=vehicle.id;request.driverId=driver.id;request.tripId=id(m,'TRIP');vehicle.status='moving';vehicle.tripId=request.tripId;driver.status='on-trip';driver.tripId=request.tripId;m.activeTrips.push({id:request.tripId,requestId:request.id,vehicleId:vehicle.id,driverId:driver.id,fromZone:request.fromZone,toZone:request.toZone,startedAt:at,dueAt:at+duration,duration,distanceKm:request.distanceKm,fare:request.fare,progress:0,route:urbanPath(from,to),routeLocked:true,routeSource:'GH Mobility · مسار حضري ثابت'});assigned++;}return assigned;}
  function seedDemand(m,at,count){for(let i=0;i<count;i++)generate(m,at+i);dispatch(m,at);}
  function launch(ctx){const state=ctx.state||ctx,m=ensure(state);if(!(state.openedCompanies||[]).includes('mobility'))throw new Error('mobility-company-not-open');if(m.status==='active')return snapshot(state);const capex=recordFleetPurchase(state,m,FLEET_BASELINE,'شراء يدوي لأسطول GH Mobility الأساسي');m.status='active';m.launchedAt=now(state);m.lastDemandAt=now(state);seedDemand(m,now(state),72);m.events.unshift({id:id(m,'MOB-EV'),at:now(state),type:'NETWORK_LAUNCHED',vehicles:m.vehicles.length,drivers:m.drivers.length,capex});return snapshot(state);}
  function buyFleet(ctx,{quantity=48}={}){const state=ctx.state||ctx,m=ensure(state),qty=Math.max(4,Math.min(240,Math.round(Number(quantity)||48)));if(m.status!=='active')return launch(ctx);recordFleetPurchase(state,m,qty,`شراء يدوي لدفعة GH Mobility · ${qty} مركبة`);seedDemand(m,now(state),Math.min(36,Math.ceil(qty*.15)));return snapshot(state);}
  function ensureBaseline(ctx){const state=ctx.state||ctx,m=ensure(state);if(m.status!=='active'||m.vehicles.length>=FLEET_BASELINE)return 0;const missing=FLEET_BASELINE-m.vehicles.length;recordFleetPurchase(state,m,missing,`ترقية مسجلة لخط أساس BUILD255 · ${missing} مركبة`);seedDemand(m,now(state),72);return missing;}
  function complete(state,m,at){const done=m.activeTrips.filter(t=>t.dueAt<=at),open=m.activeTrips.filter(t=>t.dueAt>at);let gross=0,payout=0;for(const trip of done){const request=m.rideRequests.find(r=>r.id===trip.requestId),vehicle=m.vehicles.find(v=>v.id===trip.vehicleId),driver=m.drivers.find(d=>d.id===trip.driverId),driverPay=trip.fare*.73,platform=trip.fare-driverPay;if(request){request.status='completed';request.completedAt=trip.dueAt;}if(vehicle){vehicle.status='available';vehicle.zoneId=trip.toZone;vehicle.tripId=null;vehicle.totalTrips++;vehicle.totalKm+=trip.distanceKm;vehicle.battery=Math.max(18,vehicle.battery-trip.distanceKm*.42);if(vehicle.battery<30)vehicle.battery=100;}if(driver){driver.status='online';driver.zoneId=trip.toZone;driver.tripId=null;driver.totalTrips++;driver.earnings+=driverPay;}gross+=trip.fare;payout+=driverPay;m.tripArchive.unshift({...trip,status:'completed',completedAt:trip.dueAt,driverPayout:driverPay,platformRevenue:platform});}m.activeTrips=open;m.tripArchive=m.tripArchive.slice(0,1200);m.rideRequests=m.rideRequests.filter(r=>r.status!=='completed'||at-r.completedAt<86400).slice(-1600);if(done.length){const operatingCost=payout+gross*.055,profit=gross-operatingCost;m.kpis.completed+=done.length;m.kpis.grossBookings+=gross;m.kpis.driverPayouts+=payout;m.kpis.platformRevenue+=profit;globalThis.GH_FINANCE_CORE?.execute?.({state},'apply-simulation-journal',{journal:{todayProfit:profit,sectorProfit:{mobility:profit},tripProfit:{mobility:profit},tripRevenue:{mobility:gross},tripFuel:{mobility:operatingCost},tripMaintenance:{mobility:0},tripCount:{mobility:done.length}}});globalThis.GH_FINANCE_CORE?.execute?.({state},'record-simulation-revenue',{company:'mobility',gross,expenses:operatingCost,net:profit,note:`إيراد رحلات GH Mobility · ${done.length} رحلة`,counterparty:'عملاء GH Mobility'});globalThis.GH_CORPORATE_CORE?.execute?.({state},'adjust-group-value',{delta:Math.max(0,profit)*.08});}return done.length;}
  function onSimulationTime(ctx,target){const state=ctx.state||ctx,m=ensure(state),at=Math.max(now(state),Number(target)||0);if(m.status!=='active'){m.lastDemandAt=at;return snapshot(state);}ensureBaseline(ctx);complete(state,m,at);let generated=0,next=m.lastDemandAt+45;while(next<=at&&generated<480){generate(m,next);generated++;next+=45;}m.lastDemandAt=next<=at?at:Math.max(m.lastDemandAt,next-45);dispatch(m,at);for(const t of m.activeTrips)t.progress=Math.max(0,Math.min(1,(at-t.startedAt)/Math.max(1,t.duration)));m.kpis.acceptanceRate=m.kpis.requests?Math.round((m.kpis.requests-m.rideRequests.filter(r=>r.status==='queued').length)/m.kpis.requests*1000)/10:100;m.kpis.completionRate=m.kpis.requests?Math.round(m.kpis.completed/m.kpis.requests*1000)/10:100;return snapshot(state);}
  function snapshot(state){const m=ensure(state),moving=m.vehicles.filter(v=>v.status==='moving').length,queued=m.rideRequests.filter(r=>r.status==='queued').length;return {status:m.status,vehicles:m.vehicles.length,available:m.vehicles.length-moving,moving,drivers:m.drivers.length,online:m.drivers.filter(d=>d.status==='online').length,queued,activeTrips:m.activeTrips.length,completed:m.kpis.completed,grossBookings:m.kpis.grossBookings,driverPayouts:m.kpis.driverPayouts,platformRevenue:m.kpis.platformRevenue,acceptanceRate:m.kpis.acceptanceRate,completionRate:m.kpis.completionRate,avgRating:m.kpis.avgRating,zones:m.zones.length};}
  function liveVehicles(state,limit=120){const m=ensure(state),zoneById=new Map(m.zones.map(z=>[z.id,z])),tripByVehicle=new Map(m.activeTrips.map(t=>[t.vehicleId,t])),ordered=[...m.vehicles].sort((a,b)=>(b.status==='moving')-(a.status==='moving'));return ordered.slice(0,Math.max(0,Number(limit)||120)).map(vehicle=>{const trip=tripByVehicle.get(vehicle.id),from=zoneById.get(trip?.fromZone||vehicle.zoneId)||m.zones[0],to=zoneById.get(trip?.toZone||vehicle.zoneId)||from,progress=trip?Math.max(0,Math.min(1,Number(trip.progress)||0)):0,route=trip?.route?.length?clone(trip.route):[[...from.coords],[...to.coords]];return {id:vehicle.id,name:vehicle.name,manufacturer:vehicle.manufacturer,model:vehicle.model,icon:vehicle.icon,type:'mobility',phase:trip?'moving':'idle',status:vehicle.status,coords:routePosition(route,progress),route,progress,routeLocked:vehicle.routeLocked!==false,tripId:trip?.id||null,driverId:trip?.driverId||null,from:from.name,to:to.name,battery:vehicle.battery,totalTrips:vehicle.totalTrips};});}
  function renderFleet(ctx){const m=ensure(ctx.state),s=snapshot(ctx.state),money=ctx.fmtMoney||String,groups=[];for(const spec of CLASSES)for(const model of spec.models){const vehicles=m.vehicles.filter(v=>v.assetClass===spec.id&&v.model===model);if(vehicles.length)groups.push({spec,model,vehicles});}return `<article class="list-item"><div class="list-item-head"><div><h3>سجل أسطول GH Mobility الحقيقي</h3><p>طرازات سيارات فعلية مسجلة كأصول مملوكة؛ المسارات والشراء منفصلان، وكل نقطة على الخريطة خفيفة.</p></div><span class="tag positive">${s.vehicles} أصل</span></div>${groups.map(x=>`<div class="spec-row"><span>${x.spec.icon} ${x.model} · ${x.spec.name} · ${x.vehicles.filter(v=>v.status==='moving').length} متحركة</span><b>${x.vehicles.length} · ${money(x.vehicles.reduce((n,v)=>n+(Number(v.purchasePrice)||0),0))}</b></div>`).join('')||'<div class="empty">لا توجد سيارات مملوكة بعد. استخدم الشراء اليدوي.</div>'}<div class="action-row"><button class="primary-btn" data-gh-action="mobility-buy-fleet">شراء دفعة سيارات يدوية · 48 مركبة</button></div></article>`;}
  function render(ctx){const s=snapshot(ctx.state),money=ctx.fmtMoney||String;if(s.status!=='active')return `<article class="list-item"><h3>إطلاق GH Mobility يدويًا</h3><p>الزر يشتري ويسجل أسطولًا كبيرًا من سيارات حقيقية (Tesla، BYD، Toyota، Mercedes-Benz وغيرها) ويجهز شركاء القيادة. لا يتخذ AI قرار شراء.</p><div class="metric-row"><div><span>الأسطول الأساسي</span><b>${FLEET_BASELINE} مركبة</b></div><div><span>الطرازات الواقعية</span><b>12 طرازًا</b></div><div><span>مناطق الرياض</span><b>${ZONES.length}</b></div></div><div class="action-row"><button class="primary-btn" data-gh-action="mobility-launch">شراء وإطلاق الأسطول يدويًا</button></div></article>`;return `<article class="list-item"><div class="list-item-head"><div><h3>مركز GH Mobility اللحظي</h3><p>سيارات فعلية، مسار حضري ثابت، ونقطة سوداء واحدة لكل مركبة متحركة. التحصيل يسجل مباشرة في دفتر الشركة.</p></div><span class="tag positive">LIVE</span></div><div class="metric-row"><div><span>المركبات</span><b>${s.vehicles}</b></div><div><span>في رحلات</span><b>${s.moving}</b></div><div><span>السائقون المتاحون</span><b>${s.online}</b></div></div><div class="metric-row"><div><span>رحلات مكتملة</span><b>${s.completed}</b></div><div><span>إجمالي الحجوزات</span><b>${money(s.grossBookings)}</b></div><div><span>إيراد المنصة</span><b>${money(s.platformRevenue)}</b></div></div><div class="action-row"><button class="secondary-btn" data-gh-action="mobility-buy-fleet">شراء يدوي لـ 48 مركبة</button></div></article>${renderFleet(ctx)}`;}
  const API={VERSION,FLEET_BASELINE,ZONES,CLASSES,CAPITALS,ensure,launch,buyFleet,ensureBaseline,onSimulationTime,snapshot,liveVehicles,routePosition,urbanPath,render,renderFleet};globalThis.GH_MOBILITY_CORE=API;if(globalThis.window&&window!==globalThis)window.GH_MOBILITY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
