(()=>{
  'use strict';
  const VERSION='2.9.1';
  const ZONES=Object.freeze([
    {id:'KAFD',name:'مركز الملك عبدالله المالي',coords:[24.767,46.643],weight:1.25},
    {id:'OLAYA',name:'العليا',coords:[24.711,46.674],weight:1.18},
    {id:'AIRPORT',name:'مطار الملك خالد',coords:[24.958,46.702],weight:1.12},
    {id:'DIRIYAH',name:'الدرعية',coords:[24.735,46.575],weight:.92},
    {id:'MALQA',name:'الملقا',coords:[24.798,46.608],weight:1.02},
    {id:'RIMAL',name:'الرمال',coords:[24.846,46.813],weight:.84},
    {id:'INDUSTRIAL',name:'المدينة الصناعية',coords:[24.529,46.789],weight:.78},
    {id:'STATION',name:'محطة قطار الرياض',coords:[24.648,46.716],weight:.98}
  ]);
  const CLASSES=Object.freeze([
    {id:'eco-ev',name:'GH Go Electric',count:48,cost:42000,capacity:4,rate:1.05,base:2.8,icon:'🚙'},
    {id:'comfort',name:'GH Comfort',count:18,cost:61000,capacity:4,rate:1.42,base:4.5,icon:'🚘'},
    {id:'premium',name:'GH Black',count:8,cost:108000,capacity:4,rate:2.35,base:9,icon:'🚖'},
    {id:'accessible-van',name:'GH Access',count:6,cost:79000,capacity:6,rate:1.72,base:5.5,icon:'🚐'}
  ]);
  const clone=v=>globalThis.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v));
  const now=s=>Math.max(0,Number(s.simSeconds)||0);
  const hash=text=>{let h=2166136261>>>0;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;};
  const random=(seed,min=0,max=1)=>min+(hash(seed)/4294967295)*(max-min);
  const distance=(a,b)=>{const r=Math.PI/180,dLat=(b[0]-a[0])*r,dLon=(b[1]-a[1])*r,x=Math.sin(dLat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
  function ensure(state){
    const m=state.mobility=state.mobility&&typeof state.mobility==='object'?state.mobility:{};
    m.schema='gh-mobility-v1';m.version=VERSION;m.status=m.status||'not-launched';
    for(const key of ['vehicles','drivers','rideRequests','activeTrips','tripArchive','events'])m[key]=Array.isArray(m[key])?m[key]:[];
    m.zones=Array.isArray(m.zones)&&m.zones.length?m.zones:clone(ZONES);m.sequence=Math.max(0,Number(m.sequence)||0);m.lastDemandAt=Math.max(0,Number(m.lastDemandAt)||0);
    m.kpis={requests:0,completed:0,cancelled:0,grossBookings:0,driverPayouts:0,platformRevenue:0,avgRating:4.91,acceptanceRate:100,completionRate:100,...(m.kpis||{})};
    return m;
  }
  function id(m,prefix){m.sequence++;return `${prefix}-${String(m.sequence).padStart(7,'0')}`;}
  function vehicleBatch(m,scale=1){const start=m.vehicles.length;for(const spec of CLASSES){const count=Math.max(1,Math.round(spec.count*scale));for(let i=0;i<count;i++)m.vehicles.push({id:id(m,'MOB-V'),assetClass:spec.id,name:`${spec.name} ${String(start+m.vehicles.length+1).padStart(3,'0')}`,icon:spec.icon,capacity:spec.capacity,purchasePrice:spec.cost,ownership:'owned',condition:100,battery:100,status:'available',zoneId:ZONES[(start+i)%ZONES.length].id,tripId:null,totalTrips:0,totalKm:0});}}
  function driverBatch(state,m,count){const first=m.drivers.length;for(let i=0;i<count;i++)m.drivers.push({id:id(m,'DRV'),name:`شريك قيادة ${String(first+i+1).padStart(4,'0')}`,status:'online',rating:Number(random(`driver:${first+i}`,4.72,4.99).toFixed(2)),zoneId:ZONES[(first+i)%ZONES.length].id,tripId:null,totalTrips:0,earnings:0});const hr=globalThis.GH_HR_CORE?.ensure?.(state);if(hr){hr.employmentContracts.unshift({id:id(m,'EMP-MOB'),company:'mobility',name:`${count} × شريك قيادة وتشغيل`,role:'شريك قيادة',count,center:'شبكة المدينة الذكية',salary:0,startDay:Math.floor(now(state)/86400),termMonths:24,status:'ساري',source:'GH Mobility AI'});}}
  function launch(ctx,{scale=1}={}){const state=ctx.state||ctx,m=ensure(state);if(!(state.openedCompanies||[]).includes('mobility'))throw new Error('mobility-company-not-open');if(m.status==='active')return snapshot(state);const capex=CLASSES.reduce((n,x)=>n+x.cost*Math.max(1,Math.round(x.count*scale)),0)+1250000;globalThis.GH_FINANCE_CORE.execute({state},'spend',{company:'mobility',amount:capex,note:'إطلاق منصة GH Mobility وشراء الأسطول الذكي',method:'تحويل أصول وتقنية',taxable:false,line:'capex',counterparty:'تحالف المركبات وتقنية التنقل'});vehicleBatch(m,scale);driverBatch(state,m,Math.ceil(m.vehicles.length*1.35));m.status='active';m.launchedAt=now(state);m.lastDemandAt=now(state);generate(m,now(state));dispatch(m,now(state));m.events.unshift({id:id(m,'MOB-EV'),at:now(state),type:'NETWORK_LAUNCHED',vehicles:m.vehicles.length,drivers:m.drivers.length,capex});return snapshot(state);}
  function scale(ctx){const state=ctx.state||ctx,m=ensure(state);if(m.status!=='active')return launch(ctx);const before=m.vehicles.length,capex=2650000;globalThis.GH_FINANCE_CORE.execute({state},'spend',{company:'mobility',amount:capex,note:'توسعة شبكة GH Mobility بالذكاء التشغيلي',method:'تحويل أصول',taxable:false,line:'capex'});vehicleBatch(m,.25);driverBatch(state,m,Math.ceil((m.vehicles.length-before)*1.3));m.events.unshift({id:id(m,'MOB-EV'),at:now(state),type:'NETWORK_SCALED',vehiclesAdded:m.vehicles.length-before});return snapshot(state);}
  function zone(m,index){return m.zones[((index%m.zones.length)+m.zones.length)%m.zones.length];}
  function generate(m,at){const seq=m.sequence+1,from=zone(m,hash(`from:${seq}:${Math.floor(at/90)}`)),offset=1+Math.floor(random(`to:${seq}`,0,m.zones.length-1)),to=zone(m,m.zones.indexOf(from)+offset),km=Math.max(2.2,distance(from.coords,to.coords)*1.28),classPick=random(`class:${seq}`),service=classPick>.94?CLASSES[2]:classPick>.82?CLASSES[3]:classPick>.56?CLASSES[1]:CLASSES[0],surge=Number((1+Math.max(0,random(`surge:${Math.floor(at/900)}`,-.08,.55))).toFixed(2)),fare=Number((service.base+km*service.rate*surge).toFixed(2));m.rideRequests.push({id:id(m,'RIDE'),requestedAt:at,status:'queued',fromZone:from.id,toZone:to.id,distanceKm:Number(km.toFixed(2)),service:service.id,surge,fare});m.kpis.requests++;}
  function dispatch(m,at){let assigned=0;for(const request of m.rideRequests){if(request.status!=='queued')continue;const vehicle=m.vehicles.find(v=>v.status==='available'&&v.assetClass===request.service)||m.vehicles.find(v=>v.status==='available'),driver=m.drivers.find(d=>d.status==='online');if(!vehicle||!driver)break;const pickup=75+Math.round(random(`pickup:${request.id}`,40,260)),duration=pickup+Math.max(180,Math.round(request.distanceKm/32*3600));request.status='active';request.acceptedAt=at;request.vehicleId=vehicle.id;request.driverId=driver.id;request.tripId=id(m,'TRIP');vehicle.status='moving';vehicle.tripId=request.tripId;driver.status='on-trip';driver.tripId=request.tripId;m.activeTrips.push({id:request.tripId,requestId:request.id,vehicleId:vehicle.id,driverId:driver.id,fromZone:request.fromZone,toZone:request.toZone,startedAt:at,dueAt:at+duration,duration,distanceKm:request.distanceKm,fare:request.fare,progress:0});assigned++;}return assigned;}
  function complete(state,m,at){const done=m.activeTrips.filter(t=>t.dueAt<=at),open=m.activeTrips.filter(t=>t.dueAt>at);let gross=0,payout=0;for(const trip of done){const request=m.rideRequests.find(r=>r.id===trip.requestId),vehicle=m.vehicles.find(v=>v.id===trip.vehicleId),driver=m.drivers.find(d=>d.id===trip.driverId),driverPay=trip.fare*.73,platform=trip.fare-driverPay;if(request){request.status='completed';request.completedAt=trip.dueAt;}if(vehicle){vehicle.status='available';vehicle.zoneId=trip.toZone;vehicle.tripId=null;vehicle.totalTrips++;vehicle.totalKm+=trip.distanceKm;vehicle.battery=Math.max(18,vehicle.battery-trip.distanceKm*.42);if(vehicle.battery<30)vehicle.battery=100;}if(driver){driver.status='online';driver.zoneId=trip.toZone;driver.tripId=null;driver.totalTrips++;driver.earnings+=driverPay;}gross+=trip.fare;payout+=driverPay;m.tripArchive.unshift({...trip,status:'completed',completedAt:trip.dueAt,driverPayout:driverPay,platformRevenue:platform});}m.activeTrips=open;m.tripArchive=m.tripArchive.slice(0,600);m.rideRequests=m.rideRequests.filter(r=>r.status!=='completed'||at-r.completedAt<86400).slice(-800);if(done.length){const operatingCost=payout+gross*.055,profit=gross-operatingCost;m.kpis.completed+=done.length;m.kpis.grossBookings+=gross;m.kpis.driverPayouts+=payout;m.kpis.platformRevenue+=profit;globalThis.GH_FINANCE_CORE?.execute?.({state},'apply-simulation-journal',{journal:{todayProfit:profit,sectorProfit:{mobility:profit},cash:{mobility:profit},tripProfit:{mobility:profit},tripRevenue:{mobility:gross},tripFuel:{mobility:operatingCost},tripMaintenance:{mobility:0},tripCount:{mobility:done.length}}});globalThis.GH_CORPORATE_CORE?.execute?.({state},'adjust-group-value',{delta:Math.max(0,profit)*.08});}return done.length;}
  function onSimulationTime(ctx,target){const state=ctx.state||ctx,m=ensure(state),at=Math.max(now(state),Number(target)||0);if(m.status!=='active'){m.lastDemandAt=at;return snapshot(state);}complete(state,m,at);let generated=0,next=m.lastDemandAt+90;while(next<=at&&generated<240){generate(m,next);generated++;next+=90;}if(next<=at)m.lastDemandAt=at;else m.lastDemandAt=Math.max(m.lastDemandAt,next-90);dispatch(m,at);for(const t of m.activeTrips)t.progress=Math.max(0,Math.min(1,(at-t.startedAt)/Math.max(1,t.duration)));m.kpis.acceptanceRate=m.kpis.requests?Math.round((m.kpis.requests-m.rideRequests.filter(r=>r.status==='queued').length)/m.kpis.requests*1000)/10:100;m.kpis.completionRate=m.kpis.requests?Math.round(m.kpis.completed/m.kpis.requests*1000)/10:100;return snapshot(state);}
  function snapshot(state){const m=ensure(state),online=m.drivers.filter(d=>d.status==='online').length,moving=m.vehicles.filter(v=>v.status==='moving').length,queued=m.rideRequests.filter(r=>r.status==='queued').length;return {status:m.status,vehicles:m.vehicles.length,available:m.vehicles.length-moving,moving,drivers:m.drivers.length,online,queued,activeTrips:m.activeTrips.length,completed:m.kpis.completed,grossBookings:m.kpis.grossBookings,platformRevenue:m.kpis.platformRevenue,acceptanceRate:m.kpis.acceptanceRate,completionRate:m.kpis.completionRate,avgRating:m.kpis.avgRating};}
  function liveVehicles(state,limit=80){const m=ensure(state),zoneById=new Map(m.zones.map(z=>[z.id,z])),tripByVehicle=new Map(m.activeTrips.map(t=>[t.vehicleId,t]));return m.vehicles.slice(0,Math.max(0,Number(limit)||80)).map(vehicle=>{const trip=tripByVehicle.get(vehicle.id),from=zoneById.get(trip?.fromZone||vehicle.zoneId)||m.zones[0],to=zoneById.get(trip?.toZone||vehicle.zoneId)||from,progress=trip?Math.max(0,Math.min(1,Number(trip.progress)||0)):0;return {id:vehicle.id,name:vehicle.name,icon:vehicle.icon,type:'mobility',phase:trip?'moving':'idle',status:vehicle.status,coords:trip?[...from.coords]:[...from.coords],route:trip?[[...from.coords],[...to.coords]]:[[...from.coords],[...from.coords]],progress,tripId:trip?.id||null,driverId:trip?.driverId||null,from:from.name,to:to.name,battery:vehicle.battery,totalTrips:vehicle.totalTrips};});}
  function render(ctx){const s=snapshot(ctx.state),money=ctx.fmtMoney||String;if(s.status!=='active')return `<article class="list-item"><h3>إطلاق شبكة التنقل الذكية</h3><p>اعتماد واحد يشتري أسطولًا متنوعًا، يجهز شركاء القيادة، يفتح مناطق الطلب، ثم يبدأ التسعير والإسناد والرحلات والتحصيل تلقائيًا.</p><div class="metric-row"><div><span>الأسطول الأولي</span><b>80 مركبة</b></div><div><span>الفئات</span><b>اقتصادي · مريح · فاخر · وصول</b></div><div><span>المناطق</span><b>${ZONES.length}</b></div></div><div class="action-row"><button class="primary-btn" data-gh-action="mobility-launch">اعتماد الإطلاق الكامل</button></div></article>`;return `<article class="list-item"><div class="list-item-head"><div><h3>مركز GH Mobility اللحظي</h3><p>الطلب والتسعير والإسناد والوصول والتحصيل تعمل آليًا بزمن المحاكاة.</p></div><span class="tag positive">LIVE</span></div><div class="metric-row"><div><span>المركبات</span><b>${s.vehicles}</b></div><div><span>في رحلات</span><b>${s.moving}</b></div><div><span>السائقون المتاحون</span><b>${s.online}</b></div></div><div class="metric-row"><div><span>رحلات مكتملة</span><b>${s.completed}</b></div><div><span>إجمالي الحجوزات</span><b>${money(s.grossBookings)}</b></div><div><span>إيراد المنصة</span><b>${money(s.platformRevenue)}</b></div></div><div class="metric-row"><div><span>قبول الطلب</span><b>${s.acceptanceRate}%</b></div><div><span>الإكمال</span><b>${s.completionRate}%</b></div><div><span>التقييم</span><b>${s.avgRating}/5</b></div></div><div class="action-row"><button class="secondary-btn" data-gh-action="mobility-scale">توسعة AI للشبكة</button></div></article>`;}
  const API={VERSION,ZONES,CLASSES,ensure,launch,scale,onSimulationTime,snapshot,liveVehicles,render};globalThis.GH_MOBILITY_CORE=API;if(globalThis.window&&window!==globalThis)window.GH_MOBILITY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
