(()=>{'use strict';const VERSION='3.0.0',MAX_ASSET_PURCHASE_QUANTITY=1000,num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0;
function ensure(s){for(const k of ['supplierTransactions','constructionContracts','commercialTenders'])s[k]=Array.isArray(s[k])?s[k]:[];return s;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);const F=globalThis.GH_FINANCE_CORE;if(cmd==='supplier-payment'){const company=p.company||'group',amount=num(p.amount);if(!p.supplier?.name&&!p.supplier?.legalName)throw new Error('supplier-required');const supplier=p.supplier.legalName||p.supplier.name,payment=F.execute({state:s},'pay-by-cheque',{company,amount,note:p.note||'دفعة مورد',beneficiary:supplier,line:p.budgetLine||'capex',taxable:p.taxable!==false,requestRef:p.requestRef||null,type:'شيك مصرفي'}),doc=payment.invoice,cheque=payment.cheque;if(!cheque||cheque.status!=='مصروف'||doc.status!=='مسددة')throw new Error('supplier-cheque-not-cleared');const row={id:p.id||`SUP-${Math.floor(now(s))}-${s.supplierTransactions.length+1}`,company,supplierId:p.supplier.id||'',supplier,amount,method:'شيك مصرفي',reference:cheque.id,invoiceReference:doc.number,note:p.note||'',at:now(s)};s.supplierTransactions.unshift(row);return {supplier:p.supplier,invoice:doc,cheque,settlement:payment.settlement,reference:cheque.id,transaction:row};}
if(cmd==='award-construction'){const bid=p.bid;if(!bid?.supplier)throw new Error('winning-bid-required');const payment=execute({state:s},'supplier-payment',{company:p.company||'group',amount:num(bid.quote),supplier:bid.supplier,note:`دفعة إنشاء وتسليم · ${p.siteName}`,method:'شيك مصدق',budgetLine:'capex'});const r={id:p.id||`BUILD-${Math.floor(now(s))}-${s.constructionContracts.length+1}`,company:p.company||'group',facilityKind:p.facilityKind,siteName:p.siteName,contractor:bid.supplier.legalName||bid.supplier.name,contractorId:bid.supplier.id,contractorTaxId:bid.supplier.taxId,awardScore:bid.score,amount:num(bid.quote),method:'شيك مصدق',paymentRef:payment.reference,status:'قيد التنفيذ',awardedAt:now(s),bids:Array.isArray(p.bids)?p.bids:[]};s.constructionContracts.unshift(r);s.commercialTenders.unshift({id:`TN-${r.id}`,kind:'إنشاء',company:r.company,subject:r.siteName,status:'تمت الترسية',winner:r.contractor,amount:r.amount,bids:r.bids,at:now(s)});return r;}
if(cmd==='configure-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');for(const k of ['capacityKey','capacityAmount','energyKind','commissioned','leadDays'])if(Object.prototype.hasOwnProperty.call(p,k))r[k]=p[k];return r;}
if(cmd==='complete-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');r.commissioned=true;r.status=p.status||'مكتمل / مشغل';r.completedAt=p.completedAt??now(s);return r;}
if(cmd==='record-tender'){const r={id:p.id||`TN-${Math.floor(now(s))}-${s.commercialTenders.length+1}`,kind:p.kind||'توريد',company:p.company||'group',subject:p.subject||'',status:p.status||'تمت الترسية',winner:p.winner||'',amount:num(p.amount),bids:Array.isArray(p.bids)?p.bids:[],at:now(s)};s.commercialTenders.unshift(r);return r;}
if(cmd==='run-tender'){const bids=(Array.isArray(p.bids)?p.bids:[]).filter(x=>x&&x.supplier).sort((a,b)=>num(b.score)-num(a.score)||num(a.annual)-num(b.annual));if(!bids.length)throw new Error('no-valid-bids');if(num(p.studyCost))execute({state:s},'supplier-payment',{company:p.company||'group',amount:num(p.studyCost),supplier:{id:'PROC-STUDY',legalName:'مكتب دراسات المشتريات'},note:`دراسة ${p.subject||'مناقصة'}`,budgetLine:'other'});const winner=bids[0],baseline=num(p.annualSpend)*.22,saving=Math.max(0,Math.round(baseline-num(winner.annual)));s.advanced=s.advanced||{};s.advanced.procurement=s.advanced.procurement||{annualSpend:num(p.annualSpend),savings:0,tenders:[]};s.advanced.procurement.tenders=Array.isArray(s.advanced.procurement.tenders)?s.advanced.procurement.tenders:[];s.advanced.procurement.savings=num(s.advanced.procurement.savings)+saving;const summary={at:now(s),saving,winner:winner.supplier,bids};s.advanced.procurement.tenders.unshift(summary);const tender=execute({state:s},'record-tender',{kind:p.kind||'توريد',company:p.company||'group',subject:p.subject||'',winner:winner.supplier,amount:num(winner.annual),bids});return {...tender,saving};}
if(cmd==='purchase-assets'){
 const type=String(p.type||''),qty=Number(p.qty??1),item=(ctx.assetCatalog||globalThis.GH_ASSET_CATALOG)?.[p.type]?.[p.tab||'new']?.find(i=>i.id===p.item?.id),base=[...(s.globalBases||[]),...(s.customHubs||[])].find(f=>f.id===p.base?.id),supplier=p.supplier,mode=String(p.mode||'cash'),facility=globalThis.GH_FACILITY_CORE;
 if(!facility?.assetCapacity||!facility?.assetOccupancy||!facility?.isAssetFacilityCompatible)throw new Error('facility-capacity-owner-missing');
 if(!Number.isInteger(qty)||qty<1||qty>MAX_ASSET_PURCHASE_QUANTITY||!['cash','finance','lease'].includes(mode)||!['air','sea','road'].includes(type)||!item?.id||!base?.id||!facility.isAssetFacilityCompatible(type,base))throw new Error('invalid-asset-purchase');
 const manual=Boolean(p.manual)||String(p.requestRef||'').startsWith('MANUAL-');
 if(!manual)throw new Error('manual-asset-purchase-required');
 if(!supplier?.name&&!supplier?.legalName)throw new Error('asset-supplier-required');
 const realism=globalThis.GH_REALISM?.migrate?.(s);const deliveries=realism?.procurement?.deliveries;if(!Array.isArray(deliveries))throw new Error('delivery-store-unavailable');
 const capacity=facility.assetCapacity(base),current=facility.assetOccupancy(s,base);if(current+qty>capacity)throw new Error(`delivery-capacity:${Math.max(0,capacity-current)}/${capacity}`);
 const total=num(item.price)*qty,upfront=num(p.upfront);if(total<=0)throw new Error('invalid-asset-price');
 const expected=mode==='cash'?total:mode==='finance'?total*Number(item.downPayment||.2):num(item.leaseMonthly)*3*qty;
 if(Math.abs(expected-upfront)>.01)throw new Error('purchase-upfront-mismatch');
 const fundingGap=(s.infiniteMoney||s.godMoney)?0:Math.max(0,expected-(Number(F.operating?.(s,type))||0)),policy=globalThis.GH_POLICY_CORE?.procurement?.({item,base,qty,freeCapacity:capacity-current,fundingGap});
 if(!policy?.approved)throw new Error(`manual-purchase-policy:${(policy?.blocked||[]).map(row=>row.id).join(',')||'unavailable'}`);
 const paid=execute({state:s},'supplier-payment',{company:type,amount:upfront,supplier,note:`${mode==='lease'?'دفعة إيجار':'شراء'} ${qty} × ${item.name}`,budgetLine:'capex',requestRef:p.requestRef||null});if(!paid?.cheque?.id||paid.cheque.status!=='مصروف'||paid.invoice?.status!=='مسددة')throw new Error('supplier-payment-contract-invalid');const payment={kind:'cheque',ref:paid.cheque.id,invoiceRef:paid.invoice.number,company:type,amount:upfront};
 if(mode==='finance'){const book=F.book(s,type),residual=Math.max(0,total-upfront);F.execute({state:s},'set-debt',{company:type,amount:num(book.debt)+residual});}
 if(!globalThis.GH_CORPORATE_CORE?.execute)throw new Error('corporate-owner-unavailable');globalThis.GH_CORPORATE_CORE.execute({state:s},'unlock-sector',{type});
 const rnd=globalThis.GH_DETERMINISM;if(!rnd?.nextId)throw new Error('determinism-core-unavailable');const nowSeconds=now(s),day=Math.floor(nowSeconds/86400),created=[];
 // The serial is display-only, but recalculating it by scanning every owned
 // asset and pending order inside this loop made a large purchase quadratic.
 // Take one coherent pre-transaction count, then advance it locally.
 const firstSerial=(s.assets||[]).reduce((count,asset)=>count+(asset?.type===type?1:0),0)+deliveries.reduce((count,delivery)=>count+(delivery?.type===type&&delivery.status==='pending'?1:0),0)+1;
 for(let i=0;i<qty;i++){const serial=firstSerial+i,newId=rnd.nextId(s,`N-${type}`),orderId=rnd.nextId(s,`DEL-${type.toUpperCase()}`),asset={id:newId,type,icon:item.icon,name:`GH ${type==='air'?'Air':type==='sea'?'Ocean':'Truck'} ${100+serial}`,company:p.companyName||type,catalogId:item.id,routeId:null,baseFacility:base.id,progress:0,fuel:100,phase:'delivery',model:item.name,year:p.tab==='used'?2021:2026,condition:item.condition||100,specs:JSON.parse(JSON.stringify(item.specs||{})),ownership:mode,monthlyLease:mode==='lease'?num(item.leaseMonthly):0,leaseTermMonths:mode==='lease'?60:0,leaseStartSeconds:mode==='lease'?nowSeconds:0,purchasePrice:num(item.price)};const immediate=p.immediateDelivery===true,row={id:orderId,status:'pending',payment:{...payment},requestRef:p.requestRef||null,orderedDay:day,orderedAtSeconds:nowSeconds,dueDay:immediate?day:day+Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),dueAtSeconds:immediate?nowSeconds:nowSeconds+Math.max(60,Number(p.leadSeconds)||60),contractLeadDays:Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),immediateDelivery:immediate,type,catalogId:item.id,baseId:base.id,destination:base.name,supplier:supplier?.legalName||supplier?.name||p.supplierName||'المورد المختار',asset};deliveries.push(row);created.push(row);}
 if(created.length!==qty||created.some(d=>d.baseId!==base.id||d.requestRef!==(p.requestRef||null)))throw new Error('delivery-contract-generation-failed');
 return {orderId:created[0]?.id||null,deliveryOrderIds:created.map(d=>d.id),assetIds:created.map(d=>d.asset.id),count:created.length,baseId:base.id};
}
throw new Error(`Unknown procurement command: ${cmd}`)}
const API={VERSION,MAX_ASSET_PURCHASE_QUANTITY,ensure,execute};globalThis.GH_PROCUREMENT_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('procurement',API);if(globalThis.window&&window!==globalThis)window.GH_PROCUREMENT_CORE=API;})();
