(()=>{'use strict';const VERSION='2.9.1',num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0;
function ensure(s){for(const k of ['supplierTransactions','constructionContracts','commercialTenders'])s[k]=Array.isArray(s[k])?s[k]:[];return s;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);const F=globalThis.GH_FINANCE_CORE;if(cmd==='supplier-payment'){const company=p.company||'group',amount=num(p.amount);if(!p.supplier?.name&&!p.supplier?.legalName)throw new Error('supplier-required');const doc=F.execute({state:s},'spend',{company,amount,note:p.note||'دفعة مورد',method:p.method||'تحويل بنكي',counterparty:p.supplier.legalName||p.supplier.name,line:p.budgetLine||'capex'});const row={id:p.id||`SUP-${Math.floor(now(s))}-${s.supplierTransactions.length+1}`,company,supplierId:p.supplier.id||'',supplier:p.supplier.legalName||p.supplier.name,amount,method:p.method||'تحويل بنكي',reference:doc.number,note:p.note||'',at:now(s)};s.supplierTransactions.unshift(row);return {supplier:p.supplier,invoice:doc,reference:doc.number,transaction:row};}
if(cmd==='award-construction'){const bid=p.bid;if(!bid?.supplier)throw new Error('winning-bid-required');const payment=execute({state:s},'supplier-payment',{company:p.company||'group',amount:num(bid.quote),supplier:bid.supplier,note:`دفعة إنشاء وتسليم · ${p.siteName}`,method:'شيك مصدق',budgetLine:'capex'});const r={id:p.id||`BUILD-${Math.floor(now(s))}-${s.constructionContracts.length+1}`,company:p.company||'group',facilityKind:p.facilityKind,siteName:p.siteName,contractor:bid.supplier.legalName||bid.supplier.name,contractorId:bid.supplier.id,contractorTaxId:bid.supplier.taxId,awardScore:bid.score,amount:num(bid.quote),method:'شيك مصدق',paymentRef:payment.reference,status:'قيد التنفيذ',awardedAt:now(s),bids:Array.isArray(p.bids)?p.bids:[]};s.constructionContracts.unshift(r);s.commercialTenders.unshift({id:`TN-${r.id}`,kind:'إنشاء',company:r.company,subject:r.siteName,status:'تمت الترسية',winner:r.contractor,amount:r.amount,bids:r.bids,at:now(s)});return r;}
if(cmd==='configure-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');for(const k of ['capacityKey','capacityAmount','energyKind','commissioned'])if(Object.prototype.hasOwnProperty.call(p,k))r[k]=p[k];return r;}
if(cmd==='complete-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');r.commissioned=true;r.status=p.status||'مكتمل / مشغل';r.completedAt=p.completedAt??now(s);return r;}
if(cmd==='record-tender'){const r={id:p.id||`TN-${Math.floor(now(s))}-${s.commercialTenders.length+1}`,kind:p.kind||'توريد',company:p.company||'group',subject:p.subject||'',status:p.status||'تمت الترسية',winner:p.winner||'',amount:num(p.amount),bids:Array.isArray(p.bids)?p.bids:[],at:now(s)};s.commercialTenders.unshift(r);return r;}
if(cmd==='run-tender'){const bids=(Array.isArray(p.bids)?p.bids:[]).filter(x=>x&&x.supplier).sort((a,b)=>num(b.score)-num(a.score)||num(a.annual)-num(b.annual));if(!bids.length)throw new Error('no-valid-bids');if(num(p.studyCost))F.execute({state:s},'spend',{company:p.company||'group',amount:num(p.studyCost),note:`دراسة ${p.subject||'مناقصة'}`,method:'تحويل بنكي',line:'other'});const winner=bids[0],baseline=num(p.annualSpend)*.22,saving=Math.max(0,Math.round(baseline-num(winner.annual)));s.advanced=s.advanced||{};s.advanced.procurement=s.advanced.procurement||{annualSpend:num(p.annualSpend),savings:0,tenders:[]};s.advanced.procurement.tenders=Array.isArray(s.advanced.procurement.tenders)?s.advanced.procurement.tenders:[];s.advanced.procurement.savings=num(s.advanced.procurement.savings)+saving;const summary={at:now(s),saving,winner:winner.supplier,bids};s.advanced.procurement.tenders.unshift(summary);const tender=execute({state:s},'record-tender',{kind:p.kind||'توريد',company:p.company||'group',subject:p.subject||'',winner:winner.supplier,amount:num(winner.annual),bids});return {...tender,saving};}
if(cmd==='purchase-assets'){
 const type=String(p.type||''),qty=Number(p.qty??1),item=(ctx.assetCatalog||globalThis.GH_ASSET_CATALOG)?.[p.type]?.[p.tab||'new']?.find(i=>i.id===p.item?.id),base=[...(s.globalBases||[]),...(s.customHubs||[])].find(f=>f.id===p.base?.id),supplier=p.supplier,mode=String(p.mode||'cash');
 if(!Number.isInteger(qty)||qty<1||qty>50||!['cash','finance','lease'].includes(mode)||!['air','sea','road'].includes(type)||!item?.id||!base?.id||base.owned!==true||base.company!==type||!(type==='air'?['airport-base']:type==='sea'?['port-base']:['depot','logistics']).includes(base.kind))throw new Error('invalid-asset-purchase');
 const request=s.advanced?.procurement?.assetRequests?.find(r=>r.id===p.requestRef);
 if(!request||request.baseId!==base.id||request.company!==type||request.catalogId!==item.id||Number(request.qty)!==qty||!request.authority?.id||!['ordering','authorized'].includes(request.status))throw new Error('purchase-request-contract');
 if(!p.prepaid&&(!supplier?.name&&!supplier?.legalName))throw new Error('asset-supplier-required');
 const realism=globalThis.GH_REALISM?.migrate?.(s);const deliveries=realism?.procurement?.deliveries;if(!Array.isArray(deliveries))throw new Error('delivery-store-unavailable');
 const modeled=Number(s.advanced?.facilities?.[base.id]?.capacity),fallback=['airport','airport-base'].includes(base.kind)?24:['port','port-base'].includes(base.kind)?18:['depot','logistics'].includes(base.kind)?Number(base.bays||42):12,capacity=Number.isFinite(modeled)&&modeled>0?modeled:fallback;
 const pending=deliveries.filter(d=>d.status==='pending'&&d.baseId===base.id).length,current=(s.assets||[]).filter(a=>a.baseFacility===base.id).length+pending;if(current+qty>capacity)throw new Error(`delivery-capacity:${Math.max(0,capacity-current)}/${capacity}`);
 const total=num(item.price)*qty,upfront=num(p.upfront);if(total<=0)throw new Error('invalid-asset-price');
 const expected=mode==='cash'?total:mode==='finance'?total*Number(item.downPayment||.2):num(item.leaseMonthly)*3*qty;
 if(Math.abs(expected-upfront)>.01)throw new Error('purchase-upfront-mismatch');
 let payment;
 if(p.prepaid){const r=s.advanced?.procurement?.assetRequests?.find(x=>x.id===p.requestRef),ch=s.finance?.cheques?.find(c=>c.id===r?.payment?.chequeId);if(!ch||ch.status!=='مصروف'||ch.company!==type||Number(ch.amount)<expected)throw new Error('prepayment-evidence-required');payment={kind:'cheque',ref:ch.id,company:type,amount:ch.amount};}
 if(!p.prepaid&&upfront>0){const paid=execute({state:s},'supplier-payment',{company:type,amount:upfront,supplier,note:`${mode==='lease'?'دفعة إيجار':'شراء'} ${qty} × ${item.name}`,method:p.paymentMethod||'شيك مصدق',budgetLine:'capex'});if(!paid?.reference||paid.invoice?.status!=='مدفوعة')throw new Error('supplier-payment-contract-invalid');payment={kind:'invoice',ref:paid.reference,company:type,amount:upfront};}
 if(!payment)throw new Error('payment-required');
 if(mode==='finance'){const book=F.book(s,type),residual=Math.max(0,total-upfront);F.execute({state:s},'set-debt',{company:type,amount:num(book.debt)+residual});}
 if(!globalThis.GH_CORPORATE_CORE?.execute)throw new Error('corporate-owner-unavailable');globalThis.GH_CORPORATE_CORE.execute({state:s},'unlock-sector',{type});
 const rnd=globalThis.GH_DETERMINISM;if(!rnd?.nextId)throw new Error('determinism-core-unavailable');const nowSeconds=now(s),day=Math.floor(nowSeconds/86400),created=[];
 for(let i=0;i<qty;i++){const serial=(s.assets||[]).filter(a=>a.type===type).length+deliveries.filter(d=>d.type===type&&d.status==='pending').length+1,newId=rnd.nextId(s,`N-${type}`),orderId=rnd.nextId(s,`DEL-${type.toUpperCase()}`),asset={id:newId,type,icon:item.icon,name:`GH ${type==='air'?'Air':type==='sea'?'Ocean':'Truck'} ${100+serial}`,company:p.companyName||type,catalogId:item.id,routeId:null,baseFacility:base.id,progress:0,fuel:100,phase:'delivery',model:item.name,year:p.tab==='used'?2021:2026,condition:item.condition||100,specs:JSON.parse(JSON.stringify(item.specs||{})),ownership:mode,monthlyLease:mode==='lease'?num(item.leaseMonthly):0,leaseTermMonths:mode==='lease'?60:0,leaseStartSeconds:mode==='lease'?nowSeconds:0,purchasePrice:num(item.price)};const row={id:orderId,status:'pending',payment:{...payment},requestRef:p.requestRef||null,orderedDay:day,orderedAtSeconds:nowSeconds,dueDay:day+Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),dueAtSeconds:nowSeconds+Math.max(60,Number(p.leadSeconds)||60),contractLeadDays:Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),type,catalogId:item.id,baseId:base.id,destination:base.name,supplier:supplier?.legalName||supplier?.name||p.supplierName||'المورد المختار',asset};deliveries.push(row);created.push(row);}
 if(created.length!==qty||created.some(d=>d.baseId!==base.id||d.requestRef!==(p.requestRef||null)))throw new Error('delivery-contract-generation-failed');
 return {orderId:created[0]?.id||null,deliveryOrderIds:created.map(d=>d.id),assetIds:created.map(d=>d.asset.id),count:created.length,baseId:base.id};
}
throw new Error(`Unknown procurement command: ${cmd}`)}
const API={VERSION,ensure,execute};globalThis.GH_PROCUREMENT_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('procurement',API);if(globalThis.window&&window!==globalThis)window.GH_PROCUREMENT_CORE=API;})();
