(()=>{'use strict';const VERSION='3.0.0',MAX_ASSET_PURCHASE_QUANTITY=1000,num=v=>Math.max(0,Number(v)||0),now=s=>Number(s.simSeconds)||0;
function ensure(s){for(const k of ['supplierTransactions','constructionContracts','commercialTenders'])s[k]=Array.isArray(s[k])?s[k]:[];return s;}
const purchaseBatches=new WeakMap();
function purchaseKey(companyId,assetMode){return `${String(companyId||'')}\u0000${String(assetMode||'')}`;}
function withPurchaseBatch(state,apply){if(!state||typeof state!=='object'||typeof apply!=='function')throw new TypeError('procurement-purchase-batch-invalid');if(!globalThis.GH_TRANSACTION_CORE?.isActive?.())throw new Error('procurement-purchase-batch-requires-full-transaction');const active=purchaseBatches.get(state);if(active){active.depth++;try{const value=apply();if(value?.then)throw new Error('procurement-purchase-batch-must-be-synchronous');return value;}finally{active.depth--;}}const platform=globalThis.GH_COMPANY_PLATFORM,serialCounts=new Map(),occupancyByBase=new Map(),deliveries=Array.isArray(state.realism?.procurement?.deliveries)?state.realism.procurement.deliveries:[];for(const asset of state.assets||[]){const baseId=String(asset?.baseFacility||'');if(baseId)occupancyByBase.set(baseId,(occupancyByBase.get(baseId)||0)+1);const mode=String(asset?.assetMode||asset?.type||''),owner=String(asset?.ownerCompanyId||asset?.companyId||platform?.ownerForLegacyAssetMode?.(mode)||'');if(owner&&mode){const key=purchaseKey(owner,mode);serialCounts.set(key,(serialCounts.get(key)||0)+1);}}for(const row of deliveries){if(row?.status!=='pending')continue;const baseId=String(row.baseId||'');if(baseId)occupancyByBase.set(baseId,(occupancyByBase.get(baseId)||0)+1);const mode=String(row.assetMode||row.type||''),owner=String(row.ownerCompanyId||row.companyId||platform?.ownerForLegacyAssetMode?.(mode)||'');if(owner&&mode){const key=purchaseKey(owner,mode);serialCounts.set(key,(serialCounts.get(key)||0)+1);}}const batch={depth:1,serialCounts,occupancyByBase};purchaseBatches.set(state,batch);try{const value=apply();if(value?.then)throw new Error('procurement-purchase-batch-must-be-synchronous');return value;}finally{purchaseBatches.delete(state);}}
function commandOwner(s,p={}){const ownerCompanyId=String(p.ownerCompanyId||p.companyId||p.company||'group').trim();if(!ownerCompanyId)throw new Error('procurement-owner-company-missing');const platform=globalThis.GH_COMPANY_PLATFORM;if(platform)platform.requireCompany(s,ownerCompanyId,{operational:ownerCompanyId!=='group',capability:'finance.book'});return ownerCompanyId;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);const F=globalThis.GH_FINANCE_CORE;if(cmd==='supplier-payment'){const company=commandOwner(s,p),amount=num(p.amount);if(!p.supplier?.name&&!p.supplier?.legalName)throw new Error('supplier-required');const supplier=p.supplier.legalName||p.supplier.name,payment=F.execute({state:s},'pay-by-cheque',{company,amount,note:p.note||'دفعة مورد',beneficiary:supplier,line:p.budgetLine||'capex',taxable:p.taxable!==false,requestRef:p.requestRef||null,type:'شيك مصرفي'}),doc=payment.invoice,cheque=payment.cheque;if(!cheque||cheque.status!=='مصروف'||doc.status!=='مسددة')throw new Error('supplier-cheque-not-cleared');const row={id:p.id||`SUP-${Math.floor(now(s))}-${s.supplierTransactions.length+1}`,ownerCompanyId:company,supplierId:p.supplier.id||'',supplier,amount,method:'شيك مصرفي',reference:cheque.id,invoiceReference:doc.number,note:p.note||'',at:now(s)};s.supplierTransactions.unshift(row);return {supplier:p.supplier,invoice:doc,cheque,settlement:payment.settlement,reference:cheque.id,transaction:row};}
if(cmd==='award-construction'){const bid=p.bid;if(!bid?.supplier)throw new Error('winning-bid-required');const ownerCompanyId=commandOwner(s,p),payment=execute({state:s},'supplier-payment',{ownerCompanyId,amount:num(bid.quote),supplier:bid.supplier,note:`دفعة إنشاء وتسليم · ${p.siteName}`,method:'شيك مصدق',budgetLine:'capex'});const r={id:p.id||`BUILD-${Math.floor(now(s))}-${s.constructionContracts.length+1}`,ownerCompanyId,facilityKind:p.facilityKind,siteName:p.siteName,contractor:bid.supplier.legalName||bid.supplier.name,contractorId:bid.supplier.id,contractorTaxId:bid.supplier.taxId,awardScore:bid.score,amount:num(bid.quote),method:'شيك مصدق',paymentRef:payment.reference,status:'قيد التنفيذ',awardedAt:now(s),bids:Array.isArray(p.bids)?p.bids:[]};s.constructionContracts.unshift(r);s.commercialTenders.unshift({id:`TN-${r.id}`,kind:'إنشاء',ownerCompanyId,subject:r.siteName,status:'تمت الترسية',winner:r.contractor,amount:r.amount,bids:r.bids,at:now(s)});return r;}
if(cmd==='configure-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');for(const k of ['capacityKey','capacityAmount','energyKind','commissioned','leadDays'])if(Object.prototype.hasOwnProperty.call(p,k))r[k]=p[k];return r;}
if(cmd==='complete-construction'){const r=s.constructionContracts.find(x=>x.id===p.id);if(!r)throw new Error('construction-not-found');r.commissioned=true;r.status=p.status||'مكتمل / مشغل';r.completedAt=p.completedAt??now(s);return r;}
if(cmd==='record-tender'){const ownerCompanyId=commandOwner(s,p),r={id:p.id||`TN-${Math.floor(now(s))}-${s.commercialTenders.length+1}`,kind:p.kind||'توريد',ownerCompanyId,subject:p.subject||'',status:p.status||'تمت الترسية',winner:p.winner||'',amount:num(p.amount),bids:Array.isArray(p.bids)?p.bids:[],at:now(s)};s.commercialTenders.unshift(r);return r;}
if(cmd==='run-tender'){const ownerCompanyId=commandOwner(s,p),bids=(Array.isArray(p.bids)?p.bids:[]).filter(x=>x&&x.supplier).sort((a,b)=>num(b.score)-num(a.score)||num(a.annual)-num(b.annual));if(!bids.length)throw new Error('no-valid-bids');if(num(p.studyCost))execute({state:s},'supplier-payment',{ownerCompanyId,amount:num(p.studyCost),supplier:{id:'PROC-STUDY',legalName:'مكتب دراسات المشتريات'},note:`دراسة ${p.subject||'مناقصة'}`,budgetLine:'other'});const winner=bids[0],baseline=num(p.annualSpend)*.22,saving=Math.max(0,Math.round(baseline-num(winner.annual)));s.advanced=s.advanced||{};s.advanced.procurement=s.advanced.procurement||{annualSpend:num(p.annualSpend),savings:0,tenders:[]};s.advanced.procurement.tenders=Array.isArray(s.advanced.procurement.tenders)?s.advanced.procurement.tenders:[];s.advanced.procurement.savings=num(s.advanced.procurement.savings)+saving;const summary={at:now(s),ownerCompanyId,saving,winner:winner.supplier,bids};s.advanced.procurement.tenders.unshift(summary);const tender=execute({state:s},'record-tender',{kind:p.kind||'توريد',ownerCompanyId,subject:p.subject||'',winner:winner.supplier,amount:num(winner.annual),bids});return {...tender,saving};}
if(cmd==='purchase-assets'){
 const platform=globalThis.GH_COMPANY_PLATFORM,assetMode=String(p.assetMode||p.type||''),companyId=String(p.ownerCompanyId||p.companyId||platform?.ownerForLegacyAssetMode?.(assetMode)||''),qty=Number(p.qty??1),item=(ctx.assetCatalog||globalThis.GH_ASSET_CATALOG)?.[assetMode]?.[p.tab||'new']?.find(i=>i.id===p.item?.id),base=[...(s.globalBases||[]),...(s.customHubs||[])].find(f=>f.id===p.base?.id),supplier=p.supplier,mode=String(p.mode||'cash'),facility=globalThis.GH_FACILITY_CORE,batch=purchaseBatches.get(s);
 if(!facility?.assetCapacity||!facility?.assetOccupancy||!facility?.isAssetFacilityCompatible)throw new Error('facility-capacity-owner-missing');
 if(!platform)throw new Error('company-platform-missing');
 const company=platform.requireCompany(s,companyId,{operational:true,capability:'operations.fleet'}),assetClass=String(p.assetClass||platform.assetClassForLegacyMode(assetMode)||company.definition.classification.assetClasses[0]||'');
 if(!company.definition.classification.assetClasses.includes(assetClass)||!company.definition.classification.routeModes.includes(assetMode))throw new Error('asset-company-profile-mismatch');
 if(!Number.isInteger(qty)||qty<1||qty>MAX_ASSET_PURCHASE_QUANTITY||!['cash','finance','lease'].includes(mode)||!item?.id||!base?.id||!facility.isAssetFacilityCompatible({assetMode,ownerCompanyId:companyId,assetClass},base,s))throw new Error('invalid-asset-purchase');
 const manual=Boolean(p.manual)||String(p.requestRef||'').startsWith('MANUAL-');
 if(!manual)throw new Error('manual-asset-purchase-required');
 if(!supplier?.name&&!supplier?.legalName)throw new Error('asset-supplier-required');
 const realism=globalThis.GH_REALISM?.migrate?.(s);const deliveries=realism?.procurement?.deliveries;if(!Array.isArray(deliveries))throw new Error('delivery-store-unavailable');
 const capacity=facility.assetCapacity(base),current=batch?(batch.occupancyByBase.get(base.id)||0):facility.assetOccupancy(s,base);if(current+qty>capacity)throw new Error(`delivery-capacity:${Math.max(0,capacity-current)}/${capacity}`);
 const total=num(item.price)*qty,upfront=num(p.upfront);if(total<=0)throw new Error('invalid-asset-price');
 const expected=mode==='cash'?total:mode==='finance'?total*Number(item.downPayment||.2):num(item.leaseMonthly)*3*qty;
 if(Math.abs(expected-upfront)>.01)throw new Error('purchase-upfront-mismatch');
 const fundingGap=(s.infiniteMoney||s.godMoney)?0:Math.max(0,expected-(Number(F.operating?.(s,companyId))||0)),policy=globalThis.GH_POLICY_CORE?.procurement?.({item,base,qty,freeCapacity:capacity-current,fundingGap});
 if(!policy?.approved)throw new Error(`manual-purchase-policy:${(policy?.blocked||[]).map(row=>row.id).join(',')||'unavailable'}`);
 const paid=execute({state:s},'supplier-payment',{ownerCompanyId:companyId,amount:upfront,supplier,note:`${mode==='lease'?'دفعة إيجار':'شراء'} ${qty} × ${item.name}`,budgetLine:'capex',requestRef:p.requestRef||null});if(!paid?.cheque?.id||paid.cheque.status!=='مصروف'||paid.invoice?.status!=='مسددة')throw new Error('supplier-payment-contract-invalid');const payment={kind:'cheque',ref:paid.cheque.id,invoiceRef:paid.invoice.number,ownerCompanyId:companyId,company:companyId,amount:upfront};
 if(mode==='finance'){const residual=Math.max(0,total-upfront);if(residual>0)F.execute({state:s},'record-asset-finance',{company:companyId,amount:residual,ref:`ASSET-FIN-${paid.cheque.id}`,lender:supplier.legalName||supplier.name,assetCatalogId:item.id,invoiceRef:paid.invoice.number});}
 if(!globalThis.GH_CORPORATE_CORE?.execute)throw new Error('corporate-owner-unavailable');globalThis.GH_CORPORATE_CORE.execute({state:s},'unlock-sector',{type:company.definition.classification.primarySectorId});
 const rnd=globalThis.GH_DETERMINISM;if(!rnd?.nextId)throw new Error('determinism-core-unavailable');const nowSeconds=now(s),day=Math.floor(nowSeconds/86400),created=[];
 // Count serials and facility occupancy once per authorized multi-base purchase.
 const serialKey=purchaseKey(companyId,assetMode),priorSerialCount=batch?(batch.serialCounts.get(serialKey)||0):((s.assets||[]).reduce((count,asset)=>count+(String(asset?.ownerCompanyId||asset?.companyId||platform.ownerForLegacyAssetMode(asset?.assetMode||asset?.type)||'')===companyId&&String(asset?.assetMode||asset?.type||'')===assetMode?1:0),0)+deliveries.reduce((count,delivery)=>count+(String(delivery?.ownerCompanyId||delivery?.companyId||platform.ownerForLegacyAssetMode(delivery?.assetMode||delivery?.type)||'')===companyId&&String(delivery?.assetMode||delivery?.type||'')===assetMode&&delivery.status==='pending'?1:0),0)),firstSerial=priorSerialCount+1;
 for(let i=0;i<qty;i++){const serial=firstSerial+i,newId=rnd.nextId(s,`N-${companyId}`),orderId=rnd.nextId(s,`DEL-${String(companyId).toUpperCase()}`),asset={id:newId,ownerCompanyId:companyId,assetMode,assetClass,operationProfileId:company.definition.classification.operationProfileId,type:assetMode,icon:item.icon,name:`${platform.resolveIdentity(s,companyId)?.shortName||companyId} ${100+serial}`,catalogId:item.id,routeId:null,baseFacility:base.id,progress:0,fuel:100,phase:'delivery',model:item.name,year:p.tab==='used'?2021:2026,condition:item.condition||100,specs:JSON.parse(JSON.stringify(item.specs||{})),ownership:mode,monthlyLease:mode==='lease'?num(item.leaseMonthly):0,leaseTermMonths:mode==='lease'?60:0,leaseStartSeconds:mode==='lease'?nowSeconds:0,purchasePrice:num(item.price)};const immediate=p.immediateDelivery===true,row={id:orderId,status:'pending',payment:{...payment},requestRef:p.requestRef||null,orderedDay:day,orderedAtSeconds:nowSeconds,dueDay:immediate?day:day+Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),dueAtSeconds:immediate?nowSeconds:nowSeconds+Math.max(60,Number(p.leadSeconds)||60),contractLeadDays:Math.max(1,Math.floor(Number(p.documentLeadDays)||1)),immediateDelivery:immediate,ownerCompanyId:companyId,assetMode,assetClass,type:assetMode,catalogId:item.id,baseId:base.id,destination:base.name,supplier:supplier?.legalName||supplier?.name||p.supplierName||'المورد المختار',asset};deliveries.push(row);created.push(row);}
 if(created.length!==qty||created.some(d=>d.baseId!==base.id||d.requestRef!==(p.requestRef||null)))throw new Error('delivery-contract-generation-failed');if(batch){batch.serialCounts.set(serialKey,priorSerialCount+created.length);batch.occupancyByBase.set(base.id,current+created.length);}realism.procurement.pendingDeliveryCount=Math.max(0,Number(realism.procurement.pendingDeliveryCount)||0)+created.length;
 return {orderId:created[0]?.id||null,deliveryOrderIds:created.map(d=>d.id),assetIds:created.map(d=>d.asset.id),count:created.length,baseId:base.id};
}
throw new Error(`Unknown procurement command: ${cmd}`)}
const API={VERSION,MAX_ASSET_PURCHASE_QUANTITY,ensure,execute,withPurchaseBatch};globalThis.GH_PROCUREMENT_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('procurement',API);if(globalThis.window&&window!==globalThis)window.GH_PROCUREMENT_CORE=API;})();
