(() => {
  'use strict';
  const VERSION='2.9.0';
  const SCHEMA='2.0.0';
  const TYPES=['group','air','sea','road','power','bank'];
  const SECTORS=['air','sea','road','power','bank'];
  const names={group:'المجموعة',air:'الطيران',sea:'البحرية',road:'اللوجستيات',power:'الطاقة',bank:'البنك'};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
  const money=n=>{n=Number(n)||0;const s=n<0?'-':'';n=Math.abs(n);return s+'$'+(n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.round(n));};
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const hash=s=>{let h=2166136261>>>0;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;};
  const rand=(seed,min=0,max=1)=>{let x=hash(seed);x^=x<<13;x^=x>>>17;x^=x<<5;return min+((x>>>0)/4294967295)*(max-min);};
  const defaultBudget=()=>({period:0,lines:{payroll:0,fuel:0,maintenance:0,marketing:0,insurance:0,technology:0,capex:0,other:0},actual:{payroll:0,fuel:0,maintenance:0,marketing:0,insurance:0,technology:0,capex:0,other:0},forecast:{},variance:{}});
  const initial=()=>({
    schema:SCHEMA,version:VERSION,migratedAt:0,
    economy:{oil:78,jetFuel:0.86,bunker:640,diesel:0.98,electricity:72,gas:39,carbon:52,freight:100,baseRate:.046,usdIndex:100,airDemand:100,seaDemand:100,roadDemand:100,powerDemand:100,lastEvent:null,eventHistory:[]},
    financial:{statements:{},consolidated:{},intercompanyEliminations:0,lastCloseDay:0},
    budgets:Object.fromEntries(TYPES.map(t=>[t,defaultBudget()])),
    aviation:{ask:0,rpk:0,loadFactor:0,yield:0,rask:0,cask:0,caskExFuel:0,otp:92,technicalDelayRate:1.8,maintenanceDue:0,aog:0,dispatchReliability:98,utilization:0,avgCondition:100,maintenanceReserveCoverage:100,healthMonitoringScore:80},
    maritime:{utilization:0,cii:'B',eexi:'Compliant',waitingHours:0,demurrage:0,dryDockDue:0,avgBunkerCost:0,attainedCii:0,requiredCii:1,ciiRatio:1,correctiveAction:false,correctivePlanStatus:'غير مطلوب',consecutiveD:0,lastCiiYear:-1,ciiHistory:[],eexiReadiness:100,fuelIntensity:0},
    logistics:{onTime:94,damageRate:.7,emptyMiles:18,warehouseUtilization:0,orderCycleHours:27,customsHours:9,throughput:0,customsScore:4,shipmentScore:4,trackingScore:4,infrastructureScore:4,serviceScore:4,timelinessScore:4,lpiProxy:4,networkBalance:80},
    energy:{storageSoc:55,roundTripEfficiency:86,degradation:1,cycles:0,capacityFactor:0,curtailment:2,ppaShare:55,spotShare:45,storageHealth:99,effectiveStorageMWh:0,availableMW:0,reserveMargin:0,renewableShare:0,storageThroughputMWh:0,roundTripLossMWh:0},
    banking:{cet1:14,tier1:15,totalCapital:17,rwa:0,lcr:120,nsfr:112,npl:1.9,costOfRisk:1.1,loanDeposit:0,hqla:0,cet1RegMin:4.5,tier1RegMin:6,totalCapitalRegMin:8,capitalConservationBuffer:2.5,cet1Headroom:0,lcrHeadroom:0,nsfrHeadroom:0,provisionCoverage:100,stableFundingBuffer:0,distributionRestricted:false},
    market:{share:{air:8,sea:6,road:7,power:4,bank:3},competitorPressure:{air:50,sea:50,road:50,power:50,bank:50},routeShares:{},lastResponseDay:0},
    reputation:{group:70,air:72,sea:70,road:71,power:73,bank:74},
    risk:{appetite:'balanced',limits:{netDebtEbitda:3,minLiquidity:50000000,maxFxExposure:.20,maxCountryExposure:.30,maxCustomerExposure:.15,minBankCapital:13,minLcr:100},register:[],lastReviewDay:0},
    board:{meetings:[],resolutions:[],nextMeetingDay:30},
    procurement:{pipeline:[],deliveries:[],leadTimes:{air:120,sea:210,road:21,power:365,bank:45},supplierScores:{}},
    projects:[],insurance:{renewalIndex:100,claimsTrend:0},
    taxFx:{fxExposure:0,hedgedPct:0,taxRate:.15},rating:{grade:'BBB',outlook:'Stable',score:62},dividends:{history:[],available:0},
    ai:{authority:{autoLimit:250000,withinBudgetLimit:1000000,ceoLimit:250000000,boardAbove:250000000},hurdleRate:.10,learning:{approved:0,rejected:0,preferredROIC:.12},businessCases:{},lastCommitteeDay:0},
    people:{succession:{},executiveScore:75},morningBriefs:[],eventQueue:[],controls:{lastIntegrityDay:0,issues:[]}
  });
  function deepDefaults(target,defs){for(const [k,v] of Object.entries(defs)){if(target[k]===undefined)target[k]=typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));else if(v&&typeof v==='object'&&!Array.isArray(v)&&target[k]&&typeof target[k]==='object'&&!Array.isArray(target[k]))deepDefaults(target[k],v);}return target;}
  function migrate(state){
    state.realism=state.realism&&typeof state.realism==='object'?state.realism:initial();deepDefaults(state.realism,initial());
    const r=state.realism;r.schema=SCHEMA;r.version=VERSION;
    const p=String(state.profile?.riskAppetite||'balanced');r.risk.appetite=p;
    if(!r.migratedAt){r.migratedAt=Number(state.simSeconds)||0;r.controls.issues=[];}
    normalizeEventQueue(state);return r;
  }
  function normalizeEventQueue(state){const q=state.realism.eventQueue;if(!Array.isArray(q))state.realism.eventQueue=[];else{const seen=new Set();state.realism.eventQueue=q.filter(x=>x&&x.id&&!seen.has(x.id)&&(seen.add(x.id),true)).sort((a,b)=>(a.at||0)-(b.at||0));}}
  function entityName(state,t){return t==='group'?(state.profile?.name||'المجموعة'):(state.companyRegistry?.[t]?.legalName||names[t]);}
  function books(state,t){return state.companyFinance?.[t]||null;}
  function cash(state,t){const b=books(state,t);return (b?.accounts||[]).reduce((n,a)=>n+(Number(a.balance)||0),0);}
  function ownedValue(state,t){return (state.assets||[]).filter(a=>a.type===t&&a.ownership!=='lease').reduce((n,a)=>n+(Number(a.purchasePrice)||0)*clamp((Number(a.condition)||100)/100,.4,1),0);}
  function ledgerTotals(state,t,days=30){const b=books(state,t),cut=(Number(state.simSeconds)||0)-days*86400;let income=0,expense=0;for(const e of (b?.ledger||[])){if((Number(e.at)||0)<cut)continue;const amt=Number(e.amount)||0;if(e.kind==='intercompany'||e.kind==='internal'||e.kind==='bank-credit'||e.kind==='cash-sweep')continue;if(String(e.from||'').includes('عميل')||String(e.note||'').includes('إيراد')||String(e.note||'').includes('فاتورة رحلة'))income+=amt;else expense+=amt;}return {income,expense};}
  function statements(state,t){
    const b=books(state,t)||{debt:0,taxPayable:0},lt=ledgerTotals(state,t,30),c=cash(state,t),recv=(state.finance?.receivables||[]).filter(x=>(x.company||'group')===t).reduce((n,x)=>n+(Number(x.total)||0),0),pay=(state.finance?.payables||[]).filter(x=>(x.company||'group')===t).reduce((n,x)=>n+(Number(x.total)||0),0),debt=Math.max(0,Number(b.debt)||0),simSeconds=Math.max(0,Number(state.simSeconds)||0),simYear=2026+Math.floor(simSeconds/(365*86400));
    const usefulYears={air:20,sea:25,road:8,power:25,bank:12,group:20},salvagePct={air:.12,sea:.15,road:.08,power:.10,bank:.05,group:.05};let assetVal=0,depr=0,leaseLiab=0,rou=0,leaseInterest=0;
    for(const a of (state.assets||[]).filter(a=>a.type===t)){
      const price=Math.max(0,Number(a.purchasePrice)||0),condition=clamp(Number(a.condition)||100,0,100);
      if(a.ownership==='lease'){
        const monthly=Math.max(0,Number(a.monthlyLease)||0),term=Math.max(12,Number(a.leaseTermMonths)||60),start=Math.max(0,Number(a.leaseStartSeconds)||Number(a.deliveredAtSeconds)||simSeconds),elapsed=Math.min(term,Math.max(0,Math.floor((simSeconds-start)/(30*86400)))),remaining=Math.max(0,term-elapsed),monthlyRate=Math.pow(1.07,1/12)-1;
        const pv=monthlyRate?monthly*(1-Math.pow(1+monthlyRate,-remaining))/monthlyRate:monthly*remaining;leaseLiab+=pv;const initialPv=monthlyRate?monthly*(1-Math.pow(1+monthlyRate,-term))/monthlyRate:monthly*term;const carrying=initialPv*Math.max(0,1-elapsed/term);rou+=carrying;depr+=term?initialPv/term:0;leaseInterest+=pv*monthlyRate;
      }else{
        const life=usefulYears[t]||15,salvage=price*(salvagePct[t]||.08),modelYear=Math.min(simYear,Math.max(2000,Number(a.year)||simYear)),ageYears=Math.max(0,simYear-modelYear),annualDep=Math.max(0,(price-salvage)/life),accum=Math.min(price-salvage,annualDep*ageYears),book=Math.max(salvage,price-accum);assetVal+=book*(.75+.25*condition/100);depr+=annualDep/12;
      }
    }
    const revenue=lt.income,leaseServiceExcluded=0,opex=Math.max(0,lt.expense-leaseServiceExcluded),ebitda=revenue-opex,interest=debt*.07/12+leaseInterest,pretax=ebitda-depr-interest,tax=Math.max(0,pretax*.15),net=pretax-tax,assets=c+recv+assetVal+rou,liabilities=pay+debt+leaseLiab+(Number(b.taxPayable)||0),equity=assets-liabilities;
    const workingCapitalDelta=recv*.03-pay*.02,operatingCF=net+depr-workingCapitalDelta,investingCF=-(state.constructionContracts||[]).filter(x=>(x.company||'group')===t&&String(x.status||'').includes('مكتمل')===false).reduce((n,x)=>n+(Number(x.amount)||0)/Math.max(1,Number(x.totalDays)||180),0),financingCF=0;
    return {revenue,opex,ebitda,depr,interest,tax,net,assets,liabilities,cash:c,receivables:recv,payables:pay,debt,leaseLiability:leaseLiab,rouAsset:rou,equity,operatingCF,investingCF,financingCF,workingCapitalDelta};
  }
  function closeFinancials(state,day){const r=migrate(state);let rev=0,op=0,assets=0,liab=0,net=0,ocf=0,icf=0,fcf=0;for(const t of TYPES){const s=statements(state,t);s.equity=s.assets-s.liabilities;r.financial.statements[t]=s;rev+=s.revenue;op+=s.opex;assets+=s.assets;liab+=s.liabilities;net+=s.net;ocf+=s.operatingCF;icf+=s.investingCF;fcf+=s.financingCF;}let eliminations=0;for(const t of TYPES){for(const e of (books(state,t)?.ledger||[])){if(e.kind==='intercompany'||e.kind==='bank-credit'||e.kind==='cash-sweep')eliminations+=Number(e.amount)||0;}}r.financial.intercompanyEliminations=eliminations;r.financial.consolidated={revenue:rev,opex:op,ebitda:rev-op,net,assets,liabilities:liab,equity:assets-liab,operatingCF:ocf,investingCF:icf,financingCF:fcf};r.financial.lastCloseDay=day;}
  function inferBudgetActual(state,t){const s=statements(state,t),assets=(state.assets||[]).filter(a=>a.type===t),fuel=assets.reduce((n,a)=>n+(Number(a.lastTrip?.fuelCost)||0),0)*8,maint=assets.reduce((n,a)=>n+(Number(a.lastTrip?.maintReserve)||0),0)*8,payroll=(state.crew||[]).filter(c=>c.sector===t).reduce((n,c)=>n+(Number(c.count)||0)*((Number(c.salaryMin)||0)+(Number(c.salaryMax)||0))/2*30,0);return {payroll,fuel,maintenance:maint,marketing:s.revenue*.018,insurance:Math.max(0,ownedValue(state,t)*.0008),technology:s.revenue*.01,capex:0,other:Math.max(0,s.opex-payroll-fuel-maint)};}
  function updateBudgets(state,day){const r=migrate(state),period=Math.floor(day/30);for(const t of TYPES){const b=r.budgets[t];if(b.period!==period){b.period=period;b.actual=Object.fromEntries(Object.keys(b.lines).map(k=>[k,0]));}const act=inferBudgetActual(state,t);b.actual={...b.actual,...act};const s=statements(state,t),base=Math.max(500000,s.revenue||cash(state,t)*.04);const godPlan=state.companyBudgets?.[t],manualLimit=godPlan?.enabled?Math.max(0,Number(godPlan.limit)||0):0,manualLines=godPlan?.lines&&typeof godPlan.lines==='object'?godPlan.lines:null,manualLineTotal=manualLines?Object.values(manualLines).reduce((n,x)=>n+(Math.max(0,Number(x)||0)),0):0;if(manualLimit>0&&manualLineTotal>0){b.lines={payroll:Number(manualLines.payroll)||0,fuel:Number(manualLines.fuel)||0,maintenance:Number(manualLines.maintenance)||0,marketing:Number(manualLines.marketing)||0,insurance:Number(manualLines.insurance)||0,technology:Number(manualLines.technology)||0,capex:Number(manualLines.capex)||0,other:Number(manualLines.other)||0};}else if(manualLimit>0){b.lines={payroll:manualLimit*.22,fuel:manualLimit*.23,maintenance:manualLimit*.10,marketing:manualLimit*.05,insurance:manualLimit*.04,technology:manualLimit*.05,capex:manualLimit*.23,other:manualLimit*.08};}else if(!Object.values(b.lines).some(Number)){b.lines={payroll:base*.22,fuel:base*.25,maintenance:base*.10,marketing:base*.04,insurance:base*.03,technology:base*.04,capex:base*.24,other:base*.08};}const elapsed=(day%30)+1;for(const k of Object.keys(b.lines)){b.forecast[k]=(Number(b.actual[k])||0)/Math.max(1,elapsed)*30;b.variance[k]=(Number(b.forecast[k])||0)-(Number(b.lines[k])||0);}}}
  function updateOps(state,day){
    const r=migrate(state),assets=state.assets||[],air=assets.filter(a=>a.type==='air'),sea=assets.filter(a=>a.type==='sea'),road=assets.filter(a=>a.type==='road');
    let ask=0,rpk=0,rev=0,cost=0,fuel=0,movingAir=0,airCondition=0,maintReserve=0,maintExposure=0;
    for(const a of air){
      const cap=Math.max(0,Number(a.specs?.capacity)||0),d=Math.max(0,Number(a.lastTrip?.distanceKm)||Number(a.lastTrip?.distance)||0),condition=clamp(Number(a.condition)||100,0,100);
      const demand=clamp((r.economy.airDemand||100)/100,.65,1.35),conditionFactor=clamp(.82+(condition-70)*.004,.70,1.06),lf=clamp(.78*demand*conditionFactor,.52,.96);
      ask+=cap*Math.max(1,d);rpk+=cap*lf*Math.max(1,d);rev+=Number(a.lastTrip?.revenue)||0;
      const fuelCost=Number(a.lastTrip?.fuelCost)||0,crewCost=Number(a.lastTrip?.crewCost)||0,reserve=Number(a.lastTrip?.maintReserve)||0;
      fuel+=fuelCost;maintReserve+=reserve;maintExposure+=Math.max(0,(100-condition)/100)*(Number(a.purchasePrice)||0)*.0008;cost+=fuelCost+crewCost+reserve;
      if(a.phase==='moving')movingAir++;airCondition+=condition;
      a.flightHours=(Number(a.flightHours)||0)+(a.phase==='moving'?4:0);a.flightCycles=(Number(a.flightCycles)||0)+(a.phase==='turnaround'?1:0);a.nextCheckHours=Number(a.nextCheckHours)||600;
    }
    r.aviation.ask=ask;r.aviation.rpk=rpk;r.aviation.loadFactor=ask?clamp(rpk/ask*100,0,100):0;r.aviation.yield=rpk?rev/rpk:0;r.aviation.rask=ask?rev/ask:0;r.aviation.cask=ask?cost/ask:0;r.aviation.caskExFuel=ask?(cost-fuel)/ask:0;
    r.aviation.maintenanceDue=air.filter(a=>(Number(a.flightHours)||0)>=(Number(a.nextCheckHours)||600)||Number(a.condition)<72).length;r.aviation.aog=air.filter(a=>Number(a.condition)<60).length;
    r.aviation.avgCondition=air.length?airCondition/air.length:100;r.aviation.utilization=air.length?movingAir/air.length*100:0;
    r.aviation.dispatchReliability=air.length?clamp(100-(r.aviation.aog/air.length*100)-(r.aviation.maintenanceDue/air.length*2.5),55,99.95):100;
    r.aviation.technicalDelayRate=clamp(100-r.aviation.dispatchReliability,.05,15);r.aviation.otp=clamp(98-r.aviation.technicalDelayRate*.65-Math.max(0,r.aviation.utilization-88)*.12,55,99.5);
    r.aviation.maintenanceReserveCoverage=maintExposure?clamp(maintReserve/maintExposure*100,0,250):100;r.aviation.healthMonitoringScore=clamp(r.aviation.dispatchReliability*.55+r.aviation.avgCondition*.35+Math.min(100,r.aviation.maintenanceReserveCoverage)*.10,0,100);

    let seaDistance=0,seaFuelProxy=0,seaTransport=0,seaCondition=0,movingSea=0;
    for(const a of sea){const d=Math.max(1,Number(a.lastTrip?.distanceKm)||Number(a.lastTrip?.distance)||1),cap=Math.max(1,Number(a.specs?.capacity)||Number(a.specs?.teu)||Number(a.specs?.dwt)||1),cond=clamp(Number(a.condition)||100,0,100);seaDistance+=d;seaTransport+=d*cap;seaFuelProxy+=Math.max(0,Number(a.lastTrip?.fuelCost)||0)/Math.max(1,r.economy.bunker);seaCondition+=cond;if(a.phase==='moving')movingSea++;}
    const avgSea=sea.length?seaCondition/sea.length:100;r.maritime.utilization=sea.length?movingSea/sea.length*100:0;
    r.maritime.fuelIntensity=seaTransport?seaFuelProxy/seaTransport*1e6:0;
    const ageConditionPenalty=clamp((92-avgSea)/100,0,.5),utilPenalty=clamp(Math.abs(r.maritime.utilization-78)/100,0,.35),intensityBase=Math.max(.55,r.maritime.fuelIntensity||.85);
    const simYear=Math.max(0,Math.floor(day/365));r.maritime.requiredCii=clamp(.90-simYear*.018,.72,.95);r.maritime.attainedCii=clamp(intensityBase*(1+ageConditionPenalty+utilPenalty*.15),.35,2.5);r.maritime.ciiRatio=r.maritime.attainedCii/Math.max(.01,r.maritime.requiredCii);
    const ratio=r.maritime.ciiRatio;r.maritime.cii=ratio<=.82?'A':ratio<=.93?'B':ratio<=1.08?'C':ratio<=1.20?'D':'E';
    if(r.maritime.lastCiiYear!==simYear){const prev=r.maritime.ciiHistory[0];r.maritime.consecutiveD=r.maritime.cii==='D'?(prev?.rating==='D'?(Number(prev.consecutiveD)||1)+1:1):0;r.maritime.ciiHistory.unshift({year:simYear,rating:r.maritime.cii,ratio:r.maritime.ciiRatio,consecutiveD:r.maritime.consecutiveD});r.maritime.ciiHistory=r.maritime.ciiHistory.slice(0,8);r.maritime.lastCiiYear=simYear;}
    r.maritime.correctiveAction=r.maritime.cii==='E'||r.maritime.consecutiveD>=3;r.maritime.correctivePlanStatus=r.maritime.correctiveAction?'مطلوب':r.maritime.cii==='D'?`مراقبة D (${r.maritime.consecutiveD}/3)`:'غير مطلوب';
    r.maritime.eexiReadiness=clamp(avgSea*.72+(100-Math.max(0,r.economy.bunker-640)/10)*.08+(100-r.maritime.dryDockDue*5)*.20,0,100);r.maritime.eexi=r.maritime.eexiReadiness>=70?'Compliant':'Action required';r.maritime.dryDockDue=sea.filter(a=>Number(a.condition)<70).length;r.maritime.avgBunkerCost=r.economy.bunker;
    r.maritime.waitingHours=clamp((100-r.maritime.utilization)*.18+r.maritime.dryDockDue*6,0,96);r.maritime.demurrage=Math.round(r.maritime.waitingHours*Math.max(0,sea.length)*1200);

    const hubs=(state.customHubs||[]).filter(h=>['logistics','depot'].includes(h.kind)||h.company==='road').length;
    r.logistics.warehouseUtilization=clamp(road.length/Math.max(1,hubs*14)*100,0,100);const weakRoad=road.filter(a=>Number(a.condition)<70).length;
    r.logistics.onTime=clamp(97-(r.logistics.warehouseUtilization>90?(r.logistics.warehouseUtilization-90)*.45:0)-weakRoad*1.5,60,99);r.logistics.emptyMiles=clamp(22-road.length*.25+hubs*.3,7,35);r.logistics.damageRate=clamp(.45+road.filter(a=>Number(a.condition)<75).length*.12,.2,5);r.logistics.orderCycleHours=clamp(30+(r.logistics.warehouseUtilization-70)*.25,12,72);r.logistics.throughput=Math.round(road.length*18*(r.logistics.onTime/100));
    r.logistics.customsHours=clamp(7+(100-r.logistics.onTime)*.22+(r.economy.freight-100)*.03,3,48);r.logistics.customsScore=clamp(5-r.logistics.customsHours/16,1,5);r.logistics.shipmentScore=clamp(3.9-(Math.max(0,r.economy.freight-100)*.012)-r.logistics.emptyMiles*.018+Math.min(0.7,road.length*.012),1,5);r.logistics.trackingScore=clamp(2.8+(state.advanced?.cyber?.coverage||70)/100*1.4-r.logistics.damageRate*.08,1,5);r.logistics.infrastructureScore=clamp(2.6+Math.min(1,hubs/8)*1.5-Math.max(0,r.logistics.warehouseUtilization-92)*.03,1,5);r.logistics.serviceScore=clamp(2.8+(100-r.logistics.emptyMiles)/100*1.3+(r.logistics.onTime-80)*.02,1,5);r.logistics.timelinessScore=clamp(1+r.logistics.onTime/25,1,5);r.logistics.lpiProxy=(r.logistics.customsScore+r.logistics.shipmentScore+r.logistics.trackingScore+r.logistics.infrastructureScore+r.logistics.serviceScore+r.logistics.timelinessScore)/6;r.logistics.networkBalance=clamp(100-r.logistics.emptyMiles-Math.max(0,r.logistics.warehouseUtilization-85)*.6,0,100);

    const e=state.energy||{},gasMW=Number(e.gasMW)||0,solarMW=Number(e.solarMW)||0,windMW=Number(e.windMW)||0,totalMW=gasMW+solarMW+windMW,renewableMW=solarMW+windMW,availability=clamp(Number(e.availability)||90,0,100);
    const weatherFactor=clamp(.74+rand(`energy:${day}:weather`,-.08,.08),.58,.90),thermalFactor=.72;r.energy.capacityFactor=totalMW?clamp(((gasMW*thermalFactor+renewableMW*weatherFactor)/totalMW)*(availability/100)*100,0,100):0;r.energy.availableMW=totalMW*availability/100;r.energy.renewableShare=totalMW?renewableMW/totalMW*100:0;
    const storageMWh=Math.max(0,Number(e.storageMWh)||0),spread=Math.max(0,r.economy.electricity-r.economy.gas),beforeSoc=r.energy.storageSoc;
    if(storageMWh>0&&spread>25&&r.energy.storageSoc>20){r.energy.storageSoc=clamp(r.energy.storageSoc-8,5,100);r.energy.cycles+=.08;}else if(storageMWh>0&&r.economy.electricity<75&&r.energy.storageSoc<90){r.energy.storageSoc=clamp(r.energy.storageSoc+7,0,100);r.energy.cycles+=.07;}
    r.energy.roundTripEfficiency=clamp(86-r.energy.degradation*.10,78,90);r.energy.degradation=clamp(1+r.energy.cycles*.012,1,20);r.energy.storageHealth=clamp(100-r.energy.degradation,60,100);r.energy.effectiveStorageMWh=storageMWh*r.energy.storageHealth/100;r.energy.storageThroughputMWh=Math.abs(r.energy.storageSoc-beforeSoc)/100*r.energy.effectiveStorageMWh;r.energy.roundTripLossMWh=r.energy.storageThroughputMWh*(1-r.energy.roundTripEfficiency/100);r.energy.reserveMargin=totalMW?clamp((r.energy.availableMW-(totalMW*.78))/Math.max(1,totalMW*.78)*100,-50,80):0;r.energy.curtailment=clamp(Math.max(0,r.energy.renewableShare-55)*.08+Math.max(0,r.energy.storageSoc-92)*.1,0,25);
  }
  function bankingMetrics(state){
    const r=migrate(state),b=state.bank||{},deposits=Math.max(1,Number(b.deposits)||0),loans=Math.max(0,Number(b.loans)||0),offBalance=Math.max(0,Number(b.offBalance)||0),nplPct=clamp(Number(b.npl)||0,0,100);
    const creditRwa=loans*.72,offBalanceRwa=offBalance*.35,operationalRwa=Math.max(0,(Number(b.branches)||0)*2500000),rwa=Math.max(1,creditRwa+offBalanceRwa+operationalRwa),reportedCapitalRatio=clamp(Number(b.capitalRatio)||16.4,0,40),capital=reportedCapitalRatio/100*rwa,hqla=Math.max(0,Number(b.hqla)||0);
    const stressedOutflows=Math.max(1,deposits*.18+(Number(b.wholesaleFunding)||0)*.25),lcr=clamp(hqla/stressedOutflows*100,0,400),stableFunding=Math.max(0,Number(b.stableFunding)||0),requiredStable=Math.max(1,Number(b.requiredStableFunding)||loans*.85),nsfr=clamp(stableFunding/requiredStable*100,0,300),cet1=capital/rwa*100,tier1=cet1+1,totalCapital=cet1+2.4,nplAmount=loans*nplPct/100,provisions=Math.max(0,Number(b.provisions)||0);
    return {rwa,cet1,tier1,totalCapital,hqla,stressedOutflows,lcr,stableFunding,requiredStable,nsfr,npl:nplPct,loanDeposit:loans/deposits*100,costOfRisk:nplPct*.55,provisionCoverage:nplAmount?clamp(provisions/nplAmount*100,0,500):250,cet1Headroom:cet1-(r.banking.cet1RegMin+r.banking.capitalConservationBuffer),lcrHeadroom:lcr-100,nsfrHeadroom:nsfr-100,stableFundingBuffer:stableFunding-requiredStable,distributionRestricted:cet1<(r.banking.cet1RegMin+r.banking.capitalConservationBuffer)};
  }
  function updateBank(state){const r=migrate(state),m=bankingMetrics(state);Object.assign(r.banking,m);}
  function updateMarketShare(state,day){const r=migrate(state),counts={air:0,sea:0,road:0,power:0,bank:0};for(const a of (state.assets||[]))counts[a.type]=(counts[a.type]||0)+1;for(const t of SECTORS){const infra=t==='power'?((state.energy?.gasMW||0)+(state.energy?.solarMW||0)+(state.energy?.windMW||0))/200:t==='bank'?(state.bank?.branches||0):counts[t];const rep=r.reputation[t]||70,pressure=r.market.competitorPressure[t]||50;r.market.share[t]=clamp(2+infra*1.15+(rep-65)*.18-pressure*.035,0.5,42);if(day-r.market.lastResponseDay>=7){const share=r.market.share[t];r.market.competitorPressure[t]=clamp(45+share*1.15+rand(`${day}:${t}:pressure`,-5,6),20,95);}}if(day-r.market.lastResponseDay>=7)r.market.lastResponseDay=day;}
  function updateRisk(state,day){
    const r=migrate(state),s=r.financial.consolidated||{},netDebt=Math.max(0,(Number(state.debt)||0)-(Number(state.cash)||0)),ebitda=Math.max(1,Number(s.ebitda)||1),lev=netDebt/ebitda,liq=Number(state.cash)||0,issues=[];
    if(lev>r.risk.limits.netDebtEbitda)issues.push({id:'LEV',severity:'high',title:'الرافعة المالية أعلى من شهية المخاطر',value:lev.toFixed(2)+'x'});
    if(liq<r.risk.limits.minLiquidity)issues.push({id:'LIQ',severity:'high',title:'السيولة أقل من الحد الوقائي',value:money(liq)});
    if(r.banking.cet1<r.banking.cet1RegMin)issues.push({id:'CET1-REG',severity:'critical',title:'CET1 دون الحد التنظيمي الأساسي',value:r.banking.cet1.toFixed(1)+'%'});else if(r.banking.cet1<r.risk.limits.minBankCapital)issues.push({id:'CET1',severity:'high',title:'CET1 دون الحد الداخلي للمجموعة',value:r.banking.cet1.toFixed(1)+'%'});if(r.banking.tier1<r.banking.tier1RegMin)issues.push({id:'TIER1-REG',severity:'critical',title:'Tier 1 دون الحد الأساسي',value:r.banking.tier1.toFixed(1)+'%'});if(r.banking.totalCapital<r.banking.totalCapitalRegMin)issues.push({id:'TCAP-REG',severity:'critical',title:'إجمالي رأس المال دون الحد الأساسي',value:r.banking.totalCapital.toFixed(1)+'%'});if(r.banking.distributionRestricted)issues.push({id:'CET1-BUFFER',severity:'medium',title:'CET1 داخل نطاق حماية رأس المال؛ التوزيعات تحتاج تحفظًا',value:r.banking.cet1.toFixed(1)+'%'});
    if(r.banking.lcr<100)issues.push({id:'LCR',severity:'high',title:'LCR دون 100%',value:r.banking.lcr.toFixed(0)+'%'});if(r.banking.nsfr<100)issues.push({id:'NSFR',severity:'high',title:'NSFR دون 100%',value:r.banking.nsfr.toFixed(0)+'%'});if(r.banking.provisionCoverage<80&&r.banking.npl>2)issues.push({id:'PROV',severity:'medium',title:'تغطية مخصصات القروض المتعثرة منخفضة',value:r.banking.provisionCoverage.toFixed(0)+'%'});
    if(r.aviation.maintenanceDue>0)issues.push({id:'MNT-AIR',severity:'medium',title:'طائرات تستحق صيانة',value:String(r.aviation.maintenanceDue)});if(r.aviation.dispatchReliability<94)issues.push({id:'AIR-REL',severity:'high',title:'اعتمادية الإقلاع منخفضة',value:r.aviation.dispatchReliability.toFixed(1)+'%'});if(r.aviation.maintenanceReserveCoverage<75)issues.push({id:'AIR-MRES',severity:'medium',title:'احتياطي الصيانة لا يغطي التعرض الفني',value:r.aviation.maintenanceReserveCoverage.toFixed(0)+'%'});
    if(r.maritime.correctiveAction)issues.push({id:'CII',severity:r.maritime.cii==='E'?'high':'medium',title:'تصنيف CII يحتاج خطة تصحيح',value:r.maritime.cii});if(r.maritime.eexiReadiness<70)issues.push({id:'EEXI',severity:'medium',title:'جاهزية EEXI منخفضة',value:r.maritime.eexiReadiness.toFixed(0)+'/100'});
    if(r.logistics.warehouseUtilization>92)issues.push({id:'WH',severity:'medium',title:'تشبع مراكز اللوجستيات',value:r.logistics.warehouseUtilization.toFixed(0)+'%'});if(r.logistics.lpiProxy<3)issues.push({id:'LPI',severity:'medium',title:'جودة الشبكة اللوجستية منخفضة',value:r.logistics.lpiProxy.toFixed(2)+'/5'});
    if(r.energy.storageSoc<10||r.energy.storageSoc>95)issues.push({id:'ESS-SOC',severity:'medium',title:'SOC التخزين خارج نطاق التشغيل المفضل',value:r.energy.storageSoc.toFixed(0)+'%'});if(r.energy.reserveMargin<0)issues.push({id:'PWR-RES',severity:'high',title:'هامش القدرة المتاحة سلبي',value:r.energy.reserveMargin.toFixed(1)+'%'});
    r.risk.register=issues;r.risk.lastReviewDay=day;
  }
  function updateRating(state){const r=migrate(state),s=r.financial.consolidated||{},ebitda=Number(s.ebitda)||0,enterprise=Math.max(1,Number(state.groupValue)||Number(s.assets)||1),lev=ebitda>1000000?(Number(state.debt)||0)/ebitda:(Number(state.debt)||0)/enterprise*2,liq=(Number(state.cash)||0)/Math.max(1,Number(state.debt)||1),operatingAdj=(Number(s.revenue)||0)<1000000?0:(s.net>0?5:-8),score=clamp(72-lev*7+Math.min(12,liq*5)+operatingAdj-r.risk.register.length*2,32,95);r.rating.score=Math.round(score);r.rating.grade=score>=82?'A':score>=74?'A-':score>=66?'BBB+':score>=58?'BBB':score>=50?'BBB-':score>=42?'BB+':'BB';r.rating.outlook=r.risk.register.some(x=>x.severity==='high')?'Negative':s.net>0?'Stable':'Negative';globalThis.GH_CORPORATE_CORE?.execute?.({state},'set-credit-rating',{grade:r.rating.grade});}
  function updateInsurance(state){
    const r=migrate(state),condition=(state.assets||[]).length?(state.assets||[]).reduce((n,a)=>n+(Number(a.condition)||100),0)/(state.assets||[]).length:100,incidents=(state.advanced?.safety?.incidents||0),claims=(state.advanced?.insurance?.claims||[]),openClaims=claims.filter(c=>!['مدفوع','مغلق','مرفوض'].includes(c.status)).length,paid=claims.filter(c=>c.status==='مدفوع').reduce((n,c)=>n+(Number(c.paid)||0),0),reserve=claims.reduce((n,c)=>n+(Number(c.reserve)||0),0);
    r.insurance.claimsTrend=clamp((100-condition)*.12+incidents*1.4+openClaims*.8,0,35);r.insurance.renewalIndex=clamp(92+r.insurance.claimsTrend*2+(r.risk.register.length*1.5)+(reserve?paid/Math.max(1,reserve)*12:0),75,190);
  }
  function supplierScores(state){const r=migrate(state);for(const tx of (state.supplierTransactions||[])){const id=tx.supplierId||tx.supplier||'unknown';const x=r.procurement.supplierScores[id]||(r.procurement.supplierScores[id]={name:tx.supplier||id,spend:0,transactions:0,score:82});x.spend+=Number(tx.amount)||0;x.transactions++;x.score=clamp(88-rand(`${id}:${x.transactions}`,0,10),60,98);}}
  function enrichProcurement(state,day){const r=migrate(state),req=state.advanced?.procurement?.assetRequests||[];for(const p of req){let q=r.procurement.pipeline.find(x=>x.sourceId===p.id);if(!q){q={id:`PRC2-${p.id}`,sourceId:p.id,company:p.type||p.company||'group',title:p.title||p.id,stage:'Requisition',createdDay:day,technicalScore:Math.round(rand(`${p.id}:tech`,72,96)),commercialScore:Math.round(rand(`${p.id}:com`,68,95)),leadDays:r.procurement.leadTimes[p.type]||30};r.procurement.pipeline.push(q);}const st=String(p.status||'');q.stage=st==='completed'?'Delivered':st==='delivering'?'PO / Delivery':st==='readiness'?'Operational Readiness':['authorized','blocked_funding','ordering'].includes(st)?'Approval / Funding':st==='awaiting_authorization'?'Approval':'Evaluation';}}
  function updateTaxFxAndDividends(state,day){const r=migrate(state),countries=new Set((state.globalBases||[]).map(x=>x.country||x.countryCode).filter(Boolean)),baseTax=.15+Math.min(.07,countries.size*.005);r.taxFx.taxRate=baseTax;r.taxFx.fxExposure=Number(state.advanced?.treasury?.fxExposure)||Math.max(0,(Number(state.debt)||0)*.28);r.taxFx.hedgedPct=Number(state.advanced?.treasury?.hedgeRatio)||0;const floor=r.risk.limits.minLiquidity,excess=Math.max(0,(Number(state.cash)||0)-floor);r.dividends.available=Math.round(excess*.35);}
  function updatePrograms(state,day){
    const r=migrate(state);globalThis.GH_GOVERNANCE_CORE?.execute?.({state},'tick-sustainability',{day});
    const research=state.research||{};r.controls.researchEffects={efficiency:clamp((Number(research.efficiency)||0)/100,0,1),automation:clamp((Number(research.automation)||0)/100,0,1),cleanEnergy:clamp((Number(research.cleanEnergy)||0)/100,0,1)};
  }
  function updateReputation(state){
    const r=migrate(state);r.reputation.air=Math.round(clamp(58+r.aviation.otp*.18+r.aviation.dispatchReliability*.12-r.aviation.aog*2,40,96));r.reputation.sea=Math.round(clamp(68+(r.maritime.cii==='A'?12:r.maritime.cii==='B'?8:r.maritime.cii==='C'?2:-7)+(r.maritime.utilization-60)*.08-r.maritime.dryDockDue*.8,40,96));r.reputation.road=Math.round(clamp(55+r.logistics.onTime*.20+r.logistics.lpiProxy*4-r.logistics.damageRate*2,40,96));r.reputation.power=Math.round(clamp(64+r.energy.capacityFactor*.15+r.energy.storageHealth*.08-r.energy.curtailment*.45+Math.min(8,r.energy.reserveMargin*.08),40,96));r.reputation.bank=Math.round(clamp(70-r.banking.npl*2+(r.banking.lcr-100)*.035+(r.banking.nsfr-100)*.025+Math.min(6,r.banking.cet1Headroom*.6),40,96));r.reputation.group=Math.round(SECTORS.reduce((n,t)=>n+r.reputation[t],0)/SECTORS.length);globalThis.GH_CORPORATE_CORE?.execute?.({state},'set-reputation',{value:r.reputation.group});
  }
  const DELIVERY_WINDOW_SECONDS=Object.freeze({air:90,sea:150,road:60});
  function compatibleDeliveryFacilities(state,type){
    const globals=Array.isArray(state.globalBases)?state.globalBases:[],hubs=Array.isArray(state.customHubs)?state.customHubs:[];
    const rows=[...globals,...hubs].filter(f=>f&&f.owned!==false);
    return rows.filter(f=>type==='air'?(['airport','airport-base'].includes(f.kind)||f.company==='air'):type==='sea'?(['port','port-base'].includes(f.kind)||f.company==='sea'):(['depot','logistics'].includes(f.kind)||f.company==='road'));
  }
  function deliveryCapacity(state,facility){
    const modeled=Number(state.advanced?.facilities?.[facility.id]?.capacity),fallback=['airport','airport-base'].includes(facility.kind)?24:['port','port-base'].includes(facility.kind)?18:['depot','logistics'].includes(facility.kind)?Number(facility.bays||42):12;
    return Number.isFinite(modeled)&&modeled>0?modeled:Math.max(1,Number(fallback)||1);
  }
  function deliveryBaseHasRoom(state,facility,deliveryId){
    const occupied=(state.assets||[]).filter(a=>a.baseFacility===facility.id).length,pending=(state.realism?.procurement?.deliveries||[]).filter(x=>x.id!==deliveryId&&x.status==='pending'&&x.baseId===facility.id).length;
    return occupied+pending<deliveryCapacity(state,facility);
  }
  function resolveDeliveryBase(state,d,snap){
    // Build246: وجهة الطلب عقد ثابت. لا إعادة توجيه صامتة إلى قاعدة أخرى.
    const exact=compatibleDeliveryFacilities(state,snap.type).find(f=>f.id===d.baseId);
    if(!exact||!deliveryBaseHasRoom(state,exact,d.id))return null;
    return exact;
  }
  function normalizeDeliveryClock(state,d){
    const now=Math.max(0,Number(state.simSeconds)||0),base=Math.max(60,DELIVERY_WINDOW_SECONDS[d.type]||600);
    if(!Number.isFinite(Number(d.orderedAtSeconds)))d.orderedAtSeconds=Math.max(0,Math.min(now,Number(d.orderedDay||0)*86400));
    if(!Number.isFinite(Number(d.dueAtSeconds))){
      const legacyDue=Number(d.dueDay);
      const legacySeconds=Number.isFinite(legacyDue)?legacyDue*86400:Infinity;
      d.dueAtSeconds=Math.min(legacySeconds,now+base);
    }
    if(Number(d.dueAtSeconds)<Number(d.orderedAtSeconds))d.dueAtSeconds=Number(d.orderedAtSeconds)+base;
    return d;
  }
  function deliverDueAssetsAt(state,simSeconds){
    const r=migrate(state),deliveries=r.procurement.deliveries||[],now=Math.max(0,Number(simSeconds)||Number(state.simSeconds)||0),day=Math.floor(now/86400);
    for(const d of deliveries){
      if(d.status!=='pending')continue;normalizeDeliveryClock(state,d);if(Number(d.dueAtSeconds)>now)continue;
      const snap=d.asset||{},existing=(state.assets||[]).find(a=>a.id===snap.id);if(existing){if(existing.baseFacility!==d.baseId||existing.deliveryOrderId!==d.id)throw new Error('existing-delivery-evidence-mismatch');d.status='delivered';d.deliveredAtSeconds=now;continue;}
      const base=resolveDeliveryBase(state,d,snap);
      if(!base){d.blockedReason='approved-destination-missing-or-full';d.lastCheckedAt=now;if(!Number.isFinite(Number(d.lastBlockedAlertAt))||now-Number(d.lastBlockedAlertAt)>=300){d.lastBlockedAlertAt=now;if(Array.isArray(state.alerts))state.alerts.unshift(`${snap.name||'أصل جديد'}: التسليم بانتظار قاعدة/مركز مملوك متوافق مع ${names[snap.type]||snap.type}. لن يعيد النظام توجيه الأصل تلقائيًا؛ سيبقى الطلب معلقًا على نفس الوجهة ويعيد المحاولة بعد معالجة السعة.`);}continue;}
      const tx=globalThis.GH_TRANSACTION_CORE;if(!tx?.execute)throw new Error('delivery-transaction-unavailable');
      (tx.isActive()?tx.join:tx.execute)(state,{label:`asset-delivery:${d.id}`,apply:()=>{
      d.blockedReason=null;
      const company=state.companyRegistry?.[snap.type]?.legalName||names[snap.type]||snap.company||'شركة تشغيلية';
      const delivered=globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'fleet','record-delivery',{deliveryId:d.id,asset:{...snap,company},baseId:base.id,phase:'idle',deliveredDay:day,deliveredAtSeconds:now},{actor:'delivery-engine'});
      if(!delivered?.ok)throw new Error(`delivery-owner-rejected:${d.id}`);
      globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'corporate','adjust-group-value',{delta:snap.ownership==='lease'?(Number(snap.purchasePrice)||0)*.08:(Number(snap.purchasePrice)||0)*.86},{actor:'delivery-engine'});
      d.status='delivered';d.deliveredDay=day;d.deliveredAtSeconds=now;
      globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'operations','record-alert',{text:`تم استلام ${snap.name} فعليًا في ${base.name||d.destination||'القاعدة'} ووضعه داخل المركز التشغيلي المحدد. الأصل جاهز للتجهيز والتشغيل.`,type:'delivery'},{actor:'delivery-engine'});
      }});
    }
    const pending=deliveries.filter(x=>x.status==='pending'),history=deliveries.filter(x=>x.status!=='pending');r.procurement.deliveries=[...pending,...history];return deliveries.filter(x=>x.status==='delivered'&&Number(x.deliveredAtSeconds)===now).length;
  }
  function deliverDueAssets(state,day){return deliverDueAssetsAt(state,Math.max(Number(state.simSeconds)||0,Number(day||0)*86400));}
  function updateProjects(state,day){const r=migrate(state),source=state.constructionContracts||[];for(const c of source){let p=r.projects.find(x=>x.sourceId===c.id);if(!p){const total=c.facilityKind==='power'?540:c.facilityKind==='hq'?120:c.facilityKind==='bank'?90:180;p={id:`CAPEX-${c.id}`,sourceId:c.id,company:c.company||'group',title:c.siteName||c.facilityKind,budget:Number(c.amount)||0,startDay:Math.floor((Number(c.awardedAt)||0)/86400),totalDays:total,stage:'Construction',progress:0,status:'Active'};r.projects.push(p);}const elapsed=Math.max(0,day-p.startDay);p.progress=clamp(elapsed/p.totalDays*100,0,100);p.stage=p.progress<10?'Permits & mobilization':p.progress<70?'Construction':p.progress<95?'Commissioning':'Operational';if(p.progress>=100){p.status='Completed';if(c.company==='power'&&c.capacityKey&&c.capacityAmount&&!c.commissioned){globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'facilities','commission-energy',{key:c.capacityKey,amount:Number(c.capacityAmount)||0},{actor:'project-commissioning'});globalThis.GH_PROCUREMENT_CORE?.execute?.({state},'complete-construction',{id:c.id,status:'مكتمل / مشغل'});globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'corporate','adjust-group-value',{delta:(Number(c.amount)||0)*.44},{actor:'project-commissioning'});globalThis.GH_DOMAIN_COMMANDS?.dispatch?.({state},'operations','record-alert',{text:`اكتمل Commissioning لمشروع ${c.siteName||p.title}. أضيفت القدرة الجديدة إلى التشغيل الفعلي.`,type:'commissioning'},{actor:'project-commissioning'});}}}}
  function updateEventQueue(state,day){const r=migrate(state),q=r.eventQueue,add=(id,at,type,title)=>{if(!q.some(x=>x.id===id))q.push({id,at,type,title,status:'pending'});};for(const c of (state.finance?.cheques||[]))if(c.status==='صادر')add(`CHQ:${c.id}`,Number(c.dueDay)||day,'payment',`استحقاق ${c.id}`);for(const p of (state.finance?.periods||[]))if(p.status==='مستحق')add(`TAX:${p.id}`,Number(p.dueDay)||day,'tax',`استحقاق ضريبة ${p.company||'group'}`);for(const x of [...(state.bank?.lettersOfCredit||[]),...(state.bank?.guarantees||[])])if(x.status==='ساري')add(`TF:${x.id}`,Number(x.expiryDay)||day,'trade-finance',`انتهاء ${x.id}`);for(const x of q)if(x.status==='pending'&&Number(x.at)<=day)x.status='due';q.sort((a,b)=>(a.at||0)-(b.at||0));if(q.length>300)q.splice(300);}
  function businessCases(state,day){const r=migrate(state),requests=state.advanced?.ai?.requests||[];for(const q of requests.filter(x=>String(x.status||'').includes('انتظار'))){const cost=Math.max(0,Number(q.cost)||0),company=q.company||'group',profit=Math.max(0,Number(state.sectorProfitToday?.[company])||0),baseBenefit=Math.max(cost*.08,profit*365*.15,250000),riskAdj=1-clamp(r.risk.register.length*.04,0,.35),annual=baseBenefit*riskAdj,rate=r.ai.hurdleRate,years=5,npv=-cost;for(let y=1;y<=years;y++)npv+=annual/Math.pow(1+rate,y);const irr=cost?annual/cost:1,payback=annual?cost/annual:0,score=clamp(50+(npv>0?18:-18)+(irr-rate)*100-r.risk.register.length*2,0,100),recommend=cost===0?'Recommend':score>=70?'Recommend':score>=55?'Conditional':'Reject';r.ai.businessCases[q.id]={requestId:q.id,company,cost,annualBenefit:annual,npv,irr,payback,score:Math.round(score),recommend,base:{npv},upside:{npv:npv+annual*.9},downside:{npv:npv-annual*1.1},day};globalThis.GH_AI_EXECUTIVE_CORE?.execute?.({state},'attach-study-result',{id:q.id,score,businessCaseId:q.id});}}
  function board(state,day){const r=migrate(state);if(day<r.board.nextMeetingDay)return;const s=r.financial.consolidated||{},m={id:`BRD-${day}`,day,agenda:['الأداء المالي','المخاطر','السيولة','الاستثمار','السلامة','رأس مال البنك'],net:Number(s.net)||0,riskCount:r.risk.register.length,rating:r.rating.grade,status:'مكتمل'};r.board.meetings.unshift(m);r.board.meetings=r.board.meetings.slice(0,24);r.board.nextMeetingDay=day+30;}
  function succession(state){const r=migrate(state),roles=['CEO','CFO','COO','CRO','CHRO','CTO','General Counsel'];for(const role of roles){if(!r.people.succession[role])r.people.succession[role]={coverage:Math.round(rand(`succ:${role}`,55,92)),readyNow:rand(`succ-ready:${role}`)>0.55?'نعم':'خلال 12-24 شهر'};}}
  function morningBrief(state,day){const r=migrate(state);if(r.morningBriefs[0]?.day===day)return;const s=r.financial.consolidated||{},topRisks=r.risk.register.slice(0,3),pending=(state.advanced?.ai?.requests||[]).filter(x=>String(x.status||'').includes('انتظار')).length,brief={day,net:Number(s.net)||0,cash:Number(state.cash)||0,risks:topRisks.map(x=>x.title),pending,headline:topRisks.length?`أولوية اليوم: ${topRisks[0].title}`:pending?`${pending} طلب اعتماد يحتاج قرارك`:'التشغيل ضمن الحدود الوقائية'};r.morningBriefs.unshift(brief);r.morningBriefs=r.morningBriefs.slice(0,30);}
  function causalEvent(state,hour){const r=migrate(state),day=Math.floor(hour/24);if(hour%72!==0)return;const roll=rand(`event:${Math.floor(hour/72)}`),e=r.economy;let ev=null;if(roll<.22){ev={id:`EV2-${hour}`,type:'oil',title:'اضطراب في إمدادات الطاقة',oil:+12,freight:+5,airDemand:-3,seaDemand:-1,duration:48};}else if(roll<.40){ev={id:`EV2-${hour}`,type:'ports',title:'ازدحام في ممرات بحرية رئيسية',freight:+14,bunker:+4,seaDemand:-2,duration:72};}else if(roll<.57){ev={id:`EV2-${hour}`,type:'rates',title:'تشدد ائتماني عالمي',baseRate:+.006,airDemand:-2,roadDemand:-2,duration:96};}else if(roll<.72){ev={id:`EV2-${hour}`,type:'growth',title:'ارتفاع في الطلب التجاري العالمي',airDemand:+5,seaDemand:+6,roadDemand:+5,powerDemand:+3,duration:72};}if(ev){e.lastEvent=ev;e.eventHistory.unshift({...ev,day});e.eventHistory=e.eventHistory.slice(0,30);for(const [k,v] of Object.entries(ev))if(typeof v==='number'&&k!=='duration')e[k]=Math.max(0,(Number(e[k])||0)+v);}}
  function onHour(state,hour){const r=migrate(state),e=r.economy;causalEvent(state,hour);const oilDrift=(78-e.oil)*.006+rand(`${hour}:oil`,-.8,.8);e.oil=clamp(e.oil+oilDrift,35,180);e.jetFuel=clamp(.52+e.oil*.0045+rand(`${hour}:jet`,-.006,.006),.45,1.75);e.bunker=clamp(300+e.oil*4.2+rand(`${hour}:bun`,-4,4),280,1200);e.diesel=clamp(.48+e.oil*.006+rand(`${hour}:dies`,-.008,.008),.5,2.0);e.gas=clamp(e.gas+(39-e.gas)*.01+rand(`${hour}:gas`,-.5,.5),15,120);e.electricity=clamp(36+e.gas*.75+rand(`${hour}:elec`,-2.2,2.2),30,190);e.freight=clamp(e.freight+(100-e.freight)*.008+rand(`${hour}:freight`,-1.3,1.3),55,220);e.baseRate=clamp(e.baseRate+(0.046-e.baseRate)*.003+rand(`${hour}:rate`,-.0002,.0002),.005,.16);e.usdIndex=clamp(e.usdIndex+(100-e.usdIndex)*.005+rand(`${hour}:usd`,-.25,.25),80,130);for(const k of ['airDemand','seaDemand','roadDemand','powerDemand'])e[k]=clamp(e[k]+(100-e[k])*.01+rand(`${hour}:${k}`,-.4,.4),65,145);if(hour%12===0)businessCases(state,Math.floor(hour/24));globalThis.GH_MARKET_CORE?.execute?.({state},'sync-economy',{values:{electricityPriceMWh:e.electricity,gasCostMWh:e.gas,baseRate:e.baseRate,freightIndex:e.freight}});}
  function integrity(state,day){const r=migrate(state),issues=[];for(const t of TYPES){const b=books(state,t);if(!b||!Array.isArray(b.accounts))issues.push(`دفتر ${t} غير صالح`);else if(b.accounts.some(a=>!Number.isFinite(Number(a.balance))))issues.push(`رصيد غير رقمي في ${t}`);}const ids=new Set();for(const a of (state.assets||[])){if(!a.id||ids.has(a.id))issues.push('معرف أصل مكرر');ids.add(a.id);}const qids=new Set();for(const q of r.eventQueue){if(qids.has(q.id))issues.push('حدث زمني مكرر');qids.add(q.id);}r.controls.issues=issues;r.controls.lastIntegrityDay=day;return issues;}
  function onDay(state,day){const r=migrate(state);closeFinancials(state,day);updateBudgets(state,day);updateOps(state,day);updateBank(state);updateMarketShare(state,day);updateRisk(state,day);updateRating(state);updateInsurance(state);updateTaxFxAndDividends(state,day);updatePrograms(state,day);updateReputation(state);supplierScores(state);enrichProcurement(state,day);deliverDueAssets(state,day);updateProjects(state,day);updateEventQueue(state,day);businessCases(state,day);board(state,day);succession(state);morningBrief(state,day);integrity(state,day);return 0;}
  function tripModifier(state,asset,eco){
    const r=migrate(state),e=r.economy,share=r.market.share[asset.type]||5,pressure=r.market.competitorPressure[asset.type]||50,rep=r.reputation[asset.type]||70;let demand=asset.type==='air'?e.airDemand:asset.type==='sea'?e.seaDemand:e.roadDemand;const demandFactor=clamp((demand/100)*(1+(rep-70)*.003)*(1+(share-5)*.006)*(1-(pressure-50)*.0015),.65,1.35);eco.revenue*=demandFactor;
    if(asset.type==='air')eco.fuelCost*=e.jetFuel/.86;else if(asset.type==='sea')eco.fuelCost*=e.bunker/640;else eco.fuelCost*=e.diesel/.98;
    const research=state.research||{},eff=clamp((Number(research.efficiency)||0)/100,0,1),auto=clamp((Number(research.automation)||0)/100,0,1),clean=clamp((Number(research.cleanEnergy)||0)/100,0,1),su=state.sustainability||{};
    eco.fuelCost*=1-eff*.055-clean*.018;eco.maintReserve*=1-eff*.045;eco.crewCost*=1-auto*.025;
    if(asset.type==='air'&&(Number(su.safShare)||0)>0)eco.fuelCost*=1-Math.min(.03,(Number(su.safShare)||0)/100*.03);if(asset.type==='road'&&(Number(su.electricRoadShare)||0)>0)eco.fuelCost*=1-Math.min(.08,(Number(su.electricRoadShare)||0)/100*.08);
    eco.margin=eco.revenue-eco.fuelCost-eco.crewCost-eco.maintReserve;eco.cashContribution=eco.revenue-eco.fuelCost-eco.maintReserve;eco.market={demandFactor,share,pressure};eco.capabilityEffects={efficiencyResearch:eff,automationResearch:auto,cleanEnergyResearch:clean};return eco;
  }
  function metric(label,value,cls=''){return `<div><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b></div>`;}
  function section(title,copy,body){return `<article class="list-item realism-section"><div class="list-item-head"><div><h3>${esc(title)}</h3><p>${esc(copy)}</p></div><span class="tag">2.0</span></div>${body}</article>`;}
  function render(ctx){const s=ctx.state,r=migrate(s);const f=r.financial.consolidated||{},b=r.banking,e=r.economy,br=r.morningBriefs[0]||{};return `<div class="workspace-intro realism-intro"><span>REALISM CORE 2.0</span><b>محاكاة مترابطة: اقتصاد → تشغيل → مالية → مخاطر → قرار.</b></div><div class="list">
    ${section('موجز الرئيس التنفيذي',br.headline||'لم يُغلق أول يوم مالي بعد.',`<div class="metric-row">${metric('صافي 30 يوم',money(f.net||0),(f.net||0)>=0?'positive':'negative')}${metric('السيولة',money(s.cash||0))}${metric('طلبات اعتماد',String(br.pending||0))}</div>${(br.risks||[]).length?`<div class="realism-alerts">${br.risks.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}`)}
    ${section('الاقتصاد العالمي الحي',e.lastEvent?.title||'الأسعار والطلب يتحركان بصورة مترابطة وغير عشوائية منفصلة.',`<div class="metric-row">${metric('النفط','$'+e.oil.toFixed(1))}${metric('Jet Fuel','$'+e.jetFuel.toFixed(2)+'/kg')}${metric('Bunker','$'+Math.round(e.bunker)+'/t')}</div><div class="metric-row">${metric('Freight Index',e.freight.toFixed(0))}${metric('الفائدة',(e.baseRate*100).toFixed(2)+'%')}${metric('طلب الطيران',e.airDemand.toFixed(0))}</div>`)}
    ${section('القوائم المالية الموحدة','قائمة دخل وميزانية وتدفقات نقدية مع استبعاد المعاملات الداخلية.',`<div class="metric-row">${metric('الإيراد',money(f.revenue||0))}${metric('EBITDA',money(f.ebitda||0))}${metric('صافي الربح',money(f.net||0),(f.net||0)>=0?'positive':'negative')}</div><div class="metric-row">${metric('الأصول',money(f.assets||0))}${metric('الالتزامات',money(f.liabilities||0))}${metric('إلغاءات داخلية',money(r.financial.intercompanyEliminations||0))}</div>`)}
    ${section('الطيران','ASK / RPK / Load Factor / Yield / CASK / RASK + Reliability / Health Monitoring.',`<div class="metric-row">${metric('Load Factor',r.aviation.loadFactor.toFixed(1)+'%')}${metric('OTP',r.aviation.otp.toFixed(1)+'%')}${metric('Dispatch',r.aviation.dispatchReliability.toFixed(1)+'%',r.aviation.dispatchReliability>=97?'positive':r.aviation.dispatchReliability<94?'negative':'')}</div><div class="metric-row">${metric('RASK',r.aviation.rask.toFixed(3))}${metric('CASK',r.aviation.cask.toFixed(3))}${metric('CASK ex-fuel',r.aviation.caskExFuel.toFixed(3))}</div><div class="metric-row">${metric('Utilization',r.aviation.utilization.toFixed(0)+'%')}${metric('Health',r.aviation.healthMonitoringScore.toFixed(0)+'/100')}${metric('MRO reserve',r.aviation.maintenanceReserveCoverage.toFixed(0)+'%')}</div>`)}
    ${section('البحرية','Utilization + CII/EEXI readiness + Dry Dock + Bunker/Waiting.',`<div class="metric-row">${metric('Utilization',r.maritime.utilization.toFixed(0)+'%')}${metric('CII',r.maritime.cii,r.maritime.correctiveAction?'negative':'positive')}${metric('EEXI readiness',r.maritime.eexiReadiness.toFixed(0)+'/100',r.maritime.eexiReadiness>=70?'positive':'negative')}</div><div class="metric-row">${metric('CII ratio',r.maritime.ciiRatio.toFixed(2)+'x')}${metric('Dry Dock',String(r.maritime.dryDockDue))}${metric('انتظار',r.maritime.waitingHours.toFixed(0)+'h')}</div><div class="metric-row">${metric('Bunker','$'+Math.round(r.maritime.avgBunkerCost)+'/t')}${metric('Demurrage',money(r.maritime.demurrage))}${metric('Corrective plan',r.maritime.correctivePlanStatus|| (r.maritime.correctiveAction?'مطلوب':'غير مطلوب'),r.maritime.correctiveAction?'negative':'positive')}</div>`)}
    ${section('اللوجستيات والمستودعات','On-time / Damage / Empty miles + جودة الجمارك والبنية والتتبع والتوقيت.',`<div class="metric-row">${metric('On-time',r.logistics.onTime.toFixed(1)+'%')}${metric('Utilization',r.logistics.warehouseUtilization.toFixed(0)+'%')}${metric('Empty miles',r.logistics.emptyMiles.toFixed(0)+'%')}</div><div class="metric-row">${metric('Damage',r.logistics.damageRate.toFixed(1)+'%')}${metric('Order cycle',r.logistics.orderCycleHours.toFixed(0)+'h')}${metric('Throughput',String(r.logistics.throughput))}</div><div class="metric-row">${metric('LPI proxy',r.logistics.lpiProxy.toFixed(2)+'/5',r.logistics.lpiProxy>=3.5?'positive':r.logistics.lpiProxy<3?'negative':'')}${metric('Customs',r.logistics.customsScore.toFixed(1)+'/5')}${metric('Shipments',r.logistics.shipmentScore.toFixed(1)+'/5')}${metric('Tracking',r.logistics.trackingScore.toFixed(1)+'/5')}</div>`)}
    ${section('الطاقة والتخزين','SOC / Round-trip efficiency / Storage health / Capacity factor / Reserve margin.',`<div class="metric-row">${metric('Storage SOC',r.energy.storageSoc.toFixed(0)+'%')}${metric('Efficiency',r.energy.roundTripEfficiency.toFixed(1)+'%')}${metric('Storage health',r.energy.storageHealth.toFixed(1)+'%')}</div><div class="metric-row">${metric('Capacity factor',r.energy.capacityFactor.toFixed(1)+'%')}${metric('Available MW',r.energy.availableMW.toFixed(0))}${metric('Reserve margin',r.energy.reserveMargin.toFixed(1)+'%',r.energy.reserveMargin>=0?'positive':'negative')}</div><div class="metric-row">${metric('Renewable mix',r.energy.renewableShare.toFixed(1)+'%')}${metric('Effective storage',r.energy.effectiveStorageMWh.toFixed(0)+' MWh')}${metric('Curtailment',r.energy.curtailment.toFixed(1)+'%')}</div>`)}
    ${section('البنك — Basel','CET1 / Tier 1 / RWA / LCR / NSFR / NPL + headroom والتغطية.',`<div class="metric-row">${metric('CET1',b.cet1.toFixed(1)+'%',b.cet1>=r.risk.limits.minBankCapital?'positive':'negative')}${metric('LCR',b.lcr.toFixed(0)+'%',b.lcr>=100?'positive':'negative')}${metric('NSFR',b.nsfr.toFixed(0)+'%',b.nsfr>=100?'positive':'negative')}</div><div class="metric-row">${metric('CET1 headroom',b.cet1Headroom.toFixed(1)+'pp',b.cet1Headroom>=0?'positive':'negative')}${metric('Tier 1',b.tier1.toFixed(1)+'%',b.tier1>=b.tier1RegMin?'positive':'negative')}${metric('Total capital',b.totalCapital.toFixed(1)+'%',b.totalCapital>=b.totalCapitalRegMin?'positive':'negative')}${metric('Provision cover',b.provisionCoverage.toFixed(0)+'%')}${metric('قروض/ودائع',b.loanDeposit.toFixed(0)+'%')}</div><div class="metric-row">${metric('RWA',money(b.rwa))}${metric('NPL',b.npl.toFixed(1)+'%')}${metric('Stable funding',money(b.stableFundingBuffer),b.stableFundingBuffer>=0?'positive':'negative')}</div>`)}
    ${section('Risk Appetite & Credit Rating',`التصنيف ${r.rating.grade} / ${r.rating.outlook}. كل اقتراح AI يُختبر مقابل حدود المخاطر.`,`<div class="metric-row">${metric('Rating',r.rating.grade)}${metric('Risk issues',String(r.risk.register.length),r.risk.register.some(x=>x.severity==='high')?'negative':'positive')}${metric('AI hurdle',(r.ai.hurdleRate*100).toFixed(0)+'%')}</div>${r.risk.register.length?`<div class="realism-risk-list">${r.risk.register.map(x=>`<div><b>${esc(x.title)}</b><span>${esc(x.value)}</span></div>`).join('')}</div>`:''}`)}
    ${section('المنافسة والسمعة','حصة السوق والضغط التنافسي تتغير حسب الأصول والسمعة والأداء.',`<div class="realism-mini-grid">${SECTORS.map(t=>`<div><span>${names[t]}</span><b>${r.market.share[t].toFixed(1)}%</b><small>ضغط ${r.market.competitorPressure[t].toFixed(0)}/100 · سمعة ${r.reputation[t]}</small></div>`).join('')}</div>`)}
    ${section('مجلس الإدارة والخلافة','اجتماع دوري، قرارات كبرى، وخطة بدلاء للمناصب الحرجة.',`<div class="metric-row">${metric('اجتماعات',String(r.board.meetings.length))}${metric('الاجتماع القادم','يوم '+r.board.nextMeetingDay)}${metric('Succession coverage',Math.round(Object.values(r.people.succession).reduce((n,x)=>n+(x.coverage||0),0)/Math.max(1,Object.keys(r.people.succession).length))+'%')}</div>`)}
    ${section('Procurement & المشاريع','Requisition → RFQ/RFP → تقييم → اعتماد → PO → تسليم، مع Lead Time.',`<div class="metric-row">${metric('Pipeline',String(r.procurement.pipeline.length))}${metric('مشاريع CAPEX',String(r.projects.length))}${metric('موردون مقيمون',String(Object.keys(r.procurement.supplierScores).length))}</div>`)}
    ${section('سلامة النواة','فحص وقائي يومي يمنع التكرار والأرصدة غير الرقمية والأحداث المكررة.',`<div class="metric-row">${metric('Integrity issues',String(r.controls.issues.length),r.controls.issues.length?'negative':'positive')}${metric('Schema',r.schema)}${metric('Core',r.version)}</div>${r.controls.issues.length?`<div class="realism-alerts">${r.controls.issues.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}`)}
  </div>`;}
  function financeHTML(state){const r=migrate(state);return `<article class="list-item realism-finance-appendix"><div class="list-item-head"><div><h3>القوائم المالية 2.0</h3><p>30 يومًا متحركًا · Consolidation مع استبعاد التعاملات الداخلية وLease liabilities.</p></div><span class="tag positive">${esc(r.rating.grade)}</span></div><div class="realism-mini-grid">${TYPES.map(t=>{const s=r.financial.statements[t]||{};return `<div><span>${esc(entityName(state,t))}</span><b>${money(s.net||0)}</b><small>إيراد ${money(s.revenue||0)} · أصول ${money(s.assets||0)}</small></div>`}).join('')}</div></article><article class="list-item realism-finance-appendix"><h3>Budget / Actual / Forecast / Variance</h3><div class="realism-budget-table">${TYPES.map(t=>{const b=r.budgets[t],plan=Object.values(b.lines).reduce((a,x)=>a+(Number(x)||0),0),actual=Object.values(b.actual).reduce((a,x)=>a+(Number(x)||0),0),forecast=Object.values(b.forecast).reduce((a,x)=>a+(Number(x)||0),0);return `<div><b>${esc(entityName(state,t))}</b><span>${money(plan)}</span><span>${money(actual)}</span><span>${money(forecast)}</span><span class="${forecast<=plan?'positive':'negative'}">${money(forecast-plan)}</span></div>`}).join('')}<div class="budget-head"><b>الشركة</b><span>Budget</span><span>Actual</span><span>Forecast</span><span>Variance</span></div></div></article>`;}
  window.GH_REALISM={VERSION,SCHEMA,migrate,onHour,onDay,onSimulationTime:deliverDueAssetsAt,tripModifier,render,financeHTML,statements,bankingMetrics};
})();
