(()=>{'use strict';const VERSION='2.9.0';
function ensure(s){s.customRoutes=Array.isArray(s.customRoutes)?s.customRoutes:[];s.routeEndpoints=s.routeEndpoints&&typeof s.routeEndpoints==='object'?s.routeEndpoints:{};s.routeCache=s.routeCache&&typeof s.routeCache==='object'?s.routeCache:{};return s;}
function signature(r){const key=c=>Array.isArray(c)?`${Number(c[0]).toFixed(3)},${Number(c[1]).toFixed(3)}`:'';const a=key(r?.route?.[0]),b=key(r?.route?.[r?.route?.length-1]);return `${r?.type||''}:${[a,b].sort().join('::')}`;}
function execute(ctx,cmd,p){const s=ctx.state||ctx;ensure(s);if(cmd==='create'){const route={...p.route};if(!route.id||!route.type||!Array.isArray(route.route)||route.route.length<2)throw new Error('invalid-route');const sig=signature(route);if(s.customRoutes.some(r=>signature(r)===sig))throw new Error('duplicate-route');s.customRoutes.push(route);return route;}
if(cmd==='delete'){const used=(s.assets||[]).some(a=>a.routeId===p.id);if(used)throw new Error('route-in-use');const n=s.customRoutes.length;s.customRoutes=s.customRoutes.filter(r=>r.id!==p.id);delete s.routeCache[p.id];return n!==s.customRoutes.length;}
if(cmd==='dedupe'){const canonical=new Map(),redirect=new Map(),kept=[];for(const route of s.customRoutes){if(!route?.id)continue;const sig=signature(route);if(!sig){kept.push(route);continue;}const existing=canonical.get(sig);if(existing){redirect.set(route.id,existing.id);delete s.routeCache[route.id];}else{canonical.set(sig,route);kept.push(route);}}if(redirect.size){const fleet=globalThis.GH_FLEET_CORE;if(!fleet?.execute)throw new Error('fleet-owner-unavailable');fleet.execute({state:s},'remap-routes',{redirect:Object.fromEntries(redirect)});s.customRoutes=kept;}return {removed:redirect.size,redirect:Object.fromEntries(redirect)};}
if(cmd==='register-endpoint'){const e={...p.endpoint};if(!e.id)throw new Error('endpoint-id-required');s.routeEndpoints[e.id]=e;return e;}
if(cmd==='cache-geometry'){if(!p.id)throw new Error('route-id-required');s.routeCache[p.id]={route:p.route,distanceKm:Number(p.distanceKm)||0,durationSeconds:Number(p.durationSeconds)||0,cachedAtSim:Number(s.simSeconds)||0};return s.routeCache[p.id];}
throw new Error(`Unknown route command: ${cmd}`);}
const API={VERSION,ensure,signature,execute};globalThis.GH_ROUTE_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('routes',API);if(globalThis.window&&window!==globalThis)window.GH_ROUTE_CORE=API;})();
