(()=>{'use strict';const VERSION='3.0.0';
function ensure(s){s.customRoutes=Array.isArray(s.customRoutes)?s.customRoutes:[];s.routeEndpoints=s.routeEndpoints&&typeof s.routeEndpoints==='object'?s.routeEndpoints:{};s.routeCache=s.routeCache&&typeof s.routeCache==='object'?s.routeCache:{};return s;}
function signature(r){const points=(Array.isArray(r?.route)?r.route:[]).filter(point=>Array.isArray(point)&&point.length>=2&&point.every(Number.isFinite)).map(point=>`${Number(point[0]).toFixed(5)},${Number(point[1]).toFixed(5)}`);if(points.length<2)return'';const forward=points.join(';'),reverse=[...points].reverse().join(';'),canonical=forward<reverse?forward:reverse,hash=(text,seed)=>{let value=seed>>>0;for(let i=0;i<text.length;i++){value^=text.charCodeAt(i);value=Math.imul(value,16777619)>>>0;}return value.toString(36);};return `${r?.type||''}:${points.length}:${hash(canonical,2166136261)}:${hash(canonical,2246822519)}`;}
function execute(ctx,cmd,p){const s=ctx.state||ctx;ensure(s);if(cmd==='create'){const route={...p.route};if(!route.id||!route.type||!Array.isArray(route.route)||route.route.length<2)throw new Error('invalid-route');const sig=signature(route);if(!sig)throw new Error('invalid-route');if(s.customRoutes.some(r=>signature(r)===sig))throw new Error('duplicate-route');s.customRoutes.push(route);return route;}
if(cmd==='delete'){const used=(s.assets||[]).some(a=>a.routeId===p.id);if(used)throw new Error('route-in-use');const n=s.customRoutes.length;s.customRoutes=s.customRoutes.filter(r=>r.id!==p.id);delete s.routeCache[p.id];return n!==s.customRoutes.length;}
if(cmd==='dedupe'){const canonical=new Map(),used=new Set((s.assets||[]).map(asset=>asset.routeId).filter(Boolean)),kept=[],removed=[],conflicts=[];for(const route of s.customRoutes){if(!route?.id)continue;const sig=signature(route);if(!sig){kept.push(route);continue;}const existing=canonical.get(sig);if(!existing){canonical.set(sig,route);kept.push(route);continue;}const existingUsed=used.has(existing.id),routeUsed=used.has(route.id);if(routeUsed&&existingUsed){kept.push(route);conflicts.push([existing.id,route.id]);continue;}if(routeUsed&&!existingUsed){const index=kept.findIndex(row=>row.id===existing.id);if(index>=0)kept.splice(index,1);delete s.routeCache[existing.id];removed.push(existing.id);canonical.set(sig,route);kept.push(route);continue;}delete s.routeCache[route.id];removed.push(route.id);}if(removed.length)s.customRoutes=kept;return {removed:removed.length,removedIds:removed,conflicts};}
if(cmd==='register-endpoint'){const e={...p.endpoint};if(!e.id)throw new Error('endpoint-id-required');s.routeEndpoints[e.id]=e;return e;}
if(cmd==='cache-geometry'){if(!p.id)throw new Error('route-id-required');s.routeCache[p.id]={route:p.route,distanceKm:Number(p.distanceKm)||0,durationSeconds:Number(p.durationSeconds)||0,cachedAtSim:Number(s.simSeconds)||0};return s.routeCache[p.id];}
throw new Error(`Unknown route command: ${cmd}`);}
const API={VERSION,ensure,signature,execute};globalThis.GH_ROUTE_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('routes',API);if(globalThis.window&&window!==globalThis)window.GH_ROUTE_CORE=API;})();
