(()=>{
  'use strict';
  const VERSION='2.9.1',SAVE_SCHEMA_VERSION='2.0.0';
  function object(v){return !!v&&typeof v==='object'&&!Array.isArray(v);}
  function finite(v){return v!==null&&v!==''&&typeof v!=='boolean'&&Number.isFinite(Number(v));}
  function structured(v){if(typeof globalThis.structuredClone==='function')try{return globalThis.structuredClone(v);}catch(_e){}return JSON.parse(JSON.stringify(v));}
  function normalize(state,defaults){
    if(!object(state))throw new Error('SAVE_ROOT_INVALID');
    if(state.saveVersion!==undefined&&state.saveVersion!==SAVE_SCHEMA_VERSION)throw new Error('SAVE_SCHEMA_UNSUPPORTED');
    const s=state,d=object(defaults)?defaults:{};for(const [k,v] of Object.entries(d))if(s[k]===undefined)s[k]=structured(v);
    s.saveVersion=SAVE_SCHEMA_VERSION;s.saveRevision=Math.max(0,Math.floor(Number(s.saveRevision)||0));s.simSeconds=Math.max(0,Number(s.simSeconds)||0);s.lastFinancialDay=Math.max(0,Math.floor(Number(s.lastFinancialDay)||0));s.lastMarketHour=Math.max(0,Math.floor(Number(s.lastMarketHour)||0));
    s.timeRecovery=object(s.timeRecovery)?s.timeRecovery:{};s.timeRecovery.queue=Array.isArray(s.timeRecovery.queue)?s.timeRecovery.queue:[];s.simulationKernel=object(s.simulationKernel)?s.simulationKernel:{};s.simulationWorld=object(s.simulationWorld)?s.simulationWorld:{};s.determinism=object(s.determinism)?s.determinism:{};s.sequences=object(s.sequences)?s.sequences:{};
    if(object(s.finance)){s.finance.journalEntries=Array.isArray(s.finance.journalEntries)?s.finance.journalEntries:[];s.finance.periods=Array.isArray(s.finance.periods)?s.finance.periods:[];if(s.finance.auditArchive!=null&&!object(s.finance.auditArchive))s.finance.auditArchive={records:{},digests:[]};if(object(s.finance.auditArchive)){s.finance.auditArchive.records=object(s.finance.auditArchive.records)?s.finance.auditArchive.records:{};s.finance.auditArchive.digests=Array.isArray(s.finance.auditArchive.digests)?s.finance.auditArchive.digests:[];}}
    return s;
  }
  function duplicateIds(rows,getId=x=>x?.id){const seen=new Set();for(const row of Array.isArray(rows)?rows:[]){const id=String(getId(row)||'');if(!id||seen.has(id))return true;seen.add(id);}return false;}
  function validate(s){
    const errors=[];if(!object(s))errors.push('root-not-object');if(String(s?.saveVersion||'')!==SAVE_SCHEMA_VERSION)errors.push('save-version');if(s?.saveRevision!==undefined&&(!finite(s.saveRevision)||Number(s.saveRevision)<0||!Number.isSafeInteger(Number(s.saveRevision))))errors.push('save-revision');if(s?.resetEpoch!==undefined&&(!finite(s.resetEpoch)||!Number.isSafeInteger(Number(s.resetEpoch))||Number(s.resetEpoch)<0))errors.push('reset-epoch');if(!finite(s?.simSeconds)||Number(s.simSeconds)<0)errors.push('sim-seconds');
    for(const key of ['assets','market'])if(!Array.isArray(s?.[key]))errors.push(key);if(!object(s?.finance)||!Array.isArray(s.finance.invoices)||!Array.isArray(s.finance.cheques)||!Array.isArray(s.finance.payables)||!Array.isArray(s.finance.receivables)||!Array.isArray(s.finance.periods))errors.push('finance');if(!object(s?.companyFinance))errors.push('company-finance');if(!object(s?.advanced))errors.push('advanced');
    if(duplicateIds(s?.assets,x=>x?.id))errors.push('asset-id');if(duplicateIds(s?.customRoutes,x=>x?.id))errors.push('route-id');if(duplicateIds(s?.realism?.procurement?.deliveries,x=>x?.id))errors.push('delivery-id');if(duplicateIds(s?.advanced?.ai?.requests,x=>x?.id))errors.push('ai-request-id');if(duplicateIds(s?.advanced?.procurement?.assetRequests,x=>x?.id))errors.push('asset-request-id');
    const inv=Array.isArray(s?.finance?.invoices)?s.finance.invoices:[];if(duplicateIds(inv,x=>x?.number||x?.id))errors.push('invoice-id');const chq=Array.isArray(s?.finance?.cheques)?s.finance.cheques:[];if(duplicateIds(chq,x=>x?.id))errors.push('cheque-id');
    for(const book of Object.values(object(s?.companyFinance)?s.companyFinance:{})){
      if(!Array.isArray(book?.accounts)||!book.accounts.length){errors.push('accounts');continue;}for(const account of book.accounts)if(!finite(account?.balance)||Number(account.balance)<0){errors.push('account-balance');break;}if(!finite(book?.debt)||Number(book.debt)<0)errors.push('debt');if(!finite(book?.taxPayable)||Number(book.taxPayable)<0)errors.push('tax-payable');
      const vat=book?.vat;if(vat!==undefined&&(!object(vat)||['output','input','creditCarry','periodOutputStart','periodInputStart'].some(k=>!finite(vat[k])||Number(vat[k])<0)))errors.push('vat');
    }
    for(const d of Array.isArray(s?.realism?.procurement?.deliveries)?s.realism.procurement.deliveries:[]){if(!d?.id||!d?.baseId||!String(d.status||'').trim())errors.push('delivery-shape');}
    for(const i of inv){const total=Number(i?.total),gross=Number(i?.amount??i?.total),tax=Number(i?.tax||0),subtotal=Number(i?.subtotal??(gross-tax));if(!finite(total)||total<0||!finite(gross)||gross<0||!finite(subtotal)||subtotal<0||!finite(tax)||tax<0||Math.abs(total-gross)>.02||Math.abs(total-(subtotal+tax))>.02)errors.push('invoice-math');}
    for(const p of Array.isArray(s?.finance?.periods)?s.finance.periods:[]){if(!finite(p?.amount)||Number(p.amount)<0||!['مستحق','مسدد','صفر'].includes(String(p?.status||'')))errors.push('tax-period');if(finite(p?.outputVAT)&&finite(p?.inputVAT)){const opening=Math.max(0,Number(p?.openingCredit)||0),expected=Math.max(0,Number(p.outputVAT)-Number(p.inputVAT)-opening),closing=Math.max(0,Number(p.inputVAT)+opening-Number(p.outputVAT));if(Math.abs((Number(p.amount)||0)-expected)>.02||Math.abs((Number(p?.closingCredit)||0)-closing)>.02)errors.push('tax-period-math');}}
    for(const j of Array.isArray(s?.finance?.journalEntries)?s.finance.journalEntries:[]){const lines=Array.isArray(j?.lines)?j.lines:[],dr=lines.reduce((n,x)=>n+(Number(x?.debit)||0),0),cr=lines.reduce((n,x)=>n+(Number(x?.credit)||0),0);if(!lines.length||Math.abs(dr-cr)>.02)errors.push('journal-unbalanced');}
    const archive=s?.finance?.auditArchive;if(archive!=null){if(!object(archive)||!object(archive.records)||!Array.isArray(archive.digests))errors.push('finance-audit-archive');else{for(const [kind,rows] of Object.entries(archive.records))if(!kind||!Array.isArray(rows))errors.push('finance-audit-records');for(const d of archive.digests){if(!d||typeof d.kind!=='string'||!Number.isInteger(Number(d.count))||Number(d.count)<=0||!finite(d.total)||Number(d.total)<0||typeof d.checksum!=='string'||!d.checksum)errors.push('finance-audit-digest');}}}
    const budgets=object(s?.companyBudgets)?s.companyBudgets:{};for(const b of Object.values(budgets)){const limit=Number(b?.limit),spent=Number(b?.spent),reserved=Number(b?.reserved||0);if(!finite(limit)||limit<0||!finite(spent)||spent<0||!finite(reserved)||reserved<0||(b.enabled&&limit>0&&spent+reserved>limit+.01))errors.push('budget');for(const [line,lineLimitRaw] of Object.entries(object(b?.lines)?b.lines:{})){const lineLimit=Number(lineLimitRaw)||0,lineSpent=Number(b?.spentByLine?.[line]||0),lineReserved=Number(b?.reservedByLine?.[line]||0);if(lineSpent<0||lineReserved<0||(b.enabled&&lineLimit>0&&lineSpent+lineReserved>lineLimit+.01))errors.push('budget-line');}}
    const cp=s?.controlPlane;if(cp!==undefined){if(!object(cp)||String(cp.schema||'')!=='gh-control-plane-v1'||!Array.isArray(cp.events)||!Array.isArray(cp.commands)||!Array.isArray(cp.incidents)||!Array.isArray(cp.outbox)||!Array.isArray(cp.blackBox)||!object(cp.registry)||!object(cp.registry.engines)||!Array.isArray(cp.registry.links))errors.push('control-plane-shape');else{for(const key of ['revision','commandSequence','eventSequence','incidentSequence','outboxSequence'])if(!finite(cp[key])||Number(cp[key])<0||!Number.isInteger(Number(cp[key])))errors.push('control-plane-sequence');if(!/^[a-f0-9]{64}$/i.test(String(cp.journalHeadHash||'')))errors.push('control-plane-journal-head');if(duplicateIds(cp.events,x=>x?.id)||duplicateIds(cp.commands,x=>x?.id)||duplicateIds(cp.incidents,x=>x?.id)||duplicateIds(cp.outbox,x=>x?.id))errors.push('control-plane-id');for(const e of cp.events){if(!Number.isInteger(Number(e?.sequence))||Number(e.sequence)<=0||!/^[a-f0-9]{64}$/i.test(String(e?.hash||''))||!/^[a-f0-9]{64}$/i.test(String(e?.previousHash||'')))errors.push('control-plane-event');}const eventIds=new Set(cp.events.map(x=>x?.id));for(const row of cp.outbox)if(row?.delivered!==true&&!eventIds.has(row?.eventId)&&row?.payload?.id!==row?.eventId)errors.push('control-plane-outbox-reference');}}
    return {ok:errors.length===0,errors:[...new Set(errors)]};
  }
  const API=Object.freeze({VERSION,SAVE_SCHEMA_VERSION,normalize,validate});globalThis.GH_SAVE_SCHEMA=API;if(globalThis.window&&globalThis.window!==globalThis)globalThis.window.GH_SAVE_SCHEMA=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
