(()=>{
  'use strict';
  const VERSION='3.0.0',SAVE_SCHEMA_VERSION='2.0.0';
  const ROUTE_TYPES=new Set(['air','sea','road']),ASSET_PHASES=new Set(['idle','delivery','turnaround','moving']);
  const ROUTE_FLEET_CAPACITY=Object.freeze({air:24,sea:24,road:64});
  const BUILTIN_ROUTES=new Set(['AIR_RUH_LHR','AIR_DXB_SIN','SEA_SIN_JED','SEA_RTM_NYC','ROAD_RUH_JED','ROAD_DXB_RUH']);
  const STATE_LIMITS=Object.freeze({customRoutes:240,routeEndpoints:360,routeCache:160,routePoints:2048,routeBytes:256*1024,routeCacheBytes:512*1024,controlEvents:240,controlCommands:120,controlIncidents:80,controlOutbox:100,controlBlackBox:120,domainCommands:240,businessEvents:240,businessWorldEvents:240,businessWorldOpportunities:120,businessWorldSponsorships:60,businessWorldCampaigns:80,businessWorldCompetitorActivity:120,businessWorldParties:500,businessWorldRelationships:1500,authorizationPeople:64,authorizationSeals:256,authorizationMandates:512,authorizationProofs:4000,authorizationSealBytes:32768,documentProofs:5000});
  const metricClock=()=>globalThis.performance?.now?.()??Date.now();
  const runtimeTelemetry={lastValidation:null,samples:[]};
  // Phase 1B-B: wall-clock pacing/scheduler telemetry is runtime-only. Older
  // Build 339 saves may still contain the former simulationEngine.snapshot()
  // payload inside simulationKernel; retain only semantic/audit fields there.
  const SIMULATION_KERNEL_RUNTIME_KEYS=Object.freeze([
    'version','frames','slices','chunks','hours','days','conflicts','cancels',
    'maxChunkMs','lastChunkMs','longTasks','hardTasks','droppedRealSeconds','backlogClamps','stallGaps',
    'maxCreateMs','lastCreateMs','maxFinishMs','lastFinishMs','maxCycleMs','lastCycleMs',
    'lastError','lastBoundary','lastSliceSeconds','lastMaintenanceHour','lastCancelReason','lastCommitReason','lastWorkStage',
    'governor','avgChunkMs','avgWorkMs','manualFailures','manualThrottleYields','lastProgressSim','lastProgressAt',
    'simSeconds','speed','backlog','jobActive','jobReadyToFinish','jobSlice','jobSpeed','hidden','manualAdvance',
    'pacing','config','coreVersion','transactionVersion'
  ]);
  function normalizeSimulationKernel(value){const kernel=object(value)?value:{};for(const key of SIMULATION_KERNEL_RUNTIME_KEYS)delete kernel[key];return kernel;}
  function publishValidationMetric(metric){const row={...metric,recordedAtMs:Date.now()};runtimeTelemetry.lastValidation=row;runtimeTelemetry.samples.push(row);if(runtimeTelemetry.samples.length>32)runtimeTelemetry.samples.shift();return row;}
  function object(v){return !!v&&typeof v==='object'&&!Array.isArray(v);}
  function finite(v){return v!==null&&v!==''&&typeof v!=='boolean'&&Number.isFinite(Number(v));}
  function dataId(v){return /^[A-Za-z][A-Za-z0-9]*(?:[._-][A-Za-z0-9]+)*$/.test(String(v||''));}
  function structured(v){if(typeof globalThis.structuredClone==='function')try{return globalThis.structuredClone(v);}catch(_e){}return JSON.parse(JSON.stringify(v));}
  function validPoint(point){return Array.isArray(point)&&point.length>=2&&typeof point[0]==='number'&&Number.isFinite(point[0])&&typeof point[1]==='number'&&Number.isFinite(point[1])&&point[0]>=-90&&point[0]<=90&&point[1]>=-180&&point[1]<=180;}
  function serializedBytes(value){try{const json=typeof value==='string'?value:JSON.stringify(value);return globalThis.TextEncoder?new TextEncoder().encode(json).byteLength:json.length*2;}catch(_error){return Infinity;}}
  function financeSequence(value){const matches=String(value||'').match(/(\d+)(?!.*\d)/);if(!matches)return 0;const n=Number(matches[1]);return Number.isSafeInteger(n)&&n>=0?n:0;}
  function compactDigestV2(value){
    if(!object(value))return value;
    const sources=Array.isArray(value.sources)?value.sources:[],ids=[...(Array.isArray(value.sourceDocumentIds)?value.sourceDocumentIds:[]),...sources.flatMap(row=>[row?.id,row?.sourceRef])].map(String).filter(Boolean),maxSequence=Math.max(Number(value.maxSequence)||0,...ids.map(financeSequence)),firstId=String(value?.idRange?.[0]||ids[0]||''),lastId=String(value?.idRange?.[1]||ids.at(-1)||'');
    const daily=Array.isArray(value.recentDaily)?value.recentDaily.filter(object).slice(-30).map(row=>({day:Math.max(0,Math.floor(Number(row.day)||0)),income:Math.max(0,Number(row.income)||0),expense:Math.max(0,Number(row.expense)||0),intercompany:Math.max(0,Number(row.intercompany)||0),count:Math.max(0,Math.floor(Number(row.count)||0)),total:Math.max(0,Number(row.total)||0)})):[];
    return {schema:'gh-finance-audit-digest-v2',id:String(value.id||`AUD-${String(value.kind||'legacy')}`),kind:String(value.kind||''),count:Math.max(1,Math.floor(Number(value.count)||sources.length||1)),total:Math.max(0,Number(value.total)||0),firstAt:Math.max(0,Number(value.firstAt)||0),lastAt:Math.max(0,Number(value.lastAt)||0),idRange:[firstId,lastId],checksum:String(value.checksum||''),maxSequence:Math.max(0,Math.floor(maxSequence)),intercompanyTotal:Math.max(0,Number(value.intercompanyTotal)||0),recentDaily:daily,at:Math.max(0,Number(value.at)||0)};
  }
  function safeDisplayText(value,maximum=240,{allowEmpty=true}={}){
    if(value==null)return allowEmpty;const raw=typeof value==='string'?value:String(value),inspected=globalThis.GH_IDENTITY?.inspectPlainText?.(raw,{minimum:allowEmpty?0:1,maximum,allowEmpty});if(inspected)return inspected.ok;const text=raw.trim();return (allowEmpty||Boolean(text))&&text.length<=maximum&&!/[<>\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069]/u.test(text);
  }
  function safeAttributeText(value,maximum=240,{allowEmpty=false}={}){return safeDisplayText(value,maximum,{allowEmpty})&&!/"/.test(String(value??''));}
  function safeLocalImage(value){const text=String(value||'');return /^assets\/[a-zA-Z0-9_.\/-]+\.(?:svg|png|jpe?g|webp)$/i.test(text)&&!text.split('/').includes('..');}
  function validSavedLogo(value){
    if(value==null||value==='')return true;const inspector=globalThis.GH_IDENTITY?.inspectCustomLogo;if(typeof inspector==='function')return inspector(value).ok;return safeLocalImage(value);
  }
  function validateIdentityState(s,errors){
    const profile=object(s?.profile)?s.profile:{};for(const [key,maximum,required] of [['name',120,true],['legalName',120,false],['tradeName',120,false],['shortName',28,false],['founder',120,false],['englishName',120,false],['city',100,false],['country',100,false]])if(profile[key]!=null&&!safeDisplayText(profile[key],maximum,{allowEmpty:!required}))errors.push(`identity-profile-${key}`);if(!validSavedLogo(profile.logo))errors.push('identity-profile-logo');for(const source of [profile.logoVariants,profile.identity?.logos])if(object(source))for(const [usage,logo] of Object.entries(source))if(!validSavedLogo(logo))errors.push(`identity-profile-logo:${usage}`);
    const registry=object(s?.companyRegistry)?s.companyRegistry:{};for(const [company,row] of Object.entries(registry)){if(!dataId(company))errors.push(`identity-company-id:${company}`);if(!object(row)){errors.push(`identity-company-shape:${company}`);continue;}for(const [key,maximum,required] of [['name',120,false],['legalName',120,false],['tradeName',120,false],['shortName',28,false],['owner',120,false],['authorizedSignatory',120,false],['mapName',48,false]])if(row[key]!=null&&!safeDisplayText(row[key],maximum,{allowEmpty:!required}))errors.push(`identity-company-${key}:${company}`);for(const key of ['taxId','commercialRegistration','businessLicense','formationContract','bankAccount','documentPrefix','accountPrefix'])if(row[key]!=null&&!safeAttributeText(row[key],180,{allowEmpty:true}))errors.push(`identity-company-${key}:${company}`);if(!validSavedLogo(row.logo))errors.push(`identity-company-logo:${company}`);for(const source of [row.logoVariants,row.identity?.logos])if(object(source))for(const [usage,logo] of Object.entries(source))if(!validSavedLogo(logo))errors.push(`identity-company-logo:${company}:${usage}`);}
    if(s?.openedCompanies!==undefined&&(!Array.isArray(s.openedCompanies)||s.openedCompanies.some(company=>!dataId(company))||new Set(s.openedCompanies).size!==s.openedCompanies.length))errors.push('identity-opened-companies');
    const formation=s?.companyRegistry?.group?.formationDocument;if(object(formation))for(const [key,maximum] of [['name',120],['shortName',28],['founder',120],['city',100],['country',100],['englishName',120]])if(formation[key]!=null&&!safeDisplayText(formation[key],maximum))errors.push(`identity-formation-${key}`);
  }
  function validateConferenceLogoState(s,errors){
    const conference=s?.advanced?.conference;if(!object(conference))return;const archive=Array.isArray(conference.archive)?conference.archive:[];if(archive.length>20)errors.push('identity-conference-archive-capacity');const rows=[conference.current,...archive.slice(0,20)].filter(object);
    const checkBrand=(brand,label)=>{if(!object(brand))return;if(brand.logo!=null&&!validSavedLogo(brand.logo))errors.push(`identity-conference-logo:${label}`);if(object(brand.variants))for(const [usage,logo] of Object.entries(brand.variants))if(!validSavedLogo(logo))errors.push(`identity-conference-logo:${label}:${usage}`);};
    const checkText=(value,maximum,label)=>{if(value!=null&&!safeDisplayText(value,maximum))errors.push(`identity-conference-text:${label}`);},checkMetrics=(metrics,label)=>{const values=Array.isArray(metrics)?metrics:[];if(values.length>128)errors.push('identity-conference-metric-capacity');for(const [metricIndex,metric] of values.slice(0,128).entries()){checkText(metric?.id,100,`${label}:metric:${metricIndex}:id`);checkText(metric?.label,180,`${label}:metric:${metricIndex}:label`);checkText(metric?.value,500,`${label}:metric:${metricIndex}:value`);}};
    const checkContribution=(contribution,label)=>{if(!object(contribution))return;for(const [key,maximum] of [['id',100],['chapterId',100],['title',180],['kicker',120],['headline',240],['subtitle',240],['caption',500],['presenter',120],['role',160],['kind',80],['templateId',80]])checkText(contribution[key],maximum,`${label}:${key}`);checkMetrics(contribution.metrics,label);const lines=Array.isArray(contribution.narration?.lines)?contribution.narration.lines:Array.isArray(contribution.narration)?contribution.narration:[];if(lines.length>128)errors.push('identity-conference-narration-capacity');for(const [lineIndex,line] of lines.slice(0,128).entries())checkText(line,500,`${label}:narration:${lineIndex}`);};
    for(const [index,row] of rows.entries()){
      const snapshot=row.snapshot;if(object(snapshot)){const group=snapshot.group;checkBrand(group?.brand,`${index}:group`);for(const [key,maximum] of [['name',180],['founder',120],['shortName',40],['creditRating',40],['priority',240]])checkText(group?.[key],maximum,`${index}:group:${key}`);const companies=Array.isArray(snapshot.companies)?snapshot.companies:[];if(companies.length>1024)errors.push('identity-conference-company-capacity');for(const [companyIndex,company] of companies.slice(0,1024).entries()){checkBrand(company?.brand,`${index}:company:${companyIndex}`);for(const [key,maximum] of [['type',100],['companyId',100],['legalName',180],['tradeName',180],['shortName',40],['priority',240]])checkText(company?.[key],maximum,`${index}:company:${companyIndex}:${key}`);for(const [personIndex,person] of [company?.manager,...(Array.isArray(company?.executives)?company.executives.slice(0,64):[])].filter(object).entries()){checkText(person.name,120,`${index}:company:${companyIndex}:person:${personIndex}:name`);checkText(person.role,160,`${index}:company:${companyIndex}:person:${personIndex}:role`);}const contributions=Array.isArray(company?.conferenceContributions)?company.conferenceContributions:[];if(contributions.length>128)errors.push('identity-conference-contribution-capacity');for(const [contributionIndex,contribution] of contributions.slice(0,128).entries())checkContribution(contribution,`${index}:company:${companyIndex}:contribution:${contributionIndex}`);}const achievements=Array.isArray(snapshot.achievements)?snapshot.achievements:[];if(achievements.length>256)errors.push('identity-conference-achievement-capacity');for(const [achievementIndex,achievement] of achievements.slice(0,256).entries()){checkText(achievement?.title,180,`${index}:achievement:${achievementIndex}:title`);checkText(achievement?.detail,500,`${index}:achievement:${achievementIndex}:detail`);}const comments=Array.isArray(snapshot.social?.comments)?snapshot.social.comments:[];if(comments.length>256)errors.push('identity-conference-comment-capacity');for(const [commentIndex,comment] of comments.slice(0,256).entries()){checkText(comment?.handle,100,`${index}:comment:${commentIndex}:handle`);checkText(comment?.country,100,`${index}:comment:${commentIndex}:country`);checkText(comment?.text,500,`${index}:comment:${commentIndex}:text`);}}
      const modes=row.presentation?.planBundle?.modes;if(object(modes))for(const mode of ['full','brief','manual']){const scenes=Array.isArray(modes[mode])?modes[mode]:[];if(scenes.length>2048)errors.push('identity-conference-scene-capacity');for(const [sceneIndex,scene] of scenes.slice(0,2048).entries()){if(scene?.logo!=null&&!validSavedLogo(scene.logo))errors.push(`identity-conference-plan-logo:${index}:${mode}:${sceneIndex}`);checkContribution(scene,`${index}:${mode}:${sceneIndex}`);checkText(scene?.chartUnit,100,`${index}:${mode}:${sceneIndex}:chartUnit`);}}
    }
  }
  function validatePresentationTextState(s,errors){
    const entityFields=[['name',180],['model',180],['status',80],['city',100],['country',100],['code',40],['iata',12],['icao',12],['detail',500],['capacity',180],['icon',16]],entityNumericFields=['year','gates','landingFeePerTon','jetA1Price','congestion','berths','maxDraftM','craneCount','bays','runwayM','elevationM','dryStorageTEU','reeferPlugs','crudeStorageBbl','fuelBunkerBbl'];for(const [bucket,rows] of [['assets',s?.assets],['globalBases',s?.globalBases],['customHubs',s?.customHubs],['branches',s?.branches]])for(const row of Array.isArray(rows)?rows:[])if(object(row)){for(const [key,maximum] of entityFields)if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-${bucket}-${key}`);for(const key of entityNumericFields)if(row[key]!=null&&!finite(row[key]))errors.push(`display-number-${bucket}-${key}`);if(row.id!=null&&!safeAttributeText(row.id,180))errors.push(`display-attribute-${bucket}-id`);if(row.name!=null&&!safeAttributeText(row.name,180,{allowEmpty:true}))errors.push(`display-attribute-${bucket}-name`);if(row.photo!=null&&row.photo!==''&&!safeLocalImage(row.photo))errors.push(`display-image-${bucket}-photo`);if(row.coords!=null&&!validPoint(row.coords))errors.push(`display-coords-${bucket}`);}
    for(const row of Array.isArray(s?.simulationWorld?.competitors)?s.simulationWorld.competitors:[])if(object(row))for(const [key,maximum] of [['name',180],['sector',120],['hq',100],['strategy',240],['marketShare',40],['risk',40]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-competitor-${key}`);
    for(const row of Array.isArray(s?.simulationWorld?.competitorAssets)?s.simulationWorld.competitorAssets:[])if(object(row))for(const [key,maximum] of [['name',180],['company',180],['type',40],['icon',16]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-competitor-asset-${key}`);
    for(const [id,row] of Object.entries(object(s?.routeEndpoints)?s.routeEndpoints:{}))if(object(row)){if(!safeAttributeText(id,180)||row.id!=null&&!safeAttributeText(row.id,180))errors.push('display-attribute-route-endpoint-id');for(const [key,maximum] of [['name',180],['city',100],['country',100],['code',40],['iata',12],['icao',12],['detail',500],['kind',60],['icon',16]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-route-endpoint-${key}`);if(row.name!=null&&!safeAttributeText(row.name,180,{allowEmpty:true}))errors.push('display-attribute-route-endpoint-name');for(const key of ['gates','landingFeePerTon','jetA1Price','congestion','berths','maxDraftM','craneCount','bays','runwayM','elevationM','dryStorageTEU','reeferPlugs','crudeStorageBbl','fuelBunkerBbl'])if(row[key]!=null&&!finite(row[key]))errors.push(`display-number-route-endpoint-${key}`);if(row.photo!=null&&row.photo!==''&&!safeLocalImage(row.photo))errors.push('display-image-route-endpoint-photo');}
    for(const row of Array.isArray(s?.customRoutes)?s.customRoutes:[])if(object(row)){if(row.id!=null&&!safeAttributeText(row.id,180))errors.push('display-attribute-route-id');for(const [key,maximum] of [['name',220],['from',160],['to',160],['routingSource',240]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-route-${key}`);}
    const market=Array.isArray(s?.market)?s.market:[];for(const row of market)if(object(row)){if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$/.test(String(row.sym||'')))errors.push('display-market-symbol');if(!safeDisplayText(row.name,120,{allowEmpty:false}))errors.push('display-market-name');for(const key of ['price','change','marketCap','pe','yield'])if(!finite(row[key]))errors.push(`display-market-${key}`);}for(const key of Object.keys(object(s?.portfolio)?s.portfolio:{}))if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$/.test(key))errors.push('display-portfolio-symbol');
    for(const row of Array.isArray(s?.mobility?.vehicles)?s.mobility.vehicles:[])if(object(row)){if(!safeAttributeText(row.id,180))errors.push('display-attribute-mobility-id');for(const [key,maximum] of [['name',180],['model',180],['assetClass',80],['baseLocation',120],['status',80],['icon',16]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-mobility-${key}`);}
    const registry=object(s?.contractRegistry)?s.contractRegistry:{};for(const [id,row] of Object.entries(registry))if(object(row)){if(!safeAttributeText(id,180)||row.number!=null&&!safeAttributeText(row.number,180))errors.push('display-attribute-contract-number');for(const [key,maximum] of [['status',80],['number',180],['companyName',180],['counterparty',180],['note',500]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-contract-${key}`);}
    for(const bucket of ['invoices','payables','receivables'])for(const row of Array.isArray(s?.finance?.[bucket])?s.finance[bucket]:[])if(object(row)){if(row.number!=null&&!safeAttributeText(row.number,180))errors.push(`display-attribute-${bucket}-number`);if(row.id!=null&&!safeAttributeText(row.id,180))errors.push(`display-attribute-${bucket}-id`);for(const [key,maximum] of [['note',500],['counterparty',180],['companyName',180],['method',100],['status',80],['accountId',180],['sourceRef',180]])if(row[key]!=null&&!safeDisplayText(row[key],maximum))errors.push(`display-text-${bucket}-${key}`);}
    for(const row of Array.isArray(s?.finance?.cheques)?s.finance.cheques:[])if(object(row)){if(row.id!=null&&!safeAttributeText(row.id,180))errors.push('display-attribute-cheque-id');if(row.invoiceNumber!=null&&row.invoiceNumber!==''&&!safeAttributeText(row.invoiceNumber,180))errors.push('display-attribute-cheque-invoice');}
    const facilityModels=object(s?.advanced?.facilities)?s.advanced.facilities:{};if(Object.keys(facilityModels).length>2048)errors.push('display-advanced-facility-capacity');for(const [facilityId,model] of Object.entries(facilityModels)){if(!safeAttributeText(facilityId,180)||!object(model)){errors.push('display-advanced-facility-shape');continue;}if(model.manager!=null&&!safeDisplayText(model.manager,180))errors.push('display-text-advanced-facility-manager');const departments=object(model.departments)?model.departments:{};for(const [department,value] of Object.entries(departments))if(!['operations','finance','hr','commercial','maintenance','security'].includes(department)||!finite(value)||Number(value)<0||Number(value)>100)errors.push('display-advanced-facility-department');const tasks=Array.isArray(model.tasks)?model.tasks:[];if(tasks.length>256)errors.push('display-advanced-facility-task-capacity');for(const task of tasks.slice(0,256)){if(!object(task)||!safeAttributeText(task.id,180)||!safeDisplayText(task.title,240,{allowEmpty:false})||!safeDisplayText(task.status,80,{allowEmpty:false}))errors.push('display-advanced-facility-task');}}
    for(const report of Array.isArray(s?.finance?.payrollReports)?s.finance.payrollReports:[])for(const [key,maximum] of [['month',80],['day',40]])if(typeof report?.[key]==='string'&&!safeDisplayText(report[key],maximum))errors.push(`display-text-payroll-${key}`);
  }
  function routeMode(route){return String(route?.routeMode||route?.type||'');}
  function routeOwner(route){return String(route?.ownerCompanyId||route?.companyId||route?.company||'');}
  function assetMode(asset){return String(asset?.assetMode||asset?.type||'');}
  function assetOwner(asset){return String(asset?.ownerCompanyId||asset?.companyId||'');}
  function knownRouteMode(mode,state,owner=''){return ROUTE_TYPES.has(mode)||globalThis.GH_COMPANY_PLATFORM?.isKnownRouteMode?.(mode)||(dataId(mode)&&owner&&object(state?.companyRegistry?.[owner]));}
  function knownAssetMode(mode,state,owner=''){return ROUTE_TYPES.has(mode)||globalThis.GH_COMPANY_PLATFORM?.ownerForLegacyAssetMode?.(mode)||(dataId(mode)&&owner&&object(state?.companyRegistry?.[owner]));}
  function routeSignature(route){const points=(Array.isArray(route?.route)?route.route:[]).filter(validPoint).map(point=>`${point[0].toFixed(5)},${point[1].toFixed(5)}`);if(points.length<2)return'';const a=points.join(';'),b=[...points].reverse().join(';');return `${routeOwner(route)||routeMode(route)}:${routeMode(route)}:${a<b?a:b}`;}
  function retiredFeatureKey(){return String.fromCharCode(97,105);}
  function retiredPanelName(){return String.fromCharCode(105,110,116,101,108,108,105,103,101,110,99,101);}
  function retiredVehicleOptionKey(){return String.fromCharCode(97,117,116,111,110,111,109,111,117,115);}
  function refreshRetiredCatalogAsset(asset){
    if(!object(asset)||!['N-T4','N-T28'].includes(asset.catalogId))return false;
    const updated=asset.catalogId==='N-T4'
      ?{model:'Hybrid Safety 24T · هجينة آمنة',drivetrain:'ديزل هجين'}
      :{model:'Electric Long Range 20T · كهربائية بعيدة',drivetrain:'كهربائي 900V'};
    let changed=false;if(asset.model!==updated.model){asset.model=updated.model;changed=true;}
    if(object(asset.specs)){const retired=retiredVehicleOptionKey();if(Object.prototype.hasOwnProperty.call(asset.specs,retired)){delete asset.specs[retired];changed=true;}if(asset.specs.drivetrain!==updated.drivetrain){asset.specs.drivetrain=updated.drivetrain;changed=true;}}
    return changed;
  }
  function transitionalRouteUser(asset){return asset?.phase==='moving'&&asset?.releaseExclusiveRouteOnArrival===true;}
  function routeCapacity(type){return ROUTE_FLEET_CAPACITY[type]||1;}
  function clearLegacyRouteAssignment(asset){asset.routeId=null;asset.routeSignature=null;asset.routeSlot=null;asset.departureScheduled=false;delete asset.departureScheduledAt;asset.releaseExclusiveRouteOnArrival=false;asset.phase='idle';asset.progress=0;asset.dwellRemaining=0;asset.reverse=false;}
  function migrationTrim(state){
    const cp=state.controlPlane;if(object(cp)){
      // Journals are newest-first. Keep their heads so journalHeadHash continues to
      // describe the latest retained event. The outbox is oldest-first: retain all
      // pending rows first, then the newest delivered evidence within the hard cap.
      cp.events=Array.isArray(cp.events)?cp.events.slice(0,STATE_LIMITS.controlEvents):[];cp.commands=Array.isArray(cp.commands)?cp.commands.slice(0,STATE_LIMITS.controlCommands):[];cp.incidents=Array.isArray(cp.incidents)?cp.incidents.slice(0,STATE_LIMITS.controlIncidents):[];cp.blackBox=Array.isArray(cp.blackBox)?cp.blackBox.slice(0,STATE_LIMITS.controlBlackBox):[];
      if(Array.isArray(cp.outbox)){
        const pendingRows=cp.outbox.filter(row=>row?.delivered!==true).slice(0,STATE_LIMITS.controlOutbox),room=Math.max(0,STATE_LIMITS.controlOutbox-pendingRows.length),delivered=cp.outbox.filter(row=>row?.delivered===true).slice(-room);
        cp.outbox=[...pendingRows,...delivered];
      }else cp.outbox=[];
    }
    if(object(state.domainRuntime)&&Array.isArray(state.domainRuntime.commands))state.domainRuntime.commands=state.domainRuntime.commands.slice(0,STATE_LIMITS.domainCommands);
    if(object(state.businessWorld)){
      for(const [key,limit] of [['events',STATE_LIMITS.businessWorldEvents],['opportunities',STATE_LIMITS.businessWorldOpportunities],['sponsorships',STATE_LIMITS.businessWorldSponsorships],['campaigns',STATE_LIMITS.businessWorldCampaigns],['competitorActivity',STATE_LIMITS.businessWorldCompetitorActivity]])state.businessWorld[key]=Array.isArray(state.businessWorld[key])?state.businessWorld[key].slice(0,limit):[];
      state.businessWorld.parties=object(state.businessWorld.parties)?state.businessWorld.parties:{};
      state.businessWorld.relationships=object(state.businessWorld.relationships)?state.businessWorld.relationships:{};
    }
    if(object(state.businessLedger)&&Array.isArray(state.businessLedger.events))state.businessLedger.events=state.businessLedger.events.slice(0,STATE_LIMITS.businessEvents);
  }
  function migrateLegacy(input){
    if(!object(input))return {state:input,changed:false};
    let state=structured(input),changed=false;const retired=retiredFeatureKey(),companyUpgrade=globalThis.GH_COMPANY_PLATFORM?.migrateState?.(state);
    if(companyUpgrade?.state){state=companyUpgrade.state;changed=companyUpgrade.changed===true;}
    if(Number(state.speed)===5){state.speed=1;changed=true;}
    if(object(state.advanced)&&Object.prototype.hasOwnProperty.call(state.advanced,retired)){delete state.advanced[retired];changed=true;}
    if(object(state.settings)&&Object.prototype.hasOwnProperty.call(state.settings,`${retired}Brief`)){delete state.settings[`${retired}Brief`];changed=true;}
    if([retiredPanelName(),`${retired}Approvals`].includes(state.lastPanel)){state.lastPanel='leadershipHub';changed=true;}
    if(object(state.controlPlane?.registry?.engines)&&Object.prototype.hasOwnProperty.call(state.controlPlane.registry.engines,retired)){delete state.controlPlane;changed=true;}
    if(object(state.domainRuntime)){
      const before=Array.isArray(state.domainRuntime.commands)?state.domainRuntime.commands.length:0;
      state.domainRuntime.commands=(state.domainRuntime.commands||[]).filter(row=>!String(row?.domain||'').toLowerCase().includes(retired)&&!String(row?.actor||'').toLowerCase().includes(retired));if(state.domainRuntime.commands.length!==before)changed=true;
    }
    const proofMigration=globalThis.GH_DOCUMENT_PROOF?.migrateLegacyLedgerProjections?.(state);if(proofMigration?.changed)changed=true;
    const idempotencyMigration=globalThis.GH_DOMAIN_COMMANDS?.migrateIdempotencyState?.(state);if(idempotencyMigration?.changed)changed=true;
    const invalidRouteIds=new Set(),seenRouteIds=new Set();
    state.customRoutes=(Array.isArray(state.customRoutes)?state.customRoutes:[]).filter(route=>{
      const mode=routeMode(route),owner=routeOwner(route);
      if(!object(route)||!route.id||seenRouteIds.has(route.id)||!knownRouteMode(mode,state,owner)||!owner||!route.fromFacility||!route.toFacility||route.fromFacility===route.toFacility||!Array.isArray(route.route)||route.route.length<2||route.route.length>STATE_LIMITS.routePoints||route.route.some(point=>!validPoint(point))||serializedBytes(route)>STATE_LIMITS.routeBytes){if(route?.id)invalidRouteIds.add(route.id);changed=true;return false;}
      seenRouteIds.add(route.id);return true;
    });
    const assets=Array.isArray(state.assets)?state.assets:[];
    for(const asset of assets)if(refreshRetiredCatalogAsset(asset))changed=true;
    for(const delivery of Array.isArray(state.realism?.procurement?.deliveries)?state.realism.procurement.deliveries:[])if(refreshRetiredCatalogAsset(delivery?.asset))changed=true;
    for(const asset of assets)if(asset.routeId&&invalidRouteIds.has(asset.routeId)){clearLegacyRouteAssignment(asset);changed=true;}
    const routeById=new Map(state.customRoutes.map(route=>[route.id,route])),assignmentGroups=new Map();for(const asset of assets)if(asset.routeId){const rows=assignmentGroups.get(asset.routeId)||[];rows.push(asset);assignmentGroups.set(asset.routeId,rows);}
    for(const [routeId,rows] of assignmentGroups)if(rows.length>1){
      const type=routeMode(routeById.get(routeId))||assetMode(rows[0]);
      if(['air','sea','road'].includes(type)){
        const capacity=routeCapacity(type),used=new Set(),ordered=[...rows].sort((a,b)=>Number(b.phase==='moving')-Number(a.phase==='moving')||(Number.isInteger(a.routeSlot)?a.routeSlot:capacity)-(Number.isInteger(b.routeSlot)?b.routeSlot:capacity)||String(a.id).localeCompare(String(b.id)));
        for(const asset of ordered){
          if(assetMode(asset)!==type){clearLegacyRouteAssignment(asset);changed=true;continue;}
          let slot=Number.isInteger(asset.routeSlot)&&asset.routeSlot>=0&&asset.routeSlot<capacity&&!used.has(asset.routeSlot)?asset.routeSlot:0;while(slot<capacity&&used.has(slot))slot++;
          if(slot>=capacity){if(asset.phase==='moving'){if(asset.releaseExclusiveRouteOnArrival!==true){asset.releaseExclusiveRouteOnArrival=true;changed=true;}}else{clearLegacyRouteAssignment(asset);changed=true;}continue;}
          used.add(slot);if(asset.routeSlot!==slot){asset.routeSlot=slot;changed=true;}if(asset.releaseExclusiveRouteOnArrival===true){asset.releaseExclusiveRouteOnArrival=false;changed=true;}
        }
        continue;
      }
      const keeper=rows.find(asset=>asset.phase==='moving')||rows[0];if(keeper.releaseExclusiveRouteOnArrival===true){keeper.releaseExclusiveRouteOnArrival=false;changed=true;}
      for(const asset of rows)if(asset!==keeper){if(asset.phase==='moving'){if(asset.releaseExclusiveRouteOnArrival!==true){asset.releaseExclusiveRouteOnArrival=true;changed=true;}}else{clearLegacyRouteAssignment(asset);changed=true;}}
    }
    const signatureGroups=new Map();for(const route of state.customRoutes){const signature=routeSignature(route),rows=signatureGroups.get(signature)||[];rows.push(route);signatureGroups.set(signature,rows);}
    const removedRouteIds=new Set();
    for(const routes of signatureGroups.values())if(routes.length>1){
      const ids=new Set(routes.map(route=>route.id)),users=assets.filter(asset=>ids.has(asset.routeId)),type=routeMode(routes[0]);
      if(['air','sea','road'].includes(type)){
        const capacity=routeCapacity(type),canonical=routes.slice().sort((a,b)=>users.filter(asset=>asset.routeId===b.id).length-users.filter(asset=>asset.routeId===a.id).length||String(a.id).localeCompare(String(b.id)))[0],accepted=[],retained=new Set([canonical.id]);
        for(const asset of users.slice().sort((a,b)=>Number(b.phase==='moving')-Number(a.phase==='moving')||Number(b.routeId===canonical.id)-Number(a.routeId===canonical.id)||String(a.id).localeCompare(String(b.id)))){
          const compatible=assetMode(asset)===type&&routeOwner(canonical)===(assetOwner(asset)||globalThis.GH_COMPANY_PLATFORM?.ownerForLegacyAssetMode?.(assetMode(asset))||assetMode(asset))&&[canonical.fromFacility,canonical.toFacility].includes(asset.baseFacility);
          if(compatible&&accepted.length<capacity){asset.routeId=canonical.id;asset.routeSignature=routeSignature(canonical);asset.routeSlot=accepted.length;if(asset.releaseExclusiveRouteOnArrival===true)asset.releaseExclusiveRouteOnArrival=false;accepted.push(asset);changed=true;continue;}
          if(asset.phase==='moving'){if(asset.releaseExclusiveRouteOnArrival!==true){asset.releaseExclusiveRouteOnArrival=true;changed=true;}retained.add(asset.routeId);}
          else{clearLegacyRouteAssignment(asset);changed=true;}
        }
        for(const route of routes)if(!retained.has(route.id)){removedRouteIds.add(route.id);changed=true;}
        continue;
      }
      const keeper=users.find(asset=>asset.phase==='moving')||users[0]||null,canonicalId=keeper?.routeId||routes[0].id;
      if(keeper?.releaseExclusiveRouteOnArrival===true){keeper.releaseExclusiveRouteOnArrival=false;changed=true;}
      for(const asset of users)if(asset!==keeper){if(asset.phase==='moving'){if(asset.releaseExclusiveRouteOnArrival!==true){asset.releaseExclusiveRouteOnArrival=true;changed=true;}}else{clearLegacyRouteAssignment(asset);changed=true;}}
      const retained=new Set(assets.map(asset=>asset.routeId).filter(id=>ids.has(id)));retained.add(canonicalId);
      for(const route of routes)if(!retained.has(route.id)){removedRouteIds.add(route.id);changed=true;}
    }
    if(removedRouteIds.size)state.customRoutes=state.customRoutes.filter(route=>!removedRouteIds.has(route.id));
    if(object(state.routeCache)){
      for(const id of Object.keys(state.routeCache))if(invalidRouteIds.has(id)||removedRouteIds.has(id)){delete state.routeCache[id];changed=true;}
      for(const route of state.customRoutes){const entry=state.routeCache[route.id];if(entry?.route){delete entry.route;entry.canonicalRouteId=route.id;entry.routeSignature=routeSignature(route);changed=true;}}
      const active=new Set([...assets.map(asset=>asset.routeId).filter(Boolean),...state.customRoutes.map(route=>route.id)]),entries=Object.entries(state.routeCache);
      entries.sort((a,b)=>Number(active.has(b[0]))-Number(active.has(a[0])));let kept=entries.slice(0,STATE_LIMITS.routeCache);while(kept.length&&serializedBytes(Object.fromEntries(kept))>STATE_LIMITS.routeCacheBytes)kept.pop();if(kept.length!==entries.length){state.routeCache=Object.fromEntries(kept);changed=true;}
    }
    if(object(state.routeEndpoints)){
      const referenced=new Set([...state.customRoutes.flatMap(route=>[route.fromFacility,route.toFacility]),...assets.map(asset=>asset.baseFacility).filter(Boolean)]);
      for(const [id,endpoint] of Object.entries(state.routeEndpoints))if(endpoint?.routeEndpoint&&!referenced.has(id)){delete state.routeEndpoints[id];changed=true;}
    }
    const before=JSON.stringify({cp:state.controlPlane?.events?.length,cc:state.controlPlane?.commands?.length,dc:state.domainRuntime?.commands?.length,be:state.businessLedger?.events?.length});migrationTrim(state);const after=JSON.stringify({cp:state.controlPlane?.events?.length,cc:state.controlPlane?.commands?.length,dc:state.domainRuntime?.commands?.length,be:state.businessLedger?.events?.length});if(before!==after)changed=true;
    return {state,changed};
  }
  function normalize(state,defaults){
    if(!object(state))throw new Error('SAVE_ROOT_INVALID');
    if(state.saveVersion!==undefined&&state.saveVersion!==SAVE_SCHEMA_VERSION)throw new Error('SAVE_SCHEMA_UNSUPPORTED');
    const s=state,d=object(defaults)?defaults:{};for(const [k,v] of Object.entries(d))if(s[k]===undefined)s[k]=structured(v);
    s.saveVersion=SAVE_SCHEMA_VERSION;s.saveRevision=Math.max(0,Math.floor(Number(s.saveRevision)||0));s.simSeconds=Math.max(0,Number(s.simSeconds)||0);s.lastFinancialDay=Math.max(0,Math.floor(Number(s.lastFinancialDay)||0));s.lastMarketHour=Math.max(0,Math.floor(Number(s.lastMarketHour)||0));if(Number(s.speed)===5)s.speed=1;
    s.timeRecovery=object(s.timeRecovery)?s.timeRecovery:{};s.timeRecovery.queue=Array.isArray(s.timeRecovery.queue)?s.timeRecovery.queue:[];s.simulationKernel=normalizeSimulationKernel(s.simulationKernel);s.simulationWorld=object(s.simulationWorld)?s.simulationWorld:{};s.determinism=object(s.determinism)?s.determinism:{};s.sequences=object(s.sequences)?s.sequences:{};
    if(object(s.finance)){s.finance.journalEntries=Array.isArray(s.finance.journalEntries)?s.finance.journalEntries:[];s.finance.periods=Array.isArray(s.finance.periods)?s.finance.periods:[];if(s.finance.auditArchive!=null&&!object(s.finance.auditArchive))s.finance.auditArchive={records:{},digests:[]};if(object(s.finance.auditArchive)){s.finance.auditArchive.records=object(s.finance.auditArchive.records)?s.finance.auditArchive.records:{};s.finance.auditArchive.digests=(Array.isArray(s.finance.auditArchive.digests)?s.finance.auditArchive.digests:[]).map(compactDigestV2);}}
    s.customRoutes=Array.isArray(s.customRoutes)?s.customRoutes:[];for(const route of s.customRoutes)if(object(route)){if(!route.routeMode&&route.type)route.routeMode=route.type;if(!route.ownerCompanyId){const owner=route.companyId||route.company||globalThis.GH_COMPANY_PLATFORM?.ownerForLegacyRouteMode?.(route.routeMode);if(owner)route.ownerCompanyId=owner;}}
    s.routeEndpoints=object(s.routeEndpoints)?s.routeEndpoints:{};s.routeCache=object(s.routeCache)?s.routeCache:{};migrationTrim(s);
    return s;
  }
  function duplicateIds(rows,getId=x=>x?.id){const seen=new Set();for(const row of Array.isArray(rows)?rows:[]){const id=String(getId(row)||'');if(!id||seen.has(id))return true;seen.add(id);}return false;}
  function validDigest(value){return /^[a-f0-9]{64}$/i.test(String(value||''));}
  function validateAuthorizationState(s,errors,verificationCache,metric){
    const auth=s?.authorization;if(auth===undefined)return;
    if(!object(auth)||auth.schema!=='gh-authorization-v1'){errors.push('authorization-shape');return;}
    const people=auth.peopleById,seals=object(auth.visualSealAssetsById)?auth.visualSealAssetsById:auth.signatureAssetsById,active=object(auth.activeVisualSealByPerson)?auth.activeVisualSealByPerson:auth.activeSignatureByPerson,mandates=auth.mandatesById,proofs=auth.proofsById;
    const archived=auth.proofArchiveById||{};if(!object(archived)){errors.push('authorization-proof-archive-shape');return;}if(serializedBytes(archived)>8*1024*1024)errors.push('authorization-proof-archive-byte-limit');for(const id of Object.keys(archived))if(Object.prototype.hasOwnProperty.call(proofs||{},id))errors.push('authorization-proof-residency-conflict');const allProofs={...archived,...proofs};
    if(!object(people)||!object(seals)||!object(active)||!object(mandates)||!object(proofs)){errors.push('authorization-shape');return;}
    if(Object.keys(people).length>STATE_LIMITS.authorizationPeople)errors.push('authorization-people-capacity');if(Object.keys(seals).length>STATE_LIMITS.authorizationSeals)errors.push('authorization-seal-capacity');if(Object.keys(mandates).length>STATE_LIMITS.authorizationMandates)errors.push('authorization-mandate-capacity');if(Object.keys(proofs).length>STATE_LIMITS.authorizationProofs)errors.push('authorization-proof-capacity');
    for(const [id,row] of Object.entries(people))if(!id||!object(row)||row.id!==id||!String(row.legalName||'').trim())errors.push('authorization-person');
    for(const [id,row] of Object.entries(seals)){
      const strokes=row?.strokes,pointCount=Array.isArray(strokes)?strokes.reduce((sum,stroke)=>sum+(Array.isArray(stroke)?stroke.length:9000),0):9000;
      const basic=!id||!object(row)||row.id!==id||!people[row.ownerPersonId]||!Array.isArray(strokes)||!strokes.length||strokes.length>64||pointCount>8192||serializedBytes(strokes)>STATE_LIMITS.authorizationSealBytes||!validDigest(row.digest),validator=globalThis.GH_AUTHORIZATION?.validateVisualSeal;
      if(basic||typeof validator!=='function'||!validator(row).ok)errors.push('authorization-seal');
    }
    for(const [personId,sealId] of Object.entries(active))if(!people[personId]||!seals[sealId]||seals[sealId].ownerPersonId!==personId||seals[sealId].status!=='active')errors.push('authorization-active-seal');
    for(const [id,row] of Object.entries(mandates))if(!id||!object(row)||row.id!==id||!people[row.principalId]||!Array.isArray(row.companyIds)||!row.companyIds.length||row.companyIds.length>120||!Array.isArray(row.scopes)||!row.scopes.length||row.scopes.length>120||!Number.isSafeInteger(Number(row.version))||Number(row.version)<1)errors.push('authorization-mandate');
    const verifier=globalThis.GH_AUTHORIZATION?.verifyProof,verificationState=typeof verifier==='function'?{...s,authorization:structured(auth)}:null;
    const proofVerificationStart=metric?metricClock():0;for(const [id,row] of Object.entries(allProofs)){if(!id||!object(row)||row.id!==id||!people[row.signerPersonId]||!seals[row.signatureAssetId||row.visualSealAssetId]||!mandates[row.mandateId]||!validDigest(row.signatureDigest||row.visualSealDigest)||!validDigest(row.payloadDigest)||!validDigest(row.proofDigest)||!Array.isArray(row.documentDigests)||row.documentDigests.some(value=>!validDigest(value)))errors.push('authorization-proof');else if(!verificationState)errors.push('authorization-proof-integrity');else if(!verifier(verificationState,id,verificationCache?.authorization).ok)errors.push('authorization-proof-integrity');}if(metric)metric.authorizationProofVerifyMs+=Math.max(0,metricClock()-proofVerificationStart);
  }
  function validateDocumentProofState(s,errors,verificationCache,metric){
    const store=s?.documentProofs;if(store===undefined)return;
    if(!object(store)||store.schema!=='gh-document-proofs-v1'||!object(store.recordsById)){errors.push('document-proof-shape');return;}
    const archived=store.archiveById||{};if(!object(archived)){errors.push('document-proof-archive-shape');return;}if(serializedBytes(archived)>16*1024*1024)errors.push('document-proof-archive-byte-limit');for(const id of Object.keys(archived))if(Object.prototype.hasOwnProperty.call(store.recordsById,id))errors.push('document-proof-residency-conflict');const records={...archived,...store.recordsById};if(Object.keys(store.recordsById).length>STATE_LIMITS.documentProofs)errors.push('document-proof-capacity');
    for(const [id,row] of Object.entries(records))if(!id||!object(row)||row.id!==id||!String(row.documentId||'').trim()||!validDigest(row.contentDigest)||!object(row.issuerSnapshot)||!object(row.signedContent)||row.authorizationProofId&&!(s.authorization?.proofsById?.[row.authorizationProofId]||s.authorization?.proofArchiveById?.[row.authorizationProofId]))errors.push('document-proof-record');
    const documentOwner=globalThis.GH_DOCUMENT_PROOF;if(typeof documentOwner?.stateDocuments!=='function'){errors.push('document-proof-owner-unavailable');return;}
    const documentCollectionStart=metric?metricClock():0,documents=documentOwner.stateDocuments(s);if(metric)metric.documentCollectionMs+=Math.max(0,metricClock()-documentCollectionStart);
    const verifier=globalThis.GH_DOCUMENT_PROOF?.verifyDocument,recordVerifier=globalThis.GH_DOCUMENT_PROOF?.verifyRecord,verificationState=typeof verifier==='function'?{...s,authorization:s.authorization?structured(s.authorization):s.authorization,documentProofs:structured(store)}:null;
    const recordVerificationStart=metric?metricClock():0;if(verificationState&&typeof recordVerifier==='function')for(const id of Object.keys(records)){const check=recordVerifier(verificationState,id,new Set(),verificationCache?.documents),acceptedLegacy=check?.legacy===true&&check?.readOnly===true&&check?.recordIntegrity===true;if(!check?.ok&&!acceptedLegacy)errors.push('document-proof-record-integrity');}if(metric)metric.documentRecordVerifyMs+=Math.max(0,metricClock()-recordVerificationStart);
    const documentVerificationStart=metric?metricClock():0;for(const document of documents)if(document?.documentProofId){if(!records[document.documentProofId]||document.contentDigest!==records[document.documentProofId].contentDigest)errors.push('document-proof-reference');else if(!verificationState)errors.push('document-proof-integrity');else{const verification=verifier(verificationState,document,verificationCache?.documents),acceptedLegacy=verification?.legacy===true&&verification?.readOnly===true&&verification?.recordIntegrity===true;if(!verification?.ok&&!acceptedLegacy)errors.push('document-proof-integrity');}}if(metric)metric.documentVerifyMs+=Math.max(0,metricClock()-documentVerificationStart);
  }
  function validate(s){
    const validationStart=metricClock(),metric={totalMs:0,authorizationMs:0,authorizationProofVerifyMs:0,documentProofMs:0,documentCollectionMs:0,documentRecordVerifyMs:0,documentVerifyMs:0,companyPlatformMs:0,otherMs:0,errors:0};
    const verificationCache={authorization:{proofs:new Map(),sealDigests:new Map(),mandateDigests:new Map()},documents:{records:new Map(),signedContentStable:new Map()}};verificationCache.documents.authorization=verificationCache.authorization;
    const errors=[];if(!object(s))errors.push('root-not-object');if(String(s?.saveVersion||'')!==SAVE_SCHEMA_VERSION)errors.push('save-version');if(s?.saveRevision!==undefined&&(!finite(s.saveRevision)||Number(s.saveRevision)<0||!Number.isSafeInteger(Number(s.saveRevision))))errors.push('save-revision');if(s?.resetEpoch!==undefined&&(!finite(s.resetEpoch)||!Number.isSafeInteger(Number(s.resetEpoch))||Number(s.resetEpoch)<0))errors.push('reset-epoch');if(!finite(s?.simSeconds)||Number(s.simSeconds)<0)errors.push('sim-seconds');
    validateIdentityState(s,errors);validateConferenceLogoState(s,errors);validatePresentationTextState(s,errors);
    for(const key of ['assets','market'])if(!Array.isArray(s?.[key]))errors.push(key);if(!object(s?.finance)||!Array.isArray(s.finance.invoices)||!Array.isArray(s.finance.cheques)||!Array.isArray(s.finance.payables)||!Array.isArray(s.finance.receivables)||!Array.isArray(s.finance.periods))errors.push('finance');if(!object(s?.companyFinance))errors.push('company-finance');if(!object(s?.advanced))errors.push('advanced');
    if(duplicateIds(s?.assets,x=>x?.id))errors.push('asset-id');if(duplicateIds(s?.customRoutes,x=>x?.id))errors.push('route-id');if(duplicateIds(s?.realism?.procurement?.deliveries,x=>x?.id))errors.push('delivery-id');
    if(s?.speed!==undefined&&![0,1,2,3,4].includes(Number(s.speed)))errors.push('speed');
    const routes=Array.isArray(s?.customRoutes)?s.customRoutes:[],routeIds=new Set(BUILTIN_ROUTES),routeById=new Map(),routeSignatureGroups=new Map();
    if(routes.length>STATE_LIMITS.customRoutes)errors.push('route-capacity');
    for(const route of routes){
      const mode=routeMode(route),owner=routeOwner(route);if(!object(route)||!route.id||!knownRouteMode(mode,s,owner)||!dataId(owner)||!route.fromFacility||!route.toFacility||route.fromFacility===route.toFacility)errors.push('route-shape');
      if(!Array.isArray(route?.route)||route.route.length<2||route.route.length>STATE_LIMITS.routePoints||route.route.some(point=>!validPoint(point))||serializedBytes(route)>STATE_LIMITS.routeBytes)errors.push('route-geometry');
      const signature=routeSignature(route);if(!signature)errors.push('route-geometry');else{const rows=routeSignatureGroups.get(signature)||[];rows.push(route);routeSignatureGroups.set(signature,rows);}
      if(route?.id){routeIds.add(route.id);if(!routeById.has(route.id))routeById.set(route.id,route);}
    }
    const routeUsers=new Map(),assets=Array.isArray(s?.assets)?s.assets:[];
    for(const asset of assets){
      const mode=assetMode(asset),owner=assetOwner(asset)||globalThis.GH_COMPANY_PLATFORM?.ownerForLegacyAssetMode?.(mode)||mode;if(!object(asset)||!String(asset.id||'').trim()||!knownAssetMode(mode,s,owner)||!dataId(owner)||!String(asset.baseFacility||'').trim())errors.push('asset-shape');
      if(!ASSET_PHASES.has(asset.phase))errors.push('asset-phase');
      if(!finite(asset.progress)||Number(asset.progress)<0||Number(asset.progress)>1)errors.push('asset-progress');
      if(!finite(asset.fuel)||Number(asset.fuel)<0||Number(asset.fuel)>100)errors.push('asset-fuel');
      if(!finite(asset.condition)||Number(asset.condition)<0||Number(asset.condition)>100)errors.push('asset-condition');
      if(asset.routeId!=null&&(!String(asset.routeId).trim()||!routeIds.has(asset.routeId)))errors.push('asset-route-reference');
      if(['moving','turnaround'].includes(asset.phase)&&!asset.routeId)errors.push('asset-route-required');
      if(asset.routeId){const users=routeUsers.get(asset.routeId)||[];users.push(asset);routeUsers.set(asset.routeId,users);const route=routeById.get(asset.routeId);if(route&&(routeMode(route)!==mode||routeOwner(route)!==owner))errors.push('asset-route-company');}
    }
    for(const [routeId,users] of routeUsers){const stable=users.filter(asset=>!transitionalRouteUser(asset)),type=routeMode(routeById.get(routeId))||assetMode(users[0]),capacity=routeCapacity(type);if(stable.length>capacity)errors.push('asset-route-capacity');}
    for(const group of routeSignatureGroups.values())if(group.length>1){const stable=group.filter(route=>{const users=routeUsers.get(route.id)||[];return !users.length||users.some(asset=>!transitionalRouteUser(asset));});if(stable.length!==1)errors.push('route-geometry-duplicate');}
    if(object(s?.routeEndpoints)){if(Object.keys(s.routeEndpoints).length>STATE_LIMITS.routeEndpoints)errors.push('route-endpoint-capacity');for(const [id,endpoint] of Object.entries(s.routeEndpoints))if(!id||!object(endpoint)||endpoint.id!==id||!validPoint(endpoint.coords))errors.push('route-endpoint');}
    else if(s?.routeEndpoints!==undefined)errors.push('route-endpoints-shape');
    if(object(s?.routeCache)){if(Object.keys(s.routeCache).length>STATE_LIMITS.routeCache||serializedBytes(s.routeCache)>STATE_LIMITS.routeCacheBytes)errors.push('route-cache-capacity');for(const [id,entry] of Object.entries(s.routeCache)){if(!id||!object(entry)||entry.route&&(!Array.isArray(entry.route)||entry.route.length<2||entry.route.length>STATE_LIMITS.routePoints||entry.route.some(point=>!validPoint(point))))errors.push('route-cache');}}
    else if(s?.routeCache!==undefined)errors.push('route-cache-shape');
    if(object(s?.advanced)&&Object.prototype.hasOwnProperty.call(s.advanced,retiredFeatureKey()))errors.push('retired-feature-state');
    const inv=Array.isArray(s?.finance?.invoices)?s.finance.invoices:[];if(duplicateIds(inv,x=>x?.number||x?.id))errors.push('invoice-id');const chq=Array.isArray(s?.finance?.cheques)?s.finance.cheques:[];if(duplicateIds(chq,x=>x?.id))errors.push('cheque-id');
    for(const book of Object.values(object(s?.companyFinance)?s.companyFinance:{})){
      if(!Array.isArray(book?.accounts)||!book.accounts.length){errors.push('accounts');continue;}for(const account of book.accounts)if(!finite(account?.balance)||Number(account.balance)<0){errors.push('account-balance');break;}if(!finite(book?.debt)||Number(book.debt)<0)errors.push('debt');if(!finite(book?.taxPayable)||Number(book.taxPayable)<0)errors.push('tax-payable');
      const vat=book?.vat;if(vat!==undefined&&(!object(vat)||['output','input','creditCarry','periodOutputStart','periodInputStart'].some(k=>!finite(vat[k])||Number(vat[k])<0)))errors.push('vat');
    }
    for(const d of Array.isArray(s?.realism?.procurement?.deliveries)?s.realism.procurement.deliveries:[]){if(!d?.id||!d?.baseId||!String(d.status||'').trim())errors.push('delivery-shape');}
    for(const i of inv){const total=Number(i?.total),gross=Number(i?.amount??i?.total),tax=Number(i?.tax||0),subtotal=Number(i?.subtotal??(gross-tax));if(!finite(total)||total<0||!finite(gross)||gross<0||!finite(subtotal)||subtotal<0||!finite(tax)||tax<0||Math.abs(total-gross)>.02||Math.abs(total-(subtotal+tax))>.02)errors.push('invoice-math');}
    for(const p of Array.isArray(s?.finance?.periods)?s.finance.periods:[]){if(!finite(p?.amount)||Number(p.amount)<0||!['مستحق','مسدد','صفر'].includes(String(p?.status||'')))errors.push('tax-period');if(finite(p?.outputVAT)&&finite(p?.inputVAT)){const opening=Math.max(0,Number(p?.openingCredit)||0),expected=Math.max(0,Number(p.outputVAT)-Number(p.inputVAT)-opening),closing=Math.max(0,Number(p.inputVAT)+opening-Number(p.outputVAT));if(Math.abs((Number(p.amount)||0)-expected)>.02||Math.abs((Number(p?.closingCredit)||0)-closing)>.02)errors.push('tax-period-math');}}
    for(const j of Array.isArray(s?.finance?.journalEntries)?s.finance.journalEntries:[]){const lines=Array.isArray(j?.lines)?j.lines:[],dr=lines.reduce((n,x)=>n+(Number(x?.debit)||0),0),cr=lines.reduce((n,x)=>n+(Number(x?.credit)||0),0);if(!lines.length||Math.abs(dr-cr)>.02)errors.push('journal-unbalanced');}
    const archive=s?.finance?.auditArchive;if(archive!=null){if(!object(archive)||!object(archive.records)||!Array.isArray(archive.digests))errors.push('finance-audit-archive');else{for(const [kind,rows] of Object.entries(archive.records))if(!kind||!Array.isArray(rows))errors.push('finance-audit-records');for(const d of archive.digests){if(!d||d.schema!=='gh-finance-audit-digest-v2'||typeof d.kind!=='string'||!d.kind||!Number.isInteger(Number(d.count))||Number(d.count)<=0||!finite(d.total)||Number(d.total)<0||typeof d.checksum!=='string'||!d.checksum||!Array.isArray(d.idRange)||d.idRange.length!==2||!Number.isSafeInteger(Number(d.maxSequence))||Number(d.maxSequence)<0||!finite(d.intercompanyTotal)||Number(d.intercompanyTotal)<0||Object.prototype.hasOwnProperty.call(d,'sources')||Object.prototype.hasOwnProperty.call(d,'sourceDocumentIds')||!Array.isArray(d.recentDaily)||d.recentDaily.length>30)errors.push('finance-audit-digest');}}}
    const budgets=object(s?.companyBudgets)?s.companyBudgets:{};for(const b of Object.values(budgets)){const limit=Number(b?.limit),spent=Number(b?.spent),reserved=Number(b?.reserved||0);if(!finite(limit)||limit<0||!finite(spent)||spent<0||!finite(reserved)||reserved<0||(b.enabled&&limit>0&&spent+reserved>limit+.01))errors.push('budget');for(const [line,lineLimitRaw] of Object.entries(object(b?.lines)?b.lines:{})){const lineLimit=Number(lineLimitRaw)||0,lineSpent=Number(b?.spentByLine?.[line]||0),lineReserved=Number(b?.reservedByLine?.[line]||0);if(lineSpent<0||lineReserved<0||(b.enabled&&lineLimit>0&&lineSpent+lineReserved>lineLimit+.01))errors.push('budget-line');}}
    const cp=s?.controlPlane;if(cp!==undefined){if(!object(cp)||String(cp.schema||'')!=='gh-control-plane-v1'||!Array.isArray(cp.events)||!Array.isArray(cp.commands)||!Array.isArray(cp.incidents)||!Array.isArray(cp.outbox)||!Array.isArray(cp.blackBox)||!object(cp.registry)||!object(cp.registry.engines)||!Array.isArray(cp.registry.links))errors.push('control-plane-shape');else{if(cp.events.length>STATE_LIMITS.controlEvents||cp.commands.length>STATE_LIMITS.controlCommands||cp.incidents.length>STATE_LIMITS.controlIncidents||cp.outbox.length>STATE_LIMITS.controlOutbox||cp.blackBox.length>STATE_LIMITS.controlBlackBox)errors.push('control-plane-capacity');for(const key of ['revision','commandSequence','eventSequence','incidentSequence','outboxSequence'])if(!finite(cp[key])||Number(cp[key])<0||!Number.isInteger(Number(cp[key])))errors.push('control-plane-sequence');if(!/^[a-f0-9]{64}$/i.test(String(cp.journalHeadHash||'')))errors.push('control-plane-journal-head');if(duplicateIds(cp.events,x=>x?.id)||duplicateIds(cp.commands,x=>x?.id)||duplicateIds(cp.incidents,x=>x?.id)||duplicateIds(cp.outbox,x=>x?.id))errors.push('control-plane-id');for(const e of cp.events){if(!Number.isInteger(Number(e?.sequence))||Number(e.sequence)<=0||!/^[a-f0-9]{64}$/i.test(String(e?.hash||''))||!/^[a-f0-9]{64}$/i.test(String(e?.previousHash||'')))errors.push('control-plane-event');}const eventIds=new Set(cp.events.map(x=>x?.id));for(const row of cp.outbox)if(row?.delivered!==true&&!eventIds.has(row?.eventId)&&row?.payload?.id!==row?.eventId)errors.push('control-plane-outbox-reference');}}
    if(Array.isArray(s?.domainRuntime?.commands)&&s.domainRuntime.commands.length>STATE_LIMITS.domainCommands)errors.push('domain-command-capacity');if(Array.isArray(s?.businessLedger?.events)&&s.businessLedger.events.length>STATE_LIMITS.businessEvents)errors.push('business-event-capacity');
    const bw=s?.businessWorld;if(bw!==undefined){if(!object(bw)||!object(bw.parties)||!object(bw.relationships)||!Number.isInteger(Number(bw.sequence))||Number(bw.sequence)<0)errors.push('business-world-shape');else{const caps={events:STATE_LIMITS.businessWorldEvents,opportunities:STATE_LIMITS.businessWorldOpportunities,sponsorships:STATE_LIMITS.businessWorldSponsorships,campaigns:STATE_LIMITS.businessWorldCampaigns,competitorActivity:STATE_LIMITS.businessWorldCompetitorActivity};for(const [key,limit] of Object.entries(caps)){const rows=bw[key];if(!Array.isArray(rows))errors.push('business-world-'+key+'-shape');else{if(rows.length>limit)errors.push('business-world-'+key+'-capacity');if(duplicateIds(rows,x=>x?.id))errors.push('business-world-'+key+'-id');}}if(Object.keys(bw.parties).length>STATE_LIMITS.businessWorldParties)errors.push('business-world-party-capacity');if(Object.keys(bw.relationships).length>STATE_LIMITS.businessWorldRelationships)errors.push('business-world-relationship-capacity');for(const [id,p] of Object.entries(bw.parties))if(!id||!object(p)||p.id!==id||!String(p.legalName||p.displayName||'').trim()||!Array.isArray(p.roles)||!Array.isArray(p.sectors))errors.push('business-world-party');for(const [id,r] of Object.entries(bw.relationships))if(!id||!object(r)||r.id!==id||!bw.parties[r.partyId]||!String(r.company||'').trim()||!Array.isArray(r.roles))errors.push('business-world-relationship');}}
    let started=metricClock();validateAuthorizationState(s,errors,verificationCache,metric);metric.authorizationMs=Math.max(0,metricClock()-started);
    started=metricClock();validateDocumentProofState(s,errors,verificationCache,metric);metric.documentProofMs=Math.max(0,metricClock()-started);
    started=metricClock();const companyValidation=globalThis.GH_COMPANY_PLATFORM?.validateState?.(s);metric.companyPlatformMs=Math.max(0,metricClock()-started);if(companyValidation&&!companyValidation.ok)errors.push(...companyValidation.errors.map(error=>`company-platform:${error}`));
    metric.totalMs=Math.max(0,metricClock()-validationStart);metric.errors=new Set(errors).size;metric.otherMs=Math.max(0,metric.totalMs-metric.authorizationMs-metric.documentProofMs-metric.companyPlatformMs);publishValidationMetric(metric);
    return {ok:errors.length===0,errors:[...new Set(errors)]};
  }
  const API=Object.freeze({VERSION,SAVE_SCHEMA_VERSION,STATE_LIMITS,ROUTE_FLEET_CAPACITY,normalize,validate,migrateLegacy,telemetry:()=>JSON.parse(JSON.stringify(runtimeTelemetry))});globalThis.GH_SAVE_SCHEMA=API;if(globalThis.window&&globalThis.window!==globalThis)globalThis.window.GH_SAVE_SCHEMA=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
