(()=>{'use strict';
const VERSION='2.9.0',now=s=>Number(s.simSeconds)||0,num=v=>Math.max(0,Number(v)||0);
function ensure(s){s.advanced=s.advanced||{};s.advanced.programs=s.advanced.programs||{initiatives:[],completed:0,lastReview:0};s.advanced.programs.initiatives=Array.isArray(s.advanced.programs.initiatives)?s.advanced.programs.initiatives:[];s.advanced.economy=s.advanced.economy||{};s.alerts=Array.isArray(s.alerts)?s.alerts:[];s.eventLog=Array.isArray(s.eventLog)?s.eventLog:[];return s.advanced;}
function execute(ctx,cmd,p={}){const s=ctx.state||ctx;ensure(s);
 if(cmd==='record-program'||cmd==='plan-program'){if(cmd==='plan-program')globalThis.GH_FINANCE_CORE?.execute?.({state:s},'spend',{company:'group',amount:num(p.studyCost||180000),note:'دراسة برنامج استراتيجي',method:'تحويل بنكي',line:'other'});const row={...p,id:p.id||`PGM-${Math.floor(now(s))}-${s.advanced.programs.initiatives.length+1}`,at:now(s),createdAt:p.createdAt??now(s),status:p.status||'بانتظار الاعتماد'};s.advanced.programs.initiatives.unshift(row);return row;}
 if(cmd==='approve-program'){const row=s.advanced.programs.initiatives.find(x=>x.id===p.id);if(!row)throw new Error('program-not-found');if(row.status==='قيد التنفيذ')return row;globalThis.GH_FINANCE_CORE?.execute?.({state:s},'spend',{company:p.company||'group',amount:num(row.budget),note:`اعتماد ${row.title}`,method:'تحويل بنكي',line:'capex'});row.status='قيد التنفيذ';row.approvedAt=now(s);return row;}
 if(cmd==='cancel-program'){const row=s.advanced.programs.initiatives.find(x=>x.id===p.id);if(!row)throw new Error('program-not-found');if(row.status==='قيد التنفيذ')throw new Error('program-already-active');row.status='مرفوض';row.closedAt=now(s);return row;}
 if(cmd==='tick-day'){const d=Math.floor(Number(p.day)||Math.floor(now(s)/86400));let completed=0;for(const row of s.advanced.programs.initiatives.filter(x=>x.status==='قيد التنفيذ')){row.remainingDays=Math.max(0,Number(row.remainingDays||0)-1);if(row.remainingDays===0){row.status='مكتمل';row.completedAt=now(s);s.advanced.programs.completed=num(s.advanced.programs.completed)+1;const C=globalThis.GH_CORPORATE_CORE,m=C?.model?.(s,row.sector||'road');if(m){m.serviceLevel=Math.min(100,num(m.serviceLevel)+5);m.automation=Math.min(100,num(m.automation)+4);}const text=`اكتمل ${row.title}: تحسن مستوى الخدمة والأتمتة في ${row.sector||'التشغيل'}.`;s.alerts.unshift(text);s.eventLog.unshift({id:`PRG-${row.id}`,at:now(s),type:'program',text:`إغلاق برنامج: ${row.title} وقياس أثره التشغيلي.`});completed++;}}s.alerts=s.alerts.slice(0,40);s.eventLog=s.eventLog.slice(0,400);return {day:d,completed};}
 if(cmd==='economy-news'){const h=Math.floor(Number(p.hour)||0);if(s.advanced.economy.lastNewsHour===h)return false;s.advanced.economy.lastNewsHour=h;const text=String(p.text||'');s.alerts.unshift(text);s.eventLog.unshift({id:`EC-${h}`,at:now(s),type:'economy',text});s.alerts=s.alerts.slice(0,40);s.eventLog=s.eventLog.slice(0,400);return true;}
 if(cmd==='apply-runtime-update'){const ops=Array.isArray(p.operations)?p.operations:[];for(const op of ops){if(op.type==='content-config')s.advanced.content={...(s.advanced.content||{}),...(op.value||{})};else if(op.type==='balance-config')s.advanced.balance={...(s.advanced.balance||{}),...(op.value||{})};else if(op.type==='economy-config')s.advanced.economy={...(s.advanced.economy||{}),...(op.value||{})};else if(op.type==='visual-manifest')s.advanced.visualManifest={...(s.advanced.visualManifest||{}),...(op.value||{})};else if(op.type==='add-events'&&Array.isArray(op.value)){op.value.slice(0,20).reverse().forEach(text=>s.alerts.unshift(String(text)));}}s.alerts=s.alerts.slice(0,40);s.advanced.updateHistory=Array.isArray(s.advanced.updateHistory)?s.advanced.updateHistory:[];s.advanced.updateHistory.unshift({id:p.id,version:p.version,installedAt:p.installedAt||new Date().toISOString(),backupKey:p.backupKey??null,rollbackOwner:p.rollbackOwner||'native-save-vault'});s.advanced.updateHistory=s.advanced.updateHistory.slice(0,20);return true;}
 if(cmd==='update-config'){s.advanced.updateHistory=Array.isArray(s.advanced.updateHistory)?s.advanced.updateHistory:[];s.advanced.updateHistory.unshift({...p,installedAt:p.installedAt||new Date().toISOString()});s.advanced.updateHistory=s.advanced.updateHistory.slice(0,20);return true;}
 throw new Error(`Unknown strategy command: ${cmd}`);
}
const API={VERSION,ensure,execute};globalThis.GH_STRATEGY_CORE=API;globalThis.GH_DOMAIN_COMMANDS?.register?.('strategy',API);if(globalThis.window&&window!==globalThis)window.GH_STRATEGY_CORE=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})();
